### ISSUE TITLE
Feature Request: Auth trigger for updated user (phone number)

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-functions#1001]
Hey there, it would be nice to have the option to trigger actions when a user is update, e.g. his number changed or his email.

Thanks:)

**Comment by rhodgkins** [comment]
+1 to this - we'd find it useful to get notified when the users `emailVerified` gets changed.

**Comment by taeold** [comment]
Thanks for filing the issue @nidegen!

Having `onUpdate` support for auth event is one of the more popular feature request, but this isn't something that the maintainers of this repo (see https://github.com/firebase/firebase-functions/issues/732 for previous discussion).

I'm closing the ticket as this isn't something we can effectively respond to. We've pinged internal teams responsible for the feature. I'd recommend that you open a [Firebase Support case](https://firebase.google.com/support); I believe that's a more effective way to have your voices heard!
