### ISSUE TITLE
Empty DeployOptions for topic function

### ISSUE THREAD

**Issue by JoelAccenture** [firebase/firebase-functions#1011]
Hi, 
I'm currently using firebase pubsub functions and I'm trying to configure options for error handling(dead-letter, message retention) in an topic().onPublish() function but I saw that the topic function is not receiving and sending the "options: DeploymentOptions" as referenced here:
https://github.com/firebase/firebase-functions/blob/9016314de51c02691e2e43abe1707468f18e6074/src/providers/pubsub.ts#L46

Why is there an empty object instead of letting us to pass the DeploymentOptions to the _topicWithOptions function?

**Comment by colerogers** [comment]
Hi @JoelAccenture, that function gets called with `DeploymentOptions` when you use the `runWith` syntax. 

Here's an article that explains runtime options in a little more detail - [manage-functions](https://firebase.google.com/docs/functions/manage-functions)

Here's what the possible runtime options are - [RuntimeOptions](https://github.com/firebase/firebase-functions/blob/9016314de51c02691e2e43abe1707468f18e6074/src/function-configuration.ts#L101)

Let me know if that makes sense
