### ISSUE TITLE
Can't use ignoreUndefinedProperties with Firestore triggers

### ISSUE THREAD

**Issue by 50an6xy06r6n** [firebase/firebase-functions#1017]
### [REQUIRED] Version info

**node:** 16.9.0

**firebase-functions:** 3.15.5

**firebase-tools:** 9.23.1

**firebase-admin:** 9.21.0

### [REQUIRED] Test case

```
const test = functions.firestore
    .document("testDoc")
    .onWrite(async (change, context) => {
        await change.after.ref.set({ testField: undefined });
    });
```

### [REQUIRED] Steps to reproduce

Put in `index.ts` and make a change to `testDoc`.

### [REQUIRED] Expected behavior

There should be a way to set `ignoreUndefinedProperties` to `true` when using functions triggers.

### [REQUIRED] Actual behavior

There doesn't seem to be a way to do this

### Were you able to successfully deploy your functions?

yeah it deploys

**Comment by thebrianchen** [comment]
@50an6xy06r6n If you use the default Functions triggers, Firestore is automatically instantiated. To use custom settings, you will have to instantiate Firestore outside the scope of your your function and set the document with your initialized Firestore instance. 

In your case:
```
const admin = require('firebase-admin');
admin.initializeApp();

const db = admin.firestore();
db.settings({ignoreUndefinedProperties: true});

const test = functions.firestore
    .document("testDoc")
    .onWrite(async (change, context) => {
        await db.doc("testDoc").set({ testField: undefined });
    });

```


See the [documentation](https://firebase.google.com/docs/functions/firestore-events#data_outside_the_trigger_event) for more information. Hope this unblocks you! I'm going to mark the issue as closed, but feel free to follow up with any other questions you may have!

**Comment by 50an6xy06r6n** [comment]
Ah I see. Didn't realize that was a recommended pattern. Thought it might cause a race condition or something.
