### ISSUE TITLE
Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by tfang17** [firebase/firebase-functions#1034]
### Related issues

n/a

### [REQUIRED] Version info

**node:**

14

**firebase-functions:**

3.17.1

**firebase-tools:**

10.1.4

**firebase-admin:**

10.0.2

### [REQUIRED] Test case

`firebase deploy --only functions:[FUNCTION_NAME]`

### [REQUIRED] Steps to reproduce

Deploy code to Firebase.

### [REQUIRED] Expected behavior

Successful deployment.

### [REQUIRED] Actual behavior

`Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0`

### Were you able to successfully deploy your functions?

No, see error above.

**Comment by krishna-fenixwork** [comment]
Does anyone able to find a solution for this? Stuck on this for 2 days.

**Comment by taeold** [comment]
@krishna-fenixwork This issue was separately discussed in https://github.com/firebase/firebase-tools/issues/4134.  Can you open up a new issue if you are having similar troubles?

**Comment by krishna-fenixwork** [comment]
Hey, @taeold thanks for the response. Well, I'm getting the same error while deploying through the firebase deploy command. I'm using the below command.

`firebase deploy --only functions:nextServer,hosting --debug`

and this is what the debug -

`[debug] [2022-02-08T12:35:42.604Z] Analyzing nodejs backend spec
[info] i  functions: preparing . directory for uploading... 
[info] i  functions: packaged . (135.39 MB) for uploading 

and

[warn] !  functions: Upload Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0 
[error] 
[error] Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0`

Couldn't understand what caused the error?

**Comment by taeold** [comment]
@krishna-fenixwork I'll use https://github.com/firebase/firebase-tools/issues/4134 to track this issue but the short story is - yes it sounds like your directory size exceeds the limit (100MB zipped).
