### ISSUE TITLE
Deploy crash: triggers not reading DATABASE_NAME from .env 

### ISSUE THREAD

**Issue by denkoul** [firebase/firebase-functions#1054]
### [REQUIRED] Version info

**node:**

v12.16.2

**firebase-functions:** 3.18.1

**firebase-tools:**

firebase-tools@10.2.2

**firebase-admin:** "^10.0.2"

### [REQUIRED] Test case

I am trying to deploy a firebase function onCreate trigger for Firebase Database.  
I was reading the database name from `functions.config().database.name`.  
I created` .env` files with `DATABASE_NAME` variable inside them.  
I try to read the name from `process.env.DATABASE_NAME`, and i am getting: `Error: There was an error deploying functions`.  

**Workaround: If I read the name from  `functions.config().database.name`, it is working.**  

### [REQUIRED] Steps to reproduce

Create Firebase Database trigger with custom set database name from .env file.  

### [REQUIRED] Expected behavior
Trigger should work as using the `functions.config().database.name`.  

### [REQUIRED] Actual behavior

> 
> Functions deploy had errors with the following functions:
> Error: There was an error deploying functions
> 
> 

### Were you able to successfully deploy your functions?

No, above error.

**Comment by taeold** [comment]
This sounds similar to issue described in https://github.com/firebase/firebase-tools/issues/4239.

Your user-specified environments are available the CLI parses your source for function triggers. I plan on having more discussion in the other issue - let's close this one in favor of that one.
