### ISSUE TITLE
Firebase Functions execution fails using Firebase free plan for sending twilio sms 

### ISSUE THREAD

**Issue by mokupindia** [firebase/firebase-functions#106]
### Version info

**firebase-tools:**

current: 3.9.2

### Were you able to successfully deploy your functions?

✔  functions[orderStatus]: Successful create operation. 
✔  functions: all functions deployed successfully!

### Actual behavior

Function log:

Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions.

Error: getaddrinfo ENOTFOUND api.twilio.com:443

Function execution took 377 ms. finished with status 'ok'

**Comment by laurenzlong** [comment]
As the error states, you need to enable billing on your account in order to make external network requests. See https://firebase.google.com/pricing/

**Comment by Bensigo** [comment]
can't i use free plan with my cloud function and hit external api endpoint

**Comment by laurenzlong** [comment]
No sorry you can't, you need a credit card on file. See https://firebase.google.com/pricing/ for more info.

**Comment by thomasbabuj** [comment]
Hi @laurenzlong, 

My function logs show the similar error, even though i  have upgraded my current plan to "Blaze"  and also without making any external network call.

Can you please give me some pointers on this.

**Comment by laurenzlong** [comment]
Hi @thomasbabuj this is probably a project-specific issue, can you file a support ticket at firebase.google.com/support
