### ISSUE TITLE
New .env-based configuration is not available on deploy

### ISSUE THREAD

**Issue by uvesten** [firebase/firebase-functions#1065]
I've spent quite a bit of time to move from the old `functions.config()` system to the new `.env`-file based config for better developer ergonomics. I'm very, very disappointed that this "feature" was released at all in its current state, since it's a major regression compared to `functions.config()`. 

That an environment variable needs to be set in the environment _before_ starting to execute an arbitrary function, that should be obvious. The config values _might_ be available inside `runWith(), .onCall()` etc, but that's not enough. Please fix this or release a new major version, removing support until you can get it right. 

My case: 

Using a config variable to decide which region to deploy functions to fails, since the  `.env`-based config is not available on function deploy. 

Example: 

```
export const copy = region(process.env.DEPLOY_REGION)
  .runWith()
  .https.onCall(
```

breaks, because the environment variable does not exist... (It's set correctly in the `.env` file)

```
export const copy = region(functions.config().deploy.region)
  .runWith()
  .https.onCall(
```

Works well.  

It's not OK to release a new feature in this state... Please fix or un-release it asap

(Reported to both here and in https://github.com/firebase/firebase-tools/issues/4361 because I don't know which project is responsible for this change)

**Comment by colerogers** [comment]
Hi @uvesten I'm sorry that this feature is causing such a headache and I understand your frustration. Since this issue has a more active thread, #1044, I'm going to close this to re-direct others there.

**Comment by inlined** [comment]
See https://github.com/firebase/firebase-functions/issues/1084 for our plans around this area.
