### ISSUE TITLE
onDelete not called when setting different data from parent node

### ISSUE THREAD

**Issue by ouchadam** [firebase/firebase-functions#107]
### Version info

**firebase-functions:** 0.6.3

**firebase-tools:** 3.11.0

**firebase-admin:** 5.2.1

### Test case

`firebase-functions.onDelete`is not called when setting different data from a parent node

### Steps to reproduce

Given a database structure of

```
/user_id
    /following
        /id_1: true
        /id_2: true
        /id_3: true
```

when setting the `user_id` node with less `following` children (effectively removing them) 

```
database.ref(userId).set({
    following: {
        id_2: true
    }
)
```

and observing 

```
functions.database.ref('/{user_id}/following/{follower_id}').onDelete
```

### Were you able to successfully deploy your functions?

Yes, no error messages

### Expected behavior

The `onDelete` trigger to be invoked. 

### Actual behavior

The `onDelete` trigger is not invoked.
The `onUpdate` trigger is also not invoked however `onWrite` is invoked with `event.data.exists` returning false.

Interestingly the web tool flashes the `/{user_id}/following/{follower_id}` node red when setting different data but the `onDelete` trigger is not invoked. 

Manually setting the `/{user_id}/following/{follower_id}`node to null or deleting directly from the web tool invokes the `onDelete` trigger as expected. 

Apologies if this is expected behaviour, I was unable to find a reference/example for this scenario.

**Comment by ouchadam** [comment]
I have reported the issue to https://firebase.google.com/support/ feel free to close or I will if the issue is acknowledged by support

**Comment by rjhuijsman** [comment]
Thanks! This is indeed surprising behavior - we're looking into it!

**Comment by rjhuijsman** [comment]
This issue was due to a bug in the Firebase Realtime Database's trigger logic. It's now fixed, your functions should work as expected. Thanks for the report!

**Comment by arpancodes** [comment]
I am facing this issue again. Using it with react-native the cloud function is not triggered onDelete. not even an error
