### ISSUE TITLE
Returning 204 from express results in a "response error" log entry

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-functions#1081]
### [REQUIRED] Version info
**node:**
16.13.1

**firebase-functions:**
3.20.1

**firebase-tools:**
10.6.0

**firebase-admin:**
10.0.2

### [REQUIRED] Test case
```typescript
const app = express()

app.patch('/test', (req, res) => {
  res.sendStatus(204)
})

export const v1 = region('europe-west1').https.onRequest(app)
```
### [REQUIRED] Steps to reproduce
See above

### [REQUIRED] Expected behavior
I expect the above to be a valid return code.

### [REQUIRED] Actual behavior
`Function execution took 4 ms. Finished with status: response error`

The log says it's a "response error", which it clearly isn't.
It used to work, but recently starting throwing "response errors".

The HTTP functions all work fine, it seems to be a logging problem only (false positive).

### Were you able to successfully deploy your functions?
Yes

### When you ran `firebase deploy`, did you see any error messages?
No

**Comment by taeold** [comment]
@larssn Thanks for raising the issue. I've confirmed internally that this issue is something that's affecting all Google Cloud Functions (the underlying platform for Firebase Functions) users. Stay tuned for updates.

**Comment by koxu1996** [comment]
There is some serious issue underneath, not directly related to the code `204`. I would like to present you the case that ends up with cryptic, annoying and unnecessary `response error` log.

---

Let us consider the following _express_ application:
```js
import * as express from "express";

const app = express();

app.use((req, res, next) => {
  res.on('close', () => {
    if (res.writableFinished === true) {
      console.log("Response was fully sent to client.");
    } else {
      console.log("Client disconnected before receiving response.");
    }
  });
  next();
});

app.get('/', async (req, res) => {
  // Simulate long-running task.
  await new Promise((resolve) => setTimeout(resolve, 5000));
  res.send('ok');
});

app.listen(3000, () => {
  console.log(`App is listening on http://localhost:3000`);
});

```
Run it locally with `$ node index.js` or `$ npx ts-node index.ts`.

If you open `http://localhost:3000` in the browser and wait 5 seconds, then you will see in console:
```
Response was fully sent to client.
```
If you open `http://localhost:3000`, but close the tab/browser before getting response, then you will see in console:
```
Client disconnected before receiving response.
```
Everything works as expected so far.

---

To convert this app into _Google Cloud_ function we have to make small change:

```js
import * as functions from "firebase-functions";

... // rest of code unchanged

//app.listen(3000, () => {
//  console.log(`App is listening on http://localhost:3000`);
//})

exports.api = functions.region('europe-central2').https.onRequest(app);
```
Run `$ firebase deploy --only functions`, and soon you can test identical scenarios as previously.

If you open `https://europe-central2-[APP_NAME].cloudfunctions.net/api` in the browser and wait 5 seconds, then you will get following logs:
```
Function execution started
Response was fully sent to client.
Function execution took 5018 ms. Finished with status code: 200
```

That is good. However, if you open `https://europe-central2-[APP_NAME].cloudfunctions.net/api`, but close the tab/browser before getting response, then **sometimes** you can get:

![image](https://user-images.githubusercontent.com/6506780/166817356-c2c5b55e-3612-4d30-bec3-938d5268b082.png)

That is completely wrong:exclamation:

- The response was not fully sent to client - is _Google Cloud Functions_ messing up with the events of _Node.js_ HTTP server?
- Why we see `response error` even if everything went fine?

To clarify why I said **sometimes** - this behavior is not deterministic. Sometimes you get `response error`, sometimes not.

---

I hope this will help you guys to track down and fix the issue :factory_worker:.

**Comment by taeold** [comment]
Update from Cloud Functions.

They have a patch and are releasing the update to customers this week. The rollout should reach all customers by end of this week.

@koxu1996 Thanks for detailed report! Google Cloud Functions (and overall, GCP) maintains a complex networking stack for serverless products like Cloud Functions and Cloud Run. In this case, I think a bad patch to that system is responsible for the error we are seeing, but if there are specific networking issue you are seeing and want an answer to, please try Cloud support. You'll likely be routed to an engineer who can explain the issue you may be seeing.

**Comment by koxu1996** [comment]
I confirm that `response error` no longer appears in my logs.
