### ISSUE TITLE
V2 Firebase Functions Timeline

### ISSUE THREAD

**Issue by dannnnthemannnn** [firebase/firebase-functions#1120]
When can we expect firebase functions that use https://cloud.google.com/functions/docs/2nd-gen/overview

### Related issues

No I don't know any related issues

### [REQUIRED] Version info

N/A

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

N/A
### [REQUIRED] Actual behavior

N/A

### Were you able to successfully deploy your functions?

yes

**Comment by inlined** [comment]
Today! Get started by importing `firebase-functions/v2` or one of its subpackages. You'll need the latest CLI to access v2 without alpha tester access. To get early access in the future, [sign up for our alpha program](https://services.google.com/fb/forms/firebasealphaprogram/)
