### ISSUE TITLE
Firebase function with express-session returning undefined value

### ISSUE THREAD

**Issue by kencanak** [firebase/firebase-functions#1126]
### Related issues
N/A

### [REQUIRED] Version info
Firebase function: v3.21.1

**node:**
v14.19.0

**firebase-functions:** v3.21.1

**firebase-tools:** v10.7.2

**firebase-admin:** v10.1.0

### [REQUIRED] Test case
- create http cloud function that's running on express
- use express-session
- init a firebase hosting, write a rewrite rules to run the dynamic hosting
- session data is accessible when accessing the app via function url directly
- session data is undefined when accessing the app via hosting url

### [REQUIRED] Steps to reproduce
[sample cloud function](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/HEAD/sessions/index.js)

sample rewrites rules:
```
"rewrites": [
        {
          "source": "/",
          "function": "sample-app"
        }
      ]
```

### [REQUIRED] Expected behavior

session data should be accessible when accessing app via hosting url

session data was undefined

### Were you able to successfully deploy your functions?
yes

**Comment by mackbdev** [comment]
Currently experiencing this issue

**Comment by mackbdev** [comment]
> Currently experiencing this issue

After some more digging the solution end up being in the [Firebase Doc ](https://firebase.google.com/docs/hosting/manage-cache#using_cookies)

The solution is to give your cookie a name of  `__session` :


```
app.use(session({ 
	name: "__session",
	secret: ...,
	resave: ...,
	cookie: ...,
	store: ...,
	saveUninitialized: ...,
}));
```

[source](https://stackoverflow.com/questions/72634189/how-to-properly-use-express-session-on-firebase-cloud-functions)

**Comment by taeold** [comment]
Hi. This limitation is in Firebase Hosting:

From the [docs](https://firebase.google.com/docs/hosting/manage-cache#using_cookies):

> When using Firebase Hosting together with Cloud Functions or Cloud Run, cookies are generally stripped from incoming requests. This is necessary to allow for efficient CDN [cache behavior](https://firebase.google.com/docs/hosting/manage-cache#set_cache-control). Only the specially-named __session cookie is permitted to pass through to the execution of your app.
