### ISSUE TITLE
CORs not working in onCall functions V2 function

### ISSUE THREAD

**Issue by dannnnthemannnn** [firebase/firebase-functions#1128]
### Related issues

No

### [REQUIRED] Version info

**node:**

v16.13.2

**firebase-functions:**

3.21.2

**firebase-tools:**

10.9.2

**firebase-admin:**

10.2.0

### [REQUIRED] Test case

```typescript
export const getAddressInfo = functionsV2.https.onCall(
  {
    minInstances: 5,
    memory: "1GiB",
    secrets: [secretKey],
    cors: true,
  },
  (request) => handler(request.data)
);
```

### [REQUIRED] Steps to reproduce

Deploy a v2 function to run in google cloud. 

### [REQUIRED] Expected behavior

CORs requests are handled properly

### [REQUIRED] Actual behavior

Get a CORs error in chrome. Weirdly it does work fine when running in the functions emulator. 

### Were you able to successfully deploy your functions?

Yes, the deployment showed no errors.

**Comment by dannnnthemannnn** [comment]
Looking into this a bit more, I see that the v2 functions are deployed to a very different URL. After updating my client code to use that URL (`https://<function-name>-<identifier>-uc.a.run.app`) it is working as expected. Now I will look if the firebase functions client libraries have v2 support or if I need to give a custom domain every time.

**Comment by taeold** [comment]
@dannnnthemannnn Unfortunately, unlike Cloud Functions v1, Cloud Functions v2 generates random URL. We don't have any way of reliably predicting this URL from Firebase client libraries and need users to explicitly pass in the url they see on Cloud Run.

See https://firebase.google.com/docs/functions/beta/callable for more info.

**Comment by ernysans** [comment]
The best way to fix this issue is to specify the domains you will call from like it's described on the docs, it was the only way it worked for me, passing `'*'` or `true` does nothing.

```javascript
https.onRequest({
    cors: [/yourdomain\.com$/, 'yourdomain.com'],
}, app);
```

[Read More on Firebase Docs](https://firebase.google.com/docs/functions/beta/http-events#configuring_cors_cross-origin_resource_sharing)

**Comment by jasan-s** [comment]
@ernysans  even passing that i am getting cors error

**Comment by pixeledo** [comment]
I was getting a CORS error in chrome and this was the error in the firebase logs:

_The request was not authenticated. Either allow unauthenticated invocations or set the proper Authorization header. Read more at https://cloud.google.com/run/docs/securing/authenticating Additional troubleshooting documentation can be found at: [](https://cloud.google.com/run/docs/troubleshooting#unauthorized-client)_

Following the second link to this page [https://cloud.google.com/run/docs/securing/managing-access#making_a_service_public](https://cloud.google.com/run/docs/securing/managing-access#making_a_service_public)

Adding the Permission worked for me. The v2 CORS code was not needed from the onCall/onRequest functions to work after adding the Permission.

**Comment by al4nnw** [comment]
To someone in the future with the same problem, try to deploy the function with a completely different name. Deleting and deploying again didn't work for me.

In my case, the first time I tried to deploy a function called "`getServices`" it failed. And then on the following deploys it worked but the request was always blocked by the CORS policy.

**Comment by valeria-edulabs** [comment]
@al4nnw Thank you! I had the same problem  - the first deploy has failed, and after that all the deployments were successful, however I'be got the CORS problem. After renaming the function and redeploying again everything worked!

**Comment by ogrotten** [comment]
@al4nnw 2025 checking in. This fixed this cors problem for me.
