### ISSUE TITLE
"firebase serve --only functions" gives various nodejs version errors/warnings

### ISSUE THREAD

**Issue by bjornbjorn** [firebase/firebase-functions#113]
### Version info

```
  "name": "functions",
  "description": "Cloud functions",
  "dependencies": {
    "firebase-admin": "^5.4.1",
    "firebase-functions": "^0.6.3",
    "request": "^2.83.0",
    "request-promise": "^4.2.2"
  },
  "private": true
}
```

### Test case

> firebase serve --only functions

Get warning / Error depending on nodejs version:

**Node 8.6.0**:
> Warning: You're using Node.js v8.6.0 but Google Cloud Functions only supports v6.11.1.

**Node 6.11.1**:
> ⚠  functions: Cannot start emulator. Please use Node version v6.9.1, you have v6.11.1

**Node 6.9.1**:
> Node.js v6.11.x or greater is required to run the Emulator!

### Steps to reproduce

Use nvm to switch between node versions and run firebase serve to see the various errors:

> nvm use 8.6.0
> firebase serve --only functions
> nvm use 6.11.1
> firebase serve --only functions
> nvm use 6.9.1
> firebase serve --only functions

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

Being able to run the cloud functions locally and access the Firebase Realtime Database

### Actual behavior

Differs with node version, but with 8.6.0 (the one that works the best) I'm able to run the functions but not able to perform any actions on the database reference (if I console.log the object it says "Failed"). Deploying the function works (and is able to push to the db).

**Comment by laurenzlong** [comment]
@bjornbjorn What's your version of firebase-tools?

If you run "firebase --version", what does it print?

**Comment by bjornbjorn** [comment]
firebase --version
3.12.0

**Comment by laurenzlong** [comment]
Can you try to do a full uninstall and then install of the latest version?

npm uninstall -g firebase-tools
npm install -g firebase-tools

**Comment by laurenzlong** [comment]
You should then have 3.13.0

**Comment by bjornbjorn** [comment]
Thank you @laurenzlong that worked and I'm now up and running and accessing the database locally with node 8.6.0.

The warnings / errors mentioned in the opening of this issue still stand though (the circular referencing of node versions).

Anyway, as far as I'm concerned; I'm all good, thanks again!

**Comment by laurenzlong** [comment]
Thanks for the update! Agreed that we should work on better (and non-circular) error logging.

**Comment by capitola-dev** [comment]
I have firebase 3.13.1 but I am having the same issue

```
node -v
v8.6.0

firebase --version
3.13.1

firebase serve --only functions,hosting
⚠  functions: Cannot start emulator. Please use Node version v6.9.1, you have v8.6.0

nvm use 6.9.1

firebase serve --only functions,hosting
⚠  functions: Cannot start emulator. Error: Module version mismatch. Expected 48, got 47.
```

**Comment by laurenzlong** [comment]
This PR fixes the confusing error messages: https://github.com/firebase/firebase-tools/pull/504

The correct version of Node to use is in v.6.11.1

**Comment by zinzinday** [comment]
`stdout@desktop-94847:~$ firebase --version
3.13.1
stdout@desktop-94847:~$ node -v
v8.6.0
stdout@desktop-94847:~$ npm -v
5.4.2
stdout@desktop-94847:/data/nodejs/my-app$ firebase serve --only functions
=== Serving from '/data/nodejs/my-app'...
⚠  functions: Cannot start emulator. Please use Node version v6.9.1, you have v8.6.0
`

**Comment by gino-m** [comment]
I was also seeing errors about version v6.11.x when I was using v6.11.1. Switching to 6.11.5 resolved this for me, and I was able to see parse errors as expected.
