### ISSUE TITLE
[Improvement] Better integration of AppCheck

### ISSUE THREAD

**Issue by wujek-srujek** [firebase/firebase-functions#1130]
Currently we need to explicitly program verification checks into each function (as far as I know), which is not very comfortable. Are there any plans to better integrate AppCheck so that verification is automatic, e.g. like it is for Firestore?

**Comment by inlined** [comment]
We would like to investigate deeper integrations, but they are not a very high priority on our roadmap given the infrastructural changes that need to happen.
