### ISSUE TITLE
Error: Digest method not supported

### ISSUE THREAD

**Issue by ghost-bullet** [firebase/firebase-functions#1132]
I add this line in my file `index.js` :
`const crypto = require('crypto');`

and after add , try upload function give me error this : 

![Screenshot 2022-06-04 180334](https://user-images.githubusercontent.com/41883595/172010336-41fa6667-24b9-4901-8402-c7462bf45a0c.png)

Why are you giving me this error firebase !

**Comment by taeold** [comment]
Hi @ghost-bullet. I'm unable to reproduce the issue with the following code

```
const crypto = require('crypto');


const functions = require("firebase-functions");
const handleAnalyticsEvent = async (event) => {
  console.log(event.params);
};

exports.onArticleOpen = functions.analytics.event('in_app_purchase').onLog(handleAnalyticsEvent);
```

Can you try running `node index.js` on your file to see if no error occurs? If you are see the same error message, you might have a bug in your code unrelated to the Functions SDK.
