### ISSUE TITLE
Sending a notification with FCM in a Cloud Function always fails with 401

### ISSUE THREAD

**Issue by wujek-srujek** [firebase/firebase-functions#1133]
### [REQUIRED] Version info

**node:** v18.2.0

**firebase-functions:** 3.21.2

**firebase-tools:** 11.0.1

**firebase-admin:** 10.2.0

### [REQUIRED] Test case

`index.ts`:
```typescript
import * as admin from 'firebase-admin';

admin.initializeApp();

export * from './messages';
```

`messages.ts`:
```dart
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';

export const publishMessage = functions.region('europe-west3')
  .firestore.document('/messages/{messageId}').onCreate(
    (snapshot, context) => {
      const data = snapshot.data();
      const message = {
        notification: {
          title: `${data.sentBy} sent a message`,
          body: data.message,
        },
      };

      return admin.messaging().sendToTopic('messages', message);
    },
  );
```

### [REQUIRED] Steps to reproduce

1. Save a new document in the /message collection.
2. This triggers the `publishMessage` function to send a notification to a topic.

### [REQUIRED] Expected behavior

A notification is sent successfully.

### [REQUIRED] Actual behavior

The error is thrown:
```
Error: An error occurred when trying to authenticate to the FCM servers. Make sure the credential used to authenticate this SDK has the proper permissions. See https://firebase.google.com/docs/admin/setup for setup instructions.
```

and raw HTML follows, part of which is `<H1>PROJECT_NOT_PERMITTED</H1>`.

### Were you able to successfully deploy your functions?

Yes, and the function is correctly triggered on document creation.

### When you ran `firebase deploy`, did you see any error messages?

No.

---

I also tried initializing the app with this:
```typescript
admin.initializeApp({
    credential: admin.credential.applicationDefault(),
});
```

but according to https://firebase.google.com/docs/admin/setup#initialize-without-parameters it should work without parameters as well.

**Comment by kendolondon** [comment]
Seeing the same error here.  I've checked that the service accounts have got FCM permissions but it's still failing with the same error described here.

**Comment by mandelmonkey** [comment]
I also get this PROJECT_NOT_PERMITTED error

I followed the instructions as follows

```
import admin from 'firebase-admin';

import serviceAccount from '../../common/constants/pushKey.json';
admin.initializeApp({
  credential: firebaseAdmin.credential.cert(serviceAccount),
});
```

and the pushKey is the json generated from

project settings -> service accounts -> firebase admin sdk -> generate new private key

However when calling 

``` admin.messaging().sendToDevice(token, payload) ```

I get the following error

```
<TITLE>PROJECT_NOT_PERMITTED</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>PROJECT_NOT_PERMITTED</H1>
<H2>Error 401</H2>
</BODY>
</HTML>
". Status code: 401.
    at FirebaseMessagingError.<anonymous> (/Users/chris/Documents/ZebedeeApps/booty/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at FirebaseMessagingError.Error (/Users/chris/Documents/ZebedeeApps/booty/node_modules/core-js/modules/es.error.cause.js:28:43)
    at FirebaseMessagingError.FirebaseError [as constructor] (/Users/chris/Documents/ZebedeeApps/booty/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Users/chris/Documents/ZebedeeApps/booty/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseMessagingError (/Users/chris/Documents/ZebedeeApps/booty/node_modules/firebase-admin/lib/utils/error.js:279:16)
    at Object.createFirebaseError (/Users/chris/Documents/ZebedeeApps/booty/node_modules/firebase-admin/lib/messaging/messaging-errors-internal.js:57:12)
    at /Users/chris/Documents/ZebedeeApps/booty/node_modules/firebase-admin/lib/messaging/messaging-api-request-internal.js:79:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errorInfo: {
    code: 'messaging/authentication-error',
    message: 'An error occurred when trying to authenticate to the FCM servers. Make sure the credential used to authenticate this SDK has the proper permissions. See https://firebase.google.com/docs/admin/setup for setup instructions. Raw server response: "<HTML>\n' +
      '<HEAD>\n' +
      '<TITLE>PROJECT_NOT_PERMITTED</TITLE>\n' +
      '</HEAD>\n' +
      '<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n' +
      '<H1>PROJECT_NOT_PERMITTED</H1>\n' +
      '<H2>Error 401</H2>\n' +
      '</BODY>\n' +
      '</HTML>\n' +
      '". Status code: 401.'
  },
  codePrefix: 'messaging'
}
```

Any ideas?

**Comment by mandelmonkey** [comment]
This library works though 
https://www.npmjs.com/package/fcm-notification

**Comment by wujek-srujek** [comment]
I also tried to do it using an exported service account key but it failed in exactly the same way as without doing anything.

What I find strange is that nobody from the Firebase team has done anything, what gives?

**Comment by mandelmonkey** [comment]
> I also tried to do it using an exported service account key but it failed in exactly the same way as without doing anything.
> 
> What I find strange is that nobody from the Firebase team has done anything, what gives?

Yes I also tried that and had the same error, I tried on two accounts as well im suprised this isnt happening more to people, maybe its recent bug in the latest sdk

**Comment by simeonlin** [comment]
I could resolve the same issue by switching from the [legacy-send-message](https://firebase.google.com/docs/cloud-messaging/send-message?hl=en#adminSDK-legacy-send-methods) to the new api: 
https://firebase.google.com/docs/cloud-messaging/send-message?hl=en#send-messages-to-topics

**Comment by wujek-srujek** [comment]
@simeonlin Yes, this is the answer, using the `send` method with a `topic` field does the trick for me. Oh man, why don't they deprecate the other methods?

**Comment by Bircansezgin** [comment]
can anyone help me?

**Comment by mellowcello77** [comment]
I have this issue too for days now. I don't want to send to a topic! What a mission, so frustrating and complicated.

**Comment by sdattatri** [comment]
I am also having the same issue.  I am calling SendTopicMessage from inside a cloud function. Getting PROJECT_NOT_PERMITTED. They say enable the legacy cloud messaging API, which I am unable to do as that link is broken(FAILED TO LOAD). Help, please.
