### ISSUE TITLE
Task queue functions require Authentication header for local testing

### ISSUE THREAD

**Issue by jcapogna** [firebase/firebase-functions#1146]
### [REQUIRED] Version info

**node:**

v16.14.0

**firebase-functions:**
3.21.2

**firebase-tools:**

11.0.1

**firebase-admin:**

10.2.0

### [REQUIRED] Test case

The example for enqueueing functions with Cloud Tasks demonstrates this: https://firebase.google.com/docs/functions/task-functions

### [REQUIRED] Steps to reproduce

- Following the example for enqueueing functions with Cloud Tasks: https://firebase.google.com/docs/functions/task-functions
- Following the steps for testing task queue functions via the emulator by running the CURL command here: https://firebase.google.com/docs/functions/task-functions#testing_task_queue_functions_using_the

### [REQUIRED] Expected behavior

The task queue function is successfully invoked

### [REQUIRED] Actual behavior

Curl returns the following message and the task queue function is not executed.
`{"error":{"message":"Unauthenticated","status":"UNAUTHENTICATED"}}%  `

### Were you able to successfully deploy your functions?

Yes, and they run fine once deployed.

**Comment by jcapogna** [comment]
I'm pretty sure I figured this out already. 

This change was made that requires task queue functions to be passed an Authorization header: https://github.com/firebase/firebase-functions/pull/1073/commits/15abd263b8c93baf6567e19e48745af7a607feed#diff-f1d3e7bf65d7f30ba71b1d716b79fc18d258e565ab3c4cfae7478c3772bdac04R116

As a result, you can test task queue functions via the emulator by including an authorization header. The curl command in the documentation needs to be amended to the following:

```
# trigger the emulated task queue function
 curl -X POST                                            # An HTTP POST request... 
 -H "content-type: application/json" \             # ... with a JSON body 
 -H "Authorization: Bearer <token>" \
 http://localhost:$PORT/$PROJECT\_ID/$REGION/$NAME \ # ... to function URL 
 -d '{"data": { ... some data .... }}'              # ... with JSON encoded data
```

I _think_ the Bearer token needs to be decodable, but I'm not 100% sure on that. 

I can think of a few solutions
1) Modify the documentation to include that an Authorization header is required
2) Do something in the emulator (and shell???) to not require an Authorization header for local testing. 

Hope I got that right. Adding the Authorization header allowed me to test locally.

**Comment by jhuleatt** [comment]
@jcapogna thanks for digging in to this!

@taeold I think this is a bug. Task Queue functions skip authenticating the token since they're guarded by IAM in production, so having to send an auth token to an emulated function doesn't match prod behavior.
