### ISSUE TITLE
Update to support firebase-admin 11.0

### ISSUE THREAD

**Issue by cupidchan** [firebase/firebase-functions#1147]
### [REQUIRED] Version info
firebase-functions@3.21.2

**node:**
v16.15.1

**firebase-functions:**
Not function specific

**firebase-tools:**
11.0.1

**firebase-admin:**
"firebase-admin": "^11.0.0",

### [REQUIRED] Test case
set firebase-admin to version 11 and
run `npm update`

### [REQUIRED] Steps to reproduce
run `npm update`

### [REQUIRED] Expected behavior
No dependencies error 

### [REQUIRED] Actual behavior
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: functions@undefined
npm ERR! Found: firebase-admin@11.0.0
npm ERR! node_modules/firebase-admin
npm ERR!   firebase-admin@"^11.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0" from firebase-functions@3.21.2
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"^3.20.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/cupidchan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cupidchan/.npm/_logs/2022-06-17T12_06_57_471Z-debug-0.log

### Were you able to successfully deploy your functions?
Yes, if I keep firebase-admin to version 10

**Comment by dereekb** [comment]
Running into this myself [on CI](https://app.circleci.com/pipelines/github/dereekb/dbx-components/991/workflows/936ead67-c81a-41bd-8701-166e27c0953a/jobs/2520/parallel-runs/0/steps/0-103).

Looks like there was a version bump a few days ago that got merged into other current changes, but it is to `^10.0.0` in #1139.
