### ISSUE TITLE
Failed to create function: Invalid function service account requested: default

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-functions#1162]
Is there a big breaking changes in Cloud Function? We haven't work with it in a months and now trying to deploy a template function for a new project but it keeps failing.

![image](https://user-images.githubusercontent.com/38008900/177057745-49dfaf51-7a46-45d0-9e58-b625d87a006a.png)

None of the function was created and in the console page this is the error 

`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"Invalid function service account requested: default. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation."},"authenticationInfo":{"principalEmail":"sample@gmail.com"},"requestMetadata":{"callerIp":"110.54.135.39","callerSuppliedUserAgent":"FirebaseCLI/11.2.0,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2022-07-03T21:16:24.084285Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.CreateFunction","authorizationInfo":[{"resource":"projects/sample/locations/asia-northeast1/functions/addedUser","permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}}],"resourceName":"projects/sample/locations/asia-northeast1/functions/addedUser","request":{"@type":"type.googleapis.com/google.cloud.functions.v1.CreateFunctionRequest","location":"projects/sample/locations/asia-northeast1","function":{"name":"projects/sample/locations/asia-northeast1/functions/addedUser","entryPoint":"addedUser","serviceAccountEmail":"default","availableMemoryMb":1024,"runtime":"nodejs10","dockerRegistry":"ARTIFACT_REGISTRY"...`

Tried
`firebase deploy --only functions:addedUser,functions:deleteFacebookUser`

Still no luck

```
Functions deploy had errors with the following functions:
        addedUser(asia-northeast1)
        deleteFacebookUser(us-central1)
i  functions: cleaning up build files...
!  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at
        https://console.cloud.google.com/artifacts/docker/sample/asia-northeast1/gcf-artifacts
        https://console.cloud.google.com/artifacts/docker/sample/us-central1/gcf-artifacts
Error: There was an error deploying functions:
- Error Failed to create function deleteFacebookUser in region us-central1
- Error Failed to create function addedUser in region asia-northeast1
```

**Comment by ArcherEmiya05** [comment]
Hello, any update on this? Badly need a help

**Comment by ArcherEmiya05** [comment]
Still no luck even with a single function
![image](https://user-images.githubusercontent.com/38008900/177151154-370c891e-2e37-4f65-9a4c-fb72f60019ce.png)

**Comment by exKAZUu** [comment]
@ArcherEmiya05 I faced the same issue, but I've fixed the issue by downgrading `firebase-tools` from `11.2.0` to `11.1.0`. Please try it.
c.f. https://github.com/firebase/firebase-tools/issues/4703

**Comment by ArcherEmiya05** [comment]
> @ArcherEmiya05 I faced the same issue, but I've fixed the issue by downgrading `firebase-tools` from `11.2.0` to `11.1.0`. Please try it. c.f. [firebase/firebase-tools#4703](https://github.com/firebase/firebase-tools/issues/4703)

Thank you so much
