### ISSUE TITLE
Adding `runWith({ invoker: "allUsers" })` to  does not update gcf permissions

### ISSUE THREAD

**Issue by Manokii** [firebase/firebase-functions#1190]
### [REQUIRED] Version info

**node:**

**firebase-functions:**
3.22.0
**firebase-tools:**

**firebase-admin:**
10.3.0
### [REQUIRED] Test case
N/A

### [REQUIRED] Steps to reproduce
1. add `.runWith({ invoker: "allUsers" })` to a cloud function
1. deploy the function

### [REQUIRED] Expected behavior
It should reflect in https://console.cloud.google.com/functions/list

### [REQUIRED] Actual behavior
It does not reflect in https://console.cloud.google.com/functions/list

### Were you able to successfully deploy your functions?
yes

**Comment by Manokii** [comment]
Does it update previously created cloud functions or it only works on new functions?

or does this option even work at all

**Comment by colerogers** [comment]
Hi @Manokii thanks for opening an issue at Firebase!

In order to correctly set the IAM policy of the function to `allUsers`, you would write your function like this,
```
.runWith({ invoker: "public" })
```

**Comment by Manokii** [comment]
> Hi @Manokii thanks for opening an issue at Firebase!
> 
> In order to correctly set the IAM policy of the function to `allUsers`, you would define your function like this,
> 
> ```
> .runWith({ invoker: "public" })
> ```

oh i see, I set it up wrong this whole time, thank you very much!
