### ISSUE TITLE
npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by nitinppatil** [firebase/firebase-functions#12]
While installing npm package getting following messages:
...functions>**npm i firebase-functions**
npm WARN package.json time-server-functions@ No repository field.
npm WARN package.json time-server-functions@ No README data
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/jsonwebtoken' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'firebase-functions'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by jwngr** [comment]
If I had to guess, you are using an old version of Node.js / `npm`. I would suggest upgrading Node.js `6.x.x` (which is the environment your Functions will actually run in) and a more recent version of `npm` (which you can update via `npm install -g npm`).
