### ISSUE TITLE
TypeError log will be split into multiple lines

### ISSUE THREAD

**Issue by ishowta** [firebase/firebase-functions#1215]
### [REQUIRED] Version info

**node:** 16

**firebase-functions:** 3.22.0

**firebase-tools:** 10.6.0

**firebase-admin:** 10.0.2

### [REQUIRED] Test case

If a TypeError occurs, the Cloud Logging log will have multiple lines.

```js
// index.js

const functions = require('firebase-functions')

exports.test = functions.https.onRequest(() => {
  'hello'()  // TypeError: "hello" is not a function
})
```

Therefore, if the file path is long, the stack trace will be a completely separate line and will not be treated as an Error.

```js
// index.js

exports.test =
    require('./test-longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong').test

// test-longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong.js

const functions = require('firebase-functions')

exports.test = functions.https.onRequest(() => {
  'hello'()  // TypeError: "hello" is not a function
})
```

![2022-08-31_142701](https://user-images.githubusercontent.com/7393198/187599741-2a29f80b-5819-4c11-84fe-f8021f69fea6.png)

### [REQUIRED] Steps to reproduce

run function

### [REQUIRED] Expected behavior

The errors are combined into a single log and sent to Error Reporting, just like normal errors.

### [REQUIRED] Actual behavior

Split into multiple logs and not sent to Error Reporting

### Were you able to successfully deploy your functions?

yes

**Comment by inlined** [comment]
This is an issue with the backend, which is managed by Cloud. I've forwarded your bug report and will report back later.

**Comment by taeold** [comment]
Unfortunately, GCF integration with Cloud Logging is outside of our control. Can you try filing a [Google Cloud Support ticket](https://cloud.google.com/support-hub) instead?
