### ISSUE TITLE
User beforeCreate blocking function is not triggered when user is created with Admin SDK

### ISSUE THREAD

**Issue by maxijonson** [firebase/firebase-functions#1219]
### [REQUIRED] Version info

**node:16.17.0**

**firebase-functions:3.18.0**

**firebase-tools:11.8.0**

**firebase-admin:10.0.2**

### [REQUIRED] Test case

```typescript
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

export const registerUser = functions.https.onCall(
  async ({ username, email, password }) => {
    const profileDoc = await admin.firestore().collection("profiles").doc();
    profileDoc.set({ username });

    await admin.auth().createUser({
      uid: profileDoc.id,
      email,
      password,
    });
  }
);

export const beforeCreate = functions.auth.user().beforeCreate(async (user) => {
  const uid = user.uid;
  const profileDoc = admin.firestore().collection("profiles").doc(uid);
  const profile = await profileDoc.get();

  if (!profile.exists) {
    throw new functions.https.HttpsError("No profile attached");
  }

  return {
    displayName: profile.data().username,
  };
});

```

### [REQUIRED] Steps to reproduce

1. Call the `registerUser` with a `username`, `email` and `password`
    - e.g.: `{ username: "maxijonson", email: "email@example.com", password: "Abc123" }`

### [REQUIRED] Expected behavior

The `beforeCreate` trigger is called when creating the user from the Admin SDK (`admin.auth().createUser`)

### [REQUIRED] Actual behavior

The `beforeCreate` trigger is never triggered. 

Using the client SDK's `createUserWithEmailAndPassword` does trigger `beforeCreate`. However, because I need to handle a `username` (plus a unique validation I've omitted from the test case for clarity), I've disabled the rights for the client SDK to create users. This way, I can make sure a new user always has a valid profile attached to it.

### Were you able to successfully deploy your functions?

Yes. Functions deploy successfully.

**Comment by taeold** [comment]
Hey @maxijonson - thanks for filing the issue.

I asked some folks and found that creating user using Admin SDK will not trigger Auth Blocking functions. Rationale is that admin SDK should already running in a privileged environment and whatever check you have for blocking user creation doesn't need to blocked for privileged operation.

I feel ambivalent about this, but alas that's how things are. Feel free to file a support case/feature request to Google Cloud Identity Platform if you would like to see an option to trigger blocking function from admin sdk too.

**Comment by zburgermeiszter** [comment]
I have been facing this odd behaviour today.
This is forcing me to duplicate the beforeCreate logic to other parts of the codebase where users are created using the Admin SDk.

**Comment by hashem78** [comment]
This limitation is mega dumb dumb

**Comment by TscharnigAndreas** [comment]
I agree with hashem78
