### ISSUE TITLE
Including auth user in trigger functions

### ISSUE THREAD

**Issue by meena-erian** [firebase/firebase-functions#1237]
### Related issues

This is about issue #300 

Can we please reopen that issue? I can't take no for an answer when asking for something so essential. Are we asking for too much if we ask to include the auth user in the context of trigger functions? Having to go for workarounds for something so basic is not what I would expect when working with a product of GOOGLE! This is frustratingly disappointing!

**Comment by inlined** [comment]
Just like issue #300, this is about infrastructure changes to a product that isn't functions. It is off topic and will be closed.

No new event providers or features to event providers are likely to be added in Cloud Functions for Firebase v1. Firestore is targeting being added to Cloud Functions 2nd generation (and thus Cloud Functions for Firebase v2) in H1 2023. We can then raise the concern with the team then.
