### ISSUE TITLE
is there any way to deploy firebase functions faster?

### ISSUE THREAD

**Issue by malikasinger1** [firebase/firebase-functions#124]
I have little project with about 20 firebase function
 it takes about 4 minutes to deploy even if i deploy single function e.g: `firebase deploy --only functions:webhook`

**Comment by malikasinger1** [comment]
so everytime i deploy the function i have to wait 4 minutes to see it in action (and test it by performing google assistant query)

**Comment by laurenzlong** [comment]
The short answer is no, but it is something we are aware of and are working on. 

For development, you can test your functions locally without needing to redeploy: https://firebase.google.com/docs/functions/local-emulator

**Comment by alexanderkjeldaas** [comment]
Any update on this?

**Comment by flamz3d** [comment]
deploying functions has become a huge bottleneck :(

**Comment by MustafaHossaini** [comment]
> The short answer is no, but it is something we are aware of and are working on.
> 
> For development, you can test your functions locally without needing to redeploy: https://firebase.google.com/docs/functions/local-emulator

Locally , you have to bloody restart the debugger if it something throws an exception. no hot reload feature or is there?
