### ISSUE TITLE
Old (cached?) config values appearing at runtime

### ISSUE THREAD

**Issue by eob** [firebase/firebase-functions#125]
### Steps to reproduce

First I try to update a config value:

`firebase functions:config:set KEY=VAL1`

Then I verify that it's updated

`firebase functions:config:get KEY`

Then I deploy

`firebase deploy --only functions`

But when I access the value at runtime (inside a firebase-function), I see the old value.

**Comment by rjhuijsman** [comment]
Just checking, does the closed issue mean that you found what was causing the behavior you saw? If yes, are you OK with sharing for posterity's sake? :)

**Comment by eob** [comment]
Yes -- sorry. User error. 

In order to run tests on my local machine, I have a wrapper around the firebase-functions library (because it causes problems when included on localhost). 

In production, the wrapper was incorrectly detecting that it wasn't running in GCS, and was loading the test values as a result instead of deferring to Google's notion of config.
