### ISSUE TITLE
Custom claims for functions.auth.user().onDelete is a string

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-functions#126]
### Version info

**firebase-functions:** 0.7.1

**firebase-tools:** 3.13.1

**firebase-admin:** 5.4.2

### Test case

Deploy the following firebase-functions:

```javascript
const functions = require('firebase-functions')
const admin = require('firebase-admin')

exports.onUserCreated = functions.auth.user().onCreate(event => {
    return admin.auth().setCustomUserClaims(event.data.uid, { hello: 'world' })
})

exports.onUserDeleted = functions.auth.user().onDelete(event => {
    const { customClaims } = event.data
    console.log(`Custom claims (type=${typeof customClaims}):`, customClaims)
    return Promise.resolve()
})
```

### Steps to reproduce

Create a user in Firebase and then view the Cloud function logs.

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

The `customClaims` should be an object as per the [`admin.auth.UserRecord`](https://firebase.google.com/docs/reference/admin/node/admin.auth.UserRecord#customClaims)

>`Custom claims (type=object): { hello: 'world' }`

### Actual behavior

The `customClaims` is a string and (it is also not listed on [`functions.auth.UserRecord`](https://firebase.google.com/docs/reference/functions/functions.auth.UserRecord) docs).

>`Custom claims (type=string): {"hello": "world"}`

**Comment by rjhuijsman** [comment]
Thanks for the thorough report! 

I indeed easily reproduced this, with just a few small edits to the suggested repro. Here's the updated code:
```
const functions = require('firebase-functions')
const admin = require('firebase-admin')

admin.initializeApp(functions.config().firebase);

exports.onUserCreated = functions.auth.user().onCreate(event => {
    console.log(JSON.stringify(event.data));
    return admin.auth().setCustomUserClaims(event.data.uid, { hello: 'world' }); 
});

exports.onUserDeleted = functions.auth.user().onDelete(event => {
    console.log(JSON.stringify(event.data));
    const { customClaims } = event.data;
    console.log(`Custom claims (type=${typeof customClaims}):`, customClaims);
    return Promise.resolve();
});
```
This also prints the JSONified `event.data` object, and we see that the backend is indeed sending us a mangled `customClaims` field:
> {"customClaims":"{\"hello\":\"world\"}", ... }

I've taken this up with the team that feeds us this data, I'll update this issue when we have a fix!

**Comment by rjhuijsman** [comment]
This issue is now fixed! A custom claim added to your UserRecord will now arrive in Functions correctly as a JavaScript object. Thanks again for the report!
