### ISSUE TITLE
[DocumentBuilder] Should be triggered if the document.update is being triggered

### ISSUE THREAD

**Issue by EricKwan2014** [firebase/firebase-functions#1265]
### [REQUIRED] Version info

**node:** v12.22.1

**firebase-functions:** 3.20.1

**firebase-tools:** 10.9.2

**firebase-admin:** 10.2.0

### [REQUIRED] Test case
db.collection('myCollection').doc('collectionId').update({ value: 1 })
db.collection('myCollection').doc('collectionId').update({ value: 1 })

and

export const handleUpdate = (_) => console.log('should be triggered');

functions.firestore.document('/myCollection/{collectionId}').onWrite(handleUpdate);

### [REQUIRED] Steps to reproduce

step 1: trigger db.collection('myCollection').doc('collectionId').update({ value: 1 }) once
step 2: handleUpdate is being triggered
step 3: trigger db.collection('myCollection').doc('collectionId').update({ value: 1 }) again
step 4: handleUpdate is not being triggered

### [REQUIRED] Expected behavior
handleUpdate should be triggered twice by definition: https://firebase.google.com/docs/reference/functions/firebase-functions.firestore.documentbuilder.md#firestoredocumentbuilderonwrite
since triggered the update function

### [REQUIRED] Actual behavior

According to the documentation mentioned: 
`Triggered when a document already exists and has any value changed.`
https://firebase.google.com/docs/functions/firestore-events#function_triggers
the handleUpdate function should be triggered twice even the updated data is exact the same with the previous data.
handleUpdate only be triggered once

**Comment by inlined** [comment]
This is working as intended. In your update, no value has changed (you wrote the existing value back to the document). This is by design and helps defend against infinite recursion.
