### ISSUE TITLE
Unhandled error TypeError for creating Firestore FieldValue

### ISSUE THREAD

**Issue by readyiman** [firebase/firebase-functions#1270]
### [REQUIRED] Version info

**node:16**

**firebase-functions:^4.0.1**

**firebase-tools:11.15.0**

**firebase-admin:^11.2.0**

### [REQUIRED] Test case

`admin.firestore.FieldValue.serverTimestamp()`

### [REQUIRED] Steps to reproduce

Write in TS (Not sure if JS affected)

### [REQUIRED] Expected behavior

Should return Field value server Timestamp. This works fine before.

### [REQUIRED] Actual behavior

```
"severity":"ERROR","message":"Unhandled error TypeError: Cannot read properties of undefined (reading 'serverTimestamp')
```

### Were you able to successfully deploy your functions?
I'm using Firebase emulator. Build from TS works fine.

**Comment by readyiman** [comment]
It doesn't work for other FieldValue too.
Had tried downgrade to 3.24.1 doesn't work too.

**Comment by ishowta** [comment]
It appears to be a problem with `firebase-admin`, not `firebase-functions`.
A similar issue is discussed here https://github.com/firebase/firebase-admin-node/discussions/1959

**Comment by readyiman** [comment]
@ishowta thank you very much, if you not commenting I wouldn't know.

It is firebase-admin issue.
