### ISSUE TITLE
Service Account seems to disappear

### ISSUE THREAD

**Issue by fgruchala** [firebase/firebase-functions#1275]
### [REQUIRED] Version info

**node:** 16

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** 11.2.0

### [REQUIRED] Steps to reproduce

1. Deploy via the **firebase-tools CLI** a Cloud Function with a dedicated service account ;
2. Check in the Google Cloud console, when you edit the previous Cloud Function, you can see that this field is blank.

<img width="567" alt="Capture d’écran 2022-10-21 à 18 10 46" src="https://user-images.githubusercontent.com/12196721/197241735-3a38cd04-962c-4143-853a-7ddb8e16dd26.png">

### [REQUIRED] Expected behavior

In the **Google Cloud console** > **Cloud Functions** > edit one
In the **Runtime Service Account**, no change has to be done, the initial service account has to be the same as the previous deployment.

### [REQUIRED] Actual behavior

No error in the deployment but the initial service account seems to be replace by a "blank" one.

### Were you able to successfully deploy your functions?

Yes, but my dedicated service account used to run the Cloud Function has specific IAM rights, so I have a service interrupt for my users.

**Comment by inlined** [comment]
Previously, cloud functions for firebase did not support many Cloud features, so we decided to leave any unspecified fields alone. This confused many customers who expected that deleting a configuration from their code to change that code, so in 4.0 we made a breaking change: your backend will be made to explicitly match what is in your code by default.

You can revert this behavior change using the new `preserveExistingChanges` option, or (recommended) you can specify the serviceAccount your function runs as in code. Both v1 and v2 support a `serviceAccount` option. If you want to specify different service accounts for different projects, I recommend checking out our new support for [parmaterized codebases](https://firebase.google.com/docs/functions/config-env#params) as well.

**Comment by taeold** [comment]
@fgruchala I think we should take a look at this issue separately. Created a new bug!
