### ISSUE TITLE
[Beta] Cannot `import` pre-built parameters, in an ES modules Functions project

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-functions#1276]
The [Beta documentation](https://firebase.google.com/docs/functions/beta/config-env#built-in_parameters) introduces "built-in parameters" that can be used to read:

- project id
- database URL
- storage bucket

I'd like to use them, in an ES modules `functions` context, but it doesn't succeed.

### [REQUIRED] Version info

**node:** 18.11.0

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** (none)

### [REQUIRED] Test case

https://github.com/akauppi/firebase-functions-bug-231022

Follow the instructions in the README.  The code (`functions/index.js`) has a few alternatives I've tried.

### [REQUIRED] Steps to reproduce

(see in the repo)

### [REQUIRED] Expected behavior

Cloud Functions start, I get a project name listed as a string.

>Note: The sample repo also asks for a DatabaseURL. That's bogus, since the `firebase.json` does not define Realtime Database. Please ignore.

### [REQUIRED] Actual behavior

As I see it, there are two problems / bugs:

1. The names actually doing anything are `projectID` and `databaseURL` (the docs have them as `projectId`, `databaseUrl`). This is bug #1.

2. How, still, to get to use them?

### Were you able to successfully deploy your functions?

No. I'm using environment variables that do work, but this new mechanism seemed cleaner, so I wanted to give it a go.

**Comment by akauppi** [comment]
Not really an issue for me, any more. 

I read the values from `FIREBASE_CONFIG` environment value: https://github.com/akauppi/GroundLevel-firebase-es/blob/next.sep22/packages/backend/functions/config.js#L43-L58

**Comment by inlined** [comment]
You can import the params with the following:

```
// javascript
const { projectID, databaseURL } = require("firebase-functions/params");

// typescript
import { projectID, databaseURL } from "firebase-functions/params"
```

But params are very much _not_ strings. You can use params to declare a dependency on configuration and to use arithmetic to configure your functions. For example, the following is valid:

```
import { projectID } from "firebase-functions/params";
import { onRequest } from "firebase-functions/v2/https";

export const hello = onRequest({
  minInstances: projectID.equals("my-prod-project").thenElse(2, 0),
}, (req, res) => {
  res.send("OK");
});
```

To get the value at runtime, use `param.value()`. Note that there _will be no value_ when we evaluate your code for deployment, so you should only call `param.value()` outside of global scope.

**Comment by akauppi** [comment]
I don't need to struggle with this - already turned away from using `firebase-functions/params` in favor of just reading the env.vars.

But, to correct your answer: no, one cannot. There are currently three ways one can declare one's Cloud Functions:

- CommonJS (`require`)
- TypeScript (`import`, transpiled)
- ES modules (`import`, native to Node.js)

The third point is omitted in Firebase documentation / samples for `firebase-functions/params`, though I know that otherwise a) it works and b) seems like a supported use case, by Firebase. I may be mistaken in the latter.
