### ISSUE TITLE
Add ability to serve individual functions

### ISSUE THREAD

**Issue by malikasinger1** [firebase/firebase-functions#128]
if i'm giving command `firebase serve --only functions:webhook` why it is still serving all of the functions which is hundreds of functions in my case

**Comment by rjhuijsman** [comment]
Thanks for the feature request! We don't currently have a filter on `serve` the same way we do for `deploy`, and maybe we should!

If you could expand a bit on your use-case, that'd help us prioritize! Are there particular reasons you have in mind why locally serving just one single function is important to you?

**Comment by malikasinger1** [comment]
in our case we have thousands of functions (most of them are on aws and we are migrating to firebase)
we have divided functions in logical parts such as I'm working on 'conversational interface' part of our application with my 4 people team inthat part we have about 50 functions(all on firebase) so we divide tasks for each day and pick seaprate functions to work on,

we have a large code base write in typescript so In our typical directory structure we have an option to only build and deploy single function (to save time by building all code),
by deploying single function other team members work remain untouched

deploying still take time, so each team member able to build only a part of code and serve it locally it become fast and more productive (if we serve all functions locally it take more resources as i mentioned we have thousands of functions with gigs of node modules)

**Comment by laurenzlong** [comment]
@malikasinger1 Thanks for the context! This is helpful for us to know.

**Comment by malikasinger1** [comment]
sounds good

**Comment by thechenky** [comment]
Thank you for the feature request. This is already in our internal issue tracker, so will close this out.

Internal bug reference: 69807672
