### ISSUE TITLE
https provider not being exported for v1 functions in v4 SDK

### ISSUE THREAD

**Issue by YannicEl** [firebase/firebase-functions#1286]
### [REQUIRED] Version info

**node:** v16.18.0

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** 11.2.0

### Test case

https://stackblitz.com/edit/typescript-z3azkd?file=index.ts

### Steps to reproduce

[](https://stackblitz.com/edit/typescript-z3azkd?file=index.ts)

### Expected behavior

In the V3 SDK the https provider for V1 functions was removed meaning that imports like ```import { CallableContext } from 'firebase-functions/v1/https';``` worked. In V4, as seen in this [commit](https://github.com/firebase/firebase-functions/commit/ffa3a574087e12e0fd866d504328b6a6e3d7f344), the http provider was removed from the ```exports``` field of the root ```package.json```.  Was this a mistake or is this intended behavior?  I am asking because other providers like auth or pubsub are exported just like in V3.

### Actual behavior

![image](https://user-images.githubusercontent.com/42739553/198685266-e0f867ca-19cd-42ca-8d44-675a560102a3.png)

**Comment by taeold** [comment]
@YannicEl Thank you for filing AND writing up a PR. Will try to get this into our next release.

**Comment by YannicEl** [comment]
Thanks a lot. Happy to help

**Comment by inlined** [comment]
Closing this as the fix goes out in our next release (probably today)
