### ISSUE TITLE
4.0.2 typescript cries "Could not find a declaration file for module 'firebase-functions'"

### ISSUE THREAD

**Issue by mmcguff** [firebase/firebase-functions#1297]
### [REQUIRED] Version info 4.0.2 (latest) as of this writing

**node:** 

v16.16.0

**firebase-functions:**
import * as functions from "firebase-functions"; cries when importing into a project. 

See screenshot below:  
![image](https://user-images.githubusercontent.com/10658437/199494636-9732fe61-9c89-40f0-9be9-32e4f4c6cdca.png)

**firebase-tools:**

11.16.0

**firebase-admin:**

run `npm install --save firebase-functions@latest` or `npm install --save firebase-functions@4.0.2`

The error is a typescript error and reads the following:  
`Could not find a declaration file for module 'firebase-functions'. 'c:/repos/upwork/rize-api-proxy/functions/node_modules/firebase-functions/lib/v1/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/firebase-functions` if it exists or add a new declaration (.d.ts) file containing `declare module 'firebase-functions';`

When you try to run command referenced to address the typescript issue, the command fails as this use of types appears to be intend for use within firebase tools.  

### Were you able to successfully deploy your functions?
Yes. 

No error messages when deploying.  This issues appears to only be an issue with typescript stuff crying in 4.0.2.  Doesn't happen in 4.0.1.

**Comment by rix133** [comment]
same problem:
deploys if `import * as functions from "firebase-functions/v1";` but shows lint error:
>"Cannot find module 'firebase-functions/v1' or its corresponding type declarations.",

shows no lint errors if `import * as functions from "firebase-functions/lib/v1";` but does not deploy with error:
>Error: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/v1' is not defined by "exports"

**Comment by exaby73** [comment]
This issue doesn't seem to be reproducible anymore. Therefore, I will close this issue. If you disagree with my decision, please comment and I can reopen it. Thank you
