### ISSUE TITLE
Impossible to find calling IP

### ISSUE THREAD

**Issue by tommyzat** [firebase/firebase-functions#1306]
There is just no way to find out who called a function for V2 functions. All methods for getting the IP address return null.

**Comment by taeold** [comment]
Hi @tommyzat - do you mind sharing more information about the issue?

As for HTTP functions, I think `X-Forwarded-For` header is available to inspect the incoming IP address. Unfortunately, I don't think the same trick can be allowed for background functions, but the ip address for background function seems less useful.
