### ISSUE TITLE
Issue with parameterized configuration using `firebase-functions/params` with emulator 

### ISSUE THREAD

**Issue by apetta** [firebase/firebase-functions#1308]
### [REQUIRED] Version info

**node:** 16.5.0

**firebase-functions:** 4.0.2

**firebase-tools:** 11.16.0

**firebase-admin:** N/A

### [REQUIRED] Steps to reproduce

You will need:

1.  Firebase project with cloud functions enabled
2.  Setup project folder w/ `firebase init functions` and choose Typescript
3. Define a .env and .env.dev with a 'dev' alias setup for the project with sample values
4. Use `defineString` from `firebase-functions/params` (w/ or w/o a default set), and set the name to one of the values in the .env files
5. Run the emulator

### [REQUIRED] Expected behavior

Based on the docs, the `defineString` function should first check the .env files for the value, if not found then use the default, and if default is not set then we are prompted for a value and it is written into an .env file suffixed with your project ID.

### [REQUIRED] Actual behavior

When starting the emulator, it always prompts you for an input even if it's defined in the .env files. Other variables set in the .env files are being read by the dotenv support (via process.env), so the .env files are placed/created correctly. When we provide an input at the prompt, it creates an empty `.env.<project_ID>` file with nothing inside. `defineString` also doesn't like a .env.dev file with a project alias set, because it clashes with a need for the `.env.<project_ID>` file instead and returns the error: `Failed to load function definition from source: FirebaseError: Can't have both dotenv files with projectId (env.[project_ID]) and projectAlias (.env.dev) as extensions.`

### Were you able to successfully deploy your functions?

Didn't attempt, this is an issue with the emulator

**Comment by taeold** [comment]
Hi @apetta - I tried reproducing the error in the latest Firebase CLI (v11.21.0) and Functions SDK (v4.2.0) without success.

Do you mind trying your code again with the latest dependencies?

**Comment by kyoh86** [comment]
While this issue pertains to a conflict between the `projectId` and `projectAlias`, I encountered a similar error during Firebase deployment with a different cause. In my case, the error message was caused by incorrectly setting the alias and projectId to the same value in the `.firebaserc` file.

Instead of:
```json
{
  "projects": {
    "<projectId>": "<projectId>"
  }
}
```
It should be:

```json
{
  "projects": {
    "<alias>": "<projectId>"
  }
}
```

Additionally, if an alias isn't necessary for your project setup, you don't need to include it in the `.firebaserc` file at all.
This particular fix may not directly address the original issue raised here, but I thought it might be helpful for anyone who stumbles upon this thread with a similar error caused by a different reason.
Hope this helps someone!

**Comment by Shahood-Sajid** [comment]
> While this issue pertains to a conflict between the `projectId` and `projectAlias`, I encountered a similar error during Firebase deployment with a different cause. In my case, the error message was caused by incorrectly setting the alias and projectId to the same value in the `.firebaserc` file.
> 
> Instead of:
> 
> {
>   "projects": {
>     "<projectId>": "<projectId>"
>   }
> }
> 
> It should be:
> 
> {
>   "projects": {
>     "<alias>": "<projectId>"
>   }
> }
> 
> Additionally, if an alias isn't necessary for your project setup, you don't need to include it in the `.firebaserc` file at all. This particular fix may not directly address the original issue raised here, but I thought it might be helpful for anyone who stumbles upon this thread with a similar error caused by a different reason. Hope this helps someone!

This was the exact issue I was facing had similar alias and project id, your explanation fixed my problem, thanks
