### ISSUE TITLE
Cannot have secret access on onCustomEventPublished function

### ISSUE THREAD

**Issue by taishi55** [firebase/firebase-functions#1310]
### [REQUIRED] Version info

**node:** 16.15.0

**firebase-functions:**  3.21.0

**firebase-tools:** 11.15.0

**firebase-admin:** 10.2.0

### [REQUIRED] Test case 
```
export const purchased = onCustomEventPublished(
  {
    eventType: "com.stripe.v1.payment_intent.succeeded",
    channel:
      "projects/xxxxx/locations/asia-northeast1/channels/firebase",
    region: "asia-northeast1",
    runWith: {secret: ["SECRET_KEY"]}
  }, async (e) => {
       // do something
  }
}
```

### [REQUIRED] Steps to reproduce

create function
add the code above

### [REQUIRED] Expected behavior

I should get the secret with `process.env.SECRET` within the function

### [REQUIRED] Actual behavior
TYPE ERROR
```
No overload matches this call.
  Overload 1 of 2, '(eventType: string, handler: (event: CloudEvent<any>) => any): CloudFunction<CloudEvent<any>>', gave the following error.
    Argument of type '{ eventType: string; channel: string; region: string; runWith: { secret: string[]; }; }' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(opts: EventarcTriggerOptions, handler: (event: CloudEvent<any>) => any): CloudFunction<CloudEvent<any>>', gave the following error.
    Argument of type '{ eventType: string; channel: string; region: string; runWith: { secret: string[]; }; }' is not assignable to parameter of type 'EventarcTriggerOptions'.
      Object literal may only specify known properties, and 'runWith' does not exist in type 'EventarcTriggerOptions'.
```

### Were you able to successfully deploy your functions?

NO

**Comment by taeold** [comment]
Looks like you are configuring the secrets options using the `runWith` tag in V2. `runWith` is not supported in v2, try this instead:

```js
export const purchased = onCustomEventPublished(
  {
    eventType: "com.stripe.v1.payment_intent.succeeded",
    channel:
      "projects/xxxxx/locations/asia-northeast1/channels/firebase",
    region: "asia-northeast1",
    secret: ["SECRET_KEY"] // LOOK HERE
  }, async (e) => {
       // do something
  }
}
```

**Comment by taishi55** [comment]
@taeold Yes I tried `secrets: ["SECRET_KEY"]`, but I couldn't deploy the function. The error message is `Secret environment variable overlaps non secret environment variable`

Your `secret: ["SECRET_KEY"]` not `secrets: ["SECRET_KEY"]` gives me a type error.

**Comment by taishi55** [comment]
Hello @taeold !
I found some mistakes on [the doc](https://firebase.google.com/docs/functions/beta/config-env#secret_parameters).

First mistake is `const { defineSecret } = require('firebase-functions/params');` .
The correct route is `firebase-functions/v2/params` not `firebase-functions/params`.

Second mistake is the code below on the doc.
```
const discordApiKey = defineSecret('DISCORD_API_KEY');

export const posttodiscord = onRequest(
  { secrets: [discordApiKey },
  (req, res) => {
    const apiKey = discordApiKey.value();
    //…
```

The correct way to define is ` { secrets: [DISCORD_API_KEY] },` not ` { secrets: [discordApiKey },`

**Comment by glorat** [comment]
Thank you for posting this issue as I ran into the error of `Secret environment variable overlaps non secret environment variable` and this was literally the only page that came up in Google.

I don't think the above solution is correct but it may have worked by some chance. Official docs note the correct syntax at https://firebase.google.com/docs/functions/2nd-gen-upgrade

In my case, I discovered the `firebase deploy` for the function was picking up the `.env` file I had and passing it to the v2 google cloud deployment, thus having a conflict with that environment variable and the defined secret. The workaround for me was to rename out the .env file before deploying (or deploy via CI, where there is no local .env file).

I feel this should be categorised as a bug in the v2 functions as it is incredibly dangerous that a local .env file is being picked up.

**Comment by exaby73** [comment]
Hello @taishi55 and @glorat. Looks like both of you are hitting some issues related, but not the same as the original issue. Please raise separate issues for these. With that said, based on the conversation, I cannot conclude whether this issue is fixed or not. Could you confirm @taishi55 if the original issue is still something you face?
