### ISSUE TITLE
Error: Cannot find module 'firebase-functions'

### ISSUE THREAD

**Issue by technohowl** [firebase/firebase-functions#132]
### Version info

**firebase-functions:**  "firebase-functions": "0.7.0"

**firebase-tools:** firebase-tools@3.15.0

**firebase-admin:**  "firebase-admin": "5.4.0" 

### Steps to reproduce

firebase deploy --only functions:myFunction

### Were you able to successfully deploy your functions?

```
functions: updating function myFunction...
⚠  functions[myFunction]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'firebase-functions'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


Functions deploy had errors. To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

### Expected behavior

Function should be deployed. I have been using this project for last 3 months. I started getting this error recently. I don't remember making any changes that would have broken the deployment.

### Actual behavior
Error: Cannot find module 'firebase-functions'

**Comment by mdo5004** [comment]
What was wrong @technohowl ? I'm having the same issue.

**Comment by mdo5004** [comment]
My issue resolved itself on its own, it seems. I deployed, had the error, waited an hour, deployed again, and had no issues. Which, in itself, may be a big issue.

**Comment by justinrosenthal** [comment]
@mdo5004 There was a production incident earlier that was causing this error, but things should be back to normal now!  https://status.firebase.google.com/incident/Functions/17027

**Comment by Mika83AC** [comment]
I'm experiencing this issue right now, but not while deploying the function to Firebase, but when it get's triggered/executed.

**Comment by laurenzlong** [comment]
If anyone experiences something similar in the future (where the error is during execution, not deployment), please open a support ticket at https://firebase.google.com/support/contact/bugs-features/ so it can be triaged properly.
