### ISSUE TITLE
Document event.auth for uid and admin

### ISSUE THREAD

**Issue by chuihinwai** [firebase/firebase-functions#133]
As per [discussion in this StackOverflow answer](https://stackoverflow.com/a/42750880/), Cloud Function events from Realtime Database includes an undocumented object `auth`. It includes an `admin` boolean field, and optionally, a `variable` object that contains an `uid` field.

```
{
  "admin": false,
  "variable": {
    "provider": "<PROVIDER>",
    "provider_id": "<PROVIDER>",
    "user_id": "<UID>",
    "token": {
      // Decoded auth token claims such as sub, aud, iat, exp, etc.
    },
    "uid": "<UID>"
  }
}
```

This is helpful for a Cloud Function to decide if an event should be ignored depending on who triggered it, and would also help avoiding an infinite loop.

I have consulted the [Text Moderation with Cloud Functions](https://github.com/firebase/functions-samples/tree/master/text-moderation) sample code. Unfortunately, a separated field would not be helpful in an delete event. 

Please document the `event.auth` object and make it an official public API. Thanks!

**Comment by daevid66** [comment]
+1 
This data could for example be used in cloud functions to stop flooding attacks from certain accounts, that could be quite hard to do with only security rules.

**Comment by inlined** [comment]
This feature has not been documented because, while it was necessary to make some of our approved APIs work, it did not get approval as an externally facing API. We are working on a new shape for Events in GCF that _will_ meet the bar, but it will look different from this.

**Comment by patrickmichalina** [comment]
Should we expect this to change in the future and this data not be available?

**Comment by laurenzlong** [comment]
It may change in format, but the functionality will not disappear.

**Comment by inlined** [comment]
@patrickmichalina We will not break already-deployed functions, but there will eventually be an SDK update that may make this field go away.

**Comment by patrickmichalina** [comment]
I see, so it sound unsafe to reference at this time. It would be super useful to acquire current user credentials to persist in the DB during these functions. Great work by the way, changing the way I build my apps!

**Comment by laurenzlong** [comment]
Yep, you got it. Thanks for the kind words!

**Comment by chuihinwai** [comment]
@laurenzlong @inlined thanks for the info. Is there a milestone or some place for us to see the progress (now that the issue is closed)?

**Comment by laurenzlong** [comment]
Thanks for the question. Any changes to interface will be part of release notes (https://github.com/firebase/firebase-functions/releases). Unfortunately, the team doesn't currently have at the bandwidth to maintain a public feature/milestone tracker.

**Comment by simkepal** [comment]
Hi,

How is the state of this? It would be great to have this functionality. 

Thank you!

**Comment by laurenzlong** [comment]
Working on it! It'll be a part of our 1.0.0 release (date TBD)

**Comment by marvin-rao** [comment]
Anything on this yet?

**Comment by inlined** [comment]
Coming soon

**Comment by bilalsoomro** [comment]
@sneh-lio The feature was added. Details here: https://stackoverflow.com/a/49796385/1874266

**Comment by sneh-lio** [comment]
> @sneh-lio The feature was added. Details here: https://stackoverflow.com/a/49796385/1874266

Yes, I have been using these for last 2 years, but are these params available in gen 2 functions?

**Comment by inlined** [comment]
2nd gen is built on CloudEvents, and last I checked the team is blocking on trying to get the standards body to ratify this as an approved way of passing auth information. I'll check up on the status there.
