### ISSUE TITLE
"unable to resolve dependency tree" error when deploying a Next.js project with firebase-functions

### ISSUE THREAD

**Issue by mrjackyliang** [firebase/firebase-functions#1335]
### Related issues

There doesn't seem to be a related issue in GitHub.

### [REQUIRED] Version info

**node:** v16.18.1

**firebase-functions:** v4.1.1

**firebase-tools:** N/A

**firebase-admin:** 11.20.0

### [REQUIRED] Test case

```
import { logger } from 'firebase-functions';
```

### [REQUIRED] Steps to reproduce

1. Start a Next.js project with `create-next-app`
2. Install `firebase-functions` and use the library. In my instance, I used `logger` in a the `/src/pages/api/` folder for Next.js.
3. Run `firebase deploy`

### [REQUIRED] Expected behavior

To successfully deploy the Next.js application to Firebase.

### [REQUIRED] Actual behavior

```
[debug] [2023-01-07T22:12:34.391Z] ----------------------------------------------------------------------
[debug] [2023-01-07T22:12:34.392Z] Command:       /Users/user/.nvm/versions/node/v16.18.1/bin/node /Users/user/.nvm/versions/node/v16.18.1/bin/firebase deploy
[debug] [2023-01-07T22:12:34.392Z] CLI Version:   11.20.0
[debug] [2023-01-07T22:12:34.392Z] Platform:      darwin
[debug] [2023-01-07T22:12:34.392Z] Node Version:  v16.18.1
[debug] [2023-01-07T22:12:34.393Z] Time:          Sat Jan 07 2023 17:12:34 GMT-0500 (Eastern Standard Time)
[debug] [2023-01-07T22:12:34.393Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-07T22:12:34.427Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-01-07T22:12:34.427Z] > authorizing via signed-in user (xxx@xxx.xxx)
[debug] [2023-01-07T22:12:34.427Z] [iam] checking project firebaseproject-1234567890 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-01-07T22:12:34.428Z] > refreshing access token with scopes: []
[debug] [2023-01-07T22:12:34.429Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-01-07T22:12:34.429Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-01-07T22:12:34.671Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2023-01-07T22:12:34.672Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-01-07T22:12:34.679Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/firebaseproject-1234567890:testIamPermissions [none]
[debug] [2023-01-07T22:12:34.680Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/firebaseproject-1234567890:testIamPermissions x-goog-quota-user=projects/firebaseproject-1234567890
[debug] [2023-01-07T22:12:34.680Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/firebaseproject-1234567890:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-01-07T22:12:35.050Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/firebaseproject-1234567890:testIamPermissions 200
[debug] [2023-01-07T22:12:35.051Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/firebaseproject-1234567890:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-01-07T22:12:35.052Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/firebaseproject-1234567890 [none]
[debug] [2023-01-07T22:12:35.525Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/firebaseproject-1234567890 200
[debug] [2023-01-07T22:12:35.526Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/firebaseproject-1234567890 {"projectId":"firebaseproject-1234567890","projectNumber":"000000000000000","displayName":"XXXXXXXXXXX","name":"projects/firebaseproject-1234567890","resources":{"hostingSite":"firebaseproject-1234567890"},"state":"ACTIVE","etag":"0000000000000000"}
[debug] [2023-01-07T22:12:36.334Z] defaultcredentials: writing to file /Users/user/.config/firebase/xxx_xxx_xxx_application_default_credentials.json
[debug] [2023-01-07T22:12:53.886Z] Error: Command failed: npm i --omit dev --no-audit
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at prepareFrameworks (/Users/user/.nvm/versions/node/v16.18.1/lib/node_modules/firebase-tools/lib/frameworks/index.js:335:42)
    at async deploy (/Users/user/.nvm/versions/node/v16.18.1/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.
```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxxxx@1.0.0
npm ERR! Found: firebase-functions@4.1.1
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"^4.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-functions@"^3.23.0" from firebase-frameworks@0.6.2
npm ERR! node_modules/firebase-frameworks
npm ERR!   firebase-frameworks@"^0.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Were you able to successfully deploy your functions?

I was able to successfully deploy with an outdated `firebase-functions` warning to Firebase after downgrading `firebase-functions` to `3.23.0`. Trying to use `--legacy-peer-deps` will work on the local side, but once it begins building in the cloud, it will fail again.

```
npm install firebase-functions@3.23.0 && firebase deploy
```

**Comment by blidd-google** [comment]
Hi @mrjackyliang, sorry it took a while for us to get back to you.

We've actually been hard at work on a feature that solves exactly your problem. It's called Firebase Web Frameworks, and it's purpose is to make deploying modern web apps with Firebase an easy and seamless experience (with special attention to Next.js, given it's meteoric rise in popularity). You can check out our [docs here](https://firebase.google.com/docs/hosting/nextjs), and if you have any more issues, feel free to file them at https://github.com/firebase/firebase-tools/issues.

**Comment by mrjackyliang** [comment]
> Hi @mrjackyliang, sorry it took a while for us to get back to you.
> 
> 
> 
> We've actually been hard at work on a feature that solves exactly your problem. It's called Firebase Web Frameworks, and it's purpose is to make deploying modern web apps with Firebase an easy and seamless experience (with special attention to Next.js, given it's meteoric rise in popularity). You can check out our [docs here](https://firebase.google.com/docs/hosting/nextjs), and if you have any more issues, feel free to file them at https://github.com/firebase/firebase-tools/issues.

Isn't that the feature where you enable web frameworks? I already have that enabled, and that's where the bug occurred if I don't keep firebase functions at that particular version.

**Comment by mrjackyliang** [comment]
```
# npm resolution error report

While resolving: project@1.0.0
Found: firebase-functions@4.2.1
node_modules/firebase-functions
  firebase-functions@"4.2.1" from the root project

Could not resolve dependency:
peer firebase-functions@"^3.23.0" from firebase-frameworks@0.6.2
node_modules/firebase-frameworks
  firebase-frameworks@"^0.6.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

@blidd-google can you re-open this? this is not fixed. I do use web frameworks and have `firebase-tools@11.23.1`

**Comment by taeold** [comment]
@mrjackyliang Thanks for getting back to use.

IIUC, the root issue seems to be that the [firebase-framworks package](https://github.com/FirebaseExtended/firebase-framework-tools/blob/aa62d567a73f4b04c4d1849364617a847d3e3315/package.json#L63) doesn't support `firebase-functions` v4. 

IIUC, the `logger` module shouldn't be too different between `v3` and `v4` - is there a problem if you pin your `firebase-functions` dependency to `v4` in your `package.json`?

**Comment by mrjackyliang** [comment]
If I use firebase functions v4, I am unable to deploy to firebase using `firebase deploy`.

I think it has to be the same version or a version lower than that to work.

**Comment by 0xterran** [comment]
I am having this same issue

**Comment by joenewbry** [comment]
Hey also running into this challenge. And solved with with the solution recommended above:

`npm install firebase-functions@3.23.0 && firebase deploy`

Seems like the latest firebase-frameworks package requires an older version of firebase-functions.

<img width="849" alt="Screenshot 2023-04-24 at 4 38 17 PM" src="https://user-images.githubusercontent.com/2561196/234111489-c6c4132f-a126-4a55-81aa-e5cb99ea5f26.png">

**Comment by ChoongLiang** [comment]
Try `npm config set legacy-peer-deps true` then `firebase deploy`, works for me. credit: [Stackoverflow](https://stackoverflow.com/questions/71830754/npm-err-code-eresolve-npm-err-eresolve-unable-to-resolve-dependency-tree-in-re)

**Comment by taeold** [comment]
With https://github.com/FirebaseExtended/firebase-framework-tools/commit/45534ef4382c17caa02c91f60baae78ea8622a23, latest `functions-framework` package should be compatible with the latest `firebase-functions` package.

Please let us know if this continues to be an issuE!
