### ISSUE TITLE
Cannot access req.rawBody without augment.

### ISSUE THREAD

**Issue by Zelfapp** [firebase/firebase-functions#1338]
I need to access the buffer to get the rawBody in order to create a local hmac for validating webhooks. By adding this augment...

```node
declare module 'http' {
  interface IncomingMessage {
    rawBody: unknown
  }
}
```

...my script works, without any typescript errors (rawBody set to "unknown"), and I'm able to create the local hmac successfully by accessing req.rawBody.

Without the augment `req.rawBody` errors: "Property 'rawBody' does not exist on type 'Request<{}". 

In node_modules/firebase-functions/lib/common/providers/https.d.ts I see this, referring to rawBody: Buffer, but how do I access it without the augment?

![image](https://user-images.githubusercontent.com/11559805/212919019-67aed6f6-f804-45ea-92ea-dd9c88c92786.png)

### [REQUIRED] Version info

**node:** v16.16.0
**firebase-functions:** ^4.1.1 (This script is a v2 function)
**firebase-tools:** 11.20.0
**firebase-admin:** ^11.0.1

### [REQUIRED] Test case

```node
import { onRequest } from 'firebase-functions/v2/https'
import { logger } from 'firebase-functions/v2'
import express from 'express'
import cors from 'cors'

const app = express()

// Automatically allow cross-origin requests
app.use(cors({ origin: true }))

// Remove this and req.rawBody will no longer be accessible.
declare module 'http' {
  interface IncomingMessage {
    rawBody: unknown
  }
}

/**
 * Shopify webhooks consumer.
 */
app.post('/ingest', async (req, res) => {
  try {
    logger.info('rawData', String(req.rawBody))

    logger.info(req.body)

    res.send({ process: true })
    return
  } catch (error) {
    logger.info(error)
    res.send({ failed: true })
    return
  }
})

exports.endpoint = onRequest(
  {
    region: ['us-east4'],
  },
  app,
)
```

### [REQUIRED] Steps to reproduce

Add the augment to expose rawBody.

### [REQUIRED] Expected behavior

I should be able to easily access req.rawBody.

### [REQUIRED] Actual behavior

Have to do a workaround that I'm not even sure is correct and likely will break at some point when express or firebase-functions is upgraded.

### Were you able to successfully deploy your functions?

Yes, but not solid.

**Comment by Zelfapp** [comment]
I was able to resolve this by changing `rawBody` to `raw` and avoid the conflict.

```node
declare module 'http' {
  interface IncomingMessage {
    raw: string
  }
}
```

**Comment by Zelfapp** [comment]
If I change augment to the following the argument error goes away for Express app const. However, is this the right way to access req.rawBody?

```node
declare module 'http' {
  interface IncomingMessage {
    rawBody: unknown
  }
}
```

**Comment by colerogers** [comment]
Hi @Zelfapp I think the issue is that typescript is looking at `req` and thinks you are using the Express defined `Request` type and not the Functions SDK since you're defining the handler in `app.post(...)`. At runtime, you will get `req.rawBody` since the Functions SDK injects that for you when place your express app in the Functions HTTP `onRequest` Trigger. 

You can get around this by importing `Request` from `firebase-functions/v2/https` and casting `(req as Request).rawBody`. This works on my end, but let me know if I missed something. Thanks and I'll mark this as closed for now!

Here's what the full code would be:
```
import { onRequest, Request } from 'firebase-functions/v2/https'
import { logger } from 'firebase-functions/v2'
import express from 'express'
import cors from 'cors'

const app = express()

// Automatically allow cross-origin requests
app.use(cors({ origin: true }))

/**
 * Shopify webhooks consumer.
 */
app.post('/ingest', async (req, res) => {
  try {
    logger.info('rawData', String((req as Request).rawBody))

    logger.info(req.body)

    res.send({ process: true })
    return
  } catch (error) {
    logger.info(error)
    res.send({ failed: true })
    return
  }
})

exports.endpoint = onRequest(
  {
    region: ['us-east4'],
  },
  app,
)
```
