### ISSUE TITLE
Can't deploy V2 functions setting memory to 512MiB, nor to 1GiB

### ISSUE THREAD

**Issue by ochoacabriles** [firebase/firebase-functions#1346]
### Related issues

https://github.com/firebase/firebase-tools/issues/4803
https://github.com/firebase/firebase-tools/pull/4823/files/f83d73cd5e0a6b8e2cb244ab2cc3cad2b171ae2a#diff-335210cf49d8d220a2cd4b150e188e5941bfdbd9e8e0eda200e8b8962d053f11R203

### [REQUIRED] Version info

**node: 16**

**firebase-functions: 4.2.0**

**firebase-tools: 11.18.0 and 11.22.0**

**firebase-admin: 11.2.0**

### [REQUIRED] Test case
Deploying a v2 function like this doesn't work:

```js
import { onRequest } from 'firebase-functions/v2/https'

export const myFunction1 = onRequest({ memory: '512MiB' }, (request, response) => {
  response.send('OK');
});
```

This works, though: 
```js
import { onRequest } from 'firebase-functions/v2/https'

export const myFunction2 = onRequest({ memory: '2GiB' }, (request, response) => {
  response.send('OK');
});
```
It also works if memory is not specified (in this case, it defaults to 256MiB) *but only if the value hasn't been changed in google console (I changed it using the GUI to 512MiB and the following deployment failed)*.

### [REQUIRED] Steps to reproduce
Write 2 functions with those configurations. myFunction1 will fail to deploy, while myFunction2 will succeed.

### [REQUIRED] Expected behavior
Both deployments should succeed.

### [REQUIRED] Actual behavior
When setting memory allocation to 512MiB or to 1GiB, the deployment is failing with this message:
>⚠  functions: HTTP Error: 400, Could not update Cloud Run service projects/myproject/locations/europe-west1/services/myFunction1. spec.template.spec.containers.resources.limits.cpu: Invalid value specified for cpu. Total cpu < 1 is not supported with concurrency > 1.

Checking the linked related issues, I think that `memoryGen1Cpu` is being used to map the CPU from memory in this cases (it explains why the message says that cpu is < 1 while using 512MiB and 1GiB but not 2GiB). It shouldn't be that way, though, as it's a v2 function (unless I'm missing something).

### Were you able to successfully deploy your functions?
Yeah, setting memory to 2GiB.

Error messages when firebase deploy was run:
>⚠  functions: HTTP Error: 400, Could not update Cloud Run service projects/myproject/locations/europe-west1/services/myFunction1. spec.template.spec.containers.resources.limits.cpu: Invalid value specified for cpu. Total cpu < 1 is not supported with concurrency > 1.

**Comment by trevor-rex** [comment]
I had this same issue when trying to add minInstances to an existing function. Deleting and redeploying also fixed it. I hope this does not happen in our production environment as deleting a function is less than ideal for app reliability...

**Comment by colerogers** [comment]
Hey folks, I tried to reproduce using `firebase-functions` v`4.3.1` and `firebae-tools` v`11.29.1` and I'm not running into any issues. Anyone running into this, can you update to the latest versions and try again? Thanks

**Comment by pwightman** [comment]
Can confirm that upgrading to `firebase-tools` @ `12.0.0` fixed the issue. Upgrading `firebase-functions` to `4.3.1` alone did not fix it.

**Comment by ochoacabriles** [comment]
Thank you guys!

We fixed it at the moment by setting it to 2GiB, that's why we hadn't answered here before, sorry about that :)
