### ISSUE TITLE
ESM modules are not supported using Javascript even though Google Cloud function support them

### ISSUE THREAD

**Issue by arisAlexis** [firebase/firebase-functions#1349]
### [REQUIRED] 

**node:**
18.13.0

**firebase-functions:** 4.2.0

**firebase-tools:** 11.22.0

**firebase-admin:** 10.3.0

### [REQUIRED] Steps to reproduce
index.js file includes:

```
async function f() {
    const a = await import("b");
}
```

or a plain import on top.

### [REQUIRED] Expected behavior

Should run since Google Cloud Functions support ESM modules for 2 years now.

### [REQUIRED] Actual behavior

Linter error "unexpected token import". Note that adding "type":"module" to package.json doesn't solve the problem since the linter file is recognised as a module etc.

### Were you able to successfully deploy your functions?
no

 29:32  error  Parsing error: Unexpected token import

✖ 1 problem (1 error, 0 warnings)

node:events:491
      throw er; // Unhandled 'error' event
      ^

**Comment by taeold** [comment]
Hi @arisAlexis!

Cloud Functions for Firebase does support deploying functions packaged as ES module. However, it looks like the eslint setting will also need to be configured to get over the linter issue.

I think either of this workaround would work:

1) Disable eslint during deploy by removing predeploy script in your `firebase.json`:

```diff
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ],
      "predeploy": [
--        "npm --prefix \"$RESOURCE_DIR\" run lint"
      ]
    }
  ]
}
```

2. Modify your `.eslintrc.js`'s parser option:
```diff
  parserOptions: {
--    "ecmaVersion": "2018",
++    "ecmaVersion": "latest",
++    "sourceType": "module",
  },
```

Let me know how it goes!
