### ISSUE TITLE
Firebase emulator functions - './lib/logger/compat' not defined

### ISSUE THREAD

**Issue by ryanper** [firebase/firebase-functions#1351]
### [REQUIRED] Version info
node: 16.18.1

firebase-admin :  11.5.0

firebase-functions: 4.2.1

firebase-tools: 11.23.1

### [REQUIRED] Test case

When running firebase emulators  I get the following error:

functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/logger/compat' is not defined by "exports" in <project path>/node_modules/firebase-functions/package.json

I see a difference between versions prior to 4.0.0 which defines an additional export. 

Current version 4.2.1 only exports
```
    "./logger/compat": "./lib/logger/compat.js",
```
Versions prior to 4.0.0 exports 
```
    "./logger/compat": "./lib/logger/compat.js",
    "./lib/logger/compat": "./lib/logger/compat.js",
```

Adding the additional export path in package.json does not trigger the error in firebase functions emulator.

**Comment by taeold** [comment]
Hey @ryanper. Removing export paths under `lib` was one of intentional breaking change for the v4 major release.

IIUC importing from `logger/compat` should be identical to importing `lib/logger/compat`. Is that not the case in your setup? Would love to hear about use case.

**Comment by ryanper** [comment]
Hi @taeold, thanks for that. I think I did not fully understand the error message and started looking first in `/node_modules/firebase-functions`. I had a hunch about the breaking change and just completely missed that my code might reference `lib/logger/compat` directly. So all good my bad for not thinking about that. Thank you.

**Comment by taeold** [comment]
@ryanper Great to hear that it was a simple fix!
