### ISSUE TITLE
Invoker not accepting parameterised configuration

### ISSUE THREAD

**Issue by aldo-roman** [firebase/firebase-functions#1361]
### [REQUIRED] Version info

**node:** v18.14.0

**firebase-functions:** ^4.2.0

**firebase-tools:** ^11.22.0

**firebase-admin:** ^11.5.0

### [REQUIRED] Test case

```ts
import * as functions from 'firebase-functions'
import { defineString } from 'firebase-functions/params'

const SOME_INVOKER = defineString('SOME_INVOKER')

export const getVoicefileForCallFn = functions
	.runWith({
		invoker: [SOME_INVOKER],
	})
	.https.onRequest(...)
```

### [REQUIRED] Steps to reproduce

1. Add the function above to your firebase project

### [REQUIRED] Expected behaviour

The code compiles

### [REQUIRED] Actual behavior

The code does not compile, as `invoker` cannot accept `Param<string>`.

The same code works for `minInstances`, which accepts `Expression<T>`

### Were you able to successfully deploy your functions?

I've had to escape with `defineString(...) as unknown as string`

### Relevant link

https://github.com/firebase/firebase-functions/blob/7d8329b9a0812a5d1313237acdb3481a071fb25c/src/v1/function-configuration.ts#L233

This line needs to also accept `Expression<string>`

**Comment by blidd-google** [comment]
Hi @aldo-roman, thanks for flagging this. We are working on parametrizing every runtime configuration option. I'm going to go ahead and close this issue, but please stay tuned for those changes!
