### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by gmcdowell** [firebase/firebase-functions#1364]
### Related issues

#383 
#303

### [REQUIRED] Version info

na

**node:**

na

**firebase-functions:**

**firebase-tools:**

na

**firebase-admin:**

### [REQUIRED] Test case

na

### [REQUIRED] Steps to reproduce

na

### [REQUIRED] Expected behavior

Us developers SHOULD be able to use a single language in our Flutter projects. Enough is enough!!!

### [REQUIRED] Actual behavior

na

### Were you able to successfully deploy your functions?

na

**Comment by blidd-google** [comment]
Hi all, thanks for voicing your support for Dart — while the team has definitely taken note of the enthusiasm around this feature request, unfortunately official Dart support is not on our short-term roadmap. Google Cloud Functions does not officially support Dart as a runtime, and Cloud Functions for Firebase will likely be stuck without Dart support either until GCF decides to make that investment. If you are intent on writing your functions in Dart, you could consider using the [Functions Framework for Dart](https://pub.dev/packages/functions_framework) to write Dart functions on Google Cloud Run.

I'm going to close this issue for now, but we promise we've noticed everyone's interest!
