### ISSUE TITLE
Unable to connect Cloud SQL with Firebase Functions V2

### ISSUE THREAD

**Issue by service-paradis** [firebase/firebase-functions#1366]
### Related issues

#1217 that were closed without proper resolution.

### [REQUIRED] Version info

**node:** 18.13.0

**firebase-functions:** 4.2.1

**firebase-tools:** 11.24.1

**firebase-admin:** 11.5.0

### [REQUIRED] Test case

I am attempting to migrate a Firebase Functions project from V1 to V2 to try out beta features. However, it appears that Cloud SQL connections are not yet supported in V2, and there is no mention of this in the documentation.

### [REQUIRED] Steps to reproduce

1. Create a Firebase Function that connects to a Cloud SQL database using a socket path like /cloudsql/INSTANCE_CONNECTION_NAME.
2. Call this function.
3. Receive an `ENOENT` error that was not received using V1.

### [REQUIRED] Expected behavior

I expected that Cloud SQL would be available to the function as it was in V1.

### [REQUIRED] Actual behavior

Here's an improved version of the issue, taking into account the provided template:

Related issues
I found no related issues.

[REQUIRED] Version info
node: v18.13.0

firebase-functions: v4.2.1

firebase-tools: v11.24.1

firebase-admin: v11.5.0

[REQUIRED] Test case
I am attempting to migrate a Firebase Functions project from V1 to V2 to try out beta features. However, it appears that Cloud SQL connections are not yet supported in V2, and there is no mention of this in the documentation.

[REQUIRED] Steps to reproduce
Create a Firebase Function that connects to a Cloud SQL database using a socket path like /cloudsql/INSTANCE_CONNECTION_NAME.
Call this function.
Receive an ENOENT error that was not received using V1.
[REQUIRED] Expected behavior
I expected that Cloud SQL would be available to the function as it was in V1.

[REQUIRED] Actual behavior

I received an ENOENT error while trying to connect to the database. According to https://cloud.google.com/sql/docs/mysql/connect-run?hl=fr#console, it looks like I would need to add a Cloud SQL connection to my service. However, I am unsure how to do this while deploying my function using Firebase Tools.

### Were you able to successfully deploy your functions?

Yes, without any errors. The function itself seems to be working as expected, but it cannot connect to a Cloud SQL instance.

It would be helpful if the Firebase Functions documentation clearly stated whether Cloud SQL connections are currently supported in V2 or not.

Ideally, Cloud SQL database connections should be established seamlessly, without requiring any manual service updates. In version 1 of Firebase Functions, Cloud SQL database connections were automatically supported. Therefore, it is reasonable to expect that version 2 should also provide this functionality with minimal additional effort.

**Comment by Berlioz** [comment]
V2 Functions are backed by Cloud Run, so I would have a look at the docs for connecting a Run container to Cloud SQL (https://cloud.google.com/sql/docs/mysql/connect-run) and see if that works (you can find the underlying Cloud Run container via the Google Cloud Console). I will definitely pass on the feedback about the documentation being clearer.

**Comment by service-paradis** [comment]
Hello @Berlioz, thank you for following up. However, as stated in the original thread (https://github.com/firebase/firebase-functions/issues/1217), we have attempted several solutions without success.

Even if a solution is found, V1 already works automatically, so it would be beneficial if connecting to a Cloud SQL instance using V2 could be made as simple as it was before.

**Comment by service-paradis** [comment]
Hello @taeold and @Berlioz,

I apologize for tagging both of you, but I was hoping you could shed some light on why this issue is still closed. As far as I can see, there are no solutions available for using Cloud SQL in V2 functions, while it was automatically supported in V1. Could you please provide more information on this issue and whether there are any plans to address it?

As mentioned in my previous message, I think it would be beneficial if connecting to a Cloud SQL instance using V2 could be made as simple as it was before.

Thank you for your time and assistance.

**Comment by taeold** [comment]
Hey @service-paradis! Do you mind opening up a new issue. I'm worried that we'll miss your feedback since we do not have a good process for surfacing comments in closed issues.

**Comment by service-paradis** [comment]
Thank you for your response, @taeold. I appreciate your help. However, this will be the third ticket created for the same issue. Nonetheless, I will proceed to open a new one.
