### ISSUE TITLE
v4.2.1 Database initialized multiple times when getting admin.database() reference

### ISSUE THREAD

**Issue by vojdan** [firebase/firebase-functions#1367]
### Related issues
N/A

### [REQUIRED] Version info

**node:** v16.16.0

**firebase-functions:** 4.2.1

**firebase-tools:** 11.22.0

**firebase-admin:** 10.3.0

### [REQUIRED] Test case

I upgraded my working app from `firebase-functions@4.2.0` to `firebase-functions@4.2.1`

### [REQUIRED] Steps to reproduce

Execute the `admin.database()` command to get the realtime database instance.

The error I get is:
`FIREBASE FATAL ERROR: Database initialized multiple times. Please make sure the format of the database URL matches with each database() call.`

Another error also appeared when trying to get FieldValue . Where previously getting a reference like admin.firestore.FieldValue worked, it suddenly started returning undefined and Googling I found I could get a reference from `import { FieldValue } from 'firebase-admin/firestore';`  where before I used `import * as admin from 'firebase-admin';`

### [REQUIRED] Expected behavior

Everything works.

### [REQUIRED] Actual behavior

Error: FIREBASE FATAL ERROR: Database initialized multiple times. Please make sure the format of the database URL matches with each database() call

### Were you able to successfully deploy your functions?

Didn't try.

**Comment by blidd-google** [comment]
Hi @vojdan, thanks for flagging this issue. Could you provide a small example that allows us to reproduce your error? Are you getting your error when trying to start the functions emulator or when trying to deploy?
