### ISSUE TITLE
`event.data.val()` is `null` in unit tests

### ISSUE THREAD

**Issue by zgosalvez** [firebase/firebase-functions#137]
### Version info
**firebase-functions:** 0.7.3
**firebase-tools:** 3.15.3
**firebase-admin:** 5.5.1

### Test case

```ts
//
// In unit test
//
// ...
user = {
  firstName: 'me'
};
event = {
  params: {
    userId: 'user-id',
  },
  data: new functions.database.DeltaSnapshot(null, null, null, user)
};
console.log(event.data.val()); // 1st log
await myFunctions.onUserWrite(event);
// ...
```
```ts
//
// In onUserWrite
//
export.onUserWrite = functions.database.ref('/users/userId').onWrite(async event => {
  // ...
  console.log(event.data.val()); // 2nd log
  // ...
);
```

### Were you able to successfully deploy your functions?

No, since unit tests fail, but manually deploying (skipping unit tests) shows no issues.

### Expected behavior

1st and 2nd logs, should both show `user` object.

### Actual behavior

- 1st log shows `null`
- 2nd log shows `null`

---

Reverting back to **firebase-functions:** 0.7.2 fixes the issue.

**Comment by laurenzlong** [comment]
@zgosalvez Thanks for pointing this out! We recently changed the signature of DeltaSnapshot, and this led to the accidental affect of breaking unit tests. I'll make a PR to mend this.

**Comment by zgosalvez** [comment]
Thanks, @laurenzlong ! When can we expect this fix to be released?

**Comment by laurenzlong** [comment]
It'll be released in the next few days, you can see the release notes at https://github.com/firebase/firebase-functions/pull/145
