### ISSUE TITLE
Unexpected token 'export' error in jest unit tests after upgrading to firebase functions v4

### ISSUE THREAD

**Issue by amkoehler** [firebase/firebase-functions#1373]
After upgrading firebase-functions to v4, I started receiving the dreaded `Unexpected token 'export'` error in our unit tests, specifically with the `firebase-functions/lib/logger` module. This typically occurs when jest is trying to load an ECMAScript module, but I'm not educated enough on that to know if it's for sure the issue here. 

Jest provides a few solutions (noted in the error below), none of which have worked for me. There other popular suggestions ([here](https://stackoverflow.com/a/49676319/1569757) and [here](https://github.com/react-dnd/react-dnd/issues/3443)), and those didn't work either. Hoping this is a simple jest config issue, but so far I have hit a wall. 

### Related issues

n/a

### [REQUIRED] Version info

**node:** 16.20.0

**firebase-functions:** 4.2.1

**firebase-tools:** 11.25.3

**firebase-admin:** 11.6.0

### [REQUIRED] Test case

I set up a repo [here](https://github.com/amkoehler/firebase-functions-v4-jest-error) that recreates the issue. 

### [REQUIRED] Steps to reproduce

See README of my repo for details on how to run locally.

### [REQUIRED] Expected behavior

The tests should continue to pass as they did with v3 of `firebase-functions`

### [REQUIRED] Actual behavior

```bash
~/dev/tinkering/firebase-functions-v4-jest-error main*
❯ npx nx run test-node-app:test

> nx run test-node-app:test

● Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/packages/test-node-app" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

 FAIL   test-node-app  packages/test-node-app/src/main.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    .../firebase-functions-v4-jest-error/node_modules/firebase-functions/lib/logger/index.d.ts:5
    export declare type LogSeverity = "DEBUG" | "INFO" | "NOTICE" | "WARNING" | "ERROR" | "CRITICAL" | "ALERT" | "EMERGENCY";
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/@jest/core/node_modules/jest-runtime/build/index.js:1495:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.4 s
Ran all test suites.
```

### Were you able to successfully deploy your functions?

n/a. No deployment is necessary for running tests.

**Comment by Maddemacher** [comment]
I had a similar issue with the @firebase/util package and i added a moduleNameMapper for that dependency to force it to use the main export of @firebase/util which in my case was commonjs instead of an esm

```
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testPathIgnorePatterns: ["lib"],
  moduleNameMapper: {
    "@firebase/util": require.resolve('@firebase/util'),
  },
  setupFiles: ["<rootDir>/jest/setup.ts"],
};
```

Maybe that is of some use to you

**Comment by amkoehler** [comment]
I noticed the [docs](https://firebase.google.com/docs/functions/writing-and-viewing-logs) now show the import as `firebase-functions/logger` instead of `firebase-functions/lib/logger`. Updating my imports resolved the issue.
