### ISSUE TITLE
Error in v2 Firestore Triggers Documentation or Type Information

### ISSUE THREAD

**Issue by trevor-rex** [firebase/firebase-functions#1386]
### [REQUIRED] Version info

**node:**

16.16.0

**firebase-functions:**

4.3.1

**firebase-tools:**

11.30.0

**firebase-admin:**

11.5.0

### [REQUIRED] Test case

```
import { onDocumentCreated } from "firebase-functions/v2/firestore";
export const myFunction = onDocumentCreated(
  "collection/{doc}",
  async (event) => {

    event.data.after.data(); //hover over or check typing for event.data.after
    ...
})
```

### [REQUIRED] Steps to reproduce

1. Write the above code in a Node.js environment, and see that there is a type error on the first line of the function
2. Hover over `event` and see that it is typed as a `FirestoreEvent<QueryDocumentSnapshot | undefined, {
    doc: string;
}>` without any `before` or `after` fields.

### [REQUIRED] Expected behavior

I would expect to be able to use the same syntax as is in the documentation for v2 firestore triggers:
https://firebase.google.com/docs/functions/beta/firestore-events#reading_and_writing_data
`event.data.after.data()`

### [REQUIRED] Actual behavior

I cannot do so because `event` is a 
```
FirestoreEvent<QueryDocumentSnapshot | undefined, {
    doc: string;
}>
```

### Were you able to successfully deploy your functions?

I have not yet tried, as I do not know if the typing or the documentation is correct.

**Comment by trevor-rex** [comment]
Looking closer, I believe that the type information is correct and that the documentation is just wrong/misleading. It doesn't make sense for there to be a `before` or `after` on an `onDocumentCreated` event, so I believe the first example on the documentation I linked should either be updated to be
```
import {
  onDocumentCreated,
  Change,
  FirestoreEvent
} from "firebase-functions/v2/firestore";

exports.createuser = onDocumentCreate("users/{userId}", (event) => {
    // Get an object representing the document
    // e.g. {'name': 'Marie', 'age': 66}
    const newValue = event.data.data();

    // access a particular field as you would any JS property
    const name = newValue.name;

    // perform more operations ...
});
```

or it should use a different trigger to demonstrate the `after` syntax
```
import {
  onDocumentWritten,
  Change,
  FirestoreEvent
} from "firebase-functions/v2/firestore";

exports.createuser = onDocumentWritten("users/{userId}", (event) => {
    // Get an object representing the document
    // e.g. {'name': 'Marie', 'age': 66}
    const newValue = event.data.after.data();

    // access a particular field as you would any JS property
    const name = newValue.name;

    // perform more operations ...
});
```

**Comment by taeold** [comment]
Thank you so much for pointing out this issue. I will get the documentation updated asap.

**Comment by taeold** [comment]
Updated doc is now alive! Thank you so much for your help improving our documentations!
