### ISSUE TITLE
Firebase Alert triggers in v2 do not scope correctly in Firebase Console if opts parameter is used

### ISSUE THREAD

**Issue by JRR-OSU** [firebase/firebase-functions#1387]
Hi there,

To provide some context on the below issue, I am attempting to build a Slack bot that will provide custom behavior for alert triggers in our iOS and Android apps. For this to work, I need to build functions which will scope to the individual project IDs which correspond to our Android and iOS apps in the Firebase project respectively. However, I noticed that the only way I can get a function to appear to correctly scope in the Firebase console is if I use the string appId version of the function. Based on what the docs say I believe I should also be able to pass opts as well and scope it this way, but that does not result in the expected behavior after deployment.

Additionally I ran into another issue in that I cannot use environment variables outside of my function scope. This is likely the expected behavior as I understand it, but I would like to ask the team what are the best practices / recommendations here now that config() is deprecated? I'd like to just scope my appIds to variables that exist at the file scope but not have to hard code them. The docs haven't elucidated this for me since it appears a lot of it hasn't been updated for V2 yet. 

### Related issues

N/A.

### [REQUIRED] Version info

**node:** v16.15.1

**firebase-functions:** 11.28.0

**firebase-tools:** 11.28.0

### [REQUIRED] Test case

```
const {
  onNewFatalIssuePublished
} = require("firebase-functions/v2/alerts/crashlytics");

const https = require("https");

const IOS_APP_ID = `firebase_app_id_here`;

exports.postfatalissuetoslack = onNewFatalIssuePublished({ appId: IOS_APP_ID }, async (event) => {
  const appId = event.appId;
  const {id, title, subtitle, appVersion} = event.data.payload.issue;
  const PROJECT_ID = `${process.env.PROJECT_ID}`;
  const BUNDLE_ID = `${process.env.BUNDLE_ID}`;
   ...
   // post information to Slack
});
```

### [REQUIRED] Steps to reproduce

Deploy the above function in an iOS firebase project. Observe that in the console the function is not scoped to the app id. 

### [REQUIRED] Expected behavior

The expected behavior is like this example:
```
const {
  onNewFatalIssuePublished
} = require("firebase-functions/v2/alerts/crashlytics");

const https = require("https");

/* Unfortunately until Firebase supports environment variables outside of function scope,
   it is necessary to hardcode the app ID for scoping each function.
*/
const IOS_APP_ID = `firebase_app_id_here`;

exports.postfatalissuetoslack = onNewFatalIssuePublished(IOS_APP_ID, async (event) => {
  const appId = event.appId;
  const {id, title, subtitle, appVersion} = event.data.payload.issue;
  const PROJECT_ID = `${process.env.PROJECT_ID}`;
  const BUNDLE_ID = `${process.env.BUNDLE_ID}`;
   ...
   // post information to Slack
});
```

The above example correctly will scope the function to `IOS_APP_ID`

### [REQUIRED] Actual behavior

     
Actual behavior of what happens is that the function is marked "ALL PROJECTS" when deployed to the firebase console, though with the opts param one would think it should just be scoped to IOS_APP_ID.
    
### Were you able to successfully deploy your functions?

I was able to successfully deploy the latter example, however the issue is that because the variable resides out of the function scope, I cannot use .env or a secret to keep my IOS_APP_ID. It will have to be hardcoded for the example to work. Is there any way in V2 to store config variables that can be used to scope functions? It seemed like passing opts would work for this, but it did not. 

Please let me know if there is something wrong with my approach here and the best practice on how to scope these alert triggers on a per-project basis. Thank you!

**Comment by JRR-OSU** [comment]
I'm not sure if @taeold or another team member would be willing to weigh in here on the best practice for scoping and whether this is indeed a bug or not. Any advice is much appreciated; thanks!

**Comment by inlined** [comment]
In preparation for some future features we're planning, we don't provide environment variables when analyzing your function. To allow you to dynamically configure your functions, however, we offer [params](https://firebase.google.com/docs/functions/config-env?gen=2nd#parameter_types). Params are special in two ways:

1. They automatically become placeholders during code analysis
2. The CLI will ensure they exist before your function is deployed

So you can say:

```
const {
  onNewFatalIssuePublished
} = require("firebase-functions/v2/alerts/crashlytics");
const params = require("firebase-functions/params");

const https = require("https");

const appId = params.defineString("IOS_APP_ID", {
  description: "The iOS app ID to monitor, as provided by the Firebase console"
});
const bundleId = params.defineString("BUNDLE_ID");

// Params can be used directly in configs:
// Also, you can now use capital letters in 2nd gen functions! 🎉
exports.postFatalIssueToSlack = onNewFatalIssuePublished({appId}, async (event) => {
  const appId = event.appId;
  const {id, title, subtitle, appVersion} = event.data.payload.issue;
  
  // Access params' bound values at runtime
  const BUNDLE_ID = bundleId.value();

  // some params are built in
  const PROJECT_ID = params.projectId.value();

   ...
   // post information to Slack
});
```

**Comment by csongorkeller** [comment]
I'm just wondering whether the crashlytics triggeres are working at all, since here it says that they were deprecated:https://github.com/firebase/firebase-functions/issues/863

What's the status then with the Crashlytics Cloud triggers? Are they working or deprecated fully?
