### ISSUE TITLE
Functions V2 do not expose eventId (pubsub, tasks providers)

### ISSUE THREAD

**Issue by mpsq** [firebase/firebase-functions#1388]
### [REQUIRED] Version info

node: 18

firebase-functions: 4.4

firebase-tools: 11.30

firebase-admin: 11.7

### [REQUIRED] Expected behavior

This library provides functions V1 with a context parameter that has a unique `eventId` property. This value is extremely useful for custom tracing / logging.

### [REQUIRED] Actual behavior

Functions V2 lack of this property, only Firestore triggers have an `eventId`. Functions created from the `pubsub` and `tasks` providers do not have this information.

**Comment by colerogers** [comment]
Hi @mpsq the V2 functions have events published through [Eventarc](https://cloud.google.com/eventarc/docs) and the use the [CloudEvent](https://github.com/cloudevents/spec) standard. This spec has a required property on all events called `id`. You should be able to simply use `event.id` inside your V2 function to create a similar workflow as V1. Thanks!

**Comment by mpsq** [comment]
Thank you for the quick answer. However I don't think this issue should be closed. After investigating this repository, my findings are:

- :green_circle: `FirestoreEvent` (`onDocument*`), Event has an `id` like you said (since [Event extends CloudEvent](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/v2/providers/firestore.ts#L86))
- :green_circle: `PubSub` (`onMessagePublished`) has an `id` ([the Event is a CloudEvent directly](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/v2/providers/pubsub.ts#L287))
- :red_circle: HTTP functions (`onRequest`) do not, they receive [a Request](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/common/providers/https.ts#L45) which is basically an express `Request`
- :red_circle: `Tasks` (`onTaskDispatched`) functions do not, they use [a custom `Request` type](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/common/providers/tasks.ts#L96)
- :red_circle: `Scheduled` (`onSchedule`) functions do not, `ScheduleEvent` [does not extend CloudEvent](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/v2/providers/scheduler.ts#L79)

For the last 3 events, is there a way to get the `event.id` that you mentioned? The code seems to be showing that it is not possible, for reference, this was possible with functions v1 (via the [EventContext](https://github.com/firebase/firebase-functions/blob/47cfc61b52448e711af9261722049af58471b545/src/v1/cloud-functions.ts#L91).

Thank you.

**Comment by colerogers** [comment]
Hey @mpsq if you noticed in the [docs](https://firebase.google.com/docs/functions), both Tasks & Scheduled functions are grouped under `Call functions directly` and not `Trigger background functions`. They are HTTP functions that are directly invoked from Cloud Tasks and Cloud Scheduler. Since they're not events, the `id` field or extending a CloudEvent doesn't really make sense. You can read more about them [here](https://firebase.google.com/docs/functions/task-functions?gen=2nd) and [here](https://firebase.google.com/docs/functions/schedule-functions?gen=2nd).

For logging, I'd probably just use a timestamp for Tasks and maybe the `scheduleTime` property for Scheduled functions.

**Comment by mpsq** [comment]
Thanks for the details and links. Overall it makes sense. I will have a go at this, I might be able to compute a tracing id like cloud logging does for http fns (since they are http fns too!). If not I will use the scheduleTime and timestamp 👌
