### ISSUE TITLE
Any firebase-tools version after 11.17.0 fails to deploy (Failed to find location of Firebase Functions SDK)

### ISSUE THREAD

**Issue by snorreks** [firebase/firebase-functions#1389]
If i try to use any versions after firebase-tools 11.17.0, i get "Failed to find location of Firebase Functions SDK" error. I have also tried the latest firebase-tools 12.0.0, and i get the same error. I have tried to uninstall and install firebase-tools again. Using pnpm and global.
`firebase deploy --only functions`
`pnpm firebase deploy --only functions`
But get the same error.

### [REQUIRED] Version info

**node:** 18.14.2

**firebase-functions:** 4.4.0

**firebase-tools:** 11.17.0

**firebase-admin:** 11.8.0

**os:** Windows 11 Pro, 22H2, 22621.1105

### [REQUIRED] Steps to reproduce

1. Deploy any function using `firebase deploy --only functions`
2. Notice that no function can deploy.

### [REQUIRED] Expected behavior

Expect to deploy the functions.

### [REQUIRED] Actual behavior

[firebase-debug.log](https://github.com/firebase/firebase-functions/files/11438086/firebase-debug.log)

### Were you able to successfully deploy your functions?

No. I get this error
```bash
i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  artifactregistry: required API artifactregistry.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled

Error: Failed to find location of Firebase Functions SDK. Please file a bug on Github (https://github.com/firebase/firebase-tools/).
```

**Comment by snorreks** [comment]
Noticed i am in firebase-tools, moved the issue to https://github.com/firebase/firebase-tools/issues/5822.

**Comment by mileslow** [comment]
this is happening to me as well
