### ISSUE TITLE
failurePolicy option is not being applied to scheduled functions

### ISSUE THREAD

**Issue by yohannyc** [firebase/firebase-functions#1390]
### Related issues

N/A

### [REQUIRED] Version info

**node:**

v18.13.0

**firebase-functions:** 

4.2.1

**firebase-tools:** 

11.22

**firebase-admin:**

11.5.0

### [REQUIRED] Test case

Setting failurePolicy to true on a scheduled function doesn't update its configuration.

```ts
import * as functions from 'firebase-functions';

export const myFunction = functions
  .runWith({ timeoutSeconds: 120, failurePolicy: true })
  .pubsub.schedule('0 1 1 * *')
  .onRun((event) => {
    if (new Date().getTime() > Date.parse(event.timestamp) + eventMaxAgeMs) {
      console.log(`Dropping myFunction execution`);
      return;
    }
    myFunction();
  });
```

The failurePolicy option does work on pubsub functions though. So this one that is not a scheduled function works:

```ts
import * as functions from 'firebase-functions';

export const myFunction = functions
  .runWith({ failurePolicy: true })
  .pubsub.topic('topic')
  .onPublish(myFunction)
```

### [REQUIRED] Steps to reproduce

Set the failurePolicy option to true on a scheduled function and deploy, it will not change the function configuration to retry on failure.

### [REQUIRED] Expected behavior

If the failurePolicy option is set to true on a scheduled function, it should update the function configuration and retry on failure.

### [REQUIRED] Actual behavior

Setting the failurePolicy to true on a scheduled function doesn't update the function's configuration thus it doesn't retry on failure.

### Were you able to successfully deploy your functions?

I was able to successfully deploy the functions.

**Comment by blidd-google** [comment]
@yohannyc, thanks for pointing this out. I'd agree that it's a bit misleading and unexpected that setting `failurePolicy` via `runWith` doesn't result in any changes in the function configuration, but the preferred way for configuring retries for 1st gen scheduled functions is to use `retryConfig(...)`. For example:
```
import * as functions from 'firebase-functions';

export const myFunction = functions
  .pubsub.schedule('0 1 1 * *')
  .retryConfig({
    retryCount: 5,
    maxRetrySeconds: 120,
    maxDoublings: 3,
    minBackoffSeconds: 30,
    maxBackoffSeconds: 60
  })
  .onRun((event) => {
    ...
  });
```
I'd also recommend giving 2nd gen scheduled functions a try! The syntax is similar:
```
import { onSchedule } from 'firebase-functions/v2/scheduler';

export const myFunction = onSchedule(
  { 
    retryCount: 5, 
    maxRetrySeconds: 120,
    ...
  }, 
  '0 1 1 * *',
  (event) => {
    ...
  });
```

Here are the [docs](https://firebase.google.com/docs/functions/schedule-functions?gen=2nd) for more details about using 2nd gen scheduled functions. Hope this helps!
