### ISSUE TITLE
Unable to deploy functions using runtime service acct env vars

### ISSUE THREAD

**Issue by amsipe** [firebase/firebase-functions#1392]
### Related issues

[custom params](https://github.com/firebase/firebase-functions/issues/1369)

### [REQUIRED] Version info

**node:** v16.14.0

**firebase-functions:** v4.4.0

**firebase-tools:** 11.30.0

**firebase-admin:** 11.5.0

### [REQUIRED] Test case

Create a `.env.<projectId>` file.
```env
RUNTIME_SA=my-custom-sa@project.iam.gserviceaccount.com
```
Example function:
```js
const { defineString } = require('firebase-functions/params');
const paramSA = defineString('RUNTIME_SA');

const RUNTIME_OPTS = {
  serviceAccount: paramSA,
}
exports.helloWorld = functions.runWith(RUNTIME_OPTS).https.onCall(async (data, context) => {
    return true;
});
```

### [REQUIRED] Steps to reproduce

run `firebase deploy --debug --only functions:helloWorld --project <projectId>`

### [REQUIRED] Expected behavior

Deploy success with serviceAccount linked in config.

### [REQUIRED] Actual behavior

    "message": "HTTP Error: 400, Invalid function service account requested: {{ params.RUNTIME_SA }}.

### Were you able to successfully deploy your functions?

Redacted logs but still show issue:
{
  "endpoint": {
    "id": "...",
    "project": "...",
    "region": "us-central1",
    "entryPoint": "<functionName>",
    "platform": "gcfv1",
    "runtime": "nodejs16",
    "callableTrigger": {},
    "labels": {
      "deployment-tool": "cli-firebase"
    },
    "serviceAccount": "{{ params.RUNTIME_SA }}",
    "ingressSettings": null,
    "availableMemoryMb": 128,
    "timeoutSeconds": 20,
    "maxInstances": null,
    "minInstances": null,
    "vpc": null,
    "environmentVariables": {
      "RUNTIME_SA": "my-custom-sa@project.iam.gserviceaccount.com",
      "FIREBASE_CONFIG": "...",
      "GCLOUD_PROJECT": "...",
      "EVENTARC_CLOUD_EVENT_SOURCE": "..."
    },
    "codebase": "default",
    "securityLevel": "SECURE_OPTIONAL",
    "targetedByOnly": true,
    "hash": "..."
  },
  "op": "update",
  "original": {
    "name": "FirebaseError",
    "children": [],
    "context": {
      "function": "projects/<project>/<function>"
    },
    "exit": 1,
    "message": "Failed to update function projects/<project>/<function>",
    "original": {
      "name": "FirebaseError",
      "children": [],
      "context": {
        "body": {
          "error": {
            "code": 400,
            "message": "Invalid function service account requested: {{ params.RUNTIME_SA }}. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.",
            "status": "INVALID_ARGUMENT"
          }
        },
        "response": {
          "statusCode": 400
        }
      },
      "exit": 1,
      "message": "HTTP Error: 400, Invalid function service account requested: {{ params.RUNTIME_SA }}. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.",
      "status": 400
    },
    "status": 400
  }
}

**Comment by amsipe** [comment]
Forgot to mention that if hard-code the service acct as a string in the `RUNTIME_OPTS` we are able to deploy. But thats how we had it configured before this release 
https://github.com/firebase/firebase-functions/releases/tag/v4.3.0

**Comment by taeold** [comment]
Hi @amsipe - you can't use params to set service accounts... YET!

I'm going to push to get that feature out this week. Please follow along at https://github.com/firebase/firebase-tools/issues/5224.

Thank you!
