### ISSUE TITLE
Creating a v2 onSchedule function fails to create a pubsub topic

### ISSUE THREAD

**Issue by krumholz** [firebase/firebase-functions#1393]
### Related issues

None found

### [REQUIRED] Version info

**node:**
v16.19.1

**firebase-functions:**
4.4.0

**firebase-tools:**
12.0.0

**firebase-admin:**
11.8.0

### [REQUIRED] Test case

Verify in Cloud PubSub that there is no topic created.

### [REQUIRED] Steps to reproduce

Create a new v2 onSchedule function from the cli. Deploy it. Verify that the function was created in Cloud Functions, the Cloud Scheduler job was created, but there is no PubSub topic.

### [REQUIRED] Expected behavior

When creating a v2 onSchedule function a pubsub topic should be created and used as the Target for the function.

### [REQUIRED] Actual behavior

No pubsub topic was created.

### Were you able to successfully deploy your functions?

Deploy succeeded, no errors.

**Comment by krumholz** [comment]
This looks to be working now. Not sure if I did something to fix the problem or if it was something else. Closing the issue.

**Comment by redcomethk** [comment]
@krumholz Seems I have this same problem for this issue now in my project. Hope this can be reopened.

**Comment by hoatrana3** [comment]
I don't know why my `onSchedule` v2 not work, no job is found on Cloud Scheduler after deploying my Firebase project
