### ISSUE TITLE
Module @firebase/database-compat not found on Cloud Function deployment

### ISSUE THREAD

**Issue by fgruchala** [firebase/firebase-functions#1395]
### [REQUIRED] Version info

**node:** 18

**firebase-functions:** 4.4.0

**firebase-tools:** 12.0.0

**firebase-admin:** 11.8.0

### [REQUIRED] Test case

`firebase deploy --debug --force --only functions:xxx`

### [REQUIRED] Expected behavior

The targeted Cloud Function is well deployed

### [REQUIRED] Actual behavior

I have this kind of error :
```
Build failed: npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@firebase/database-compat/-/database-compat-0.3.4.tgz - Not found
```

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by fgruchala** [comment]
Thanks a lot 👍

Have a nice day

**Comment by taeold** [comment]
IIUC, the issue should now be resolved. Feel free to reopen or file a new issue if the issue persists.
