### ISSUE TITLE
Firebase Functions: Deployment Fails Due to 'setGlobalOptions' Not Being Exported Properly

### ISSUE THREAD

**Issue by bbottema** [firebase/firebase-functions#1398]
### Related issues

None that I could find.

### Version info

**Operating System:** Windows 10
**firebase --version:** 12.0.0
**node:** 18.16.0
**firebase-functions:** 4.3.1, 4.4.0
**firebase-tools:** N/A
**firebase-admin:** 11.8.0
**typescript:** 4.9.0

### Test case

```typescript
// index.ts
import {setGlobalOptions} from "./local-module";

setGlobalOptions({cpu: "gcf_gen1"});
```
Results in: 

> Error: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/v2' is not defined by "exports" in C:\my_project\firebase\functions\node_modules\firebase-functions\package.json

**Alternatively** (requires disabling eslint):
```typescript
// local-module.ts:
const {setGlobalOptions} = require("firebase-functions");

export {setGlobalOptions};

// index.ts:
import {setGlobalOptions} from "./local-module";

setGlobalOptions({cpu: "gcf_gen1"});
```
Results in:

> Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: (0 , local_module_1.setGlobalOptions) is not a function

This is right after build step: "+  functions: required API cloudbuild.googleapis.com is enabled"

### Steps to reproduce

Use the provided code snippet
Deploy the functions using "npm run deploy" (which does "firebase deploy --only functions")

### Expected behavior

The functions should successfully compile and deploy without any errors.

### Actual behavior

The code compiles, but the deployment process halts with an error, indicating an issue with generating a manifest from the function source.

### Were you able to successfully deploy your functions?

No, the deployment process halts with the following errors:

> Error: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/v2' is not defined by "exports" in C:\my_project\firebase\functions\node_modules\firebase-functions\package.json

or:

> Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: (0 , local_module_1.setGlobalOptions) is not a function

### Notes

The problem seems to be with the deploy platform, as the compiler does not show any issues.

I've tried different tsconfig settings and various import formats with no success.

### Screenshots

![image](https://github.com/firebase/firebase-functions/assets/2115718/5d4b7491-a50b-4968-ae3f-7efecc5fdfb8)

## WORKAROUND

I'm able to work around this by changing the import statement to point to the absolute path of the module in the node_modules folder. Changing:

`import {setGlobalOptions} from "firebase-functions/lib/v2";`
Into:
`import {setGlobalOptions} from "../node_modules/firebase-functions/lib/v2";`

This change allows the deployment to proceed successfully. However, this is not an ideal solution as it requires using a direct reference to the node_modules folder.

**Comment by taeold** [comment]
Hi @bbottema.

IIUC, the `setGlobalOptions` function is available on the v2 namespace. So:

```js
const {setGlobalOptions} = require("firebase-functions/v2");
import { setGlobalOptions } from "firebase-functions/v2"
```

```
import { setGlobalOptions } from "firebase-functions/v2"
```

Should both work.

Do you mind giving this a try and letting us know how it goes?

**Comment by bbottema** [comment]
Well, that compiles and deploys just great.

IntelliJ doesn't event suggest this package for import though, but is happy enough when I manually change it. Perhaps, it's better to include the import in the code example that illustrates the use of `setGlobalOptions({cpu: "gcf_gen1"})`, [here](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#python-preview_4). I wasted a lot of time on this, even had ChatGPT4 help think along with me :/
