### ISSUE TITLE
onDocumentDeleted Trigger Function Missing 'before' Property on 'event' as Stated in Documentation

### ISSUE THREAD

**Issue by lightningeater** [firebase/firebase-functions#1400]
### Related issues

[Error in v2 Firestore Triggers Documentation or Type Information #1386](https://github.com/firebase/firebase-functions/issues/1386)

### [REQUIRED] Version info

**node:**

18.16.0

**firebase-functions:**

4.4.0

**firebase-tools:**

12.0.0

**firebase-admin:**

11.8.0

### [REQUIRED] Test case
Follow [documentation](https://firebase.google.com/docs/functions/firestore-events?gen=2nd#trigger_a_function_when_a_document_is_deleted) for onDocumentDeleted:

    import { onDocumentDeleted } from "firebase-functions/v2/firestore";

    exports.deleteuser = onDocumentDeleted("users/{userId}", (event) => {
        // Get an object representing the document
        // e.g. {'name': 'Marie', 'age': 66}
        const deletedValues =  event.data.before.data();

        // perform more operations ...
    });

### [REQUIRED] Steps to reproduce

1. Implement the example 'onDocumentDeleted' code from Firebase functions v2 documentation in a Node.js environment
2. The event parameter is typed as a `FirestoreEvent<QueryDocumentSnapshot | undefined, { ... }>` rather than as a `FirestoreEvent<Change<QueryDocumentSnapshot> | undefined, { ... }>`.

### [REQUIRED] Expected behavior

If "delete" is a change behavior, it is expected to have a before and after state.

### [REQUIRED] Actual behavior

The removed document data is available on `event.data` rather than the documented `event.data.before.data()`.

    import { onDocumentDeleted } from "firebase-functions/v2/firestore";
    export const onDeleteDocument = onDocumentDeleted(path, (event) => {
          if (event.data) {
            const deletedValues = event.data;
            console.log(deletedValues);
          }
    });

### Were you able to successfully deploy your functions?

Did not attempt to build following documentation. Using workaround as noted in "Actual behavior".

**Comment by taeold** [comment]
Thank you @lightningeater for raising the issue.

Sorry for the confusion - it looks like we made a mistake in our documentation. I will go ahead and suggest a fix. Thank you and sorry again for the confusion.

**Comment by taeold** [comment]
Just pushed an updated our doc! The updated documentation should be available shortly. Thank you again for reporting the issue!
