### ISSUE TITLE
Scheduler v2 not working

### ISSUE THREAD

**Issue by elhe26** [firebase/firebase-functions#1405]
### [REQUIRED] Version info

**node: 18**

**firebase-functions:** 4.3.1

**firebase-tools:** 12.1.0

**firebase-admin:** 11.8.0

### [REQUIRED] Test case

```typescript
import { MemoryOption } from "firebase-functions/v2";
import { onSchedule, ScheduledEvent } from "firebase-functions/v2/scheduler";
import * as logger from "firebase-functions/logger";

export const hourlyData = onSchedule({
  schedule: "* * * * *",
  memory:  "256MiB" as MemoryOption,
}, (event: ScheduledEvent) => {
    logger.info(`Hello from ${event.jobName}, time: ${event.scheduleTime}`, { structuredData: true });
});
```

### [REQUIRED] Steps to reproduce

```bash
$ npm run serve
```

### [REQUIRED] Expected behavior

The function should log `Hello from ${event.jobName}, time: ${event.scheduleTime}`.

### [REQUIRED] Actual behavior

The function is not printing or doing anything. The emulator is configuring it without any issues but is not doing what it is supposed to.

### Were you able to successfully deploy your functions?

Yes (using Firebase emulator)

**Comment by blidd-google** [comment]
Hi @elhe26, thanks for reporting this issue. See https://github.com/firebase/firebase-tools/pull/5891 for a fix that is underway.
