### ISSUE TITLE
DataSnapshot.exists(): boolean when value is 0

### ISSUE THREAD

**Issue by boblepepeur** [firebase/firebase-functions#1407]
### [REQUIRED] Version info

**node:**

v20.1.0

**firebase-functions:**
 "firebase-functions": "^4.4.0",

**firebase-tools:**

**firebase-admin:**
 "firebase-admin": "^11.5.0",

### [REQUIRED] Test case

In firebase, create a node with value 0, lesson change with onWrite, if (change.after.exists()) is false

### [REQUIRED] Steps to reproduce
```
exports.OnValueWrite = functions.database.ref('/currentCheckPointPosition').onWrite(async (change, context) => {
    logger.debug(change.after.exists(), change.after.val())
});
```

* Create value currentCheckPointPosition setted to 0
* result of log is false 0

### [REQUIRED] Expected behavior

* log need to be true 0

**Comment by exaby73** [comment]
Hello @boblepepeur. This issue seems to be fixed in the latest version. Closing this issue for the same reason, If you disagree with my decision, please comment and I'll reopen it. Thank you
