### ISSUE TITLE
v1 beforeCreate blocking function does not create the user in Authentication (bug only in production)

### ISSUE THREAD

**Issue by onra2** [firebase/firebase-functions#1409]
### Related issues

no

### [REQUIRED] Version info

**node:** v20.1.0

**firebase-functions:** 12.2.1

**firebase-tools:** 12.2.1

**firebase-admin:** 12.2.1

### [REQUIRED] Test case

Create two v1 functions with region europ-west1, beforeCreate & beforeSignIn. i'm trying to make a document for the user before he is created, so create a document for the user in "beforeCreate". In beforeSignIn, try adding a customClaim to the user. Then sign in with Google. the beforeCreate & beforeSignIn functions will work perfectly in emulator as expected. Now comes the bug. Deploy the app, make sure that the functions are selected in the Authentication settings under 'Blocking functions'. Now try to create an account with Google sign in and you should get the error that "beforeSignIn" can't find the user because it doesn't exist. This only happens in production. beforeCreate successfully creates the document but the actual user is never set.

### [REQUIRED] Steps to reproduce

main.ts: 
```
import * as functions from "firebase-functions";
admin.initializeApp(functions.config().firebase);
export const auth = admin.auth();
```

```
export const beforeCreate = functions.region("europe-west1").auth.user().beforeCreate(async (user, context) => {
    log("user created", user);
    const displayName = user.displayName ? user.displayName.toLowerCase().replace(" ", "_").trim() : "user_" + randomString(10);
    await db.collection("users").doc(user.uid).set({
        uid: user.uid,
        email: user.email,
        displayName: displayName,
        privateProfile: false,
        bio: "",
        tokens: 0,
    }, { merge: true });
    await db.collection("users").doc(user.uid).collection("public").doc(user.uid).set({
        displayName: displayName,
        bio: "",
        tokens: 0,
    });
    return { customClaims: { role: "user" } };
});
```

```
export const beforeSignin = functions.region("europe-west1").auth.user().beforeSignIn(async (user, context) => {
    log("user logged in", user);
    //get user document
    const uid = user.uid;
    const userDoc = await db.collection("users").doc(uid).get();

    console.log(userDoc.data()?.coach);
    // check if user is coach
    if (userDoc.data()?.coach === true) {
        // set custom claims for role to coach
        await auth.setCustomUserClaims(uid, { role: "coach" });
    }
    else {
        // remove custom claims
        await auth.setCustomUserClaims(uid, { role: "user" });
    }
    return user;
});
```

`firebase deploy`

Sign in with Google.

beforeSignin will throw an error because it cannot find the user in Authentication.

### [REQUIRED] Expected behavior

after the "beforeCreate" execution, a user should be created.

### [REQUIRED] Actual behavior

no user is created after a successful "beforeCreate" execution.
"Unhandled error FirebaseAuthError: There is no user record corresponding to the provided identifier"

The error is different in v2 functions: Unhandled error Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.

### Were you able to successfully deploy your functions?

Yes deployment was successfull

**Comment by inlined** [comment]
I admit I'm not as familiar with managing custom claims, but [the Cloud docs](https://cloud.google.com/identity-platform/docs/blocking-functions) suggest you can just return an object with `sessionClaims` in it. Does the following work?

```
export const beforeSignin = functions.region("europe-west1").auth.user().beforeSignIn(async (user, context) => {
    const userDoc = await db.collection("users").doc(user.uid).get();
    return { sessionClaims: { role: userDoc.data()?.coach ? "coach" : "user" }};
 });
```

**Comment by onra2** [comment]
No this doesn't work, the problem doesn't come from beforeSignIn but beforeCreate. My "beforeCreate" functions creates a document in firestore but once it finished successfully it doesn't create a firebase Authentication user. So i think this is out of my reach and not a problem in my code (because if i make callable functions instead they work).

**Comment by onra2** [comment]
here i made a video demonstrating the bug: https://youtu.be/oecVveGHac0

**Comment by inlined** [comment]
I'm able to reproduce the error. The user is indeed not being created and in fact the creatUser... call is returning `auth/error-code:-47`

When doing my debugging, I noticed that removing the beforeSignin function allows the user to be created successfully. And that beforeSignin function is failing because the call to set custom claims is failing that the user doesn't exist.

As far as I can tell, Google Cloud Identity Platform requires the user to successfully be created and logged in before persisting it. Since the user hasn't been persisted, the call to set custom claims is failing. This dependency issue is probably why the documentation tells you to set claims using the return value rather than the admin SDK. When I modified your function to use the technique I suggested above, the problem no longer reproduces.

For what it's worth, I'm also not sure you need to set customClaims; you're setting claims on each session, so sessionClaims will save you a database operation on login. I've taken the liberty of rewriting your code to use best practices, including the new Admin SDK APIs:

```
import { setGlobalOptions } from "firebase-functions/v2/options";
import { beforeUserCreated, beforeUserSignedIn } from "firebase-functions/v2/identity";
import { initializeApp } from "firebase-admin/app";
import { initializeFirestore } from "firebase-admin/firestore";

const app = initializeApp();
// Turn off gRPC to improve performance of cold starts since we're not using
// realtime APIs
const firestore = initializeFirestore(app, { preferRest: true })

// I assume all your functions are in the same region; this saves you reptition
setGlobalOptions({ region: "europe-west1" });

export const beforeCreate = beforeUserCreated(async ({data: user}) => {
  console.log("user created", user);
  const displayName = user.displayName?.toLowerCase()?.trim()?.replace(" ", "_") || randomString(10);
  await firestore.doc(`users/${user.uid}`).set({
      uid: user.uid,
      email: user.email,
      displayName: displayName,
      privateProfile: false,
      bio: "",
      tokens: 0,
  }, { merge: true });
  await firestore.doc(`users/${user.uid}/public/${user.uid}`).set({
      displayName: displayName,
      bio: "",
      tokens: 0,
  });
});

export const beforeSignin = beforeUserSignedIn(async ({data: user}) => {
  console.log("user logged in", user);
  //get user document
  const userDoc = await firestore.doc(`users/${user.uid}`).get();

  console.log(userDoc.data()?.coach);
  return { sessionClaims: { role: userDoc.data()?.coach ? "coach" : "user" }}
});
```

Thank you for your patience as I debugged this issue. In the future, similar issues will probably be resolved faster by [contacting support](https://firebase.google.com/support)

**Comment by onra2** [comment]
Thank you for the fast fix!

**Comment by Mistic92** [comment]
I just deployed my blocking function and when I have beforeCreate users are not created inside firebase auth. Doesn't matter if I return 200 or something else.

**Comment by cabljac** [comment]
@Mistic92  can you open a fresh issue within the issue template? We will track it separately. Please link this issue in there, and include as much info as possible to help us reproduce
