### ISSUE TITLE
Multipart upload is broken

### ISSUE THREAD

**Issue by sarovin** [firebase/firebase-functions#141]
### Version info

**firebase-functions: 0.7.3

**firebase-tools: 3.15.4

**firebase-admin: 5.5.1

Hi,
i want use multer with my firebase functions. If i use the function with the emulator, it works but if i deploy, the function return this error:
`ERROR TypeError: Cannot read property 'filename' of undefined`

This is my code => https://pastebin.com/G0PzgtVg

It's possible upload a file with the firebase functions?

**Comment by sarovin** [comment]
i have found this error on stackoverflow => https://stackoverflow.com/questions/47242340/how-to-upload-a-file-using-express-on-firebase-cloud-functions

I have the same problem...

**Comment by justinrosenthal** [comment]
@sarovin Thanks for the report and glad you found the answer on Stackoverflow, presently that's the best way to deal with your issue.

**Comment by AlexGilleran** [comment]
... so is there any plan to fix this? 

I get that this is in beta, but you're really going to just silently break something, not document it and not even keep the bug report open?

**Comment by tomas-paronai** [comment]
Did anybody looked at this in the past year?

**Comment by jonasfrid** [comment]
Also interested in this. Any update?

**Comment by the-architect** [comment]
What's up with this issue here? It's still broken. I just wasted half a day tracking down this bug. Please reopen and investigate this please.

**Comment by the-architect** [comment]
For the next person that stumbles across this issue: the official docs have some code: https://cloud.google.com/functions/docs/writing/http#multipart_data

**Comment by emadalam** [comment]
The guide tells you to use a low level library for multipart data processing, which is not ideal if you already are using some web framework. If you are using `express` for your http functions, you can use a [forked version of multer](https://github.com/emadalam/multer) middleware for processing `multipart/form-data` on cloud functions.

Here's what you can do.
```js
const express = require('express')
const multer = require('multer')

const SIZE_LIMIT = 10 * 1024 * 1024 // 10MB
const app = express()

const multipartFormDataParser = multer({
  storage: multer.memoryStorage(),
  // increase size limit if needed
  limits: {fieldSize: SIZE_LIMIT},
  // support firebase cloud functions
  // the multipart form-data request object is pre-processed by the cloud functions
  // currently the `multer` library doesn't natively support this behaviour
  // as such, a custom fork is maintained to enable this by adding `startProcessing`
  // https://github.com/emadalam/multer
  startProcessing(req, busboy) {
    req.rawBody ? busboy.end(req.rawBody) : req.pipe(busboy)
  },
})

app.post('/some_route', multipartFormDataParser.any(), function (req, res, next) {
  // req.files is array of uploaded files
  // req.body will contain the text fields
})
```

**Comment by callezenwaka** [comment]
Thanks @emadalam 
I spent a tonne of hours debugging. I set up demo project on node.js and my code worked with multer but break in cloud functions.

**Comment by stefdelec** [comment]
Same here! Still not working! Firebase starts to be more a waste of time than saving time!

**Comment by kawerewagaba** [comment]
Wow!
This is wasn't at all obvious to me - spent quite some time debugging `multer`, `Content-Type`s, postman, `FormData()` - till I figured it could actually be a thing with cloud functions!

**Comment by jim-alexander** [comment]
I'm so glad this is closed with no solution. Guess I just won't post data to a firebase function.. 🤭

**Comment by ad-si** [comment]
This is still broken! Just wasted several hours on it 😒

**Comment by jim-alexander** [comment]
I ended up getting this working using busboy. I use this as a web-hook with sendGrid to receive and process emails and their attachments: 

```typescript

const getFieldsFromFormData = (headers, body) =>
  new Promise(async (resolve, reject) => {
    const busboy = Busboy({ headers })
    const fields: any = {}
    busboy.on('field', (field, val) => (fields[field] = val))
    busboy.on('finish', () => resolve(fields))
    busboy.on('error', (error) => reject(error))
    busboy.end(body)
  })

export const handleSendGridEmail = functions.https.onRequest(async (req, res) => {
  const fields = await getFieldsFromFormData(req.headers, req.rawBody)
  console.log(fields)
  // fields.to | fields.from | fields.email
})

```

**Comment by ad-si** [comment]
`busyboy.end()` does net seem to be supported by latest version anymore!

My workaround in the end was to parse `req.bodyRaw` myself with https://github.com/shtaif/multerator.

**Comment by ARPNetBR** [comment]
> The guide tells you to use a low level library for multipart data processing, which is not ideal if you already are using some web framework. If you are using `express` for your http functions, you can use a [forked version of multer](https://github.com/emadalam/multer) middleware for processing `multipart/form-data` on cloud functions.
> 
> Here's what you can do.
> 
> ```js
> const express = require('express')
> const multer = require('multer')
> 
> const SIZE_LIMIT = 10 * 1024 * 1024 // 10MB
> const app = express()
> 
> const multipartFormDataParser = multer({
>   storage: multer.memoryStorage(),
>   // increase size limit if needed
>   limits: {fieldSize: SIZE_LIMIT},
>   // support firebase cloud functions
>   // the multipart form-data request object is pre-processed by the cloud functions
>   // currently the `multer` library doesn't natively support this behaviour
>   // as such, a custom fork is maintained to enable this by adding `startProcessing`
>   // https://github.com/emadalam/multer
>   startProcessing(req, busboy) {
>     req.rawBody ? busboy.end(req.rawBody) : req.pipe(busboy)
>   },
> })
> 
> app.post('/some_route', multipartFormDataParser.any(), function (req, res, next) {
>   // req.files is array of uploaded files
>   // req.body will contain the text fields
> })
> ```

definitely does not work with firebase functions

**Comment by kevinrss01** [comment]
> @ARPNetBR What does not work? The original multer library still doesn't support this. If you want to use it, use the forked version in your npm dependency by pointing to the GitHub url https://github.com/emadalam/multer and then use the code sample as provided.
> 
> A few notes:
> 
> * make sure to clean up your node modules for local testing
> * the version is old and hasn't been updated to match the latest multer or busboy
> * I've been using this forked version on production forever without issues

Thanks! I can confirm that the solution is working.

**Comment by vbsh123** [comment]
> I ended up getting this working using busboy. I use this as a web-hook with sendGrid to receive and process emails and their attachments:
> 
> ```ts
> const getFieldsFromFormData = (headers, body) =>
>   new Promise(async (resolve, reject) => {
>     const busboy = Busboy({ headers })
>     const fields: any = {}
>     busboy.on('field', (field, val) => (fields[field] = val))
>     busboy.on('finish', () => resolve(fields))
>     busboy.on('error', (error) => reject(error))
>     busboy.end(body)
>   })
> 
> export const handleSendGridEmail = functions.https.onRequest(async (req, res) => {
>   const fields = await getFieldsFromFormData(req.headers, req.rawBody)
>   console.log(fields)
>   // fields.to | fields.from | fields.email
> })
> ```

Where is the file handling though? it works well for fields but not for files..

**Comment by AdityaGoyal1999** [comment]
This is still an issue. Spent a couple hours with this error until I came across this thread.

**Comment by jim-alexander** [comment]
I haven't been keeping up with this thread but here is something I've been using for ages that includes getting attachments and saving them as well:

```typescript
import Busboy from 'busboy' // ^1.6.0
import * as admin from 'firebase-admin' // ^12.0.0
import * as functions from 'firebase-functions' // ^4.9.0
import { simpleParser } from 'mailparser' // ^3.6.9
import { v4 as uuidv4 } from 'uuid' // ^9.0.1

const stg = admin.storage().bucket()
const firestore = admin.firestore()

type Fields = {
  spam_score?: string
  to?: string
  charsets?: string
  dkim?: string
  from?: string
  subject?: string
  spam_report?: string
  sender_ip?: string
  SPF?: string
  envelope?: string
  email?: string
}

const getFieldsFromFormData = (headers: any, body: Buffer): Promise<Fields> =>
  new Promise(async (resolve, reject) => {
    const busboy = Busboy({ headers })
    const fields: any = {}
    busboy.on('field', (field: string, val: any) => (fields[field] = val))
    busboy.on('finish', () => resolve(fields))
    busboy.on('error', (error) => reject(error))
    busboy.end(body)
  })

export const onEmail = functions.https.onRequest(async (req, res) => {
  let fields
  try {
    fields = await getFieldsFromFormData(req.headers, req.rawBody)
  } catch (error) {
    functions.logger.error(error)
    res.status(500).send()
    return
  }

  if (!fields?.to || !fields?.from || !fields?.email) {
    functions.logger.error('Fields not adequate: ', fields)
    res.status(500).send()
    return
  }

  const parsed = await simpleParser(fields.email)
  if (!parsed.attachments.length) {
    functions.logger.error('No attachments in email')
    res.status(204).send()
    return
  }

  // Process each attachment
  for (const attachment of parsed.attachments) {
    const uuid = uuidv4()
    if (attachment.filename) {
      await stg.file(`attachments/${uuid}`).save(attachment.content, {
        metadata: {
          contentType: attachment.contentType,
          metadata: { 
            fileName: attachment.filename, 
            source: 'email' 
          },
        },
      })
    }
  }

  res.status(200).send()
})
```
