### ISSUE TITLE
CrashlyticsStabilityDigestPayload only contains empty fields

### ISSUE THREAD

**Issue by vibin** [firebase/firebase-functions#1414]
### Version info

**node:** 16.16.0

**firebase-functions:** 4.2.1

**firebase-tools:** Not using this

**firebase-admin:** 11.5.0

### Test case

This is an intermittent issue, so I don't think there is an MCVE, but sharing the sample code below:

```ts
const {
    onStabilityDigestPublished,
} = require("firebase-functions/v2/alerts/crashlytics");

exports.poststabilitydigest = onStabilityDigestPublished(async (event) => {
    logger.info(`Stability digest payload`, event.data.payload);
});
```

### Steps to reproduce

No steps to reproduce as such, but my observation is that the alert payload contains empty values even though the email alert sent contains the full information.

Screenshot of the email sent by Firebase Crashlytics:

<img src="https://github.com/firebase/firebase-functions/assets/3243556/f1ae0eb0-c184-416f-8488-007cc4619fd6" width=500 />

### Expected behavior

The payload should contain all the values which the Email had

### Actual behavior

All the fields under every issue under `trendingIssues` are empty. Including `eventCount`, `userCount`, `issue.title`.

Sharing the log for `event.data.payload` below:
```json
{
  "insertId": "redacted",
  "jsonPayload": {
    "@type": "type.googleapis.com/google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload",
    "trendingIssues": [
      {
        "eventCount": "0",
        "userCount": "0",
        "type": "",
        "issue": {
          "subtitle": "",
          "title": "",
          "appVersion": "",
          "id": ""
        }
      },
      {
        "type": "",
        "userCount": "0",
        "issue": {
          "subtitle": "",
          "id": "",
          "title": "",
          "appVersion": ""
        },
        "eventCount": "0"
      },
      {
        "issue": {
          "subtitle": "",
          "title": "",
          "id": "",
          "appVersion": ""
        },
        "type": "",
        "userCount": "0",
        "eventCount": "0"
      },
      {
        "type": "",
        "userCount": "0",
        "issue": {
          "subtitle": "",
          "id": "",
          "appVersion": "",
          "title": ""
        },
        "eventCount": "0"
      }
    ],
    "digestDate": {
      "month": 6,
      "day": 4,
      "year": 2023
    },
    "message": "Stability digest payload"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "configuration_name": "poststabilitydigest",
      "revision_name": "poststabilitydigest-00005-qop",
      "location": "us-central1",
      "service_name": "poststabilitydigest",
      "project_id": "meesho-supply"
    }
  },
  "timestamp": "2023-06-05T05:09:44.591727Z",
  "severity": "INFO",
  "labels": {
    "instanceId": "redacted",
    "goog-managed-by": "cloudfunctions"
  },
  "logName": "projects/meesho-supply/logs/run.googleapis.com%2Fstdout",
  "receiveTimestamp": "2023-06-05T05:09:44.928649585Z"
}
```

### Were you able to successfully deploy your functions?

Yes. No errors during deployment.

**Comment by vibin** [comment]
Just to add more context, I received a stability alert today but the fields were actually present!

**Comment by colerogers** [comment]
@vibin Hi thanks for opening your first issue in the functions sdk! If I'm understanding correctly, this doesn't seem like a functions SDK issue but a backend problem in the Crashlytics product. Since this repo is specifically for the functions sdk, I'm going to close out this issue. The best place to report this so that the Crashlytics team can take a look would be the [Firebase support page](https://firebase.google.com/support). Let me know if I misunderstood. Thanks!

**Comment by MartinMetselaar** [comment]
@vibin Were you able to resolve this issue? Since the same is happening for me.

**Comment by vibin** [comment]
> @vibin Were you able to resolve this issue? Since the same is happening for me.

We just filter out the items under `trendingIssues` with empty values. 

From what I can see, it looks like Crashlytics backend is always populating 4 items under `trendingIssues` - so when there are only say 3 issues to highlight, the 4th one has the empty values.
I verified this by tallying the event data against what is shown in the stability digest emails.

**Comment by MartinMetselaar** [comment]
Thank you for your insights :)! I will implement the same behaviour and will need to figure out what I will do when all 4 items are empty.

**Comment by MartinMetselaar** [comment]
I have sent a message to [Firebase support page](https://firebase.google.com/support) and they were able to resolve the issue. My stability digests don't contain 4 empty items anymore, but the `trendingIssues` only contains the relevant items.
