### ISSUE TITLE
The Crashlytisc Data structor is not right.

### ISSUE THREAD

**Issue by fr-zhangduanfang** [firebase/firebase-functions#1415]
Sample link https://github.com/firebase/functions-samples/blob/main/Node/alerts-to-discord/functions/index.js

When I deployed with Google Cloud Platform the data structor is unexpected, in this demo the param (event) is a CrashlyticsEvent type, but actually it's a NewFatalIssuePayload type
<img width="795" alt="image" src="https://github.com/firebase/firebase-functions/assets/83061385/4ad0f1fc-4332-4ef2-a996-365cf1ac6a9f">

it's shows the error when I use the const {id, title, subtitle, appVersion} = event.data.payload.issue;

after I fix it to const {id, title, subtitle, appVersion} = event.payload.issue; it successed,
But there is another problem, how can I get the appId to confirm which app has encounter the crash.

I think the event data should like
{ "id": "2133", "source": "iOS", "type": "crash", "appId": "32444", "alertType":"crashlytics.newFatalIssue", "data": { "creatTime": "2023/3/22 8:00:33", "endTime": "2023/3/22 8:00:33", "payload": { "issue": { "id":"3244242", "title": "there is a crash", "subTitle": "subtitle", "appVersion": "3.24" } } } }
but it was
{"data": { "creatTime": "2023/3/22 8:00:33", "endTime": "2023/3/22 8:00:33", "payload": { "issue": { "id":"3244242", "title": "there is a crash", "subTitle": "subtitle", "appVersion": "3.24" } } }

But if I use firebase CLI to deploy the function, the data structor is as expected, so i think there is maybe some difference with deploy with Goole Cloud Platform.

**Comment by exaby73** [comment]
Hello @fr-zhangduanfang. Could you please provide a minimal example so that I may verify the issue?
