### ISSUE TITLE
GET /echo request to ExpressJS app with any JSON body returns 400 (axios) or HTTP/2 stream 0 was not closed cleanly (CURL)

### ISSUE THREAD

**Issue by tohagan** [firebase/firebase-functions#1417]
### Related issues

- None found

### [REQUIRED] Version info

**node:**
18

**firebase-functions:**
4.4.0

**firebase-tools:**
12.3.1

**firebase-admin:**
11.8.0

#### GET Request with no JSON body  - Works in Firebase and Emulator

curl --request GET --url https://australia-southeast1-ptc-payments-stg.cloudfunctions.net/tst/echo --header 'accept: application/json' --header 'content-type: application/json'  -k

#### GET Request with JSON body  - Work on Emulator, Fails in Firebase Deployment

Fails  with 400 bad request (axios client) returns a Google Cloud HTML page

curl --request GET --url https://australia-southeast1-ptc-payments-stg.cloudfunctions.net/tst/echo --header 'accept: application/json' --header 'content-type: application/json' --data '{ "some": "data" }' -k

returns ...  `curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)`

All 4 test cases using `humao.rest-client` VSCode plugin:

```md
## Run using https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Local Emulator /tst/echo - Works

GET http://127.0.0.1:5001/ptc-payments-stg/australia-southeast1/tst/echo HTTP/1.1
accept: application/json
content-type: application/json

### Local Emulator /tst/echo - Works

GET http://127.0.0.1:5001/ptc-payments-stg/australia-southeast1/tst/echo HTTP/1.1
accept: application/json
content-type: application/json

{ "key": "value" }

### Deployed - /tst/echo - Works (no body sent)

GET https://australia-southeast1-ptc-payments-stg.cloudfunctions.net/tst/echo HTTP/1.1
Accept: application/json
Content-Type: application/json

### Deployed - /tst/echo - fails with 400 response (Google HTML page), Nothing logged Log Explorer so looks like it never called the express app code.

GET https://australia-southeast1-ptc-payments-stg.cloudfunctions.net/tst/echo HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "key": "value" }

```

### [REQUIRED] Steps to reproduce

1. Create a firebase function project with following dependencies

    "express": "^4.18.2",
    "firebase-admin": "^11.8.0",
    "firebase-functions": "^4.4.0",

2. Export the tst function that routes /tst/echo path via an ExpressJS app 

This a simplified app (my real app has many paths that all work on the Emulator). I've tested more complex paths and express paths works fine but only if the GET body is empty. 

NONE of the logging in this app is emitted when the 400 error occurs.  So I suspect that the issue is further up the stack.

```ts
import * as functions from 'firebase-functions'
import express from 'express'
const app = express()
export const tst = functions.region('australia-southeast1').https.onRequest(app)

app.get('/echo', async (req, res) => {
  console.log('/echo')
  console.log('req.body', JSON.stringify(req.body || {}))
  res.status(200).json( req.body )
})

// eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/ban-types
app.use(async (req: express.Request, res: express.Response, next: Function) => {
  res.status(404).send('error: 404 Not Found ' + req.path)
})

// eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/ban-types
app.use(async (err: Error, req: express.Request, res: express.Response, next: Function) => {
  console.error(err.stack)
  res.status(500).send('error: 500 Internal Server Error')
});
```

### [REQUIRED] Expected behavior

GET request with JSON payload should pass the payload to the ExpressJS route.

### [REQUIRED] Actual behavior

Fails  with 400 bad request (axios client) returns a Google Cloud HTML page and when called using CURL it appears to also clear the HTTP/2 stream with an internal error.

### Were you able to successfully deploy your functions?

Yes.   Inumerable times.

**Comment by Berlioz** [comment]
I think you're right about the issue being further up the stack. From testing myself, I strongly suspect that the Cloud Functions backend blanket rejects GET requests containing a HTTP body, which have a somewhat sketchy/undefined meaning in the HTTP standards. The docs for [setting up your own Cloud Load Balancer](https://cloud.google.com/load-balancing/docs/https#illegal_request_and_response_handling) characterize "the request method does not allow a body, but the request has one" as an error check which cannot be disabled by a custom load balancer. Unfortunately I don't think there's anything the maintainers of this repository can do about that.

**Comment by tohagan** [comment]
So my feature request would be to modify the Firebase Functions *emulator* to now also return 400 for GET requests containing JSON body content and include an explanation. This would match production and have helped me catch this bug early.
