### ISSUE TITLE
Create a pub/sub function targeting subscription rather than topic

### ISSUE THREAD

**Issue by zach-bicycle** [firebase/firebase-functions#1418]
### Related issues

#1322 

### [REQUIRED] Version info

**node:**

18.16.0

**firebase-functions:**

4.4.0

**firebase-tools:**

11.28.0

**firebase-admin:**

11.8.0

### [REQUIRED] Test case

Implement a pubsub cloud function with firebase-functions. The configuration objects exposed don't provide a way to specify a subscription on a particular topic.

### [REQUIRED] Steps to reproduce

`functions.region('us-central1').runWith().pubsub.topic('somePubsubEvent') .onPublish(...)`
There is no option to configure a subscription on the topic `somePublishedEvent`.

### [REQUIRED] Expected behavior

`firebase-functions` exposes a configuration parameter for the subscription on a topic you wish to subscribe to.

### [REQUIRED] Actual behavior

There is no way to configure the subscription that a cloud function is subscribed to.

### Were you able to successfully deploy your functions?

No, as  the configuration option is missing.

**Comment by inlined** [comment]
This is by design. A subscription should be owned by only one subscriber and there is no reason to manually take over a different subscription.
