### ISSUE TITLE
Cloud Functions onCreate triggers not running

### ISSUE THREAD

**Issue by ftonato** [firebase/firebase-functions#1422]
Hello,

### Related issues

None.

### Version info

**node:** 18.2.0

**firebase-functions:** 4.3.1

**firebase-tools:** I don't have this as a dependency 🤔 

**firebase-admin:** 11.8.0

### Test case

1. In my frontend I have a method to allow my users to create their accounts and be redirected to the dashboard, its code:

```javascript
import { signIn } from 'next-auth/react';

const handleSignIn = async () => {
  try {
    await signIn('google', { callbackUrl: ROUTES.DASHBOARD });
  } catch (error) {
    console.error(`[handleSignIn]: ${error}`);
  }
};
```

2. In my "functions" directory I've this `index.ts` with the following functions:
```typescript
import * as admin from "firebase-admin";
import {UserRecord} from "firebase-admin/auth";
import * as functions from "firebase-functions";

admin.initializeApp();
const db = admin.firestore();

const serverTimestamp = (): admin.firestore.FieldValue => {
  return admin.firestore.FieldValue.serverTimestamp();
};

const serverLog = (message: string): void => {
  functions.logger.log(message);
};

export const createUserDocument = functions.auth.user()
  .onCreate(async (user: UserRecord) => {
    try {
      await db.collection("users")
        .doc(user.uid)
        .set({
          ...JSON.parse(JSON.stringify(user)),
          credits: 3,
        });
    } catch (error) {
      serverLog(`[createUserDocument]: ${error}`);
    }
  });

export const createRecipeDocument = functions.auth.user()
  .onCreate(async (user: UserRecord) => {
    try {
      await db.collection("recipes")
        .doc()
        .set({
          user_id: user.uid,
          createdAt: serverTimestamp(),
          title: "abc",
          description: "def",
        });
    } catch (error) {
      serverLog(`[createRecipeDocument]: ${error}`);
    }
  });

export const helloWorld = functions.https.onRequest((request, response) => {
  serverLog(`[helloWorld] log: ${request}`);
  response.status(200).send("Hello, World!");
});
```

### Steps to reproduce

1. Access the app and trigger the `handleSignIn` function.
2. Verify that the user is created in the app and Firestore database.
4. Check if the Cloud Functions `createUserDocument` and `createRecipeDocument` are triggered and executed.

### Expected behavior

The Cloud Functions `onCreate` triggers should run when a new user is created via the `handleSignIn` function.

### Actual behavior

The Cloud Functions `onCreate` triggers are not running when a new user is created.

### Were you able to successfully deploy your functions?

Yes, I was able to successfully deploy the functions without any error messages, but I also don't have any "log" that these functions were invoked.

**Comment by colerogers** [comment]
@ftonato thanks for opening your first issue in firebase!

Could you try to use firebase auth instead of `next-auth` and see if you still run into this issue? I'm not too sure what `next-auth` does under the hood and it could help to diagnose where the issue is coming from (either firebase or next-auth). Thanks!
