### ISSUE TITLE
Replay protection is broken using consumeAppCheckToken

### ISSUE THREAD

**Issue by indicava** [firebase/firebase-functions#1427]
### [REQUIRED] Version info

node: v16.20.0

firebase-functions: 4.4.1

firebase-tools: 12.4.0

firebase-admin: 11.9.0

### [REQUIRED] Test case
 
Callable cloud function code:

`
export const submitQuestionForApproval = functions
	.runWith({
		enforceAppCheck: true,
		consumeAppCheckToken: true,
	})
	.https.onCall(async (data, context) => {
		functions.logger.info(`context.app.alreadyConsumed = ${context.app.alreadyConsumed}`)
	})
`

Client code (Web SDK):

import { httpsCallable } from "firebase/functions"
const submitQuestionForApproval = httpsCallable(functions, "submitQuestionForApproval", {
	limitedUseAppCheckTokens: true,
})

const response = submitQuestionForApproval({})

### [REQUIRED] Steps to reproduce

1. Create a cloud function with "consumeAppCheckToken" set to true
2. Call the cloud function from a properly (AppCheck initialized) configured Web client
3. Cloud functions always returns 401 Unauthorized even though client has refreshed with a valid AppCheck token.

### [REQUIRED] Expected behavior

Cloud function should not be returning 401 Unauthorized, it should execute and only populate the context.app.alreadyConsumed property.

### [REQUIRED] Actual behavior

Callable Function ALWAYS returns a 401 status code. Even if enforceAppCheck is set to false.
I have attached a screenshot from Chrome dev tools showing client successfully refreshing it's AppCheck token but still getting a 401.
<img width="1728" alt="Screenshot 2023-06-20 at 13 59 05" src="https://github.com/firebase/firebase-functions/assets/14321802/f3eb3493-8cd6-4bdf-bdbf-dd4e93b0110b">
 
### Were you able to successfully deploy your functions?

Yes.

**Comment by indicava** [comment]
For anyone who finds this, I got a work around for this issue from Firebase support:

_"In order to make it work it is necessary to add the "Firebase App Check Token Verifier" role in the App Engine default service account"_

**Comment by blidd-google** [comment]
Hi @indicava, thanks for sharing your fix. Since the issue has been resolved, I'm going to close it for now.
