### ISSUE TITLE
Dart Support

### ISSUE THREAD

**Issue by mohamadlounnas** [firebase/firebase-functions#1431]
What if we could use Dart as a language option for building cloud functions? I think this could bring some amazing benefits to the Firebase ecosystem, and I'd love to share my thoughts with you.

Developer-Friendly: Dart is a popular and easy-to-learn language. By adding Dart support to Firebase Cloud Functions, developers can leverage their existing Dart skills, resulting in faster development and more robust applications.

- Improved Performance: Dart has fast startup times and efficient runtime performance. Integrating Dart into Firebase Cloud Functions would reduce cold start times and improve execution speeds, leading to quicker response times for users and optimized resource utilization.

- Thriving Ecosystem: Dart has a vibrant ecosystem with a wide range of libraries and tools. Enabling Dart support in Firebase Cloud Functions would provide developers access to this rich ecosystem, empowering them to build feature-rich serverless applications.

- Flutter Integration: Dart is the primary programming language for Flutter. By supporting Dart in Firebase Cloud Functions, developers can seamlessly integrate frontend and backend development, promoting code reuse and accelerating development cycles.

Dart support to Firebase Cloud Functions would enhance developer productivity, improve performance, provide access to a thriving ecosystem, and streamline integration with Flutter. I believe this enhancement would have a significant positive impact on the Firebase developer community.

**Comment by taeold** [comment]
Hey @mohamadlounnas - thanks for sharing your thoughts on Dart functoin here!

Dart support in CF3 is definitely one of the most requested feature request for Cloud Functions for Firebase. Not in the roadmap yet, but always great to hear about the use cases for Dart! Please make sure you upvote https://firebase.uservoice.com/forums/948424-general/suggestions/46573903-support-dart-in-cloud-functions - I hope to use these signals to help the team shape the roadmap!

**Comment by taeold** [comment]
Duplicate of https://github.com/firebase/firebase-functions/issues/1385

**Comment by thruthesky** [comment]
I love to code in Dart with the Firebase Cloud Functions.
Please, Please, ... 100 x please, support Dart language to develop the Firebase Cloud Functions.

**Comment by esenmx** [comment]
This is the single biggest productivity drop in one of my projects.

**Comment by Albertbol** [comment]
It will help so much to share types across application by using dart in backend and front end

**Comment by Rexios80** [comment]
I just released [firebase_js_interop](https://pub.dev/packages/firebase_js_interop) which allows you to compose Firebase Cloud Functions in the Dart language

**Comment by saidkacem** [comment]
Do we have any updates on this topic ?  or at least a roadmap. It would be big plus for flutter framework

**Comment by safield** [comment]
Where is the Dart love at??

**Comment by Rexios80** [comment]
@safield I know it's not official (or fully featured yet), but [firebase_js_interop](https://pub.dev/packages/firebase_js_interop) has been working well for me in several projects

**Comment by safield** [comment]
> [@safield](https://github.com/safield) I know it's not official (or fully featured yet), but [firebase_js_interop](https://pub.dev/packages/firebase_js_interop) has been working well for me in several projects

I am sure you have Mr. Author.

**Comment by DavidOrakpo** [comment]
Fingers crossed for this

**Comment by adifyr** [comment]
> Hey [@mohamadlounnas](https://github.com/mohamadlounnas) - thanks for sharing your thoughts on Dart functoin here!
> 
> Dart support in CF3 is definitely one of the most requested feature request for Cloud Functions for Firebase. Not in the roadmap yet, but always great to hear about the use cases for Dart! Please make sure you upvote https://firebase.uservoice.com/forums/948424-general/suggestions/46573903-support-dart-in-cloud-functions - I hope to use these signals to help the team shape the roadmap!

@taeold That UserVoice thread has been itself active for a couple of years now. We've seen no action on this despite how requested it is. May I ask what's going on?

**Comment by vanlooverenkoen** [comment]
<img width="894" height="650" alt="Image" src="https://github.com/user-attachments/assets/b57f67e7-68b7-4dba-a55d-6a649898b31d" />

😱 😱 😱 😱 😱
