### ISSUE TITLE
Throwing HttpsError always causes Internal Server Error

### ISSUE THREAD

**Issue by abegehr** [firebase/firebase-functions#1437]
### [REQUIRED] Version info

**node:** v18.15.0

**firebase-functions:** 4.4.1

**firebase-tools:** 12.4.3

**firebase-admin:** 11.9.0

### [REQUIRED] Test case

Simple test function:
```ts
import { HttpsError, onRequest } from 'firebase-functions/v2/https'
import * as logger from 'firebase-functions/logger'

export const testError = onRequest(async (req, res) => {
  logger.info('testError', req.body)
  throw new HttpsError('unimplemented', 'test error', { some: 'data' })
  res.send('ok')
})
```

### [REQUIRED] Steps to reproduce

Deploy the testError v2 firebase-function from the test case above and open the function url in a browser. You will see internal server error (500). AS I understand [HttpsError](https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.https.httpserror), it should respond with unimplemented (501). It doesn't seem to matter which HttpsError I throw, it always returns internal server error (500) even when throwing a client-side error like unauthenticated (401).

Http status codes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

### [REQUIRED] Expected behavior

Respond with the HttpsError that was thrown in the function.

If I manually catch and send the HttpsError it works as expected:

```ts
import { HttpsError, onRequest } from 'firebase-functions/v2/https'
import * as logger from 'firebase-functions/logger'

export const testError = onRequest(async (req, res) => {
  try {
    logger.info('testError', req.body)
    throw new HttpsError('unauthenticated', 'test error', { some: 'data' })
    res.send('ok')
  } catch (error) {
    if (error instanceof HttpsError) {
      logger.info('HttpsError', error)
      res.status(error.httpErrorCode.status).send(error.toJSON())
    } else {
      logger.error('unknown error', error)
      throw error
    }
  }
})
```

### [REQUIRED] Actual behavior

Always responds with internal server error (500), regardless of the thrown HttpsError.

### Were you able to successfully deploy your functions?

Yes.

**Comment by LogansUA** [comment]
I'm not sure why that was closed, but I'm literally having the same issue atm, except I'm using Python for functions, here's an example
Firebase function
```py
@https_fn.on_request(cors=options.CorsOptions(cors_origins="*", cors_methods="post"))
def get_expenses(req: https_fn.Request) -> https_fn.Response:
    # Some code here
    raise https_fn.HttpsError(
        code=https_fn.FunctionsErrorCode.INVALID_ARGUMENT,
        message="CUSTOM MESSAGE",
    )
    
    # Some successful code here
```

Firebase hosting (vue.js, but that shouldn't matter here)
```ts
import { getFunctions, httpsCallable } from 'firebase/functions';

const functions = getFunctions();
const getExpenses = httpsCallable(functions, "get_expenses");

try {
  const res: any = await getExpenses();

  history.value = res.data;
} catch (error: any) {
  console.log("Get expense error", error, typeof error, JSON.parse(JSON.stringify(error)));
  const code = error.code;
  const message = error.message;
  const details = error.details;
  console.log(code, message, details);

  throw error;
}
```

Browser console output
<img width="748" alt="Screenshot 2023-10-01 at 00 21 14" src="https://github.com/firebase/firebase-functions/assets/7515743/62356dbb-5041-4db6-ad3b-05898422ab08">

Also, in the Networks tab for that request, the Response is straight empty obviously that's cause the status code is 500, but just wanted to mention that.

**Comment by ramadhanabs** [comment]
Same with me, i'm using HTTPS callable on my client and sending error code by using HttpsError instance but got FirebaseError: internal and can't access code, message or details..

**Comment by zivuch** [comment]
Any solution? :)

**Comment by Yuzobra** [comment]
> I had the same behavior and was able to reproduce. With Python 2nd gen cloud functions, if you use https_fn.on_request() mistakenly instead of https_fn.on_call(), even though https_fn.on_request() will work perfectly fine for **successful** calls, it will not work for raising the HttpsError. The result you'll see is "internal" instead of the HttpsError you raised/threw.
> 
> [-@https_fn.on_request](mailto:-@https_fn.on_request)() [+@https_fn.on_call](mailto:+@https_fn.on_call)() def download_doc(req: https_fn.CallableRequest):
> 
> Checking the definition to make sure I was using what was documented with https_fn.on_call fixed this.

Not sure why this is happening, but changing to `on_call` seems to have solved for me.

**Comment by ruohomaa** [comment]
I have this exact same issue, I am using 6.3.2 of `firebase-functions`
I am using js not python. Any solution for this ?

**Comment by NayamAmarshe** [comment]
Try using this format:

```
response.status(400).send({
  error: {
    status: 'THIS_IS_NOT_VALID',
    message: 'this should be ignored'
  }
});
```

**Comment by IsseiKanda** [comment]
It's been 2 years since this error's been reported and still not fixed? 
Having same problem in typescript with "firebase-admin": "^13.2.0", "firebase-functions": "^6.3.2".

**Comment by IsseiKanda** [comment]
It was an easy mistake to make, and a bit embarrassing — but I’m sharing it anyway in case it helps someone else.
In my case, this happened because I was wrapping all errors with an internal HttpsError, including those I had already thrown intentionally.

**Bad example**

```
// Always returns 'internal' because the 'not-found' error is caught and replaced.
try {
  throw new HttpsError("not-found", "Missing API key");
} catch (e) {
  throw new HttpsError("internal", "Something went wrong", e);
}
```

 **Fixed version**

```
try {
  throw new HttpsError("not-found", "Missing API key");
} catch (e) {
  if (e instanceof HttpsError) throw e;
  throw new HttpsError("internal", "Something went wrong", e);
}
```
