### ISSUE TITLE
Firebase function onWrite-Trigger returns null event.data when key/push-id ends in numbers

### ISSUE THREAD

**Issue by Merve40** [firebase/firebase-functions#144]
The `event` Argument in Firebase Function-Trigger for `onWrite(event)` returns null, if the key/push-id ends in numbers. 

```Javascript
exports.notify = functions.database.ref("/Message/{pushId}").onWrite(event => {
    const body = event.data.val(); // returns null
    ...
}
```

### Version info
**firebase-tools: 3.14.0**
**firebase-functions:^0.7.1**

### Test case & How to reproduce
`https://my-firebase-url.com/Message/{pushId}/..`

This push-id cannot be recognized by the trigger, thus returns null as argument:
`https://my-firebase-url.com/Message/n_12/..`

This push-id works:
`https://my-firebase-url.com/Message/blabla/..`

**Comment by inlined** [comment]
Tried very hard to reproduce this but I can't. I strongly suspect you're getting a null because the `onWrite` event also fires when the pushId is deleted (where the value is correctly "null"). If you only want to handle creation events, you can listen to `onCreate` instead.
