### ISSUE TITLE
Cloud Function V2 randomly not creating deterministic Function URL

### ISSUE THREAD

**Issue by akb5566** [firebase/firebase-functions#1447]
### Related issues

- None I could find.

### [REQUIRED] Version info

**node:**
- Node v19.5.0

**firebase-functions:**
- firebase-functions 4.4.1

**firebase-tools:**
- firebase-tools: 12.4.4

**firebase-admin:**
- 11.10.1

### [REQUIRED] Test case

Cloud Function 
````javascript
exports.updateChatroomEpoch = onCall(async (request) => {
    return 'hello';
});
````
Client Side
````javascript
import { cloudFunc } from '$lib/firebase/firebaseConfig';
import { httpsCallable } from 'firebase/functions';
httpsCallable(cloudFunc, myFuncName).then((res) => {
    console.log('ya')
})
````

### [REQUIRED] Steps to reproduce

- Use `firebase deploy --only functions` to deploy the Cloud Function.

### [REQUIRED] Expected behavior

According to https://cloud.google.com/functions/docs/calling/http#url, Cloud Function 2nd Gen should generate 2 Function URL:
- `https://REGION-PROJECT_ID.cloudfunctions.net/FUNCTION_NAME`
- `https://FUNCTION_NAME-RANDOM_HASH-REGION.a.run.app`
 
The `cloudfunctions.net` one has a deterministic format, while the latter one does not (including random hash).

### [REQUIRED] Actual behavior

Some of my functions only generate the `a.run.app` one, not the `cloudfunctions.net` one.

<img width="1273" alt="a1" src="https://github.com/firebase/firebase-functions/assets/10397897/0ecd2daa-98f3-40f5-a48a-1b42271cfc47">

<img width="559" alt="a2" src="https://github.com/firebase/firebase-functions/assets/10397897/2271ae07-4d11-4ac5-8601-39d478ef53cf">

In `GCP Cloud Function Console`, click on the `cloudfunctions.net` endpoint (the red arrows), it shows "Page not found". 

However, if I navigate to `GCP Cloud Run Console`(the green arrows), it did successfully created an `a.run.app` endpoint(the orange arrow).

<img width="1280" alt="a3" src="https://github.com/firebase/firebase-functions/assets/10397897/684a2810-5bf2-4c4b-854f-4c582dd71ded">

<img width="421" alt="a4" src="https://github.com/firebase/firebase-functions/assets/10397897/3938af37-d173-4cfd-abc3-7f457afdb240">

The `cloudfunctions.net` endpoint was somehow not created. This makes the `httpsCallable` from the client side always fail (the client  would receive a CORS Error), because the `httpsCallable` is trying to access a url that does not exist. 

### Other information

This seems to happen randomly. I have deployed 68 functions at the same time, but only 2 of them have this problem.

<img width="1265" alt="a5" src="https://github.com/firebase/firebase-functions/assets/10397897/062ab0b2-cb39-4b67-ab97-18f91a3e555a">

The solution is to delete the specific functions and deploy them again. And hope that they will create the endpoint this time. (At least it worked for me). 

You HAVE TO delete the function, not just redeploy. Redeploy does not solve this problem.

I think this need to be investigated because it is clear that something went wrong when "deploying", but there are no errors from the `firebase-tools`. All the developer can see is the CORS Error in the browser, which can mean anything from incorrect region to not having permissions. But all they really need to do in this case is to delete the functions and deploy them again.

### Were you able to successfully deploy your functions?

There were not error messages running `firebase deploy`.

**Comment by Berlioz** [comment]
So I'm really sorry to say this given that you've put a lot of work into this Github issue, but I think you'd have a lot more luck with Firebase Support (https://firebase.google.com/support/troubleshooter/contact)--this seriously looks like an issue with the integration with Google Cloud Functions. Debugging this is likely going to involve looking at deploy-specific logs and that means identifying your cloud project and peeking at its contents. We can't do that off of a Github issue, but we can with a contact made through support.

**Comment by JJ11teen** [comment]
I am experiencing the same issue.

I understand that a support ticket is better for specific cases, but thought it was worth capturing that this is happening to multiple users here as well.

**Comment by JJ11teen** [comment]
Also massive thanks to @akb5566 for the write up and workaround! (:

**Comment by LogansUA** [comment]
Yep, so same thing for me. Deleting and re-deploy function through GCP Console -> `Cloud Functions` worked, thank you @akb5566 
Also, [this thread](https://stackoverflow.com/a/77190877/3450900) might answer some of the questions regarding functions URL

**Comment by thandal** [comment]
Same thing happened to me today.
