### ISSUE TITLE
404 (Not Found) on function deploy with express

### ISSUE THREAD

**Issue by mmarchal** [firebase/firebase-functions#1454]
### [REQUIRED] Version info

**node:** v18.16.1

**firebase-functions:**12.4.7

**firebase-tools:**12.4.7

**firebase-admin:**12.4.7

### [REQUIRED] Test case

I have a function deployed that allows me to retrieve information from my Cloud Firestore but when I try to access it through a Flutter app I get a cors error.
So i try to add express required to help and when i try to call my function, I have a 404 Not Found with message <pre>Cannot GET /</pre>

### [REQUIRED] Steps to reproduce

That is my actual code

```
const express = require("express");
const app = express();

app.get("/getNearestItem1", async (_req, res) => {
    try {
        ...
    } catch (error) {
        ...
    }

    // Ajoute l'en-tête CORS à la réponse
    res.set("Access-Control-Allow-Origin", "http://localhost:3000");

    // Autres en-têtes CORS optionnels
    res.set("Access-Control-Allow-Methods", "GET");
    res.set("Access-Control-Allow-Headers", "Content-Type");

    // Envoie la réponse
    res.send("Hello World!");
});

exports.getNearestItem1 = functions.https.onRequest(app);
```

### [REQUIRED] Expected behavior

For the example, just have a "Hello World" message

### [REQUIRED] Actual behavior

GET http://127.0.0.1:5001{projectName}/us-central1/getNearestItem 404 (Not Found)

**Comment by Berlioz** [comment]
I think it's recommended to configure CORS by passing it into the function options in v2? Like
`exports.getNearestItem1 = https.onRequest({ cors: true }, app)` 
But also I haven't tried this in combination with Express, which I know has a CORS middleware that handles all the headers for you.

I'm happy to try and help but you are going to get significantly faster and better advice on this sort of thing from Firebase Support, which has people with training and playbooks and SLAs and stuff, than rolling the dice on Github tickets.
