### ISSUE TITLE
Deploy message showing "shutdown requested via /__/quitquitquit" using version 12.4.1

### ISSUE THREAD

**Issue by taeold** [firebase/firebase-functions#1456]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.1

**Platform:** macOS

### [REQUIRED] Test case

Init a new CF3 functions project

### [REQUIRED] Steps to reproduce

`firebase deploy`

### [REQUIRED] Expected behavior

Deploy succeeds without suspicious error log entries

### [REQUIRED] Actual behavior

```
" i functions: Loading and anaylzing source code for codebase default to determine what to deploy
Serving at port 8061

shutdown requested via /__/quitquitquit"
```

which is confusing. Shouldn't print this if this is all internal implementation detail

**Comment by jeangq24** [comment]
Tuve este mismo error intentando hacer `deploy` de una `onCall function`, obtenia el error y cuando ejecutaba `firebase emulators:start` tambien me salia el mismo error.

Investigue por varias horas pero ninguna de las opciones que me daban me funciono, entre degradar mis versiones de firebase, node y npm, hasta modificar lineas de condigo en el proyecto de firebase-tools hubo algo que me funciono que no lo vi como posibles soluciones.

informacion de versiones:


`SO:Kali_Linux 2023.3`

`Node: 16.16/18.18`

`npm: 10.2.0`

`firebase: 12.6.2 (medio de intalacion del CLI: "sudo npm install -g firebase-tool")`




Abra el arcihvo de la siguiente ruta (necesitara permisos root) y edite la siguiente variable:

`
ruta - /usr/lib/node_modules/firebase-tools/lib/deploy/functions/runtimes/discovery/index.js
`

o

`
ruta - raiz_del_proyecto_firebase_tools/src/deploy/functions/runtimes/discovery
/index.ts
`

Edite la siguiente el parametro `timeout` en la funcion `detectFromPort`

`
Antes ->  timeout = 10000
Despues -> timeout = 50000
`

Asegurese de guardar cambios correctamente y haga su `firebase deploy/firebase emulators:start` sin el molesto error.


PD: No estoy seguro de que esta pasando con esto, en caso de que esto pueda ser una solucion fuerte para todos me gustaria saber que es lo que pasa.

**Comment by chapeee** [comment]
did anyone solve it?

**Comment by drewburnett** [comment]
@chapeee Are you experiencing issues all of a sudden? I just updated to OS Sonoma today and my project isn't working anymore.

**Comment by chapeee** [comment]
> @chapeee Are you experiencing issues all of a sudden? I just updated to OS Sonoma today and my project isn't working anymore.

yes, it was all of a sudden,  I solved it by setting the Firebase version as 2.
I am using Nuxt and Nitro as server.

**Comment by Adrxx** [comment]
@chapeee  What do you mean setting the firebase version as 2??
