### ISSUE TITLE
DeltaDocumentSnapshot data() returns incorrect any type

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-functions#146]
In the [reference docs]( https://firebase.google.com/docs/reference/functions/functions.firestore.DeltaDocumentSnapshot#data) it says that the DeltaDocumentSnapshot data method returns a DeltaDocumentSnapshot. The text is correct I guess, just not the return type. According to the source code it is any.

See [src/providers/firestore.ts#L79](https://github.com/firebase/firebase-functions/blob/master/src/providers/firestore.ts#L79)

I arrived here from posting this issue earlier firebase/firebase-js-sdk/issues/330

**Comment by laurenzlong** [comment]
The documentation is actually wrong, and the code is correct. We'll fix the doc, thanks!

**Comment by laurenzlong** [comment]
Doc has been fixed. See https://firebase.google.com/docs/reference/functions/functions.firestore.DeltaDocumentSnapshot#data
