### ISSUE TITLE
Realtime Database onCreate trigger is not called when the entrance is big

### ISSUE THREAD

**Issue by Dric0** [firebase/firebase-functions#1467]
### [REQUIRED] Version info

**node:** 10

**firebase-functions:** 3.19.0

**firebase-tools:** 7.6.1

**firebase-admin:** 8.6.1

### [REQUIRED] Test case
Sometimes the user insert base64 images in the realtime database, so to reduce cost I created a onCreate cloud function to convert the base64 to a file in firebase storage, replacing the base64 entrance with the URL to the file in storage instead.

The path for the onCreate function is ```'users/{uid}/{mode}/{patientId}/{recordId}/text/ops/{index}/insert/image'```
```js
const admin = require('firebase-admin');
const functions = require('firebase-functions');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

module.exports = async function (snapshot, context) {
  const { uid, mode, patientId, recordId, index } = context.params;
  const db = admin.database();
  const data = {};

  // Grab the current value of what was written to the Realtime Database.
  const current = snapshot.val();
  if (current) {
    try {
      const bucket = admin
        .storage()
        .bucket();
      const imageBuffer = Buffer.from(current.split(',')[1], 'base64');
      // Image converted to buffer
      const fileType = current.match(/[^:/]\w+(?=;|,)/)[0];
      const fileName = `image${index}.${fileType}`;
      const filePath = `users/${uid}/${mode}/${patientId}/${recordId}/text/ops/${index}/insert/image/${fileName}`;
      const file = bucket.file(filePath);
      let response = null;
      const tempLocalFile = path.join(os.tmpdir(), fileName);
      // Writing data do file using "save"
      await file.save(imageBuffer, {
        metadata: {
          // Enable long-lived HTTP caching headers
          // Use only if the contents of the file will never change
          // (If the contents will change, use cacheControl: 'no-cache')
          cacheControl: 'public, max-age=31536000',
          contentType: fileType,
        },
      });
      await file.download({ destination: tempLocalFile });
      // The file has been downloaded to tempLocalFile
      const uuid = uuidv4();
      response = await bucket.upload(tempLocalFile, {
        destination: filePath,
        metadata: {
          // Enable long-lived HTTP caching headers
          // Use only if the contents of the file will never change
          // (If the contents will change, use cacheControl: 'no-cache')
          cacheControl: 'public, max-age=31536000',
          metadata: {
            firebaseStorageDownloadTokens: uuid,
          },
        },
        // predefinedAcl: 'authenticatedRead',
        public: true,
      });
      // Once the image has been uploaded delete the local files to free up disk space.
      fs.unlinkSync(tempLocalFile);
      if (response && response[0].metadata && response[0].metadata.mediaLink) {
        data[`users/${uid}/${mode}/${patientId}/${recordId}/text/ops/${index}/insert/image`] = response[0].metadata.mediaLink;
      }
      return db.ref().update(data);
    } catch (error) {
      functions.logger.error(error, context.params);
    }
  }
  return null;
}
```

### [REQUIRED] Steps to reproduce
When saving a base64 image to the realtime database, if it is a big entrance, 500kb+ is already big enough, the onCreate trigger does not get called. If the entrance is 300kb, the trigger runs as expected and successfully generates the file in firebase storage and replace the base64 string with the URL from storage.

### [REQUIRED] Expected behavior
The trigger should be called for all cases, despite the size of the entrance. There is a limitation of 10mb per node in the realtime database, the cloud function triggers should be able to run according to this limit.

### [REQUIRED] Actual behavior
If the entrance is more than 500kb (just an estimate) the function is never triggered, no logs are even shown in the function logs.

### Were you able to successfully deploy your functions?
Yes

**Comment by taeold** [comment]
@Dric0 Thanks for filing the issue and sorry we didn't respond earlier.

It looks like we need to peek into the internal infrastructure to further diagnose the issue you are seeing. Can you please file a [Firebase Support ticket](https://firebase.google.com/support) so we can route the issue to the correct team?

**Comment by taeold** [comment]
Arg sorry, upon reading through our documentation more closely, this is working as intended:

https://firebase.google.com/docs/database/usage/limits#global

> The size of an event consists of the following values:The existing data at the write location.The update value, or the delta in data necessary to write the new data to the location.Write operations larger than 1MB succeed on the database, but they don't trigger a function invocation.

It probably is that the referred node is >1MB and your are hitting this limitation.  If you suspect there is more to issue, please do file a Firebase support ticket as I suggested earlier to allow me to route the issue to the appropriate eng team.
