### ISSUE TITLE
v2 onRequest does not enforce AppCheck

### ISSUE THREAD

**Issue by AmitMY** [firebase/firebase-functions#1474]
### Related issues

https://github.com/firebase/firebase-functions/issues/1377

### [REQUIRED] Version info

"firebase-admin": 
"firebase-functions": 

**node:** v18.15.0

**firebase-functions:** "4.4.1",

**firebase-tools:** 12.5.4

**firebase-admin:** "11.11.0",

### [REQUIRED] Test case

```ts
import {onRequest} from 'firebase-functions/v2/https';

onRequest({enforceAppCheck: true}, (req, res) => res.status(200).end());
```
### [REQUIRED] Steps to reproduce

Set up a cloud function using v2 onRequest, with `enforceAppCheck: true`

### [REQUIRED] Expected behavior

Calling the function (locally or when deployed) with the HTTP request should be blocked if no app check token is available

### [REQUIRED] Actual behavior

Function works fine, same as https://github.com/firebase/firebase-functions/issues/1377 without any token

### Were you able to successfully deploy your functions?

yes

**Comment by Berlioz** [comment]
The just-add-water AppCheck integration is for callable functions, i.e ones created with onCall(), not onRequest(). As a workaround you can import the firebase-admin SDK and [verify the X-Firebase-AppCheck header](https://firebase.google.com/docs/app-check/custom-resource-backend) yourself. (If you use vscode or something else with typescript autocomplete, you'll see that enforceAppCheck is only a defined property on CallableOptions, not HttpsOptions).

**Comment by AmitMY** [comment]
I am using WebStorm, and indeed it does show `enforceAppCheck` as an option for HttpsOptions
<img width="220" alt="image" src="https://github.com/firebase/firebase-functions/assets/5757359/f2c7deb5-ea8d-4b91-a0f2-4e3924780bd2">

This is a bug then, specifically here:
https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/v2/providers/https.ts#L52

Fixed in: https://github.com/firebase/firebase-functions/pull/1477

**Comment by riccardocescon** [comment]
I am using firebase-functions v6.1.1. by adding enforceAppCheck: true on my onRequest function will not enforce the app check, all requests will be accepted

**Comment by davidpinosp** [comment]
Me too. I am using v6.3.0 and it doesnt work. It seems like its an error from inheriting from  Global Functions which includes the enforceAppCheck flag

**Comment by riccardocescon** [comment]
@Berlioz is there any update about this?
onRequest not enforces app check at all
