### ISSUE TITLE
Firebase Emulator simply does not initialize .env.[project]

### ISSUE THREAD

**Issue by Padreco-lbr** [firebase/firebase-functions#1482]
### Related issues

[Firebase Emulator simply does not initialize .env || .env.local || .env.default #1094
](https://github.com/firebase/firebase-functions/issues/1094)

Just reopening this issue, since it was closed by a bot but still happens.

**Comment by OskarGroth** [comment]
Running into the same issue.

**Comment by taeold** [comment]
Re-opening https://github.com/firebase/firebase-functions/issues/1094 - thanks for escalating.
