### ISSUE TITLE
Gen 2 onCall handlers don't have traces

### ISSUE THREAD

**Issue by ciriousjoker** [firebase/firebase-functions#1487]
### [REQUIRED] Version info

**node:** v16.19.0

**firebase-functions:** v4.5.0

**firebase-tools:** v12.7.0

**firebase-admin:** v11.11.0

### [REQUIRED] Test case

```ts
import { onCall } from "firebase-functions/v2/https";

export const checkoutAddPaymentMethodPayPal = onCall(async (request) => {
  console.log("This should have a trace, but it does not.");
});
```

### [REQUIRED] Steps to reproduce

1. Deploy above code
2. Check cloud function logs
3. Try to view the logs from "same trace"

### [REQUIRED] Expected behavior

Should have a trace.

### [REQUIRED] Actual behavior

Doesn't, "same trace" is greyed out.

### Were you able to successfully deploy your functions?

Yes, deployment works.

---

Related:
- #1439
- #1440 

Reason for this is most likely, that unlike the `onRequest` function, the `onCall` handler isn't wrapped in `wrapTraceContext()`.

**Comment by joshgare** [comment]
Seeing the same issue, making debugging on stackdriver much more troublesome than V1 functions.

**Comment by blidd-google** [comment]
Thanks for bringing this to our attention, PR is out that wraps onCall handlers with trace context.
