### ISSUE TITLE
Nodejs 14 Deprecation

### ISSUE THREAD

**Issue by rwesley23** [firebase/firebase-functions#1488]
### [REQUIRED] Version info
 **node:** 14

 **firebase-functions:** 4.5.0
 
 **firebase-tools:** 12.8.1
 
 **firebase-admin:** 11.11.0

Hello everyone, we currently have approximately 500 functions deployed for Node.js 14. According to the Google Cloud Console, Node.js 14 is scheduled to be deprecated on January 30, 2024. The message suggests updating these functions to the latest available runtime version. I would appreciate some clarification on whether our functions will still be able to execute on February 1, or if they will continue to run but won't allow deployment updates. Thank you!

**Comment by Berlioz** [comment]
https://cloud.google.com/functions/docs/runtime-support

Node 14 will be deprecated on the 30th, but not decomissioned. "During the deprecation period, you can generally continue to create new functions and update existing functions using the runtime. You should use this time to migrate functions that use the deprecated runtime to a more up-to-date runtime.".
