### ISSUE TITLE
TS: Typescript Functions Not Hot Re-Loading Correctly

### ISSUE THREAD

**Issue by SamJbori** [firebase/firebase-functions#1489]
### [REQUIRED] Version info

**node:**

v18.17.1
**firebase-functions:**
4.3.1
**firebase-tools:**
12.9.1

**firebase-admin:**
11.8.0
### [REQUIRED] Test case

I initialized the project using the command `firebase init functions`, in typescript, when I launch using `npm run serve` the code works however when I change the code the the terminal shows the functions reloading, however the changes are not reflected and the code runs on it's old version, only when I end and restart it again the change reflected, I used npm package `concurrently ` to run `tsc --watch` and `npm run serve` and it fixed it!

**Comment by blidd-google** [comment]
Hi @SamJbori, you are correct that running `tsc --watch` in another process is necessary to recompile your TypeScript code as you make changes and to reflect those changes in the emulator.
