### ISSUE TITLE
Fastly 503 first byte timeout

### ISSUE THREAD

**Issue by remie** [firebase/firebase-functions#1495]
### [REQUIRED] Version info

**node:** 18

**firebase-functions:** 4.4.1

**firebase-tools:** 12.6.2

**firebase-admin:** 11.11.0

### [REQUIRED] Test case

We've been unable to create a repeatable test case as this is not an application error

### [REQUIRED] Steps to reproduce

We've been unable to reproduce the issue as this is not an application error

### [REQUIRED] Expected behavior

The expected behavior is that we do get 503 first byte timeout responses when Cloud function execution falls within the limits of Cloud function timeouts

### [REQUIRED] Actual behavior

We are getting intermittent reports of 504 First byte timeout errors returned by Fastly CDN even though the GCP log explorer shows that the underlying function requests have returned with an 200 error code within ~110s of execution.

### Were you able to successfully deploy your functions?

Yes, this is a production error.

I tried to contact Firebase support but that only resulted in some recommendations to improve our performance and latency even though this is not about performance of latency of our app but a mismatch in configuration between Firebase hosting, Fastly and Cloud functions. This is not a "me" problem, and I would love for someone from Firebase to investigate. I can provide screenshots of log explorer upon request.

**Comment by Berlioz** [comment]
Sorry to deliver bad news, especially since this fell through the cracks over the holidays, but this is a limitation of Hosting.

From the [Hosting dynamic content docs](https://firebase.google.com/docs/hosting/functions):
> Note: Firebase Hosting is subject to a 60-second request timeout. Even if you configure your HTTPS function with a longer request timeout, you'll still receive an HTTPS status code 504 (request timeout) if your function requires more than 60 seconds to run. To support dynamic content that requires longer compute time, consider using an [App Engine flexible environment](https://cloud.google.com/appengine/docs/flexible/).
