### ISSUE TITLE
Firebase deploy not working due to experimental skipdeployingnoopfunctions

### ISSUE THREAD

**Issue by ksinghal** [firebase/firebase-functions#1499]
### Related issues

I found this on StackOverflow: https://stackoverflow.com/questions/77271442/skipdeployingnoopfunctions-in-firebase-causing-http-error-400-cloud-run-servic

### [REQUIRED] Version info

**node:**

v18.15.0

**firebase-functions:**

"firebase-functions": "^4.4.1"

**firebase-tools:**

13.0.1

**firebase-admin:**

"firebase-admin": "^11.10.1"

### [REQUIRED] Test case

There is someone else with the same problem: https://stackoverflow.com/questions/77271442/skipdeployingnoopfunctions-in-firebase-causing-http-error-400-cloud-run-servic

### [REQUIRED] Steps to reproduce

1. deploy functions to firebase functions
2. make no changes to function source
3. deploy again, you get the message "Skipping the deploy of unchanged functions with experimental support for skipdeployingnoopfunctions" and "Skipped (No changes detected)"

### [REQUIRED] Expected behavior

Functions to successfully complete deploy, since they were actually skipped anyways

### [REQUIRED] Actual behavior

✔  functions[smartsign-api:XXX(us-central1)] Skipped (No changes detected)
Error: HTTP Error: 400, Cloud Run service `XXX` does not exist in region `YYY` in this project.

### Were you able to successfully deploy your functions?

No, I received the above error. It works when I actually change the function source. I only have about 8 functions I am deploying currently.

**Comment by chriswaterbury** [comment]
I am also seeing this behavior with the same Error: HTTP Error: 400, Cloud Run service XXX does not exist in region YYY in this project.

**Comment by chriswaterbury** [comment]
Still seeing this behavior. Breaks CI/CD implementation because every deploy fails if there aren't function updates.

**Comment by chriswaterbury** [comment]
I opened an issue for the cli here https://github.com/firebase/firebase-tools/issues/6636.

**Comment by exaby73** [comment]
Since this is a CLI issue and a corresponding issue has been opened on `firebase-tools`, I feel safe to close this issue. Please follow updates on https://github.com/firebase/firebase-tools/issues/6636
