### ISSUE TITLE
Deployment Error: Function with scheduler  failed with "timezone is invalid"

### ISSUE THREAD

**Issue by avivdaniel** [firebase/firebase-functions#1504]
**Description:**

- Trying to write a Cloud Function to backup Firestore collections into a Google Cloud Storage bucket.

- Using a Blaze plan.
- firebase tools version - 12.7.0

- Referring to the documentation at https://cloud.google.com/firestore/docs/solutions/schedule-export.

**index.js file :**
```
const functions = require("firebase-functions");
const firestore = require("@google-cloud/firestore");
const client = new firestore.v1.FirestoreAdminClient();

const bucket = "gs://MY_BUCKET_NAME_HERE";

exports.scheduledFirestoreExport = functions.pubsub
    .schedule("every 7 days")
    .onRun((context) => {
      const projectId = process.env.GCP_PROJECT;
      const databaseName = client.databasePath(projectId, "(default)");

      return client.exportDocuments({
        name: databaseName,
        outputUriPrefix: bucket,
        collectionIds: [],
      })
          .then((responses) => {
            const response = responses[0];
            console.log(`Operation Name: ${response["name"]}`);
          })
          .catch((err) => {
            console.error(err);
            throw new Error("Export operation failed");
          });
    });
```
**package.json file:**

```

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "index.js",
  "dependencies": {
    "@google-cloud/firestore": "^7.1.0",
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.5.0"
  },
  "devDependencies": {
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
```

**Deployment Error:**
When running firebase deploy --only functions, encountering the following error about timezone :
<img width="731" alt="Screenshot 2023-12-17 at 16 38 44" src="https://github.com/firebase/firebase-functions/assets/60057464/b33b66df-a4a7-4ab8-9a28-de1ed5be8093">

**Error on google cloud console that may be related**
`Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'firebase-admin/auth'
Require stack:
- /layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/common/providers/identity.js
- /layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/v1/providers/auth.js
- /layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/v1/index.js
- /workspace/index.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/common/providers/identity.js:25:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
Could not load the function, shutting down.. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.`

Can anyone face the same problem?

**Comment by exaby73** [comment]
Hello @avivdaniel. From your screenshot, you are deploying to `us-central1` but your project seems to be in one of the Europe regions. Could you set your region to the correct region using `setGlobalOptions`? See [Change a function's region or regions](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#modify-region)

**Comment by avivdaniel** [comment]
> Hello @avivdaniel. From your screenshot, you are deploying to `us-central1` but your project seems to be in one of the Europe regions. Could you set your region to the correct region using `setGlobalOptions`? See [Change a function's region or regions](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#modify-region)

Yes you are right :) that was the issue. Thanks!

**Comment by exaby73** [comment]
Glad you got it working. I feel safe closing this issue. Feel free to comment and I can reopen the issue if you disagree
