### ISSUE TITLE
Discrepancy between built-in config parameters in documentation vs sdk

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-functions#1508]
### [REQUIRED] Version info

**node:** 18.19.0

**firebase-functions:** 4.5.0

**firebase-tools:** 12.9.1

**firebase-admin:** 11.9.0

### [REQUIRED] Test case

The [documentation for build-in parameters](https://firebase.google.com/docs/functions/config-env?gen=2nd#built-in_parameters) specify the following:

`projectId` — the Cloud project in which the function is running.
`databaseUrl` — the URL of the Realtime Database instance associated with the function (if enabled on the Firebase project).

However, the SDK exposes `projectID` and `databaseURL`:

https://github.com/firebase/firebase-functions/blob/a64fd48fac12cd6293885ec8402a334037470c44/src/params/index.ts#L72-L83

The documentation should be updated to be consistent with the SDK.

### [REQUIRED] Steps to reproduce

View documentation here: https://firebase.google.com/docs/functions/config-env?gen=2nd#built-in_parameters
View inconsistent code here: https://github.com/firebase/firebase-functions/blob/a64fd48fac12cd6293885ec8402a334037470c44/src/params/index.ts#L72-L83

### [REQUIRED] Expected behavior

The documentation to be consistent with the SDK

### [REQUIRED] Actual behavior

Documentation | SDK
-- | --
projectId | projectID
databaseUrl | databaseURL

### Were you able to successfully deploy your functions?

Yes

**Comment by Berlioz** [comment]
Thank you for this report! Our technical writer team has fixed this internally. I'm not quite sure what kind of propagation delay to expect getting it out to production, but this mistake should be fixed fairly soon on the public docs.

**Comment by johnnyoshika** [comment]
Looks like the documentation has already been updated
