### ISSUE TITLE
Bug in database.d.ts

### ISSUE THREAD

**Issue by sebastianrueckerai** [firebase/firebase-functions#1516]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `firebase-functions@4.6.0` for the project I'm working on.

You can find details about the issue here
**https://github.com/firebase/firebase-functions/issues/1496**

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/firebase-functions/lib/common/providers/database.d.ts b/node_modules/firebase-functions/lib/common/providers/database.d.ts
index fe660d1..1d40471 100644
--- a/node_modules/firebase-functions/lib/common/providers/database.d.ts
+++ b/node_modules/firebase-functions/lib/common/providers/database.d.ts
@@ -97,7 +97,7 @@ export declare class DataSnapshot implements database.DataSnapshot {
      * @return `true` if enumeration was canceled due to your callback
      *   returning `true`.
      */
-    forEach(action: (a: DataSnapshot) => boolean | void): boolean;
+    forEach(action: (a: any) => boolean | void): boolean;
     /**
      * Returns `true` if the specified child path has (non-`null`) data.
      *
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sceee** [comment]
Duplicates #1513

**Comment by exaby73** [comment]
Fixed by https://github.com/firebase/firebase-functions/pull/1517. I will close this issue for that reason
