### ISSUE TITLE
How to deploy function with latest secrets at RUNTIME?

### ISSUE THREAD

**Issue by davidoort** [firebase/firebase-functions#1532]
### [REQUIRED] Version info

**node:** 19.9

**firebase-functions:** ^4.7.0

**firebase-tools:** 12.6.2

**firebase-admin:** ^11.11.0

### [REQUIRED] Test case

Deploy a function with firebase deploy --only functions with the following config

```
setGlobalOptions({
  region: 'us-central1',
  secrets: [
    "openai",
  ],
});
```
And see the following in the function settings:
<img width="318" alt="image" src="https://github.com/firebase/firebase-functions/assets/21220927/4aafe09a-b25e-4b43-aeb4-5fe314cd7c7c">

### [REQUIRED] Steps to reproduce

1. Create a secret in Google Secret Manager
2. Deploy a function with firebase deploy --only functions with the following config

```
setGlobalOptions({
  region: 'us-central1',
  secrets: [
    "secret_name",
  ],
});
```

### [REQUIRED] Expected behavior

Doing something like:
```
setGlobalOptions({
  region: 'us-central1',
  secrets: [
    openaiSecret:latest,
  ],
});
```
And seeing the following in the deployed function settings:
<img width="338" alt="image" src="https://github.com/firebase/firebase-functions/assets/21220927/2fbbadf0-d8a8-41e4-a902-b1aa4ee9d552">

### [REQUIRED] Actual behavior

The secrets as environment variables had a fixed version set to the latest version at DEPLOY time. I could only find a way to update them to the latest version at RUNTIME through the GUI.

### Were you able to successfully deploy your functions? Yes, but the secrets had a fixed version set to the latest version at DEPLOY time.

No

**Comment by inlined** [comment]
As a team we have decided that this is an anti-pattern and have gone through steps to _prevent_ this behavior. Pinning to the latest version causes your fleet to have different values depending on when the container was last started, which would likely be the source of great customer confusion and many support requests. For example, if you have `minInstances` set, your key may never actually rotate until next deploy.

If you use `firebase functions:secrets:set` it will automatically identify all functions that depend on this secret value and prompt you to redeploy to push the latest value everywhere.
