### ISSUE TITLE
Papertrail doesnt connect on firebase functions.

### ISSUE THREAD

**Issue by vongohren** [firebase/firebase-functions#154]
### Version info

**firebase-functions:**
6.11

**firebase-tools:**
3.14

### Test case

Use winston papertrail lib and try to log to papertrail on a host they provide you with
I tried the normal URL, works fine in emulator and locally
Host: logsX.papertrailapp.com
Port: 40XXX

Aswell as with IP directly but then I got a different error.

### Steps to reproduce

Just try to run the code, and it wont connect and cant find these dns or IP.

```
const winston = require('winston')
import * as functions from 'firebase-functions';
require('winston-papertrail').Papertrail;

const DEV = process.env.NODE_ENV !== 'production';
console.log(DEV)
const papertrailConfig = functions.config().papertrail;

const winstonConsole = new winston.transports.Console({
    prettyPrint: true,
    colorize: 'all',
    silent: false,
    timestamp: false
})

const exceptionHandlers = [winstonConsole]
const transports = [winstonConsole]

if(!DEV) {
  const winstonPapertrail = new winston.transports.Papertrail({
    host: papertrailConfig.host,
    port: papertrailConfig.port,
    colorize: true,
    program: papertrailConfig.name
  })

  winstonPapertrail.on('error', function(err) {
    console.log(err);
  });

  exceptionHandlers.push(winstonPapertrail);
  transports.push(winstonPapertrail);
}

winston.handleExceptions(exceptionHandlers);

class Logger {
  constructor() {
      this.mainLogger = new winston.Logger({
        transports: transports
      });
  }

  log(level, message) {
      this.mainLogger[level](message);
  }

  close() {
      this.mainLogger.close()
  }
}

const LoggerClass = new Logger();

process.on("unhandledRejection", function(reason, promise) {
    LoggerClass.log('error', reason)
});

module.exports = LoggerClass;
```

### Were you able to successfully deploy your functions?

Yes, it was successfull

### Expected behavior

Connect to papertrail, and send logs.

### Actual behavior

`{ Error: getaddrinfo ENOTFOUND logsX.papertrailapp.com logsX.papertrailapp.com:40XXX
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'logsX.papertrailapp.com',
  host: 'logsX.papertrailapp.com',
  port: '40XXX' }`

`{ Error: connect ETIMEDOUT 169.XX.XX.XXX:40XXX
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '169.XX.XX.XXX',
  port: 40XXX }`

**Comment by justinrosenthal** [comment]
Have you enabled billing on your Firebase project?  The free Spark plan does not allow making external network requests from within your functions, so this could explain the behavior you're seeing.  Note that if you upgrade to the Blaze plan (pay as you go), you're still eligible for a free tier of resources, as explained [here](https://firebase.google.com/pricing/):

> The Spark plan allows outbound network requests only to Google-owned services. Inbound invocation requests are allowed within the quota. On the Blaze plan, Cloud Functions provides a perpetual free tier. The first 2,000,000 invocations, 400,000 GB-sec, 200,000 CPU-sec, and 5 GB of Internet egress traffic is provided for free each month. You are only charged on usage past this free allotment.

**Comment by vongohren** [comment]
@justinrosenthal aahhh thanks! I remember that now, but guess I forgot in the heat of the moment! It just didnt make sense at all :P Thanks for the catch!
