### ISSUE TITLE
Firestore requires GCLOUD_PROJECT environment variable to be set for unit tests

### ISSUE THREAD

**Issue by gmeans** [firebase/firebase-functions#157]
While attempting to set up a testing configuration similar to the [Official Docs](https://firebase.google.com/docs/functions/unit-testing#review_complete_sample_test_code) I ran into an issue with my firestore cloud functions.

**Please note:** I don't actually have any tests for the firestore cloud functions. I was just running the hello world test and working on wiring everything up.

Briefly, I kept getting the following error when trying to run tests:
```
TypeError: Path must be a string. Received undefined
```

It turned out to be related to these lines:

https://github.com/firebase/firebase-functions/blob/fbe4b646bf6517b80a63062dfece5e2d0de21a8a/src/providers/firestore.ts#L37-L39

Running my tests w/ the env variable set works:

```
GCLOUD_PROJECT=my-project-id npm run test
```

Ideally this shouldn't be necessary since the firebase config includes a `projectId` attribute already. Otherwise it should be noted in the documentation that this environment variable is available.

### Version info

**firebase-functions:** 0.7.5

**firebase-tools:** 3.16.0

**firebase-admin:** 5.6.0

### Test case

Attempting to test a firestore cloud function using mocha.

* Set up the testing configuration from the documentation with only the Hello World test.
* Include a Firestore cloud function as part of your functions, but have not tests for them.

### Steps to reproduce

* With the above test case, simply run your tests.

### Were you able to successfully deploy your functions?

N/A

### Expected behavior

![screen shot 2017-12-24 at 9 51 51 am](https://user-images.githubusercontent.com/277741/34327356-190366d4-e890-11e7-8a7e-f07482e84842.png)

### Actual behavior

![screen shot 2017-12-24 at 9 52 40 am](https://user-images.githubusercontent.com/277741/34327361-359726f0-e890-11e7-9683-7aa7e482e9b6.png)

**Comment by tsemerad** [comment]
I ran into this as well. I would love to see official documentation showing how to unit test firestore cloud functions.

**Comment by laurenzlong** [comment]
Thanks for filing, I will get the documentation fixed.

**Comment by merlinnot** [comment]
That's really nice of you. May I kindly ask if you have any information regarding local testing of Firestore? There's a nice solution for a Realtime Database, but testing Firestore is unfortunately much less pleasant.

**Comment by laurenzlong** [comment]
The documentation was updated a few weeks ago to include this: https://firebase.google.com/docs/functions/unit-testing.

@merlinnot I'm working on a separate library that will make unit testing easier for all the event types. Look out for it! :) Sign up at https://firebase.google.com/alpha if you want to new features before they come out.

**Comment by merlinnot** [comment]
@laurenzlong Thank you for the link, I've participated in many of Google's alphas so I hope to get access to this one too :) Does your work cover just invoking these functions or also calls to the methods of `firebase-admin` (especially Firestore)?

**Comment by laurenzlong** [comment]
Awesome! Initially it'll just be for invoking these function, but it may grow to cover other scenarios in the future.
