### ISSUE TITLE
Any Document Trigger Failing for nested triggers

### ISSUE THREAD

**Issue by andresvlaeminck** [firebase/firebase-functions#1570]
### Related issues

this person is running into a similar issue as I am: [StackOverflow](https://stackoverflow.com/questions/78483973/error-in-firebase-function-2n-gen-typeerror-cannot-read-properties-of-undefin)

### [REQUIRED] Version info

**node:**
v19.0.1

**firebase-functions:**
5.0.1

**firebase-tools:**
13.6.0

**firebase-admin:**
12.1.1

### [REQUIRED] Test case
`
 exports.chatNotification = onDocumentCreated("Matches/{matchID}/Messages/{messageID}", async (event) => {
   console.log("function is working") 
  });`
### [REQUIRED] Steps to reproduce

1. Deploy the function (works fine)
2. Write to the Messages collection

### [REQUIRED] Expected behavior

function running normally and printing "function is working"

### [REQUIRED] Actual behavior

TypeError: Cannot read properties of undefined (reading 'value')
    at func (/workspace/node_modules/firebase-functions/lib/v2/providers/firestore.js:297:115)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:113:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Were you able to successfully deploy your functions?

Deployment works as expected

**Comment by andresvlaeminck** [comment]
Using older versions of firebase and functions seems to work:
"firebase-admin": "^11.8.0",
"firebase-functions": "^4.3.1"

**Comment by exaby73** [comment]
Could you tell me which specific versions are causing this issue?
