### ISSUE TITLE
While npm install firebase its unable to download grpc module and i have tried it independently also

### ISSUE THREAD

**Issue by ankush2394** [firebase/firebase-functions#158]
### Version info

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

**Comment by asifm** [comment]
You have not provided any detail. When you open an issue, you must follow the guideline.

**Comment by ankush2394** [comment]
Steps to produce - 1. npm install firebase 
Only one step process.
Node version tried- 8.9.3 and 6.3 versions 
Npm version tried - 5.4 and 3.2 
Also tried deleting node_packages and then npm install.
Also tried including firebase in package.json and then npm install.
Also tried same process with yarn and bower.
Error is its unable to download grpc module@1.8 .
Also tried downloading grpc independently with both firewall open and close.
Any other expected solution before i need to eject at last.

**Comment by asifm** [comment]
Current Node version running Cloud Functions is 6.11.5. Could you try with this version?

**Comment by ankush2394** [comment]
![image](https://user-images.githubusercontent.com/11161508/34377640-ed53e3f8-eb17-11e7-8cac-50749ae1df4d.png)
![image](https://user-images.githubusercontent.com/11161508/34377662-fcc72a52-eb17-11e7-930e-4817e008a5cc.png)

**Comment by ankush2394** [comment]
Not working again.

**Comment by asifm** [comment]
I was also having the same problem, but it went away when I used Node 6.11.5. My npm is 5.5.1 (latest version). You could try after updating your npm. If that doesn't solve it, I hope someone else will be able to help.

**Comment by ankush2394** [comment]
So I already tried out with the version of npm you have mentioned but that doesnot solve it.
Anyways, thanks for the concern.

**Comment by laurenzlong** [comment]
@ankush2394 from your screenshots, you were actually installing "firebase", not "firebase-functions", please file your issue in https://github.com/firebase/firebase-js-sdk/issues
