### ISSUE TITLE
V2 Database triggers. Impossible to override "retry" value

### ISSUE THREAD

**Issue by JR-RomanZaiats** [firebase/firebase-functions#1584]
### [REQUIRED] Version info

**node:** v20.11.1

**firebase-functions:** 4.9.0

**firebase-tools:** 13.7.4

**firebase-admin:** 12.0.0

### [REQUIRED] Test case

I have investigated that there is no override of "retry" prop for v2->providers->database.js,
meanwhile, firestore.js allows to override it.
<img width="1721" alt="image" src="https://github.com/firebase/firebase-functions/assets/142788342/567d5de0-4e19-45ec-8ab5-fa4340b394bc">

### [REQUIRED] Steps to reproduce

Declare trigger function with such config
<img width="703" alt="image" src="https://github.com/firebase/firebase-functions/assets/142788342/c104c054-c3a9-4c3e-93dd-cd3c9640e997">

run ```npx firebase deploy --only functions:rdbms-testRetryRTDB```

after deployment the retry is disabled
<img width="147" alt="image" src="https://github.com/firebase/firebase-functions/assets/142788342/4c7edef1-a1a4-4bca-b391-1be6c6d91ace">

### [REQUIRED] Expected behavior

retry config works properly

### [REQUIRED] Actual behavior

retry config is ignored during deployment

**Comment by MaxGenash** [comment]
same problem

**Comment by MaxGenash** [comment]
@taeold @mbleigh @inlined would be nice if smb could look into it :)

**Comment by exaby73** [comment]
Hey! I've found the issue being that the retry parameter in the functions.yaml config that's sent over to GCP doesn't get populated. I'm working on a fix right now. Sorry for the late response :)
