### ISSUE TITLE
How to create API Documentation?

### ISSUE THREAD

**Issue by voxelbusters** [firebase/firebase-functions#159]
Is it possible to create Swagger/OpenAPI documentation for the Firebase Cloud Functions?

**Comment by laurenzlong** [comment]
Could you be more specific about what you mean? Do you mean that you'd like to create documentation for REST APIs that you create by writing HTTPS functions?

**Comment by voxelbusters** [comment]
Yea. Sorry for not being clear.
Is it possible to create API spec for the http endpoints I wrote as
functions? If so how can i do it?

**Comment by DePalmo** [comment]
I too tried using Swagger but they are not following OpenAPI 3.0 specs, so I found a better solution: https://www.getpostman.com/

**Comment by voxelbusters** [comment]
@DePalmo  May I know your workflow for creating specification?

**Comment by DePalmo** [comment]
I manually added route by route and attached their actual responses where possible (Postman can call your API and you can use an actual response from it), otherwise I created a sample response manually.
