### ISSUE TITLE
v5.1.0 Fails to deploy on "firebaseextensions.instances.list"

### ISSUE THREAD

**Issue by jeffgaynor** [firebase/firebase-functions#1598]
### Related issues

n/a

### [REQUIRED] Version info

**node:**  v20.16.0

**firebase-functions:** ^5.1.0

**firebase-tools:** ^13.15.3

**firebase-admin:** "^12.3.1"

### [REQUIRED] Test case

Run `firebase deploy --only functions --force`

### [REQUIRED] Steps to reproduce

Upgrade Firebase Functions to latest version: 5.1.0

### [REQUIRED] Expected behavior

Functions deploy successfully

### [REQUIRED] Actual behavior

Functions fail to deploy

### Were you able to successfully deploy your functions?

Initial output was:
```Project Console: https://console.firebase.google.com/project/my-repo/overview
$ firebase deploy --only functions --force

=== Deploying to 'my-project'...

i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8[79](https://github.com/my-repo/actions/runs/10479672777/job/29025902274#step:7:80)0

✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled

Error: An unexpected error has occurred.
Error: Process completed with exit code 2.
```

Running deploy with debugging shows this detail: 
```["firebase.projects.get","firebaseextensions.instances.list"]***
[2024-08-21T14:58:54.306Z] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.want (/home/runner/work/my-repo/node_modules/firebase-tools/lib/deploy/extensions/planner.js:120:28)
    at prepareDynamicExtensions (/home/runner/work/my-repo/node_modules/firebase-tools/lib/deploy/extensions/prepare.js:122:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepare (/home/runner/work/my-repo/node_modules/firebase-tools/lib/deploy/functions/prepare.js:62:9)
    at async chain (/home/runner/work/my-repo/node_modules/firebase-tools/lib/deploy/index.js:40:9)
    at async deploy (/home/runner/work/my-repo/node_modules/firebase-tools/lib/deploy/index.js:97:5)
```

Downgrading identical code to v5.0.1 works. So it's definitely an issue with v5.1.0, which included this: https://github.com/firebase/firebase-functions/pull/1590 related to extensions.

**Comment by AmilKey** [comment]
I got an error "firebase cloud error Failed to load function definition from source" when I upgraded from 5.0.1 to 5.1.0

**Comment by rendomnet** [comment]
Same issue here.
```
[debug] [2024-08-26T16:42:30.433Z] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.want (/Users/---/Library/pnpm/global/5/.pnpm/firebase-tools@13.15.3_encoding@0.1.13/node_modules/firebase-tools/lib/deploy/extensions/planner.js:120:28)
```

**Comment by christopheramason** [comment]
I am seeing an issue when deploying via CI probably due to a similar/related issue with a change made in 5.1.0

```
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled

Error: HTTP Error: 403, The caller does not have permission
```

**Comment by metabit-goody** [comment]
I was able to resolve this by updating to the latest version of firebase-tools (13.16.0)

**Comment by exaby73** [comment]
@jeffgaynor @rendomnet @christopheramason Were you able to solve this as well by upgrading the firebase-tools package?

**Comment by exetico** [comment]
@google-oss-bot : I'm facing the same issue. Could you please re-open it?

What's the most fitted IAM role for `firebaseextensions.instances.list`? I'm struggling to find it.

```
    "firebase-functions": "^6.0.1",
    "firebase-tools": "^13.19.0",
```

Also mentioned here:
https://github.com/firebase/firebase-tools/issues/7582#issuecomment-2373420949

**Comment by ifielker** [comment]
`Firebase Extensions Viewer` is a good role for giving firebaseextensions.instances.list

**Comment by kevinsschmidt** [comment]
I can't event find this permission in IAM.

![image](https://github.com/user-attachments/assets/69402d00-0ea6-47b2-b001-eb226d3f5edd)

**Comment by IbrahimItani01** [comment]
Anyone found a solution?
I am trying to deploy a NestJS App to Firebase Cloud Functions using Bitbucket pipelines and this error keeps showing in deployment:
`error while checking permissions, command may fail: Authorization failed. This account is missing the following required permissions on project :
  firebaseextensions.instances.list
[2025-03-26T11:58:56.947Z] No OAuth tokens found
[2025-03-26T11:58:56.949Z] >>> [apiv2][query] GET https://firebaseextensions.googleapis.com/v1beta/projects/instances pageSize=100&pageToken=
[2025-03-26T11:58:57.227Z] <<< [apiv2][status] GET https://firebaseextensions.googleapis.com/v1beta/projects/instances 403
[2025-03-26T11:58:57.228Z] <<< [apiv2][body] GET https://firebaseextensions.googleapis.com/v1beta/projects/instances {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
Error: Request to https://firebaseextensions.googleapis.com/v1beta/projects/instances?pageSize=100&pageToken= had HTTP Error: 403, The caller does not have permission
[2025-03-26T11:58:57.230Z] Error Context: {
  "body": {
    "error": {
      "code": 403,
      "message": "The caller does not have permission",
      "status": "PERMISSION_DENIED"
    }
  },
  "response": {
    "statusCode": 403
  }
}`

**Comment by Gustavoopb** [comment]
> `Firebase Extensions Viewer` is a good role for giving firebaseextensions.instances.list

Hey @ifielker I had the same issue reported, and it fixed by adding `Firebase Extensions Viewer`. I saw that some other resources gives the list of resources that can be added to allow access to certain api. Do you think this approach could be added here? 
One example is: 
```
Error: Missing permissions required for functions deploy. You must have permission iam.serviceAccounts.ActAs on service account <account-principal>.

To address this error, ask a project Owner to assign your account the "Service Account User" role from this URL:

https://console.cloud.google.com/iam-admin/iam?project=<project-id>
Error: Process completed with exit code 1.
```
