### ISSUE TITLE
⚠  functions[functionName]: Deployment error. Failure in the execution environment

### ISSUE THREAD

**Issue by goelmk** [firebase/firebase-functions#160]
### Version info

**firebase-functions:** 0.7.5

**firebase-tools:** 3.16.0

**firebase-admin:** 5.6.0

### Test case

firebase deploy --only functions:<functionName>

### Steps to reproduce

Run `firebase deploy` or `firebase deploy --only functions:<functionName>`

### Were you able to successfully deploy your functions?

Yes, all except one causing the issue. Earlier there were 5-6 functions which shown deployment error but deploying them one at a time using `--only functions:<functionName>` worked, but one of the functions a consistently showing this error while the same function I have had deployed earlier about 4 weeks back successfully.

### Expected behavior

Should deploy all the functions without any errors.

### Actual behavior

⚠  functions[functionName]: Deployment error.
Failure in the execution environment

**Comment by goelmk** [comment]
@laurenzlong can you please help with this?

**Comment by laurenzlong** [comment]
This looks like a production issue, can you file a support ticket at firebase.google.com/support
