### ISSUE TITLE
Slow execution of (simple) functions

### ISSUE THREAD

**Issue by Druux** [firebase/firebase-functions#161]
### Version info

**firebase-functions:** 0.8.0

**firebase-tools:** 3.16.0

**firebase-admin:** Currently not in use.

### Test case

I have just created a simple cloud function:
```
exports.sayHelloToUser = functions.https.onRequest((req, res) => {
        return res.send("That's a test.");
});
```

### Steps to reproduce

Just create the function - deploy - test.
You can even test my function via the url: https://us-central1-fnx-pbox.cloudfunctions.net/sayHelloToUser

### Were you able to successfully deploy your functions?

Yes.

### Expected behavior

Due to the fact that the function basically returns a simple string, I expect to get a response within a few milliseconds.
I know that firebase-functions is currently in beta, but I think the execution time, especially of simple functions, shouldn't be that long.

### Actual behavior

It depends - sometimes I am getting the response instantly, sometimes I am getting the response after seconds (!!!). Why is there such a high fluctuation?

Log:
![image](https://user-images.githubusercontent.com/9655723/34561248-5693dfe4-f149-11e7-8445-40d993775781.png)

**Comment by merlinnot** [comment]
From: https://cloud.google.com/functions/docs/bestpractices/tips

> Note: Several of the recommendations in this document center around what is known as a cold start. Functions are stateless, and the execution environment is often initialized from scratch, which is called a cold start. Cold starts are expensive. It is best practice to avoid unnecessary cold starts, and to streamline the cold start process to whatever extent possible (for example, by avoiding unnecessary dependencies).

You can find some context in https://github.com/firebase/firebase-functions/issues/35

**Comment by laurenzlong** [comment]
Thanks for stepping in @merlinnot !

**Comment by erichiggins** [comment]
This answer isn't good enough.  If the delay was only due to cold start, then you'd expect to see subsequent calls be performant. That's simply not the case.

Furthermore, the documentation linked by @merlinnot is for GCP Cloud Functions. Since Firebase Functions appear to be a rebranded (and possibly watered-down) version of Cloud Functions, it'd be useful to know what the differences are (especially performance differences).

The Firebase Functions logs lack the debugging tools that developers need to diagnose performance issues on their own. While they can be viewed in the more advanced GCP Logging console, there does not appear to be any detailed Trace capabilities like there are for other GCP offerings.

**Comment by laurenzlong** [comment]
Hey @erichiggins we share the same infrastructure as Google Cloud Functions so the performance characteristics are the same. Everything on that page applies. 

We are aware that lack of advanced trace capabilities is a concern, and we are actively working on it.

**Comment by erichiggins** [comment]
Thanks @laurenzlong .  Great to hear that tracing is being worked on!

Regarding the original issue, is there agreement on your end that more could be done to improve the performance of Firebase Functions from an infrastructure standpoint? If so, is there at least one public ticket open for tracking progress?

**Comment by laurenzlong** [comment]
Here's the public tracker for Google Cloud Functions https://issuetracker.google.com/savedsearches/559729

**Comment by slavafomin** [comment]
I'm also encountering a terrible response time from Firebase Functions, the simple "Hello World" example is taking from 2 to 5 seconds to respond. This makes the platform absolutely unusable in production. Is there any optimizations that we can do to improve it?

The idea behind Firebase Functions looks amazing, we would definitely want to use it in our next project, but performance issue raises very serious concerns right now.

**Comment by ntomallen** [comment]
Agreed. One use case for an app we're building is accessing a Facebook Graph API edge without a user access token - which means using our app secret in the server environment to handle the API call. Having a long response time for http function triggers means that we'll probably have to look for a solution elsewhere for this sort of API request.

**Comment by pythagoras1357** [comment]
ugh, I've just implemented a relatively straight-forward function triggered from a realtime db update, and it takes SECONDS, some times many. Unusable.

**Comment by andrew-veresov** [comment]
It looks like multiple instances of a Function are created at run time. Some of them might be in a cold state but some might be already warmed up. So as many requests you have as lower latency will be (less ~2-3sec fluctuations)

**Comment by larssn** [comment]
My educated guess would be that you're hitting a load balancer, with X (8'ish I'm guessing) nodes behind it, each with their own execution environment and cold starts (after deployment).

**Comment by harrison0723** [comment]
I can second what @enzomd said. I even wrote a little cron job that pings my function every minute. Despite *some* 3 seconds wait time, the majority of waiting time for requests still seem very random, averaging at 10-15 seconds. Even the engineering manager for React [agrees with us](https://twitter.com/sophiebits/status/1028491825747656705).

I have interacted with a few people at the Firebase team ([on SO](https://stackoverflow.com/questions/51782742/how-can-i-keep-google-cloud-functions-warm)) and from email support. Based on the replies, I think the team should really tackle this issue, instead of just telling us that we need to improve our codebase, or that this is just a **trade off**.

Firebase is really an amazing platform, and I'm really thankful for the people behind it, so please don't take my comments as criticizing. I simply want the best for Firebase and I really hope the team could eventually solve this issue and make it an even better platform.

**Comment by enzomd** [comment]
I just updated my function to the node 8 runtime, with 2GB of RAM (even though the GCP web UI says the function only uses 150MB max).

My response times dropped from >10s to around 3 seconds. Still too slow.

**Comment by ntomallen** [comment]
A few days ago, I implemented a sort of complex cloud function that does a lot of calculation based off of the users "history" in a collection. Kind of an audit sort of thing. On a dry run, it takes about 3 seconds from call to response (it's https callable), which is much better than I thought it would be. So it definitely seems that the feature is getting better, but definitely not in the real-time category yet.

**Comment by tojacob** [comment]
Do these tests, if someone serves you. The function returns a simple "hello world" ✌
The first 10 are cold starts.

![01](https://user-images.githubusercontent.com/26469677/45575141-0f597380-b838-11e8-868a-410fa4c323f8.png)
![02](https://user-images.githubusercontent.com/26469677/45575142-0f597380-b838-11e8-83da-314d3a9121e5.png)
![03](https://user-images.githubusercontent.com/26469677/45575143-0f597380-b838-11e8-8ca5-ee10731d5ebd.png)

**Comment by buzzware** [comment]
I'm in Australia and I also find the Firebase console slow. I'm on Telstra FTTN. Here's a speed check 
![image](https://user-images.githubusercontent.com/28285/45737330-0f82b600-bc20-11e8-8854-27374b6f016f.png)

and here's what I get loading the firebase console database tab in Chrome Canary's network waterfall graph with caching disabled in the browser :

![image](https://user-images.githubusercontent.com/28285/45737751-42797980-bc21-11e8-9aa1-664e41607699.png)

It repeatedly takes about 15 seconds to load everything (not counting the ongoing listening request). 16 of the requests take over 500ms, and 4 of them are over 1s.

Is this normal?

**Comment by andrew-veresov** [comment]
@buzzware it's better to report a new issue about slow console loading time. This thread is focused on firebase functions/firestore latency issues.

**Comment by buzzware** [comment]
This is now an issue for my client. I thought I'd try pinging my firebase app server regularly to keep it awake and monitor the response time. Its great to see StackDriver does this (StackDriver is a hidden gem I'm finding).

I created a heartbeat function that simply tries to get a non-existant record from firestore (to wake it up) then returns {success: true} as json.

Attached are the graphs, highlighting different client locations.

<img width="614" alt="screen shot 2018-10-31 at 11 22 53 am" src="https://user-images.githubusercontent.com/28285/47765029-fda62f80-dd02-11e8-94cc-cc33778d4767.png">
<img width="609" alt="screen shot 2018-10-31 at 11 23 13 am" src="https://user-images.githubusercontent.com/28285/47765030-fda62f80-dd02-11e8-8690-60a71db0fe18.png">
<img width="615" alt="screen shot 2018-10-31 at 11 23 19 am" src="https://user-images.githubusercontent.com/28285/47765031-fda62f80-dd02-11e8-8cc3-e27540d5f712.png">
<img width="645" alt="screen shot 2018-10-31 at 11 23 29 am" src="https://user-images.githubusercontent.com/28285/47765032-fe3ec600-dd02-11e8-8fcb-2c4560b7d2e3.png">

Conclusions :

1) When pinging every minute the issue is perhaps more geographic than due to cold starts. You get good results if you are US based, but can still be regularly over 5s for Singapore and Belgium. Perhaps this explains the complaints here that don't seem to be recognised by the dev team - it doesn't happen from where they are.
2) Pinging every 5 minutes gives a worse response (need to investigate further) - probably due to cold starts.

BTW, I regularly see 5 to 10s in occasional use from Australia, perhaps including a cold start.

Thought :
Pinging one function in the app doesn't necessarily keep all functions in a project awake. Functions could be deployed on different servers in different datacenters. Perhaps each function could look for a special KeepWarm header that causes it to do nothing. Then I could ping certain critical functions.

**Comment by buzzware** [comment]
Some early data pinging every 10 minutes
![image](https://user-images.githubusercontent.com/28285/47769614-6a2b2980-dd17-11e8-845f-b47a7cebb10f.png)

**Comment by buzzware** [comment]
10 minute intervals
![image](https://user-images.githubusercontent.com/28285/47826757-9cd72f80-ddb4-11e8-8768-d1aa38af1e90.png)

**Comment by buzzware** [comment]
For comparison, this is loading the index.html every 10 minutes. Where is the CDN ? I was expecting this to be much faster and more consistent.
![image](https://user-images.githubusercontent.com/28285/47889371-9dd79200-de84-11e8-93f4-8587f83adf39.png)

**Comment by buzzware** [comment]
The last one is just my domain /index.html. I don't want to specify my domain, but I'll try monitoring the raw google address in case the DNS has anything to do with it.

**Comment by mbleigh** [comment]
If you're up for sharing more detail privately, my email is my last name at
google.com

**Comment by buzzware** [comment]
Michael, I appreciate your interest, but I think if any internal person spent an hour creating a firebase project and uptime monitoring in StackDriver, they'd see the same thing. I've done my best to draw attention to it, but Google needs to take it from here. I want to base my business on Firebase (for 2 present plus future projects), but this issue could be a deal breaker for some things, including one present project. A platform that works for only some projects is annoying. I'm only wanting Firebase to live up to its marketing, which Google obviously has the capability to do. It looks like an oversight (most likely) or a deliberate cost saving (?) strategy.

**Comment by mbleigh** [comment]
I am a Googler, I'm telling you for certain that the latency you're seeing on a static file on Firebase Hosting is unexpectedly high, and I'm asking for more details so that I can help find out what's going on. I'm also doing some of my own analysis, but I can actually go look at specific data to your tests if you give me some more info.

Just trying to help! 👍

**Comment by buzzware** [comment]
OK, I'll try and find some time over the weekend to make that test project

**Comment by buzzware** [comment]
After emails with @mbleigh I've made this test project https://github.com/buzzware/latency-test-us hosted at https://latency-test-us.firebaseapp.com and set up stack driver to monitor index.html (on FB Hosting), heartbeat?database=true and heartbeat?database=false.
I did a quick test with https://www.webpagetest.org eg. https://www.webpagetest.org/result/181104_7X_6f1c3dcd8e83dbdba2dd7c114cb3058e/
and as he says, the latency there is decent (~600ms) including a database request.
The issue may be stackdriver, but I have seen long delays on my projects in Chrome dev tools.

**Comment by buzzware** [comment]
The domain name/DNS seems to explain the 5+ second peaks.

Firebase domain :
![image](https://user-images.githubusercontent.com/28285/47979019-c87f5000-e0fb-11e8-9d7e-09bf64af74b0.png)

My custom domain, hosted by synergywholesale.com, an Australian registrar with DNS servers in Sydney, Melbourne and CA
![image](https://user-images.githubusercontent.com/28285/47979031-d7660280-e0fb-11e8-9c49-f21c8ca0705e.png)

These peaks appear on Firebase hosting and functions with my custom domain, but do not appear on a Cloudfront site in Australia, or on any Firebase domain I've tried.
I think this means it is not a Google issue.

**Comment by buzzware** [comment]
Here are the result for that latency-test-us project :

![image](https://user-images.githubusercontent.com/28285/47979218-cec1fc00-e0fc-11e8-9afc-c912ed3559e5.png)

![image](https://user-images.githubusercontent.com/28285/47979229-e26d6280-e0fc-11e8-98e9-68f16e38e9ef.png)

![image](https://user-images.githubusercontent.com/28285/47979243-fd3fd700-e0fc-11e8-9174-75691ffae178.png)

An Australian AWS Cloudfront Site (for comparison) :
![image](https://user-images.githubusercontent.com/28285/47979264-22344a00-e0fd-11e8-8d5b-ccd8193a7c16.png)

**Comment by mbleigh** [comment]
Good sleuthing! Thanks for sharing all of your findings!

**Comment by stevebrush** [comment]
Curious why this issue was closed?

**Comment by buzzware** [comment]
@stevebrush It was closed in January. That is a good question, but right now my only issue is the speed with a couple of low traffic sites in development. It seems to perform ok when under load. My issue above turned out to be the DNS. 

Can anyone else comment on performance under load?

**Comment by emgould** [comment]
Have any of you down in Australia have any experience with performance of the firebase real-time database ( not firestore )?

**Comment by anubhavberry** [comment]
I've moved off realtime database. Only using firestore and (slight segway)
have experienced performance issues particularly outside business Melbourne
Sydney business hours. Perth has the worst performance.

**Comment by emgould** [comment]
Thanks for the response. Our use case is ill-suited for firestore.  I was just curious how latent/slow it is given it so far from the central us where firebase realtime db is hosted.

**Comment by anubhavberry** [comment]
When we were using realtime db response was almost comparable to Firestore.
BTW migrating to Firestore is quite easy, it's cheaper, out of beta and is
now available in Australia

**Comment by couchfault** [comment]
This is still very much an issue. I've been working with firebase / node 8 and simple https callable functions querying small firestore collections for documents containing small paragraphs of text takes between 4 and 10 seconds, with some functions occasionally taking upwards of a minute and timing out. None of these functions implement complex logic or large queries, and my firestore database is quite small.

**Comment by buzzware** [comment]
Use express to put all endpoints on one function, then use Stack Driver uptime monitoring and/or  Cloud Scheduler to hit an endpoint every minute. I get good consistent times doing this.

**Comment by couchfault** [comment]
@buzzware Does this cause firebase to cache the function? I'm currently using onCall functions so this would require a refactor. If I can't find a better solution I'll try it. I just finished writing a lazy loader for all my functions to prevent unused functions from being loaded

**Comment by buzzware** [comment]
The key point they don't tell you is that each exported function in functions/index.js ends up being executed in its own container(s) separate from the others. So waking up one function does not wake up the others, and in development if you don't yet have users and loading your app requires a few firebase functions, there are going to be multiple cold starts.
So putting all endpoints on one function means that when one wakes up, they all wake up.
The functions api is based on express, so its not hard to migrate.
Also, if you set up stackdriver uptime monitoring to hit it every minute, your api will always be awake, you'll have monitoring and you'll still be under the free threshold.
See https://github.com/buzzware/function-split-test

**Comment by couchfault** [comment]
By combining @buzzware's StackDriver suggestion and writing a lazy loading function, I managed to get most functions to execute in under a second. Thanks! Here's the function I use for anyone who's interested:
```
const moduleCache = {
    categories: null,
    pages: null,
    stickylinks: null,
    sections: null,
    groups: null,
    calendars: null,
    testimonials: null,
    locations: null,
    guidebios: null,
    maps: null,
    events: null,
    media: null,
    menulinks: null,
    shortlinks: null,
    contact: null,
    images: null,
    cloudinary: null
};

const hotloadFunction = function(functionName, moduleName, moduleFunction) {
    if (!process.env.FUNCTION_NAME || process.env.FUNCTION_NAME === functionName) {
        var module;
        if (moduleCache[moduleName]) {
            module = moduleCache[moduleName];
        } else {
            module = (moduleCache[moduleName] = require('./' + moduleName + '.js'));
        }
        return module[moduleFunction];
    }
    return null;
}
```
Usage eg:
`exports.createCategory = hotloadFunction('createCategory', 'categories', 'create');`
It assumes functions are stored in `./$moduleName.js`, so tweak accordingly.

**Comment by kayzenkayzen** [comment]
@couchfault really works without side effects?

**Comment by mellowcello77** [comment]
So my question is, as always, how scalable is cloud functions it if simple queries take a minute to run?  Not a cold start issue.

**Comment by mbleigh** [comment]
@mellowcello77 if you have a simple query that reliably takes a minute to run, it would be really valuable to us to see the specific code and details about the underlying database where that is the case. However, this isn't really the best venue for such a discussion since this is a repository for the `firebase-functions` SDK, and those kinds of performance issues are unlikely to be related. I'd recommend reaching out to Firebase Support with details (especially if you can come up with a reproducible example of a severe performance issue).

**Comment by mellowcello77** [comment]
> @mbleigh Hi, you are right, I need to show an example to back my comment. I have removed it for now.

**Comment by manwithsteelnerves** [comment]
For those who are facing inconsistent cold start times when using firestore with cloud functions is because of the gRpc library connections.

We made a Rest client based on nodejs-firestore to keep it compatible with original version and see better performance.
Please let me know if you have any feedback. The cold starts are much better (2s) now and consistent.

Steps to install
```
1. npm install @bountyrush/firestore
2. Replace require('@google-cloud/firestore') with require('@bountyrush/firestore')
3. Have FIRESTORE_USE_REST_API = 'true' in your environment variables. (process.env.FIRESTORE_USE_REST_API should be set to 'true' for using in rest mode. If its not set, it just standard firestore with grpc connections)
```

**Comment by gOzaru** [comment]
> require('@bountyrush/firestore')
Hello @manwithsteelnerves 
Can you show us example of how to implement it with firebase-admin??
Or is there an example file there?
Thank you.

**Comment by manwithsteelnerves** [comment]
Hey! 
Thanks for trying it out!
Yea! We see a massive performance improvement too 👯 


Firestore in firebase-admin's module internally refers the [nodejs firestore](https://github.com/googleapis/nodejs-firestore) project and our implementation extends the same project. So this makes it totally compatible with all available firestore nodejs implementations.

This is how we use it in our project (firestore-imports.ts).
```
const {Firestore, setLogFunction, QuerySnapshot, DocumentSnapshot, Transaction, DocumentReference, CollectionReference, Query, FieldValue} = require('@bountyrush/firestore'); //require('@google-cloud/firestore');
export {Firestore, setLogFunction, QuerySnapshot, DocumentSnapshot, Transaction, DocumentReference, CollectionReference, Query, FieldValue};
```
As you can see, @google-cloud/firestore is commented and replaced with @bountyrush/firestore. Nothing else!
We patched internally to use REST Api's if **FIRESTORE_USE_REST_API** is true, else it fallbacks to standard gRpc implementation.

Do share us if you see any issues on github!

**Comment by gOzaru** [comment]
I am still getting an issue. 
For example when I am about to get claim token from current registered user. 
It never works at all. 
Instead, my system must register this same user as a new user over and over again. 
Is my code below already correct?
```dart 
//[Define in index.js]
const admin = require("firebase-admin");
process.env.FIRESTORE_USE_REST_API = true;
const adminConfig = JSON.parse(process.env.FIREBASE_CONFIG, process.env.FIRESTORE_USE_REST_API);
admin.initializeApp(adminConfig);
```
Should I remove FIREBASE_CONFIG too?
Or I can use both of them?
If I use both of them, I got error in checking user claim token.

**Comment by manwithsteelnerves** [comment]
Can you share me a sample of your usage?
We are currently using it in our project and don't see any issue.

Don't need to remove the firebase config as its required.

I will try to add couple of demos this weekend.

**Comment by gOzaru** [comment]
This is the condition which require to use firebase-admin: 
```node.js
const functions = require("firebase-functions");
const admin = require("firebase-admin");

exports.UserExists = functions.region("asia-southeast2").https.onCall(async (data, context) => {
  let code;
  const token = data.tokenData;
  if (context.app == undefined) {
    throw new functions.https.HttpsError(
        "failed-precondition",
        "The function must be called from an App Check verified app.");
  }
  if (!context.auth) {
    throw new functions.https.HttpsError("failed-precondition", "Unauthorized User is trying to access the App.");
  }
  try {
    return await admin.auth().verifyIdToken(token).then(async (claims) => {
      if (claims.admin === true) {
        code = 1;
      } else if (claims.family === true) {
        code = 2;
      } else if (claims.investor === true) {
        code = 3;
      } else if (claims.kindOnes === true) {
        code = 5;
      } else if (claims.goodOnes === true) {
        code = 6;
      } else {
        code = 0;
      }
      if (code != 0) {
        console.log("Succeeded checking User's claim");
        return {
          "message": "Succeeded checking User's claim",
          "statusCode": code,
        };
      } else {
        console.log("Failed checking User's claim");
        return {
          "message": "Fail checking current User",
          "statusCode": code,
        };
      }
    }).catch((error) => {
      return {
        "error": error,
        "statusCode": code,
        "message": "Error verifying User idToken",
      };
    });
  } catch (e) {
    console.log("Error decoding User token");
  }
});
```

The current user  has token claim as admin.
But whenever I used these in index.js: 
```Node.js
const admin = require("firebase-admin");
process.env.FIRESTORE_USE_REST_API = true;
const adminConfig = JSON.parse(process.env.FIREBASE_CONFIG, process.env.FIRESTORE_USE_REST_API);
admin.initializeApp(adminConfig);
```
It always fails to read the user's token when I read the log in Firebase > Cloud Functions > Logs
But when I removed the process.env.FIRESTORE_REST_API, it always works at it should be without using Firestore library from @bountyrush

**Comment by gOzaru** [comment]
This is the function to add New User: 
```Node.js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const {Firestore} = require("@bountyrush/firestore");
const firestore = new Firestore();


exports.AddUserData = functions.region("asia-southeast2").https.onCall(async (data, context) => {
  if (context.app == undefined) {
    throw new functions.https.HttpsError(
        "failed-precondition",
        "The function must be called from an App Check verified app.");
  }

  if (!context.auth) {
    throw new functions.https.HttpsError("failed-precondition", "Unauthorized User is trying to access the App.");
  }

  const musiciansNet =["peacemusic0267@gmail.com", "wgtu32@gmail.com"];
  const musiciansGross = ["mannimusic21@gmail.com", "test.revenue84@gmail.com"];
  const investors =["wg.igd30@gmail.com", "atommusicaudio@gmail.com"];
  const family =["lennygosal@gmail.com", "merygosal@gmail.com"];

  let w;
  let x;
  let y;
  let z;
  let role = "Unknown";
  let code = 0;
  let message = "Unknown yet";

  const now = new Date().now;

  const email = context.auth.token.email;
  const uid = context.auth.uid;
  const name = context.auth.token.name;
  const signIn = true;
  const registerDate = Math.floor(now/1000);
  const lastSignIn = Math.floor(now/1000);
  const device = data.device;
  const type = data.type;
  const model = data.model;
  const version = data.version;

  const adminClaim = {
    admin: true,
  };

  const familyClaim = {
    family: true,
  };

  const investorClaim = {
    investor: true,
  };

  const netClaim = {
    kindOnes: true,
  };

  const grossClaim = {
    goodOnes: true,
  };

  // Adding custom claim to current User
  if (email == "had.teams@gmail.com") {
    code = 1;
    role = "Admin";
    await admin.auth().setCustomUserClaims(uid, adminClaim).then(() => {
      message = "Success! " + email + " has been set up as Admin.";
      console.log("User is Admin");
    }).catch((error) => {
      return {
        "error": error,
      };
    });
  } else {
    for (w = 0; w < family.length; w++) {
      if (email == family[w]) {
        code = 2;
        role = "Family";
        await admin.auth().setCustomUserClaims(uid, familyClaim).then(() => {
          message = "Success! " + email + " has been set up as Family.";
          console.log("User is Family");
        }).catch((error) => {
          return {
            "error": error,
          };
        });
      }
    }
    for (x = 0; x < investors.length; x++) {
      if (email == investors[x]) {
        code = 3;
        role = "Investor";
        await admin.auth().setCustomUserClaims(uid, investorClaim).then(() => {
          message = "Success! " + email + " has been set up as Investor.";
          console.log("User is Investor");
        }).catch((error) => {
          return {
            "error": error,
          };
        });
      }
    }
    for (y = 0; y < musiciansNet.length; y++) {
      if (email == musiciansNet[y]) {
        code = 5;
        role = "Kind Musician";
        await admin.auth().setCustomUserClaims(uid, netClaim).then(() => {
          message = "Success! " + email + " has been set up as Kind Musician.";
          console.log("User is Kind Musician");
        }).catch((error) => {
          return {
            "error": error,
          };
        });
      }
    }
    for (z = 0; z < musiciansGross.length; z++) {
      if (email == musiciansGross[z]) {
        code = 6;
        role = "Good Musician";
        await admin.auth().setCustomUserClaims(uid, grossClaim).then(() => {
          message = "Success! " + email + " has been set up as Good Musician.";
          console.log("User is Good Musician");
        }).catch((error) => {
          return {
            "error": error,
          };
        });
      }
    }
  }

  // Adding current User data to Firestore
  if (code != 0) {
    const addUser = firestore.collection("Felix/Server/Users/").doc(uid);
    return await addUser.set({
      "name": name,
      "email": email,
      "uid": uid,
      "role": role,
      "startSignUp": registerDate,
      "device": device,
    }).then(async () => {
      const addActivity = firestore.collection("Felix/Server/Users/").doc(uid).collection("Activity").doc(device);
      return await addActivity.set({
        "registerDate": registerDate,
        "device": device,
        "signIn": signIn,
        "lastSignIn": lastSignIn,
      }).then(async () => {
        const addDevice = firestore.collection("Felix/Server/Users/").doc(uid).collection("Device").doc(device);
        return await addDevice.set({
          "device": device,
          "type": type,
          "model": model,
          "version": version,
          "registerDate": registerDate,
          "isPhysical": true,
        }).then(() => {
          console.log("Succeeded adding User data to Firestore");
          return {
            "status": "Success",
            "code": code,
            "message": message,
          };
        });
      });
    }).catch((error) => {
      console.log("Failed adding User data to Firestore");
      return {
        "status": "Error",
        "message": "Error adding userRecord - " + error,
      };
    });
  } else {
    console.log("Unauthorized User is trying to access the App");
    return {
      "status": "Fail",
      "code": code,
    };
  }
});

```
You need to change the email address of Admin inside the file if you want to test out. 
So the logic is: 
> Check the token
> If (token is null)
   > Call function AddNewUser.js

**Comment by manwithsteelnerves** [comment]
Ok. Lets take the discussion to the project's github as its more relavent over there. I will check with the above example and update you. I see auth and firestore doesn't have much in common but I need to test once whats breaking it. Fyi, we use both of them too.

**Comment by gOzaru** [comment]
I experienced failure in checking user's claim token too using the default ways of Firestore.
It seems the culprit was this code: 
```dart
await auth.currentUser!.getIdToken(false).then((value) async {  //I set it to false, maybe I should set it to true
   Map<String, dynamic> map = {"tokenData": value};
   try {
          await userClaim.call(map).then((response) async {
            code = response.data['statusCode'];
          });
    } on FirebaseFunctionsException catch (e) {
      log("Firebase => Error processing first Cloud Function to the Server: $e");
    }
 }); 
```

**Comment by manwithsteelnerves** [comment]
Oh! Thanks for confirming. So nothing wrong with our module then right? Can you please confirm?

**Comment by gOzaru** [comment]
You can view the log here.
Yeah, nothing wrong at the moment. 
I will let you know if I find one. 

![SS - Functions](https://user-images.githubusercontent.com/3258483/135700192-11a5bbd8-57a2-4f3a-afd1-122464f2bcb9.png)

**Comment by manwithsteelnerves** [comment]
So far how is the performance? Do you see it better?

**Comment by gamemaker1** [comment]
Thanks @manwithsteelnerves, using the `@bountyrush/firestore` package brought the response times down from 3-5 seconds to 500-600 ms.

**Comment by manwithsteelnerves** [comment]
@gamemaker1  Wow! Thanks for sharing :)
