### ISSUE TITLE
6.0.1 functions: Failed to load function definition from source

### ISSUE THREAD

**Issue by joalzamora** [firebase/firebase-functions#1618]
### [REQUIRED] Version info
upgrade from ^5.0.1 to ^6.0.1

**node:**

V10

**firebase-functions:**
^6.0.1

**firebase-tools:**

**firebase-admin:**
11.8.0

### [REQUIRED] Test case

I am trying the following example code from the documentation

https://firebase.google.com/docs/functions/http-events?hl=es-419&gen=2nd#node.js

const { onRequest } = require("firebase-functions/v2/https");

exports.sayHello = onRequest(
  { cors: [/firebase\.com$/, "flutter.com"] },
  (req, res) => {
    res.status(200).send("Hello world!");
  }
);

### [REQUIRED] Steps to reproduce

npm install --save firebase-functions@latest
firebase emulators:start --only functions

functions: Failed to load function definition from source: FirebaseError: Failed to parse build specification

npm install --save firebase-functions@5.0.1
firebase emulators:start --only functions

works perfect

### [REQUIRED] Expected behavior

works perfect

### [REQUIRED] Actual behavior
functions: Failed to load function definition from source: FirebaseError: Failed to parse build specification

**Comment by chrisfp** [comment]
Did you try to use firebase-tools v13.17.0 and firebase-admin v12.5.0? That made the problem disappear to me

**Comment by joalzamora** [comment]
It worked for me to run the command sudo npm install -g firebase-tools at the operating system level, which runs the firebase emulators:start command to update to version 13.17.0, thank you
