### ISSUE TITLE
firebase admin v13 release

### ISSUE THREAD

**Issue by Ranguna** [firebase/firebase-functions#1640]
### [REQUIRED] Version info

**node:** 20

**firebase-functions:** 6.1.0

**firebase-tools:** 13.23.0

**firebase-admin:** 13.0.0

### [REQUIRED] Test case

Use a minimal firebase project with the latest firease function and firebase admin.

### [REQUIRED] Steps to reproduce

1. Install the latest firebase admin and firease functions;
2. Try to deploy your functions.

### [REQUIRED] Expected behavior

3. The functions should deploy successfuly.

### [REQUIRED] Actual behavior

3. The functions fail to deploy with the following error:

```
Build failed with status: FAILURE and message: npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: firebase-functions@6.1.0
npm error Found: firebase-admin@13.0.0
npm error node_modules/firebase-admin
npm error   firebase-admin@"^13.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer firebase-admin@"^11.10.0 || ^12.0.0" from firebase-functions@6.1.0
npm error node_modules/firebase-functions
npm error   firebase-functions@"^6.1.0" from the root project
npm error
npm error Conflicting peer dependency: firebase-admin@12.7.0
npm error node_modules/firebase-admin
npm error   peer firebase-admin@"^11.10.0 || ^12.0.0" from firebase-functions@6.1.0
npm error   node_modules/firebase-functions
npm error     firebase-functions@"^6.1.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /www-data-home/.npm/_logs/2024-11-19T21_49_32_516Z-eresolve-report.txt
```

### Were you able to successfully deploy your functions?

No.

**Comment by theskipjack** [comment]
I'm experiencing the same issue in trying to upgrade firebase-admin and firebase-functions to their latest versions

**Comment by marco-mastella** [comment]
me too, today I updated also 
firebase-functions                 ^6.1.1  →   ^6.1.2
but the problem is still there.

**Comment by FernandoAOborges** [comment]
> me too, today I updated also firebase-functions ^6.1.1 → ^6.1.2 but the problem is still there.

Did anyone manage to solve it?
