### ISSUE TITLE
Cloud Functions - Firestore query StartAfter not accepting snapshot 

### ISSUE THREAD

**Issue by alkaest2002** [firebase/firebase-functions#169]
### Version info

**firebase-functions:**  0.7.1

**firebase-tools:** 3.17.1

**firebase-admin:** 5.4.2

### Test case

Perform a batch update of Firestore documents. Use limit and startAfter to loop through data in chunks of 500 docs.

### Steps to reproduce

```
// sessionInfo has changed, update session info of all participants currently subscribed in session
if (isShareWithChanged || true)
{
  // init var
  let offset

  // batch update function
  let batchUpdate = function(offset)
  {
    // try to read first 500 docs
    let qry = admin.firestore().collection("results")
    .where("sessionUID", "==", currentData.sessionUID)
    .limit(500)
    
    // add offset if necessary
    if (offset) qry.startAfter(offset)

    // try to read docs
    qry.get()
    // success
    .then(snapshot => 
    {
    // if there are docs
    if (snapshot.size > 0) 
    {
        // cache last doc
        offset = snapshot.docs[snapshot.docs.length-1]

        // init batch
        let batch = admin.firestore().batch()
        
        // add docs to batch update
        snapshot.docs.forEach(doc => { batch.update(doc.ref, _.pick(currentData, pickArray2)) })

        // commit batch, then go recursive
        batch.commit().then(() => { batchUpdate(offset) }) 
    }
    })
}

// perform bach update
batchUpdate()
```

### Were you able to successfully deploy your functions?

 I was able to deploy my function

### Expected behavior

perform a query with a startAfter clause passing a snapshot

### Actual behavior

Error: Too many cursor values specified. The specified values must match the orderBy() constraints of the query.
    at Query._buildPosition (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/reference.js:1240:13)
    at Query.startAfter (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/reference.js:1329:28)
    at batchUpdate (/user_code/c/fs/onWriteSession.f.js:63:27)
    at batch.commit.then (/user_code/c/fs/onWriteSession.f.js:83:43)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

# solution I found so far

use an orderBy clause with a specific field, then use the startAfter clause with the same field

```
// if sessionInfo has changed, update session info of all participants currently subscribed in session
if (isShareWithChanged || true)
{
  // init var
  let offset

  // batch update function
  let batchUpdate = function(offset)
  {
    // try to read first 500 docs
    let qry = admin.firestore().collection("results")
    .orderBy("participantUID")
    .where("sessionUID", "==", currentData.sessionUID)
    .limit(500)
    
    // add offset if necessary
    if (offset) qry.startAfter(offset.get("participantUID"))

    // try to read docs
    qry.get()
    // success
    .then(snapshot => 
    {
    // if there are docs
    if (snapshot.size > 0) 
    {
        // cache last doc
        offset = snapshot.docs[snapshot.docs.length-1]

        // init batch
        let batch = admin.firestore().batch()
        
        // add docs to batch update
        snapshot.docs.forEach(doc => { batch.update(doc.ref, _.pick(currentData, pickArray2)) })

        // commit batch, then go recursive
        batch.commit().then(() => { batchUpdate(offset) }) 
    }
    })
}

// perform bach update
batchUpdate()

```

**Comment by laurenzlong** [comment]
Closing since you're not using the latest SDK, which also depends on firebase-admin 5.8.1. Please open another issue if you still experience this after updating.

**Comment by phingers** [comment]
And if my loop in the example above had more than 500, can I just write them as separate batches in the function? Or how do I push 2500 updates into the system?
