### ISSUE TITLE
Stale onWrite's event.data.val() children

### ISSUE THREAD

**Issue by shauntrennery** [firebase/firebase-functions#17]
When subscribing to a path's onWrite event, children of event.data.val() contain stale data.
e.g. if a path is updated with a new "tag" object i.e. {tag1: true, tag2: true}, event.data.val() contains the previous version of tags. i.e. {tag1: true}

**Comment by katowulf** [comment]
Hello Shaun, thanks for sharing this. Can you please add a minimal repro, sample data, and steps to reproduce this?

**Comment by laurenzlong** [comment]
Hey @shauntrennery , you might also be listening to the wrong database ref. Moreover, the onWrite event also fires for delete events, so if you've been deleting the database item in between rounds of testing, then the function would fire as well. Like Kato said, it would be helpful if you can share more detailed repro instructions.

**Comment by shauntrennery** [comment]
Hi @laurenzlong, @katowulf 

Many thanks for the prompt reply. I've triple checked the database ref and have confirmed there are no other events triggered. I'm working on replicating the problem within a demo repro. I'll update this with links, steps and sample data ASAP.

**Comment by laurenzlong** [comment]
@shauntrennery I'm going to close this issue for now, please re-open when you have a repro. Thanks!
