### ISSUE TITLE
Cannot decode type from Firestore Value: {"stringValue":""}

### ISSUE THREAD

**Issue by sahil311289** [firebase/firebase-functions#170]
I just updated the cloud functions to 0.8.1 and my code stopped running. There is another case listed under the same issue but was fixed in December 2017.

firebase-functions: 0.8.1
firebase-admin: 5.4.2

All (3) of my cloud functions have stopped working without any code change in 2 of them.

Console log:
Error: Cannot decode type from Firestore Value: {"stringValue":""}     at DocumentSnapshot._decodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:464:15)     at DocumentSnapshot.data (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:322:26)     at exports.updatePopularity.functions.firestore.document.onUpdate.event (/user_code/index.js:9:33)     at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:59:27)     at next (native)     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71     at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)     at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)     at /var/tmp/worker/worker.js:695:26     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Another one:

Error: Cannot decode type from Firestore Value: {"stringValue":""}     at DocumentSnapshot._decodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:464:15)     at DocumentSnapshot.data (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:322:26)     at exports.sendPush.functions.firestore.document.onUpdate.event (/user_code/index.js:33:33)     at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:59:27)     at next (native)     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71     at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)     at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)     at /var/tmp/worker/worker.js:695:26     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
--

Please suggest what's going on.

**Comment by laurenzlong** [comment]
firebase-functions 0.8.1 actually requires firebase-admin 5.8.1, could you try updating your package.json and then running "npm install"?

**Comment by sahil311289** [comment]
Thank you so much!
This was a life saver.

**Comment by laurenzlong** [comment]
No problem!
