### ISSUE TITLE
Getting Error 'Failed to retrieve function source code'

### ISSUE THREAD

**Issue by lewisjamesblack** [firebase/firebase-functions#175]
I get the error: "Failed to retrieve function source code" when I try and deploy a function.

![firebasebug](https://user-images.githubusercontent.com/17566103/35451455-9980b9ea-02c3-11e8-88da-5016f7ca5a7e.png)

This is all from the command line. I am using node 6.11.5 (but in the firebase-admin package.json file in the nodes folder it is says node 6.9.1 is used to download that). I am using firebase-admin@5.8.1 and firebase-functions@0.8.1.

This is the code in my index.js file that I am trying to deploy:

      const functions = require('firebase-functions');  
      exports.helloWorld = functions.https.onRequest((request, response) => {  
             response.send("Hello from Firebase!");  
      });
I have also tried to deploy many different things.

Two interesting things: 

- I used to be able to deploy any function without problem. This changed about a month ago and now every function I try gets this error. I can't remember making any change that would be related to this.

 - Also I can deploy functions from my computer (with the exact same set up and firebase versions) to other projects in the same google account and different google accounts without any problem.

Thanks

**Comment by pratiknikam** [comment]
Even I had kind of similar issue where it was failing to deploy.

`Error: Functions did not deploy properly.`.

But when I did git clone in new directory and tried to deploy from there, it worked.

**Comment by lewisjamesblack** [comment]
Hey Pratik, cheers for your answer. I have been downloading the firebase tools by doing the command 'npm install -g firebase-tools'. I'm not sure how cloning this directory would help me?

**Comment by laurenzlong** [comment]
@lewisjamesblack This seems to be a project specific issue, can you file a support ticket so we can look into it? https://firebase.google.com/support/

**Comment by lewisjamesblack** [comment]
Hey Lauren, I made a support ticket on Friday but it hasn't been resolved yet. I'm unable to send my users notifications on the app which is quite a pressing issue so i'm looking for any help I can get. Thanks allot

**Comment by rashiidmv** [comment]
is this resolved?
