### ISSUE TITLE
Default exports don't work

### ISSUE THREAD

**Issue by DominicTobias** [firebase/firebase-functions#177]
Hi,

When exporting a default from a local module e.g.

```js
exports = function blah() {}
```

And then importing it in index.js:

```js
const blah = require('./blah');
```

Gives a Type error 'blah' is not a function in the firebase logs when trying to use it in a hook. Changing the export to `exports.blah = function..` and importing that as a non-default function works. This was a pretty perplexing issue as I'd have expected exports to work in the same way as they always do in a Node project.

**Comment by laurenzlong** [comment]
The issue isn't with the local module, it's with index.js. Index.js always needs to export all of the functions. So your example will work if you changed index.js to 
```
exports.blah = require('./blah');
```
