### ISSUE TITLE
"credential" property has insufficient permission

### ISSUE THREAD

**Issue by pdmshrestha** [firebase/firebase-functions#178]
Hi,

If I initialise the admin app with following line. It works perfectly on firebase cloud but not locally.

```admin.initializeApp(functions.config().firebase);```

I get following error when I try to serve functions locally.
```
error: (node:22143) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Credential implementation provided to initializeApp() via the "credential" property has insufficient permission to access the requested resource. See https://firebase.google.com/docs/admin/setup for details on how to authenticate this SDK with appropriate permissions.
error: (node:22143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But I do not have any problem when initialising the app with following code.
```
const serviceAccount = require("./serviceAccountKey.json");
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});
```

**Comment by laurenzlong** [comment]
Local emulation only supports database and Firestore at the moment. If you're trying to access something else and it doesn't work, please file issue in https://github.com/firebase/firebase-tools/issues
