### ISSUE TITLE
Credential implementation provided to initializeApp() : ECONNRESET

### ISSUE THREAD

**Issue by esprehn** [firebase/firebase-functions#182]
### Version info

**firebase-functions:**
0.7.2

**firebase:**
4.6.1

**firebase-admin:**
5.4.3

Our cloud functions seem to sometimes error out like this:
```
FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"read ECONNRESET\"."} |  
-- | --

```

We do have code like this:
```js
const app = admin.initializeApp(functions.config().firebase);
```

But it's not clear how that is related.

### Were you able to successfully deploy your functions?

Yes, it's not clear how this failure impacts us. It's possible our functions are sometimes failing?

**Comment by laurenzlong** [comment]
Please file a support ticket: firebase.google.com/support
