### ISSUE TITLE
Authentication bug when trying to send Firebase Cloud Message

### ISSUE THREAD

**Issue by dauledk** [firebase/firebase-functions#183]
### Version info

**firebase-functions:**
0.8.1
**firebase-tools:**
5.8.1
**firebase-admin:**
3.17.4
### Test case

When trying to send FCM notification, I get unauthorized error.

### Steps to reproduce

1. clone this repo: https://github.com/dauledk/fcm-functions-bug.git
2. change pointer to test firebase repo
3. cd functions && npm i 
4. obtain a registrationToken
5. npm run -s build && npm run -s serve
6. send request: `curl -X GET \
  'http://localhost:5000/eddystone-dev-e4351/us-central1/helloWorld?token=<token-of-reciever-of-notification>' \`

### Expected behavior
The message will be sent to reciever (token holder).

### Actual behavior
An error occurred when trying to authenticate to the FCM servers. Make sure the credential used to authenticate this SDK has the proper permissions. See https://firebase.google.com/docs/admin/setup for setup instructions. Raw server response: "

```
<HTML>
    <HEAD>
        <TITLE>Unauthorized</TITLE>
    </HEAD>
    <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
        <H1>Unauthorized</H1>
        <H2>Error 401</H2>
    </BODY>
</HTML>
". Status code: 401.
```

### Things done to solve the problem
[Since I had issues with authentication before](https://github.com/firebase/firebase-functions/issues/135), I tried authentication with json-key-file: 

    const serviceAccount = require(`${__dirname}/../<path-to-key-file>.json`);
    admin.initializeApp({credential: admin.credential.cert(serviceAccount)});

**It actually works.** Since this is not a good way of authenticating (according to the last issue), I tried running this command `export GOOGLE_APPLICATION_CREDENTIALS='./<path-to-file>.json'` as recommended by @laurenzlong  adn @inlined in the last issue. This does however not solve the problem, I get same error. (I added a npm-scripts command in the functions directory called "bug" where you can see the command).

So now I am lost with authentication once again - hope that you can help me. Please ask for any additional information as needed.

**Comment by laurenzlong** [comment]
The suggestion for running `export GOOGLE_APPLICATION_CREDENTIALS='./<path-to-file>.json` only applies if you have the following code:

```
admin.initializeApp(functions.config().firebase);
```

**Comment by dauledk** [comment]
I know. 

Thats why in the repo I have both to test both. Plase note that the following combination:

```javascript
    admin.initializeApp(functions.config().firebase);
```

```javascript
export GOOGLE_APPLICATION_CREDENTIALS='./<path-to-file>.json
````
**does not work** when using FCM (hence the repo).

**Comment by laurenzlong** [comment]
Which json file are you pointing to? Where did you download the key file, which service account is it tied to?

**Comment by dauledk** [comment]
In the firebase console: https://console.cloud.google.com/iam-admin/serviceaccounts

![screen shot 2018-02-08 at 19 45 37](https://user-images.githubusercontent.com/9967422/35991819-b4bf4fd8-0d08-11e8-990c-0ac33d2c5b13.png)

**Comment by laurenzlong** [comment]
You'll want to download the key from the App Engine app default service account, not the other one that you created.

**Comment by dauledk** [comment]
So I tried exporting the other key - but no success. I then tried to debug the env, to make sure the variable was set. Running `printenv GOOGLE_APPLICATION_CREDENTIALS` was the magic command showing the real error: the env variable was not set!

I was trying to set this variable with a package.json script, but this did not seem to work?
```javascript
"key:dev": "export GOOGLE_APPLICATION_CREDENTIALS='./name-of-key.json'",
```
After runing this with npm `npm run -s key:dev`, testing with `printenv GOOGLE_APPLICATION_CREDENTIALS` showed that the variable was not set.

So for now the solution is to run the command (`export GOOGLE_APPLICATION_CREDENTIALS='./name-of-key.json'`) in the terminal and not through npm.

**Comment by laurenzlong** [comment]
Sorry, this is a package.json / Node usage question, not a Firebase question. My suggestion was to run it within the terminal.

**Comment by ajayAloha** [comment]
> So I tried exporting the other key - but no success. I then tried to debug the env, to make sure the variable was set. Running `printenv GOOGLE_APPLICATION_CREDENTIALS` was the magic command showing the real error: the env variable was not set!
> 
> I was trying to set this variable with a package.json script, but this did not seem to work?
> 
> ```js
> "key:dev": "export GOOGLE_APPLICATION_CREDENTIALS='./name-of-key.json'",
> ```
> 
> After runing this with npm `npm run -s key:dev`, testing with `printenv GOOGLE_APPLICATION_CREDENTIALS` showed that the variable was not set.
> 
> So for now the solution is to run the command (`export GOOGLE_APPLICATION_CREDENTIALS='./name-of-key.json'`) in the terminal and not through npm.
> 
> Do you now if it is possible to do this in with npm?

https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json

**Comment by BinniZenobioCordovaLeandro** [comment]
Activate `Cloud Messaging API` worked to me:

![image](https://github.com/firebase/firebase-functions/assets/42467277/bba7a773-444b-41b0-8604-5f7ef6a7951c)

![image](https://github.com/firebase/firebase-functions/assets/42467277/c997dd81-7c7d-4acf-a7d9-4fdada1e43d1)

![image](https://github.com/firebase/firebase-functions/assets/42467277/1ce38ede-5cba-41d4-ae54-3686e7f7ec81)

![image](https://github.com/firebase/firebase-functions/assets/42467277/a6e37fed-12bc-4332-867f-c60d8b91dd56)

![image](https://github.com/firebase/firebase-functions/assets/42467277/a0c3b4ef-5755-4856-beab-978cbc0e9f66)


Thanks to [ADEKOLA Abdwahab](https://dev.to/codarbind)
Credits to:
https://dev.to/codarbind/an-error-occurred-when-trying-to-authenticate-to-the-fcm-servers-2g3
