### ISSUE TITLE
Error while deploying functions: The default Firebase app already exists

### ISSUE THREAD

**Issue by andrekosak** [firebase/firebase-functions#184]
### Version info

**firebase-functions:** 0.8.1

**firebase-admin:** 5.8.2

### Steps to reproduce

I want to deploy two http-functions, that would use Admin SDK to communicate with Firestore Database. BUT. I want both functions to be in 2 separate files. So here is the content of my functions/src folder:

```
index.ts
function1.ts
function2.ts
```

content of **index.ts**:

```typescript
import { f1 } from './function1.ts';
import { f2 } from './function2.ts';

export const function1 = f1();
export const function2 = f1();
```

both **function1.ts** and **function2.ts** are using Admin SDK and using statement `admin.initializeApp(functions.config().firebase);` to init the app.

When i try to deploy my functions i get the error message: **Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once.**

### Were you able to successfully deploy your functions?

Yes, but only when i use `admin.initializeApp(functions.config().firebase);` only once. As workaround i do init of my app in **index.ts** and pass the firebase instance to my functions like that:

index.ts:
```typescript
(imports hidden)

admin.initializeApp(functions.config().firebase);
const fs = admin.firestore();

export const function1 = f1(fs);
export const function2 = f1(fs);
```

but it smells not quite well, isn't it?

### Question

So, the question actually is, if there is a proper way to split the **index.ts** to multiple files and be able to use Admin SDK in those files without passing the firestore instance to all functions.

**Comment by laurenzlong** [comment]
You can do this by giving each app its own name during initialization: https://firebase.google.com/docs/reference/admin/node/admin#.initializeApp

**Comment by voidstarfire** [comment]
I have the exact same problem, do I really need to initializeApp for every cloud function?

**Comment by laurenzlong** [comment]
@voidstarfire If you don't want to initialize an app for each function, initialize one in a helper module, then import it into the files for each function. @andrekosak explicitly said he doesn't want to use the same instance in all his functions, that's why I suggested giving each app its own name.

**Comment by voidstarfire** [comment]
Yes my bad my TSC was doing some weird caching thing that wasn't updating my JS Lib. Thanks for the reply.

**Comment by kathiravan1797** [comment]
[https://stackoverflow.com/questions/41630485/how-to-properly-exit-firebase-admin-nodejs-script-when-all-transaction-is-comple](url)
 this solves the issue for me
