### ISSUE TITLE
Cloud Function onCreate() trigger for Firestore not always guaranteed to receive new data.

### ISSUE THREAD

**Issue by majid701** [firebase/firebase-functions#185]
### Version info

**firebase-functions:** 0.8.1

**firebase-tools:** 3.17.4

**firebase-admin:** 5.8.2

### Test case

I have noticed that sometimes the event that is passed as the argument for the **onCreate()** (for cloud Firestore database) method does not contain the data that was written (and caused the trigger), instead it's an empty object. This only happens sometimes and it doesn't seem to happen for the same data every time. It seems that the triggered method sometimes reads before the object write operation has completed successfully.

### Steps to reproduce

Add **onCreate()** trigger to a function for a Firestore collection which triggers many times consecutively.

### Were you able to successfully deploy your functions?

Functions get deployed successfully. No errors.

### Expected behavior

Expected to receive the new data when calling `event.data.data()`.

### Actual behavior

Calling `event.data.data()` sometimes returns empty object.

EDIT:
It can be seen in the screenshot below that sometimes the data is received and sometimes we get an empty object. I'm just console logging the `event.data.data()` whenever the function is triggered.

![screen shot 2018-02-13 at 15 26 55](https://user-images.githubusercontent.com/15844600/36154678-7fdb047e-10d2-11e8-9454-7bb106380c44.png)

**Comment by laurenzlong** [comment]
Please file a support ticket: firebase.google.com/support

**Comment by majid701** [comment]
@laurenzlong I have already done that before creating the issue.

**Comment by laurenzlong** [comment]
Ok great, please indicate that next time. Also this Github repo is for SDK issues, so filing an issue here doesn't help.

**Comment by majid701** [comment]
@laurenzlong I'm sorry if I have made an issue at the wrong place but I felt like it was an issue with cloud functions SDK.

**Comment by laurenzlong** [comment]
No worries!
