### ISSUE TITLE
Rewrite rules in firebase hosting and functions

### ISSUE THREAD

**Issue by kongdigital** [firebase/firebase-functions#191]
Create minimal express app

```
const app = express()
app.get("/helloworld", (req, res) => res.status(200).send("hello world");
module.exports = {
  app: functions.https.onRequest(app)
}
```
When running locally and deployed to cloud functions everything works as expected. For example:
```
https://<project-id>.cloudfunctions.net/app/helloworld
```
Returns "hello world" as expected. However when using firebase hosting to rewrite the url it breaks. For example with the rewrite as follows: 
```
rewrites: [{ source: "**/app/**", function: "app"}]
```
Visiting the domain with:
```
https://example.com/app/helloworld
```

Running under cloud functions this is not a problem because the url sent to epxress is `/helloworld` however when using rewrites the url sent to express is `/app/helloworld`

I have a workaround but is this the expected behaviour?

**Comment by laurenzlong** [comment]
Can you file this in https://github.com/Firebase/firebase-tools

**Comment by mbleigh** [comment]
This is expected behavior. When rewriting from Hosting, the entire URL path is sent to the Cloud Function. This is intended, since there's no way for us to know what parts of the path you'd want to "keep" so we send the whole thing. You should build routing into your Node.js code.

**Comment by johnnyoshika** [comment]
Interesting behavior. @edkongz thanks for documenting this. It was very helpful.
