### ISSUE TITLE
error:  Error: Unsupported archive url: file://C:\Users\...\AppData\Local\Temp\undefined-helloWorld-10464zjuO4ZCMiL4k.zip

### ISSUE THREAD

**Issue by Arpanx** [firebase/firebase-functions#194]
### Version info
    "firebase-admin": "~5.9.0",
    "firebase-functions": "^0.8.1"

### Steps to reproduce
**firebase init**
"only function checked"
try
**firebase experimental:functions:shell**
OR 
 **firebase serve --only functions**
get
 functions: Error from emulator. [object Object]

try
 **functions log read**
get
2018-02-27T14:25:21.702Z - error:  Error: Unsupported archive url: file://C:\Users\Arpanx\AppData\Local\Temp\undefined-helloWorld-10464zjuO4ZCMiL4k.zip

Windows10
firebase --version  3.17.4
node --version   6.11.5

P.S.
Your source sample from ReadMe.md works as it should. So my question can be deleted, sorry.

**Comment by laurenzlong** [comment]
Closing this since we don't actually support using "firebase" commands and "functions" commands at the same time.
