### ISSUE TITLE
Error from emulator. Error occurred while parsing your function triggers

### ISSUE THREAD

**Issue by chimirala** [firebase/firebase-functions#197]
Hi,

I am trying to run a function to write data into Firestore using nodejs but I keep getting multiple errors. I have just installed firebase and ran the function. Still it says '**npm i --save firebase-functions@latest**'

Here is the code I am trying to execute:

const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp(functions.config().firebase);
var db = admin.firestore();

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
 var docRef = db.collection('users').doc('alovelace');

    var setAda = docRef.set({
        first: 'Ada',
        last: 'Lovelace',
        born: 1815});
});

And my package.json file:

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "^5.10.0",
    "firebase-functions": "^0.8.1"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0"
  },
  "private": true
}

**Comment by laurenzlong** [comment]
firebase-tools v3.17.6 was just released, should have fixed the issue.

Run "npm i -g firebase-tools"
