### ISSUE TITLE
Can't Run 'npm update' - Fails With 'firebase-admin' Dependency Error

### ISSUE THREAD

**Issue by samcaplat** [firebase/firebase-functions#203]
### Version info

**firebase-functions:** ^0.8.1

**firebase-admin:** ^5.8.2

### Expected behavior

Run ```npm update``` to update all dependencies.

### Actual behavior

Update fails with dependency error:

```
npm WARN firebase-functions@0.8.2 requires a peer of firebase-admin@~5.10.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!    (user path omitted)
```

Firebase packages are installed globally, and in the project using --save.

When running ```npm update --save firebase-admin```, the following error occurs:

```
$ npm update --save firebase-admin
npm WARN firebase-functions@0.8.1 requires a peer of firebase-admin@~5.8.1 but none is installed. You must install peer dependencies yourself.

npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!      (user path omitted)
```

**Comment by laurenzlong** [comment]
Your first update of firebase-functions didn't work, since the second error message still refers to 0.8.1. As well, since the firebase-admin is a peer dependency of firebase-admin, and the latest firebase-functions does not always depend on the latest of firebase-admin, `npm update` is not the workflow I would recommend. Try:

``` 
npm update --save firebase-functions
npm install --save firebase-admin@5.10.0

**Comment by samcaplat** [comment]
Hi Lauren,

Thanks for the super fast response, I'm not an expert at this, so I appreciate your help. Following your recommended steps, the first update finishes successfully, but unfortunately the firebase-admin update still fails with:

```
npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2018-03-18T14_31_57_510Z-debug.log
```

Here's the full log of the run:

```
3359 verbose stack Error: EINVAL: invalid argument, read
3359 verbose stack     at C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\gentle-fs\lib\rm.js:245:7
3359 verbose stack     at C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
3359 verbose stack     at C:\Users\Sam\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
3359 verbose stack     at FSReqWrap.oncomplete (fs.js:171:5)
3360 verbose cwd F:\Firebase\Functions\CloudFunctions\functions
3361 verbose Windows_NT 10.0.16299
3362 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sam\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "firebase-admin@5.10.0"
3363 verbose node v9.7.1
3364 verbose npm  v5.7.1
3365 error code EINVAL
3366 error EINVAL: invalid argument, read
3367 verbose exit [ 1, true ]
```

**Comment by samcaplat** [comment]
Hi Lauren,

Apologies for the second update, the issue seems to be a known bug in NPM 5. Downgrading to NPM 4 with ```npm install -g npm@4``` fixes the issue.

Thanks,
Sam

**Comment by laurenzlong** [comment]
Glad you figured it out!
