### ISSUE TITLE
Add timeout option for firebase experimental:functions:shell

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-functions#208]
By default, functions that are run locally with `firebase experimental:functions:shell` timeout if they take more than 60 seconds to execute. It seems there is no option to configure this timeout. It would be really convenient to add an option or to document how to change the timeout value if this is already possible.

**Comment by laurenzlong** [comment]
Please update to the latest firebase-tools, timeout has been set to 9 minutes.
