### ISSUE TITLE
Invalid type for UserRecord passed to cloud function

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-functions#209]
The code ([`src/providers/auth.ts`](https://github.com/firebase/firebase-functions/blob/master/src/providers/auth.ts#L114)) and [the documentation](https://firebase.google.com/docs/reference/functions/functions.auth.UserRecord) specify that the `data` passed to `user().onCreate` and `user().onDelete` are `UserRecord` from `firebase-admin`.

But when logging the `data` argument:

<img width="637" alt="screen shot 2018-03-23 at 15 08 32" src="https://user-images.githubusercontent.com/845425/37834006-1be5546c-2ead-11e8-8c5c-7cc5c4e6716e.png">

For examples, `providerData` should be defined (at least an empty array), and other properties should be empty string ([`firebase/firebase-admin-node/src/auth/user-record.ts`](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/user-record.ts#L138)).

Or otherwise it should not be documented as an `UserRecord`.

**Comment by laurenzlong** [comment]
fixed in firebase-functions v1.0.0
