### ISSUE TITLE
Function killed. Error: system encountered unexpected error

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-functions#21]
### Version info

firebase-functions: 0.5.2
firebase-tools: 3.5.0
firebase-admin: 4.1.3

### Test case

I'm triggering firebase functions at 10 minute intervals with node-schedule

One of my functions encountered an unexpected error:
Function killed. Error: system encountered unexpected error
<img width="950" alt="screen shot 2017-03-23 at 10 17 11" src="https://cloud.githubusercontent.com/assets/2920947/24243891/9fd8b2f0-0fb4-11e7-8e47-f9ecbb0238f8.png">

-I'm running this function on a schedule at 10 minute intervals.
-It ran for over 17 hours before failing last night.
-The function itself uses admin messaging to send a message
-However, I console log as soon as the function is triggered, whereas the screenshot attached shows that the function never even reached my console log
-I also have this same function running identically on another project at the exact same time interval, which is still currently running without fail.

### Steps to reproduce
Unsure how to reproduce.

### Were you able to successfully deploy your functions?
Yes

### Expected behavior
Is there anyway to catch or recover from an error like this?

### Actual behavior
Function failed to run and went offline after that. (It seemed to not even hit my code as the first thing I do is console.log() a start message)

**Comment by ahaverty** [comment]
It's actually worse than I thought. The function has totally stopped working since the error. It's not responding to anything. See screenshots of metrics and logs. I'm going to redeploy to see if it relaunches.

<img width="1653" alt="screen shot 2017-03-23 at 11 27 40" src="https://cloud.githubusercontent.com/assets/2920947/24245821/6095c4e0-0fbc-11e7-987a-de61a56a4583.png">
<img width="1643" alt="screen shot 2017-03-23 at 11 27 47" src="https://cloud.githubusercontent.com/assets/2920947/24245832/6831ed50-0fbc-11e7-871c-74e35a28a715.png">
<img width="1367" alt="screen shot 2017-03-23 at 11 25 15" src="https://cloud.githubusercontent.com/assets/2920947/24245838/6c1c4b54-0fbc-11e7-83a0-ed0ba1bd4dc9.png">
<img width="558" alt="screen shot 2017-03-23 at 11 27 56" src="https://cloud.githubusercontent.com/assets/2920947/24245849/734e31da-0fbc-11e7-9e19-cd193f79a34e.png">

**Comment by ahaverty** [comment]
Confirming that a redeploy brought the function back online ☑️

**Comment by laurenzlong** [comment]
Thanks for the detailed report @ahaverty . Can you fill out [a support ticket](https://firebase.google.com/support/contact/bugs-features/)? This will allow you to give us your project ID privately, so we can look up logs for it. In the ticket, you can link to this issue, mention that you've already been talking to Lauren Long so it can be routed to me. I'm going to close this issue here, since it's not an SDK bug, but a bug within the runtime environment.

**Comment by ahaverty** [comment]
Thanks @laurenzlong , bug report created 👌

**Comment by morninng** [comment]
same situation happen to me

**Comment by alexsanderkhitev** [comment]
I faced the same situation

**Comment by poi5305** [comment]
2021/7/7 still happened
SYSTEM_ERROR: system encountered unexpected error. Function invocation was interrupted.
