### ISSUE TITLE
Unmet peer dependency firebase-admin@5.11.0 invalid with firebase-functions@0.9.1

### ISSUE THREAD

**Issue by pyrliu** [firebase/firebase-functions#210]
### Version info

**firebase-functions:** 0.9.1

**firebase-tools:** 3.17.7

**firebase-admin:** 5.5.0

### Test case

```
cd functions/
npm install firebase-admin@latest firebase-functions@latest --save

functions@ /path/to/project/functions
├── UNMET PEER DEPENDENCY firebase-admin@5.11.0 invalid
└── firebase-functions@0.9.1  invalid

npm WARN firebase-functions@0.9.1 requires a peer of firebase-admin@~5.10.0 but none was installed.
```

### Steps to reproduce

At the moment, just run the above code

### Were you able to successfully deploy your functions?

Yes. I had problems deploying, thats why I updated according to guides. So everything works, just a look-and-feel issue of firebase-functions package.json dependency.

**Comment by Bengejd** [comment]
I am running into issues with Firebase functions right now, and this seems to be one of the problems I am facing.

**Comment by laurenzlong** [comment]
It means you don't have the updated firebase-admin version. The error message indicates that you need 5.10.0. To fix, run the following in the functions directory:
```
npm i --save firebase-admin@5.10.0
```

If you are using the newest firebase-functions (v1.0.0), then you would need firebase-admin 5.11.0. In that case, run:
```
npm i --save firebase-admin@5.11.0
```

**Comment by Bengejd** [comment]
Yeah, I realized that when Firebase Functions 1.0 was released. At the time of my comment, it hadn't yet though. Thank you.
