### ISSUE TITLE
Failed to minify cloud-functions

### ISSUE THREAD

**Issue by qnordic** [firebase/firebase-functions#211]
### Version info
firebase-functions: 0.9.1
firebase-tools: 3.17.7
firebase-admin: 5.10.0

### Test case

npm install --save firebase-tools firebase-admin
npm run build

### Steps to reproduce

Not sure what it takes specifically to reproduce but:
npx create-react-app my-app
<run necessary steps to step up firebase-functions>
npm run build

### Were you able to successfully deploy your functions?

functions were able to be deployed but are currently blocking my build

### Expected behavior

npm run build should produce a production ready build

### Actual behavior

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/firebase-functions/lib/cloud-functions.js:38 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! techterra-product-validator@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the techterra-product-validator@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrisqueitzsch/.npm/_logs/2018-03-26T02_44_44_464Z-debug.log

**Comment by qnordic** [comment]
This came up as user error as far as I can tell.

**Comment by gregypooh** [comment]
I'm getting this error as well. How did you go about resolving this issue?

**Comment by qnordic** [comment]
So... honestly I figured out I didn't actually need the functions. That said I never got around the error but a few friends tried my repo steps and got the error so I'm rather unclear as to what is going on. I've got a feeling in my case it had to do with improperly using import statements, I still categorize myself as n00b status when it comes to Node/React so there are mistakes I make on a semi-regular basis.

**Comment by gregypooh** [comment]
So, as expected, it was my fault haha… I’ve been trying to figure out how to use firebase-functions, and apparently you aren’t allowed to use the firebase-functions package within your React application.

Said differently, `firebase-functions` is strictly used to _create_ server functions that will run on `firebase`. There’s no reason to have the `firebase-functions` package installed in your React app.

So, I simply removed `firebase-functions`, and it deployed just fine!
