### ISSUE TITLE
Firebase function not triggered on next calendar day for Realtime DB write

### ISSUE THREAD

**Issue by afficionaddo** [firebase/firebase-functions#212]
### Test case

I have a function that triggers on RealTime- Db write.
The path I use to check for write consists of a 'date-variable' which is declared inside firebase function script in index.js:
var todayDate=new Date()
.....('reports'+todayDate+'/${key}')....

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

The function should get triggered every time any write/update is performed at the above mentioned path & send email.

### Actual behavior
If i have deployed the function today, then it will work perfectly for the current calendar day BUT on the next calendar day it does not get triggered. I have to re-deploy & then it works perfectly.

Is it the date-variable that is causing the problem?

**Comment by laurenzlong** [comment]
Please file a support ticket for server side issues: firebase.google.com/support
