### ISSUE TITLE
Migration Documentation Inconsistency with auth.user().onCreate

### ISSUE THREAD

**Issue by johnozbay** [firebase/firebase-functions#217]
In the V1.0 Migration Documentation, 

Under [Authentication](https://firebase.google.com/docs/functions/beta-v1-diff#authentication) `auth.user().onCreate` is documented to be returning `userMetadata`.

```
exports.authAction = functions.auth.user().onCreate((userMetadata, context) => {
  const creationTime = userMetadata.creationTime; // 2016-12-15T19:37:37.059Z
  const lastSignInTime = userMetadata.lastSignInTime; // 2018-01-03T16:23:12.051Z
}
```

Whereas under [functions.auth.UserBuilder](https://firebase.google.com/docs/reference/functions/functions.auth.UserBuilder) same thing is documented to be returning a [functions.auth.UserRecord](https://firebase.google.com/docs/reference/functions/functions.auth.UserRecord) which has `metadata` in it. 

I'm assuming migration docs are wrong, in that it should return the `userRecord` as per
https://github.com/firebase/firebase-functions/blob/0a0aea9fca234b12e182f4971fc6e4621bc4bff2/src/providers/auth.ts#L65

and 

https://github.com/firebase/firebase-functions/blob/0a0aea9fca234b12e182f4971fc6e4621bc4bff2/src/providers/auth.ts#L70

Also could be related to #209

**Comment by TarikHuber** [comment]
Have the same issue. 

**fiebase-functions** version **1.0.0**

Used the `onCreate` and `onDelete` auth event to calculate statistics for provider related registrations and account deletions. For this we need the `providerData` as it is in a `UserRecord`.

There is a workaround in the `onCreate` to get the `UserRecord` with just using the `admin.auth().getUser(userUid)` but we can't do that with the `onDelete` event. Here is our workaround with the `onCreate`: https://github.com/TarikHuber/react-most-wanted/blob/master/functions/auth/onCreate.f.js

Are there plans to fix this?

There are some provider data in the events `userMetadata` but not as they are in a `UserRecord`. The `password` provider data is missing but `google.com` is not. It would be great to have here the same data structure as it is in a `UserRecord`.

In the eralier versions we had the same `providerData` in the `event.data` as it was in the `UserRecord`. Example: https://github.com/TarikHuber/react-most-wanted/blob/843751d72e5791a413707a3b87786219ad1657ef/functions/auth/onCreate.f.js

**Comment by ahaverty** [comment]
I'm getting the following in typescript:
```typescript
functions.auth.user().onCreate(async (userRecord, context) => {});
```

**Comment by laurenzlong** [comment]
@johnozbay Thanks for filing! You're right, it's the documentation that's wrong. I'm working to fix it. It is a UserRecord. 

@TarikHuber In firebase-functions v1.0.0, the first parameter to both onCreate and onDelete should be a UserRecord (#209 was fixed). So you should not have to do your workaround `admin.auth().getUser(userUid)` anymore.

Could you elaborate on your statement "In the earlier versions we had the same providerData in the event.data as it was in the UserRecord. ". You mean in pre v1.0.0 firebase-functions, the providerData looked different than it does in v1.0.0? And how exactly does it look different?

**Comment by TarikHuber** [comment]
Hi @laurenzlong,

I should show more code and talk less 😆 

**Example** with version **0.9.1** using the old `event`. (Seems this changed earlier and I did not notice so no providerData to compare it with the new version)

```js
// log of (event.data)
{ email: 'test8@test.com',
  metadata: 
   UserRecordMetadata {
     creationTime: '2018-04-06T06:36:21Z',
     lastSignInTime: '2018-04-06T06:36:21Z' },
  uid: 'Ig9PHMgbpOS0OtomvzOgepKcNdo1' }
```

**Example** with version **1.0.0** using the new `(userRecord, context)` and registering with a **email**. Here we can see the difference between the `(userRecord, context)` from the function event and the `userRecord` from the `admin.auth().getUser(...)`:

```js
//log of the userRecord from (userRecord, context)

{ email: 'test8@test.com',
  emailVerified: false,
  displayName: null,
  photoURL: null,
  phoneNumber: null,
  disabled: false,
  providerData: [],
  customClaims: {},
  passwordSalt: null,
  passwordHash: null,
  tokensValidAfterTime: null,
  metadata: 
   UserRecordMetadata {
     creationTime: '2018-04-06T06:48:42Z',
     lastSignInTime: '2018-04-06T06:48:42Z' },
  uid: 'NZ0SAMHNFlR5TzNf9WmAYNZwT8y2',
  toJSON: [Function] }

//log of the userRecord from admin.auth().getUser(...)

UserRecord {
  uid: 'NZ0SAMHNFlR5TzNf9WmAYNZwT8y2',
  email: 'test8@test.com',
  emailVerified: false,
  displayName: 'Test 8',
  photoURL: undefined,
  phoneNumber: undefined,
  disabled: false,
  metadata: 
   UserMetadata {
     creationTime: 'Fri, 06 Apr 2018 06:48:42 GMT',
     lastSignInTime: 'Fri, 06 Apr 2018 06:48:42 GMT' },
  providerData: 
   [ UserInfo {
       uid: 'test8@test.com',
       displayName: 'Test 8',
       email: 'test8@test.com',
       photoURL: undefined,
       providerId: 'password',
       phoneNumber: undefined } ],
  passwordHash: 'UkVEQUNURUQ=',
  passwordSalt: undefined,
  customClaims: undefined,
  tokensValidAfterTime: 'Fri, 06 Apr 2018 06:48:42 GMT' }

```

It is the same user so no matter if I get the `userRecord` from the function event or the `admin` I should get the same result. As far I can see the only difference is the `providerData`.

It is also strange that this problem is only with the `email` provider (as far we could test it). If using a Google login we have providerData in the `userRecord` of the event.

```js

//log of the userRecord from (userRecord, context)

{ email: 'icshostadm@gmail.com',
  emailVerified: true,
  displayName: 'Hubert Pichler',
  photoURL: 'https://lh4.googleusercontent.com/-6h7gg0VLk7Q/AAAAAAAAAAI/AAAAAAAAABQ/aQBVRi4dl38/photo.jpg',
  phoneNumber: null,
  disabled: false,
  providerData: 
   [ { displayName: 'Hubert Pichler',
       email: 'icshostadm@gmail.com',
       photoURL: 'https://lh4.googleusercontent.com/-6h7gg0VLk7Q/AAAAAAAAAAI/AAAAAAAAABQ/aQBVRi4dl38/photo.jpg',
       providerId: 'google.com',
       uid: '105990070675037265490',
       toJSON: [Function] } ],
  customClaims: {},
  passwordSalt: null,
  passwordHash: null,
  tokensValidAfterTime: null,
  metadata: 
   UserRecordMetadata {
     creationTime: '2018-04-06T06:57:44Z',
     lastSignInTime: '2018-04-06T06:57:44Z' },
  uid: 'jyJjY96TwQVO75RqfKEXe7puRzU2',
  toJSON: [Function] }

//log of the userRecord from admin.auth().getUser(...)

UserRecord {
  uid: 'jyJjY96TwQVO75RqfKEXe7puRzU2',
  email: 'icshostadm@gmail.com',
  emailVerified: true,
  displayName: 'Hubert Pichler',
  photoURL: 'https://lh4.googleusercontent.com/-6h7gg0VLk7Q/AAAAAAAAAAI/AAAAAAAAABQ/aQBVRi4dl38/photo.jpg',
  phoneNumber: undefined,
  disabled: false,
  metadata: 
   UserMetadata {
     creationTime: 'Fri, 06 Apr 2018 06:57:44 GMT',
     lastSignInTime: 'Fri, 06 Apr 2018 06:57:44 GMT' },
  providerData: 
   [ UserInfo {
       uid: '105990070675037265490',
       displayName: 'Hubert Pichler',
       email: 'icshostadm@gmail.com',
       photoURL: 'https://lh4.googleusercontent.com/-6h7gg0VLk7Q/AAAAAAAAAAI/AAAAAAAAABQ/aQBVRi4dl38/photo.jpg',
       providerId: 'google.com',
       phoneNumber: undefined } ],
  passwordHash: undefined,
  passwordSalt: undefined,
  customClaims: undefined,
  tokensValidAfterTime: 'Fri, 06 Apr 2018 06:57:44 GMT' }

```

It seems that the providers in the `providerData` of the function event are no 'UserInfo'.
Could this be because I don't use TypeScript?

**Comment by laurenzlong** [comment]
@TarikHuber Thank you for the thorough example. You're right, this does seem to be a bug. It is not an SDK bug, so I've filed a bug with the corresponding backend team. 

As for why the providerData is not a 'UserInfo', it's implementation details that cause the printout to look different. But you should be able to still interact with it in the same way.

**Comment by thechenky** [comment]
Internal bug reference: 77816118.

**Comment by thechenky** [comment]
Hi everyone! The change is now live in production. For email/password sign up, the provider is `password` in `providerData` and the `uid` is the email. The format is consistent with Firebase Admin SDK. I'm going to close this out now, thanks for everyone's patience!
