### ISSUE TITLE
How to add custom label to console.log

### ISSUE THREAD

**Issue by hyzhak** [firebase/firebase-functions#218]
I've found that on https://console.cloud.google.com/logs/viewer page I could see `execution_id` which is similar session id. What is very useful to extract logs for a particular session. But is there any way to add `user_is` or any other custom label?

But sadly I can't find any documents or example, how could I achieve it.

**Comment by laurenzlong** [comment]
Unfortunately that's not possible. You can file a feature request on the Google Cloud Functions public tracker: https://issuetracker.google.com/issues/new?component=187195&template=0

**Comment by hyzhak** [comment]
@laurenzlong thank! I've created and waiting for a response

**Comment by louismorgner** [comment]
I just wanted to implement custom labels as well - I think this would be a helpful addition instead of forcing devs to implement the cloud logger themselves.
