### ISSUE TITLE
Failed to load functions source code

### ISSUE THREAD

**Issue by chrisdrohr** [firebase/firebase-functions#222]
### Version info

**firebase-functions:** 1.0.1

**firebase-tools:** 3.18.0

**firebase-admin:** 5.12.0

### Steps to reproduce
yarn run build && firebase functions:shell
or
firebase serve --only functions
or
firebase deploy --only functions

### Were you able to successfully deploy your functions?
i  functions: Preparing to emulate functions.
!  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
!  functions: Error from emulator. Error parsing triggers: Cannot find module 'C:\[path]\[project]\functions'

Try running "npm install" in your functions directory before deploying.

### Actual behavior
After migrating to the new firebase functions 1.0.0+ i have not been able to get it working again.
i have uninstalled and reinstalled all modules, as well as cleared cache on yarn and npm.

[debug] [2018-04-09T19:56:51.812Z] ----------------------------------------------------------------------
[debug] [2018-04-09T19:56:51.814Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\bboyc\AppData\Local\Yarn\config\global\node_modules\firebase-tools\bin\firebase serve --only functions
[debug] [2018-04-09T19:56:51.815Z] CLI Version:   3.18.0
[debug] [2018-04-09T19:56:51.815Z] Platform:      win32
[debug] [2018-04-09T19:56:51.815Z] Node Version:  v6.11.5
[debug] [2018-04-09T19:56:51.816Z] Time:          Mon Apr 09 2018 12:56:51 GMT-0700 (Pacific Daylight Time)
[debug] [2018-04-09T19:56:51.816Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-04-09T19:56:51.832Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-04-09T19:56:51.833Z] > authorizing via signed-in user
[debug] [2018-04-09T19:56:51.836Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/eventmakr-578e2  
  
 Mon Apr 09 2018 12:56:51 GMT-0700 (Pacific Daylight Time)
[debug] [2018-04-09T19:56:52.354Z] <<< HTTP RESPONSE 200
[debug] [2018-04-09T19:56:52.355Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/eventmakr-578e2/tokens  
  
 Mon Apr 09 2018 12:56:52 GMT-0700 (Pacific Daylight Time)
[debug] [2018-04-09T19:56:52.784Z] <<< HTTP RESPONSE 200
[debug] [2018-04-09T19:56:52.785Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/eventmakr-578e2  
  
 Mon Apr 09 2018 12:56:52 GMT-0700 (Pacific Daylight Time)
[debug] [2018-04-09T19:56:53.284Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from 'C:\Users\bboyc\Desktop\Websites\pwa-eventmakr'...
[info] 
[info] i  functions: Preparing to emulate functions.
[debug] [2018-04-09T19:56:54.484Z] Fetching environment
[debug] [2018-04-09T19:56:54.490Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/960850128777:getServerAppConfig  
  
 Mon Apr 09 2018 12:56:54 GMT-0700 (Pacific Daylight Time)
[debug] [2018-04-09T19:56:55.054Z] <<< HTTP RESPONSE 200
[debug] [2018-04-09T19:56:55.055Z] Starting @google-cloud/functions-emulator
[debug] [2018-04-09T19:56:57.707Z] Parsing function triggers
[warn] !  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
[debug] [2018-04-09T19:56:57.976Z] Error during trigger parsing:  Error parsing triggers: Cannot find module 'C:\Users\bboyc\Desktop\Websites\pwa-eventmakr\functions'

Try running "npm install" in your functions directory before deploying.
[warn] !  functions: Error from emulator. Error parsing triggers: Cannot find module 'C:\Users\bboyc\Desktop\Websites\pwa-eventmakr\functions'

Try running "npm install" in your functions directory before deploying.
[debug] [2018-04-09T19:56:57.977Z]

**Comment by laurenzlong** [comment]
Can you check your functions/package.json and ensure that the "main" field matches the name of the file that is the entry point for your functions? (It's usually 'index.js' if you're writing functions in JavaScript)

**Comment by chrisdrohr** [comment]
**package.json**
{
  "name": "functions",
  "scripts": {
    "lint": "./node_modules/.bin/tslint -p tslint.json",
    "build": "./node_modules/.bin/tslint -p tslint.json && ./node_modules/.bin/tsc",
    "serve": "yarn run build && firebase serve --only functions",
    "shell": "yarn run build && firebase functions:shell",
    "start": "yarn run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/src/index.js",
  "dependencies": {
    "@google-cloud/logging": "^1.2.0",
    "@google-cloud/storage": "^1.6.0",
    "@google-cloud/vision": "^0.19.0",
    "algoliasearch": "^3.26.0",
    "child-process-promise": "^2.2.1",
    "firebase": "^4.12.1",
    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.1",
    "mailchimp": "^1.2.0",
    "mailchimp-api-v3": "^1.8.0",
    "mandrill-api": "^1.0.45",
    "mkdirp-promise": "^5.0.1",
    "nodemailer": "^4.6.4",
    "stripe": "^5.8.0",
    "twilio": "^3.14.0"
  },
  "devDependencies": {
    "tslint": "^5.9.1",
    "typescript": "^2.8.1"
  },
  "private": true
}

**Comment by chrisdrohr** [comment]
Hi sorry i think my problem was that changed main: to lib/src/index.js, after an earlier build that included src in the lib folder.

looking at it now it is lib/index.js, and i have changed main: to match that.

sorry for the trouble! thankyou!
