### ISSUE TITLE
Expose apps() cache for firebase connections

### ISSUE THREAD

**Issue by esprehn** [firebase/firebase-functions#223]
The internals have a cache of apps in the form of `apps()` that caches the app for 2 minutes and then tears down the connection.  This isn't exposed though which means users of firebase cloud functions create long lived additional connections instead, or create and tear down connections rapidly in callbacks for non-db related functions like `user().onCreate` where the .ref property is missing.

**Comment by esprehn** [comment]
We also need the app in our database onWrite handlers for things like looking up UserRecords with app.getUser(). This results in us creating a duplicate connection to firebase which has no 2 minute cleanup timeout.

**Comment by laurenzlong** [comment]
Please follow the issues template next time. 

If I'm understanding you correctly, this is a feature request for exposing the Firebase app that the SDK creates. 

In the meanwhile, you can add code to do the clean up on the additional Firebase apps you create by following the example for impersonateMakeUppercase: https://firebase.google.com/docs/functions/database-events#accessing_user_authentication_information

**Comment by esprehn** [comment]
I'm aware of how to do it, that creates and destroys the connection for every invocation. If the cloud function sdk thinks its too expensive to do that and instead caches for 2 minutes it would seem unreasonable to ask consumers to do it too.

**Comment by thechenky** [comment]
Closed for inactivity.
