### ISSUE TITLE
Error parsing triggers: Cannot find module './providers/analytics'

### ISSUE THREAD

**Issue by jyosh** [firebase/firebase-functions#224]
I Upgraded to firebase functions version 1 and followed the migration guide. When try to deploy using the command
firebase deploy --only functions
it is giving an error saying Error parsing triggers: Cannot find module './providers/analytics'. Any idea how to resolve this?

Here is the complete log

=== Deploying to 'codingforms'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module './providers/analytics'

Try running "npm install" in your functions directory before deploying.

**Comment by laurenzlong** [comment]
Did you try to run "npm install" in your functions directory?

**Comment by laurenzlong** [comment]
thanks for the update!
