### ISSUE TITLE
'Page Not Found' When Triggering Function via Custom Domain (Hosting)

### ISSUE THREAD

**Issue by samcaplat** [firebase/firebase-functions#225]
### Version info

**firebase-functions:** ^1.0.1

**firebase-tools:** 3.18.2

**firebase-admin:** ^5.12.0

### Steps to reproduce

**index.js file:**
(implements the 'trailing slash' fix found in this issue: #27)
```
const testsExpress = express()
testsExpress.use(cors({ origin: true }))

testsExpress.get('/hello/:id', (request, response) => {
  let id = request.params.id
  response.send(`Parameter is: ${id}`)
})

const tests = functions.https.onRequest((request, response) => {
  if (!request.path) {
    request.url = `/${request.url}`
  }
  return testsExpress(request, response)
})

module.exports = {
  tests
}
```

**firebase.json file:**
```
{
  "hosting": {
    "public": "public",
    "rewrites": [
      {
        "source": "/tests",
        "function": "tests"
      }
    ]
  }
}
```

**directory tree:**
(contains node_modules directory, but has been omitted)
```
|   .firebaserc
|   firebase.json
|   output.doc   
+---functions
|   |   package.json
|   |   package-lock.json
|   |   index.js
|   |                   
\---public
        index.html
```

### Were you able to successfully deploy your functions?

Yes, Functions deployed with no error messages, and they are usable on the Firebase-provided URL.

### Expected behavior

Behaviour on the Firebase-provided URL should be the same on Hosting.

### Actual behavior

Functions are usable on the Firebase-provided URL: 
https://us-central1-example.cloudfunctions.net/tests/hello/1234
_Responds with: "Parameter is: 1234"_

Functions are not usable on our Hosting domain:
https://api.example.com/tests/hello/1234

![firebase-hosting-pagenotfound](https://user-images.githubusercontent.com/22086256/38617958-3bd08246-3d90-11e8-8203-6497f41f4e85.png)

**Notes:**
1. Our custom domain was working perfectly with Functions before we moved to Express.
2. This issue has been raised after initialising a whole new project, and deploying it to see if the behaviour changed.
3. I've attempted the various solutions in #27 but haven't had any luck.
4. After re-deploying, I waited 15 minutes to allow the changes to propagate.

Thanks for your help!

**Comment by samcaplat** [comment]
Hi all,

This issue has been solved (I think) and replaced with a new issue:

Used this solution that implements `express.Router()`: [https://code.i-harness.com/en/q/2ae07a4](url)

**index.js**
```
const testsExpress = express()
testsExpress.use(cors({ origin: true }))

router.get('/hello/:id', (request, response) => response.send('Unit test worked.'))
testsExpress.use('/tests', router)

const tests = functions.https.onRequest((request, response) => {
  if (!request.path) {
    request.url = `/${request.url}`
  }
  return testsExpress(request, response)
})

module.exports = {
  tests
}
```

**firebase.json**
```
{
  "hosting": {
    "public": "public",
    "rewrites": [
      {
        "source": "/tests/**",
        "function": "tests"
      },
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
``` 

#### Previous behaviour

Functions could only be triggered on Firebase-provided URL and localhost. Hosting failed with `Cannot GET /hello/1234`

#### Expected behaviour

Functions should be available on Hosting, Firebase-provided URL, and localhost.

#### New behaviour

Functions trigger correctly on our Hosting domain, but it's not possible to trigger functions using Firebase-provided URL or localhost:

Hosting (https://api.example.com/tests/hello/1234): Responds with `Unit test worked.`
Firebase-provided URL: Responds with `Cannot GET /hello/1234`
localhost: Responds with `Cannot GET /hello/1234`

I can't find a solution to any of this in the documentation. Is Hosting not meant to be paired with Firebase Functions using Express? I can't seem to find a straight-to-the-point solution.

Thanks for your help, please forgive the double-post!

**Comment by mbleigh** [comment]
You likely need to change `/hello/1234` to `/tests/hello/1234` (even if this means it is duplicated in the URL. Everything after the function name is considered the path, and your Express router requires the path prefix.

**Comment by samcaplat** [comment]
Hi Michael,

Thanks for replying so quickly. You're right, if I use `/tests/tests/hello/1234` on the Firebase-URL and localhost, it works as expected. I'm glad it's been diagnosed!

If the user wants to use Functions with Express alongside Hosting, and the **only** solution to this problem is to manually add an extra `/{function_name}` to the URL when testing, surely that's a fault in the design or my code. Either this needs to be documented and/or fixed, or implemented better on my side. Is there anything that can be done to solve this problem (most likely by me)?

If the answer is no, that's absolutely fine, it just means I need to write in our internal documentation:
> Functions, Hosting, and Express don't play ball with each other, so when testing on `localhost` you need to add an extra `/{function_name}/` for it to work.

Regardless, appreciate the help, thank you!
