### ISSUE TITLE
user.create not being triggered when using passwordless email login. 

### ISSUE THREAD

**Issue by Bengejd** [firebase/firebase-functions#226]
### Version info

    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.0",

### Steps to reproduce

Create a firebase function that gets triggered on.create(), use the firebase passwordless email auth, authenticate into your application, 

### Were you able to successfully deploy your functions?
Yes

### Expected behavior
Function runs on user.create() function.

### Actual behavior
The function doesn't get triggered.

**Comment by rjhuijsman** [comment]
Thanks for the report! We're working on resolving this; stay tuned!

**Comment by valmassoi** [comment]
```
    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.1",
```
Same issue. The trigger was working in `"firebase-functions": "^0.8.1"`

**Comment by laurenzlong** [comment]
@valmassoi If you reverted your SDK version, does it work again?

**Comment by valmassoi** [comment]
Yep @laurenzlong I just reverted and it works again (but I'd like to get on v1 asap):
```bash
$ yarn add firebase-functions@0.8.1 -E
# undo migration guide code changes
$ date && firebase deploy --only functions:createUser
```

Also note when I was on `1.0.1` the `functions.auth.user().onCreate` trigger would still work for new email/password users - just not my GitHub/Gmail providers

**Comment by laurenzlong** [comment]
@valmassoi Could you share your code for both v0.8.1 and v1.0.1 versions? They're both targetting the same backend so I'm very  confused as to why the SDK version would affect whether the function gets  triggered.

**Comment by valmassoi** [comment]
@laurenzlong 
```javascript
// v1.0.1
export const createUser = functions.auth
    .user()
    .onCreate(async (userRecord, context) => {
        const { uid, email, displayName } = userRecord
        const [firstName, lastName] = displayName ? displayName.split(' ') : ['', '']
        const newUserRecord = {
            uid,
            email,
            firstName,
            lastName,
            qualificationRecord: {
                kyc: "Incomplete",
                accreditation: "Incomplete",
            }
        }
        const userDocRef = admin.firestore().collection('users').doc(email)
        await userDocRef.set(newUserRecord)
        return
})
```
```javascript
// v0.8.1
export const createUser = functions.auth
    .user()
    .onCreate(async (event) => {
        const user = event.data
        const { uid, email, displayName } = user
        const [firstName, lastName] = displayName ? displayName.split(' ') : ['', '']
        const userRecord = {
            uid,
            email,
            firstName,
            lastName,
            qualificationRecord: {
                kyc: "Incomplete",
                accreditation: "Incomplete",
            }
        }
        const userDocRef = admin.firestore().collection('users').doc(email)
        await userDocRef.set(userRecord)
        return
})
```
When it doesn't work I don't even see the `outlined_flag | createUser | Function execution started` in the functions logs

**Comment by valmassoi** [comment]
Does https://github.com/firebase/firebase-functions/blob/bcb006f0965338fa5a6d9fb34389515727196ca6/src/providers/auth.ts#L65 vs https://github.com/firebase/firebase-functions/blob/bcb006f0965338fa5a6d9fb34389515727196ca6/src/providers/auth.ts#L65 have to do with it maybe?

**Comment by rjhuijsman** [comment]
The lack of functions getting triggered on a passwordless e-mail login was a server-side issue; we've fixed that now! Thanks again for the reports; let us know if you're still having trouble.

**Comment by valmassoi** [comment]
Confirmed it's working again - thanks @rjhuijsman

**Comment by radvansky-tomas** [comment]
I am experiencing same issue with anonymous user creation:

    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.5",

**Comment by radvansky-tomas** [comment]
Plus the anonym user has property:   isAnonymous: false, which is wrong as well

**Comment by radvansky-tomas** [comment]
Issue was on my side - new firebase functions version with correct syntax fixed the issue:
`exports.authAction = functions.auth.user().onCreate((userRecord, context) => {
  const creationTime = userRecord.metadata.creationTime; // 2016-12-15T19:37:37.059Z
  const lastSignInTime = userRecord.metadata.lastSignInTime; // 2018-01-03T16:23:12.051Z
}`
