### ISSUE TITLE
Event context can be undefined according to type definitions

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-functions#227]
According to the 1.0.0 Typescript definitions the context part of an event is defined as `EventContext | undefined`. For example:

```ts
const myFunction = firestore
  .document(`collection/{documentId}`)
  .onCreate((data, context) => {
    // Check if context is defined?
  });
```

I have a hard time imagining why this would ever be undefined, so I am currently ignoring it. 

Context as the second parameter to the handler function is optional, because you can supply a handler with just the `data` argument. But shouldn't that be solved via overloading? If I supply a function with both arguments then context should be guaranteed to exist, no?

**Comment by 0x80** [comment]
Hi @laurenzlong, vcode points me to 

`firebase-functions/lib/providers/firestore.d.ts` line 22:

```ts
    onCreate(handler: (snapshot: DocumentSnapshot, context?: EventContext) => PromiseLike<any> | any): CloudFunction<DocumentSnapshot>;
```

**Comment by merlinnot** [comment]
It's just defined like this in the source code, unnecessarily AFAIK. I've made a PR yesterday.

**Comment by uloga** [comment]
Typescript version 3.2.2, latest firebase - functions getting the same lint errors while following documentation on firebase. :(

**Comment by mon2104** [comment]
Latest firebase, if we use 
import {EventContext} from 'firebase-functions' 
gives error -- cannot import from outside a module. 
How to fix it ?
