### ISSUE TITLE
Deploy Error: Failure in the execution environment

### ISSUE THREAD

**Issue by duni1210** [firebase/firebase-functions#23]
Hi there,
I encountered these kind of bug randomly, and fortunately after several tries, it succeeded as it should.
I've attached some screenshots below as a contribution to eliminate the bug.
Anyway, Firebase Functions is a magical feature and it makes life easier and happier 👍 
Hope to see a stable system soon.
Thank you so much, Firebase Team :)

![firebase-functions-bug-console](https://cloud.githubusercontent.com/assets/25870280/24425401/52aa26e8-142e-11e7-8cb5-0e077591afbf.png)

![firebase-functions-bug](https://cloud.githubusercontent.com/assets/25870280/24425273/ca16e88e-142d-11e7-8064-b1fb46f13136.png)

**Comment by ahaverty** [comment]
I've the same issue in progress over here https://github.com/firebase/firebase-functions/issues/19
We haven't found any workaround yet unfortunately. Deploy with the --debug flag to capture debug logs, and send over in a private support ticket for @laurenzlong is probably our best bet at helping 👌

**Comment by laurenzlong** [comment]
Thanks for the report and the kind words @duni1210 ! Can you also file a support ticket at https://firebase.google.com/support/, and ask for it to be routed to Lauren Long. Closing this issue, since this is a server issue, not an SDK issue.
