### ISSUE TITLE
firebase deploy "Deploy Complete!" does not mean the newly deployed functions will be used right away

### ISSUE THREAD

**Issue by iosdev-republicofapps** [firebase/firebase-functions#236]
### Version info

**firebase-functions:** 1.0.1

**firebase-tools:** 3.18.4

**firebase-admin:** 5.12.0

### Steps to reproduce

Deploy a Firebase Realtime Database onUpdate function that `console.log("Hello world 1")`.  Peform an update that triggers the onUpdate and note that `Hello world 1` gets logged as expected.

Now change the log statement to log `Hello world 2` and `firebase deploy --only functions`.  Then as soon as that deploy completes, perform another update.  For a period of 10-30 seconds afterwards, any update will still log "Hello world 1" which *proves* that Firebase is still using the old version of the function, even though it claimed that the deploy completed.

### Were you able to successfully deploy your functions?

Yes.

### Expected behavior

When `firebase deploy --only functions` completes and logs "Deploy complete!" to the shell, I expect the newly deployed functions to be *instantly and consistently* available.

### Actual behavior

After "Deploy complete!" is logged, Firebase still uses the older versions of the functions, from before the deploy, for a period of 10-30 seconds afterwards.

This is not desirable because it makes the edit-deploy-test cycle unpredictable and unnecessarily slow.

My expectation is that as soon as the deploy completes, and future updates that trigger the onUpdate should use the newly deployed version of the function.  They do not.  Instead, there is some sort of "propagation delay" where the new versions of the functions are synced to Firebase.  This sync should be instantaneous, or at very least the delay should be reduced to under 1s.

**Comment by dinvlad** [comment]
To add to that, there's a short period if time where the old instances are terminated, but the new ones aren't available for servicing requests yet (resulting in, for https triggers, a `connection error`).

**Comment by laurenzlong** [comment]
Thanks for filing and the detailed explanation. That is definitely a bug, however, it is not one that we can solve with the SDK as it is a backend issue. Could you file an issue on the public tracker for Google Cloud Functions? https://issuetracker.google.com/savedsearches/559729
