### ISSUE TITLE
userRecord is undefined when using onCreate

### ISSUE THREAD

**Issue by denigada** [firebase/firebase-functions#237]
I have a function to add new database field on user creation. It was working without problems, but now it is not. 

`exports.addUserToDatabase = functions.auth.user().onCreate((userRecord, context) => {
    console.log(userRecord.data)
    const user = userRecord.data;`

It prints undefined in the functions console. I cannot reach uid.

**Comment by mbleigh** [comment]
You shouldn't need to call .data on it if you're using the 1.0 SDK.

**Comment by denigada** [comment]
userData itself is also undefined

**Comment by denigada** [comment]
context changed in update. Working code:
`exports.addUserToDatabase = functions.auth.user().onCreate(user=> {`
