### ISSUE TITLE
cacheControl update via cloud functions not working

### ISSUE THREAD

**Issue by darkylmnx** [firebase/firebase-functions#242]
I'm trying to add cacheControl metadata to every new object on cloud storage firebase but it results in a bug each time.

here's my code 
```js
exports.addCacheToImages = functions.storage.object().onFinalize(object => {
  object.updateMetadata({
    cacheControl: 'public,max-age=31536000',
  })
})
```
Then I tried
```js
exports.addCacheToImages = functions.storage.object().onFinalize(object => {
  object.cacheControl = 'public,max-age=31536000'
})
```
but still nothing though

**Comment by thechenky** [comment]
Hi @darkylmnx thank you for the feedback! Apologies for the late response - could you provide the link to the google cloud docs that helped you resolve your issue? When you say "without the need to use gcloud", do you mean without using gcs library and use the `object` instead?

**Comment by thechenky** [comment]
@darkylmnx thanks for the update - I have noted your feature request for adding cache control through the SDK in our bug tracker. Internal bug reference: 122078978. I can't guarantee we will get to this anytime soon as we're prioritizing more serious infrastructure issues and bugs at the moment. 

Regarding the documentation, I'll poke around the cloud documentation and make sure we link to this workaround in our Firebase docs. Going to close this out now - please don't hesitate to open a new issue if you encounter any other problems.
