### ISSUE TITLE
Can't retrieve serverTimestamp from functions

### ISSUE THREAD

**Issue by melvinkcx** [firebase/firebase-functions#251]
### Version info

**firebase-functions:**
1.0.3
**firebase-tools:**

**firebase-admin:**
5.12.1
### Test case

One of the document field, 'created_at'  in my Firestore uses serverTimestamp. However, when trying to get data from Firestore using admin.firestore() API, the 'created_at' field appears to be empty object. 

P/S: This problem does not appear when using firebase.firestore API.

### Were you able to successfully deploy your functions?
Yes

### Expected behavior
A timestamp object should be returned on 'created_at' field.
![screenshot_20180527_004034](https://user-images.githubusercontent.com/16914545/40578437-9b30dfae-6146-11e8-82a3-3d3a5e85a3d0.png)

### Actual behavior

![screenshot_20180527_004611](https://user-images.githubusercontent.com/16914545/40578490-728827aa-6147-11e8-9f40-f2fcac7eb291.png)

**Comment by laurenzlong** [comment]
Please share your code (for both writing to Firestore, and your functions code)

**Comment by dfischer** [comment]
@laurenzlong can you query createTime or is it only available through snapshots?

**Comment by laurenzlong** [comment]
It is available on any snapshots, the one received by the function, as well as any that result from a Firestore query such as `admin.firestore().collection(..).doc(..).get()`

**Comment by dfischer** [comment]
@laurenzlong I see what you're saying, but that means you couldn't *query* for that attribute? E.g  `usersRef.where('createTime', '<', new Date())` so would still have to store it in attribute to query for fields that match date ranges or something like that.

**Comment by laurenzlong** [comment]
Oh I see what you are saying, I'm sorry but I'm not an expert with Firestore. I recommend checking out the API reference for the Node SDK: https://cloud.google.com/nodejs/docs/reference/firestore/0.15.x/ (firebase-admin just wraps the Node SDK, so everything in that API applies)

**Comment by minhchienwikipedia** [comment]
@dfischer  Did you find any way to resolve this issue?

**Comment by dfischer** [comment]
@minhchienwikipedia store createdAt in firestore db as an attribute `doc('someDoc').set({foo: 'bar', createdAt: Date now()})`
