### ISSUE TITLE
[ts] Property 'resourceState' does not exist on type 'ObjectMetadata'

### ISSUE THREAD

**Issue by joemanfoo** [firebase/firebase-functions#255]
### Version info

**firebase-functions:** "^1.0.3"

**firebase-tools:** "3.18.5"

**firebase-admin:** "~5.12.1"

### Test case

```
import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin'

export const processUploadedFile = functions.storage.bucket('<yourappid>.appspot.com/inventory/upload').object().onFinalize((object, context) => {
  if (object.resourceState === 'not_exists') {
    console.log('object deleted, noop')
    return null
  }

  // have a file...
  console.log(`got file: ${object.name}`)
  console.log(`got metadata: ${object.metadata}`)
  return true
})
```

### Steps to reproduce

* firebase init functions
** select TypeSrcript for language
* Choose default to use Linter
* Choose install dependencies
### Expected behavior
expected to be able to read the state of the object per documentation
https://firebase.google.com/docs/reference/functions/functions.storage.ObjectMetadata#resourceState

### Actual behavior
Get error: `[ts] Property 'resourceState' does not exist on type 'ObjectMetadata'.`

**Comment by laurenzlong** [comment]
Thanks for filing! This is actually a documentation error, we used to have `resourceState` back when there was only one trigger for storage - onChange. Since we now have different triggers for different events - onFinalize, onDelete, etc. we removed the field. For onFinalize, you can be sure that the file was created, not deleted, so the if statement is not necessary. 

I've filed an internal bug for fixing the documentation.

**Comment by laurenzlong** [comment]
Also, out of curiosity, which did you get that code snippet from? If it's one of our examples, we should fix it!

**Comment by joemanfoo** [comment]
@laurenzlong  - Thanks and found code here.
https://github.com/firebase/functions-samples/blob/410086fad72cb3cdeb58a5e97e92924b8172b4f6/convert-images/functions/index.js#L55

And a quick search on the functions samples:
https://github.com/firebase/functions-samples/search?q=object.resourceState+%3D%3D%3D+%27not_exists%27&unscoped_q=object.resourceState+%3D%3D%3D+%27not_exists%27

**Comment by laurenzlong** [comment]
Thanks for pointing it out! Filed https://github.com/firebase/functions-samples/issues/412
