### ISSUE TITLE
FirebaseMessagingService() not called in background / Closed when push is sent with Firebase Functions

### ISSUE THREAD

**Issue by Martindgadr** [firebase/firebase-functions#256]
**Expected Behaviour**
Push notification arrived passing for FirebaseMessagingService() implemented class

**Actual Behaviour**
Push is received but it's not calling FirebaseMessagingService() implemented class, in order to run an specific logic inside this. Push is OK but not pass throw this class, it's estrange.
Push is implemented in Firebase Function with:
return admin.messaging().sendToDevice(tokens, payload, options)

**Steps to Reproduce**
App runs, write Firestore database and trigger firebase functions service.
first step run logic on it and push notification, notification is sent to corresponding device (token)
Notification arrive but not calling FirebaseMessagingService() if APP is closed or in background.
Platform and Version
I run this on Android phones. 3 different versions: Android 5.0 L (lollipop), 6.0 M (Marshmallow), Android 8 (oreo)

**What device vendor**
Samsung
Motorola

**Sample Push Data Payload**

`let payload = {
notification: {
title: dataNode.title,
body: dataNode.message,
sound: 'default',
content_available: 'true',
badge: '1'
}
}`

`    const options = {
        priority: "high",
        timeToLive: 60 * 60 * 24 //24 hours
    }`

**Sample Code that illustrates the problem**
Code is running OK, Push is receive into device but only works in Foreground mode. FirebaseMessagingService() implemented class only runs when app is running.

**Logs taken while reproducing problem**
N/C

**Comment by Martindgadr** [comment]
I solve the issue, for every person who has same problem in future, the solution for this you have to use **data** instead of **notification**, documentation in Firebase site is OK but do not contemplate this case, **Notification** in payload only run FirebaseMessagingService() when app is running but after that if it closed or in background, Notification is managed by OS.

        let payload = {
            data: {
                title: dataNode.title,
                body: dataNode.message,
            }
        }

        const options = {
            priority: "high",
            timeToLive: 60 * 60 * 24 //24 hours
        }

Cheers!!!

**Comment by laurenzlong** [comment]
Hi, this seems to be a documentation issue, I've filed an internal bug to fix https://firebase.google.com/docs/cloud-messaging/admin/send-messages to add details on this use case. Thanks for letting us know!

**Comment by parisa7103** [comment]
Hi
according to FCM documents, @Martindgadr  are right but in Android 8.1, I'm just sending message with payload data without notification however I didn't received message when the app is in background or is killed :(
