### ISSUE TITLE
FR: onEmailVerify() Functions Trigger

### ISSUE THREAD

**Issue by sbnon** [firebase/firebase-functions#257]
It would be helpful to be able able to trigger a Firebase Function when a user verifies their email. Currently this doesn't appear to be possible.

**Comment by laurenzlong** [comment]
Hi, this Github repo is for filing bugs with the SDK. I think this is an excellent feature request, can you file a feature request at https://firebase.google.com/support/contact/? That way it will be triaged and prioritized appropriately.
