### ISSUE TITLE
Firebase GCloud ML-Engine TypeError: Cannot read property '0' of undefined at file.download.then..ONLY FOR CERTAIN IMAGES

### ISSUE THREAD

**Issue by VeryVeryGoodNews** [firebase/firebase-functions#258]
### Version info
**npm:** 5.6.0
**firebase-functions:** 0.8.1
**firebase-admin:** 5.8.1

### Test case

I am using firebase realtime database to connect a Swift iOS front-end to a Google Cloud ML-engine hosted --- adapted from Sara Robinson's tswift-detector. See: https://github.com/sararob/tswift-detection. The problem is that it works all the time for certain images and it never works for certain other images. Upon inspection of image attributes, I see no difference between the images on which it has chosen to work all the time, and the images on which it has chosen to never work. Clearly there must be a difference between these two classes of images.

To compound the mystery, when I test out online prediction from command line using "gcloud ml-engine models predict," all images work fine and return a prediction.

### Steps to reproduce

Below are two images that never work, followed by two images that always work:

- This image never works: https://www.colourbox.com/preview/11906131-maple-tree-and-grass-silhouette.jpg

- This image never works: http://feldmanphoto.com/wp-content/uploads/awe-inspiring-house-clipart-black-and-white-disney-coloring-pages-big-clipartxtras-illistration-background-housewives-bouncy.jpeg

- This image always works: http://www.spacedesign.us/wp-content/uploads/landscape-with-old-tree-and-grass-over-white-background-black-and-black-and-white-trees.jpg

- This image always works: http://www.modernhouse.co/wp-content/uploads/2017/07/1024px-RoseSeidlerHouseSulmanPrize.jpg

### Were you able to successfully deploy your functions?
YES.

### Expected behavior

Return prediction from google cloud ML-engine.

### Actual behavior
Certain images always return the following error, while certain other images always work as expected.

    TypeError: Cannot read property '0' of undefined at file.download.then.then.then.then (/user_code/index.js:128:51) at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Here is my entire index.js:

     'use strict';
     const functions = require('firebase-functions');
     const gcs = require('@google-cloud/storage');
     const admin = require('firebase-admin');

    const exec = require('child_process').exec;
    const path = require('path');
    const fs = require('fs');
    const google = require('googleapis');
    const sizeOf = require('image-size');

    admin.initializeApp(functions.config().firebase);
    const db = admin.firestore();
    const rtdb = admin.database();
    const dbRef = rtdb.ref();

    function cmlePredict(b64img) {
        return new Promise((resolve, reject) => {
            google.auth.getApplicationDefault(function (err, authClient) {
                if (err) {
                    reject(err);
                }
                if (authClient.createScopedRequired && authClient.createScopedRequired()) {
                    authClient = authClient.createScoped([
                            'https://www.googleapis.com/auth/cloud-platform'
                    ]);
                }

            var ml = google.ml({
               version: 'v1'
            });

            const params = {
                auth: authClient,
                name: 'projects/myproject-18865/models/my_model',
                resource: {
                    instances: [
                    {
                        "image_bytes": {
                        "b64": b64img
                        }
                    }
                    ]
                }
            };

            ml.projects.predict(params, (err, result) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }
            });
        });
    });
    }

    function resizeImg(filepath) {
        return new Promise((resolve, reject) => {
            exec(`convert ${filepath} -resize 224x ${filepath}`, (err) => {
              if (err) {
                console.error('Failed to resize image', err);
                reject(err);
              } else {
                console.log('resized image successfully');
                resolve(filepath);
              }
            });
          });
    }

    exports.runPrediction = functions.storage.object().onChange((event) => {

    fs.rmdir('./tmp/', (err) => {
        if (err) {
            console.log('error deleting tmp/ dir');
        }
    });

    const object = event.data;
    const fileBucket = object.bucket;
    const filePath = object.name;
    const bucket = gcs().bucket(fileBucket);
    const fileName = path.basename(filePath);
    const file = bucket.file(filePath);

    if (filePath.startsWith('images/')) {  
        const destination = '/tmp/' + fileName;
        console.log('got a new image', filePath);
        return file.download({
            destination: destination
        }).then(() => {
            if(sizeOf(destination).width > 224) {
                console.log('scaling image down...');
                return resizeImg(destination);
            } else {
                return destination;
            }
        }).then(() => {
            console.log('base64 encoding image...');
            let bitmap = fs.readFileSync(destination);
            return new Buffer(bitmap).toString('base64');
        }).then((b64string) => {
            console.log('sending image to CMLE...');
            return cmlePredict(b64string);
        }).then((result) => {
            console.log(`results just returned and is: ${result}`);  

            let predict_proba = result.predictions[0]

            const res_pred_val = Object.keys(predict_proba).map(k => predict_proba[k])
            const res_val = Object.keys(result).map(k => result[k])

            const class_proba = [1-res_pred_val,res_pred_val]
            const opera_proba_init = 1-res_pred_val
            const capitol_proba_init = res_pred_val-0

            // convert fraction double to percentage int
            let opera_proba = (Math.floor((opera_proba_init.toFixed(2))*100))|0
            let capitol_proba = (Math.floor((capitol_proba_init.toFixed(2))*100))|0
            let feature_list = ["houses", "trees"]

            let outlinedImgPath = '';
            let imageRef = db.collection('predicted_images').doc(filePath.slice(7));
                   outlinedImgPath = `outlined_img/${filePath.slice(7)}`;
                   imageRef.set({
                    image_path: outlinedImgPath,
                    opera_proba: opera_proba,
                    capitol_proba: capitol_proba
                });

            let predRef = dbRef.child("prediction_categories");
            let arrayRef = dbRef.child("prediction_array");

        predRef.set({
                opera_proba: opera_proba,
                capitol_proba: capitol_proba,
                });

           arrayRef.set({first: {
               array_proba: [opera_proba,capitol_proba],
               brief_description: ["a","b"],
               more_details: ["aaaa","bbbb"],
               feature_list: feature_list},
            zummy1: "",
            zummy2: ""});

            return bucket.upload(destination, {destination: outlinedImgPath});

        });
    } else {
        return 'not a new image';
    }
    }); `

**Comment by laurenzlong** [comment]
Hi, the issue you are facing is not really an issue with the firebase-functions SDK. It seems to be a usage question, and StackOverflow would be the best for that. If you do believe it is in fact a bug with the Storage SDK, then please file an issue at https://github.com/googleapis/nodejs-storage

**Comment by VeryVeryGoodNews** [comment]
How is this not a problem with the firebase SDK? It works perfectly fine
with the gcloud ML-engine versions predict CLI. Please kindly re-open.

________________________________________________________________________________
Dr. Stephen G. Odaibo, M.D., M.S.(Math), M.S.(Comp. Sci.)
RETINA-AI,  Co-Founder and Chief Executive Officer
Retina Specialist, Board-Certified Ophthalmologist
Distinguished Alumni Achievement Award Winner, 2017 -- UAB College of Arts
& Sciences
Barrie Hurwitz Award for Excellence in Neurology, 2005 -- Duke Univ. School
of Medicine
Fellow of The American Society of Retina Specialists
Fellow of The American Academy of Ophthalmology
https://www.linkedin.com/in/sgodaibo
www.retina-ai.com

**Comment by VeryVeryGoodNews** [comment]
How is it not an issue with firebase? It works perfectly fine with the gcloud-ML models predict CLI. Please kindly re-open. Help needed.

**Comment by laurenzlong** [comment]
If you trace the error it refers to the variable "file", looking at your code I see: 
```
const bucket = gcs().bucket(fileBucket);
const fileName = path.basename(filePath);
const file = bucket.file(filePath);
```
So it is coming from the Storage SDK, that's why I linked to that Github repository.

**Comment by laurenzlong** [comment]
This Github repository is only for the firebase-functions SDK, in your code, that is:
```
const functions = require('firebase-functions');
```

You happened to have encountered the error while using Cloud Functions for Firebase, but it is not an issue with the firebase-functions SDK itself.

**Comment by VeryVeryGoodNews** [comment]
Ok thanks.

**Comment by VeryVeryGoodNews** [comment]
Issue was that the bad images were grayscale, not RGB as expected by my model. I initially had checked this first by looking at the shape. But the 'bad' images had 3 color channels, each of those 3 channels stored the same number --- so my model was refusing to accept them. Also, as expected and contrary to what I initially thought I observed, turns out the gcloud ML-engine predict CLI actually also failed for these images. Took me 2 days to figure this out!

**Comment by laurenzlong** [comment]
Glad you figured it out! Thanks for the update.

**Comment by VeryVeryGoodNews** [comment]
You're welcome. It is a problem with gcloud ML-engine . The problem does
not happen during training and should not be happening at predict time
either.
