### ISSUE TITLE
Require another files into index.js

### ISSUE THREAD

**Issue by rodrigoreal** [firebase/firebase-functions#26]
I see that all functions reside in a single `index.js` file.
How can i create another files and require it in the `index.js`?
I'm trying to organize my functions.

**Comment by ahaverty** [comment]
Check out my answer on functions sample repo https://github.com/firebase/functions-samples/issues/63

**Comment by jwngr** [comment]
Thanks for answering this one @ahaverty!

@rodrigoreal - In the future, please read and follow the issue template.

**Comment by geovanisouza92** [comment]
What about files on custom folders? I've placed a [Next.js build folder](https://github.com/zeit/next.js/#setting-a-custom-build-directory) inside functions, that is loaded by `next` package, but it isn't included on functions package.

**Comment by jthegedus** [comment]
@geovanisouza92 That issue is a bit different and being tracked [here (firebase-tools 291)](https://github.com/firebase/firebase-tools/issues/291) and [here (firebase-tools 376)](https://github.com/firebase/firebase-tools/issues/376)
