### ISSUE TITLE
Please, upgrade support to node 8 LTS !

### ISSUE THREAD

**Issue by realtebo** [firebase/firebase-functions#266]
```
mirko@DESKTOP-3QBL88J MINGW64 /d/google-cloud-functions/test/functions
$ firebase functions:shell
i  functions: Preparing to emulate functions.
Warning: You're using Node.js v10.3.0 but Google Cloud Functions only supports v6.11.5.
!  functions: Failed to emulate refresh
!  functions: Failed to emulate getPageIndex
!  functions: Failed to emulate parseFileWhenCreated
i  functions: No functions to emulate.
No functions emulated.

```

Ok, i must not use Node v10, but, really **_"Google Cloud Functions only supports v6.11.5."_** ?!?!?!

Actually the Node.js LTS is at 8.11.3 .
Please, keep your tools updated !

**Comment by laurenzlong** [comment]
Please file issue in https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues

**Comment by laurenzlong** [comment]
The Google Cloud Functions emulator still tries to emulate your functions when you're using a Node version above v6.11.5 but prints out a warning. So the fact  that the emulation actually fails is unexpected and is a bug.

**Comment by inmogr** [comment]
sorry I agree with him I feel like your tools development a bit slow, pls keep it up we love you and that's why we are advising you
