### ISSUE TITLE
cannot import one package

### ISSUE THREAD

**Issue by jonathan-chin** [firebase/firebase-functions#267]
For some reason, one of my imported packages are coming up as undefined. Here's a small example:

```
...
import handlebars from 'handlebars';
import QRCode from 'qrcode';
...

export const processSurvey = functions.https.onRequest((request, response) => {
    console.log(QRCode);
    console.log(handlebars);
    ...
});
```

the first log gives undefined
the second log gives the expected object
my package.json seems good:

```
...
    "dependencies": {
       ...
        "handlebars": "^4.0.11",
        "qrcode": "^1.2.0",
        ...
    }
...
```

I ran a separate test script on my local server within the same directory as my functions/src directory:

```
import QRCode from 'qrcode';

let qrCodeData = {
    action: 'dispense',
};

console.log(QRCode);
```

this script runs fine.

for some reason, when I deploy to firebase functions, QRCode is undefined but other packages are imported fine.

**Comment by laurenzlong** [comment]
What does your package.json look like?

**Comment by jonathan-chin** [comment]
here's the full package.json:

```
{
    "name": "functions",
    "scripts": {
	"lint": "tslint --project tsconfig.json",
	"build": "tsc",
	"serve": "npm run build && firebase serve --only functions",
	"shell": "npm run build && firebase functions:shell",
	"start": "npm run shell",
	"deploy": "firebase deploy --only functions",
	"logs": "firebase functions:log"
    },
    "main": "lib/index.js",
    "dependencies": {
	"@google-cloud/functions-emulator": "^1.0.0-beta.4",
	"cors": "^2.8.4",
	"firebase-admin": "^5.12.1",
	"firebase-functions": "^1.0.4",
	"handlebars": "^4.0.11",
	"nodemailer": "^4.6.6",
	"qrcode": "^1.2.0"
    },
    "devDependencies": {
	"tslint": "^5.8.0",
	"typescript": "^2.5.3"
    },
    "private": true
}
```

**Comment by laurenzlong** [comment]
Hi, I'm sorry I'm not sure why that is occurring, definitely very odd. My only thought is that you can try to import it another way, such as:

`import * as  QRCode from 'qrcode';`

**Comment by jonathan-chin** [comment]
thanks @laurenzlong 
I swear I tried that fix before in debugging
but I just did it now and it works.
