### ISSUE TITLE
Timeout at 60 seconds on localhost

### ISSUE THREAD

**Issue by shaunc869** [firebase/firebase-functions#268]
### Version info

**firebase-functions:**: 1.0.4

**firebase-tools:**: 3.18.6

**firebase-admin:**: 5.12.1

### Test case

This is typescript:

export async function runTimeout(req, res) {
    await timeout(80000);
    res.status(200).send('Timeout complete');
}

function timeout(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

Which compiles to:

function runTimeout(req, res) {
    return __awaiter(this, void 0, void 0, function* () {
        yield timeout(80000);
        res.status(200).send('Timeout complete');
    });
}
exports.runTimeout = runTimeout;
function timeout(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

### Steps to reproduce

Run the above example using a basic express app.

### Were you able to successfully deploy your functions?

This is a bug about the localhost environment only.

### Expected behavior

This should run for around 80 seconds and return.

### Actual behavior

Instead it quit at 60 seconds with the error message:

info: Execution took 62237 ms, finished with status: 'timeout'
info: Execution took 62248 ms, finished with status: 'crash'

**Comment by sambegin** [comment]
@shaunc869 

It seems to have been fixed in the firebase-tools repo : 
https://github.com/firebase/firebase-tools/pull/810

I had the same problem and we've updated firebase-tools to latest version (3.19.3) and functions can now operate for 540 seconds.

**Comment by thechenky** [comment]
@sambegin thanks for chiming in! @shaunc869 please let us know if your issue has been fixed with the latest firebase-tools.

**Comment by sambegin** [comment]
@thechenky Think I already answer that question on July 12th 

> @shaunc869
> It seems to have been fixed in the firebase-tools repo :
> firebase/firebase-tools#810
> 
> I had the same problem and we've updated firebase-tools to latest version (3.19.3) and functions can now operate for 540 seconds.

**Comment by thechenky** [comment]
Right, I just didn't want to close the issue until I heard from the original poster

**Comment by thechenky** [comment]
Seeing as I haven't heard from the original poster, going to go ahead and close this out.

**Comment by burkongla** [comment]
This seems to still be an issue when running functions locally using `emulators:start --only functions` but when running with `serve --only functions` it seems to work.
