### ISSUE TITLE
Can i use http request to another api?

### ISSUE THREAD

**Issue by danielfnz** [firebase/firebase-functions#29]
I am making a viability to use firebase-functions and would like to know if it is possible to communicate with another api using http request.

Anyone already tested?

**Comment by laurenzlong** [comment]
Yes you can, but you must have a credit card on file to make external network requests within your function. In the future, please use our [Google Groups](https://groups.google.com/forum/#!forum/firebase-talk) for something like this, Github issues are for reporting reproducible bugs or feature requests for the SDK.
