### ISSUE TITLE
Image | window | document is not defined?

### ISSUE THREAD

**Issue by afficionaddo** [firebase/firebase-functions#293]
### Version info

**firebase-functions:**  It's the one before v1.

**firebase-tools:**

**firebase-admin:**

### Test case

I am trying to use new Image() or document.createElement("img") or window.document.createElement("img") but everytime I deploy the functions, it gives an error saying "image is not defined" OR "window is not defined" OR "document is not defined".

### Steps to reproduce

1. Add a sample function with the below code: (Wrote all the three for just viewing)
![image](https://user-images.githubusercontent.com/20191900/43336822-46090a12-91a0-11e8-90cd-33f351065093.png)

2. When you deploy, it will give an error saying "image is not defined" OR "window is not defined" OR "document is not defined"

### Were you able to successfully deploy your functions?

NO.

### Expected behavior

It should recognize "image", "document", "window" as it is javascript. Why is it recognizing them? What am I missing?

### Actual behavior

An error saying "image is not defined" OR "window is not defined" OR "document is not defined".
![image](https://user-images.githubusercontent.com/20191900/43337022-813489d6-91a0-11e8-9dbb-e2fc07def031.png)

**Comment by laurenzlong** [comment]
Cloud Functions runs in Node.js, which does not have a `window` object. You may want to use something like https://www.npmjs.com/package/window
