### ISSUE TITLE
Permission denied on setting data value in firebase

### ISSUE THREAD

**Issue by vinita26** [firebase/firebase-functions#296]
I am just trying to wrote some data in firebase db:
  
  var fb = database.ref('whatsMyStatus');
  document.getElementById('clientStatus').addEventListener('input',updateStatus);
  
  function updateStatus(e){
    var myUpdate = {};
    myUpdate.email = user.email;
    myUpdate.displayName = user.displayName;
    myUpdate.status = document.getElementById('clientStatus').value;
    fb.child(user.uid).set(myUpdate);

  }
  It is giving me the below error:
  Repo.js:510 Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied
  
  My permission are already set to full for read and write.
  Also changed project App's 'App Engine default service account' permission to 'Editor' as suggested in previous issue 

discussions.
  
  Still i am not able to push data into firebase DB.

**Comment by laurenzlong** [comment]
It doesn't seem like you're using firebase-functions. Also, closing because this is not following the issues template.
