### ISSUE TITLE
Cannot install firebase-functions

### ISSUE THREAD

**Issue by Domiii** [firebase/firebase-functions#30]
I am currently unable to `firebase deploy` because `firebase-functions` won't get installed, and it won't even omit them when I tell it to during `firebase init`.

Here is the problem with `firebase-functions` in particular:

During `npm install` in my `functions` folder, I am told that the `@types/express` dependency does not exist:

> npm http 404 https://registry.npmjs.org/types/express
> npm ERR! 404 Not Found
> npm ERR! 404
> npm ERR! 404 'types/express' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it
> npm ERR! 404 It was specified as a dependency of 'firebase-functions'

When just running `npm install --save @types/express`, I get a different error:

> d:\code\self-asssessment-app\functions>npm install --save @types/express
> npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/types/express)
> npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:types/express)
> npm ERR! git clone git@github.com:types/express Cloning into bare repository 'C:\Users\Domi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-express-baf9b5a2'...
> npm ERR! git clone git@github.com:types/express Permission denied (publickey).
> npm ERR! git clone git@github.com:types/express fatal: Could not read from remote repository.
> npm ERR! git clone git@github.com:types/express
> npm ERR! git clone git@github.com:types/express Please make sure you have the correct access rights
> npm ERR! git clone git@github.com:types/express and the repository exists.
> npm ERR! addLocal Could not install types/express
> npm ERR! Error: ENOENT: no such file or directory, stat 'd:\code\self-asssessment-app\functions\types\express'
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! System Windows_NT 6.1.7601
> npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@types/express"
> npm ERR! cwd d:\code\self-asssessment-app\functions
> npm ERR! node -v v7.2.1
> npm ERR! npm -v 1.4.9
> npm ERR! path d:\code\self-asssessment-app\functions\types\express
> npm ERR! syscall stat
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     d:\code\self-asssessment-app\functions\npm-debug.log
> npm ERR! not ok code 0

I am on Windows, and my `firebase-tools` are the latest version:

> $npm list -g firebase-tools
> C:\Program Files\nodejs
> └── firebase-tools@3.6.0

`functions/package.json` contains the following dependencies (and `functions/node_modules` is empty):

```json
  "dependencies": {
    "firebase-admin": "^4.1.2",
    "firebase-functions": "^0.5"
  }
```

Any help would be greatly appreciated. Also, it worked just fine yesterday... on a different machine though...

**Comment by mbleigh** [comment]
You are on an old version of npm. Please upgrade to the latest version and
try again.

**Comment by Domiii** [comment]
Indeed, I am using Windows and `chocolatey` to manage my `NPM` installation, and used [a deprecated package](https://chocolatey.org/packages/npm). Fixed it now. Thanks a lot! :)
