### ISSUE TITLE
Error when deploying storage triggers on specified region

### ISSUE THREAD

**Issue by shrestaz** [firebase/firebase-functions#301]
### Version info

**firebase-functions:**
2.0.2

**firebase-tools:**
4.0.3

**firebase-admin:**
5.13.1

### Steps to reproduce

1. Create a storage trigger with region like so:
```typescript
export const storageTrigger = functions.region('europe-west3').storage.object().onDelete(() => {
// do something 
});
```
2. Deploy the function:
```bash
firebase deploy --only functions:storageTrigger
```

3. Error
```bash
⚠  functions: failed to create function storageTrigger
HTTP Error: 400, The request has errors
```

### Were you able to successfully deploy your functions?
When region is not explicitly defined, yes.
When region is defined as above, no.

### Expected behavior

Function deploys on the defined region.

### Actual behavior

Error while deploying function when region is defined.
```bash
⚠  functions: failed to create function storageTrigger
HTTP Error: 400, The request has errors
```

**Comment by laurenzlong** [comment]
'europe-west3' is not a supported region, you probably want 'europe-west1', see full list of supported regions at https://firebase.google.com/docs/functions/locations

**Comment by opyate** [comment]
@laurenzlong a warning in the logs would be nice instead of just defaulting to `us-central1`.

We looked at [this list](https://cloud.google.com/compute/docs/regions-zones/) and assumed it applies to all GCP products.

**Comment by laurenzlong** [comment]
@opyate That page is only for compute engine. Cloud Functions is a separate product. You're right that the server error message could be improved, I've filed an internal bug to fix this.

**Comment by opyate** [comment]
On Tue, 11 Sep 2018, 03:50 Lauren Long, <notifications@github.com> wrote:

> @opyate <https://github.com/opyate> That page is only for compute engine.
> Cloud Functions is a separate product. You're right that the server error
> message could be improved, I've filed an internal bug to fix this.
>
That's good news, thanks Lauren.

>
> --
Juan M. Uys
+44 (0) 7702 783 956 <+447702783956>
uys.io <http://www.uys.io>
opyate.com
