### ISSUE TITLE
firestore function not being triggered when region is set to europe-west1

### ISSUE THREAD

**Issue by bgorriz** [firebase/firebase-functions#308]
### Version info

**firebase-functions:** 2.0.2

**firebase-tools:**4.0.3

**firebase-admin:**5.13.1

### Test case
I tried to explain myself in [this stackoverflow entry](https://stackoverflow.com/questions/51847163/firebase-cloud-function-firestore-not-being-triggered-with-region-europe-west1)

This firestore function is working fine:

`export const firebaseUpdateTrigger =  region('us-central1')
.firestore
.document(...)
.onUpdate(...) `

while the same code with europe region does not seem to get triggered:
`export const firebaseUpdateTrigger =  region('europe-west1')
.firestore
.document(...)
.onUpdate(...) `

### Steps to reproduce

·Deploy the firebase function.
· Go to firestore and update any document in the collection.

### Were you able to successfully deploy your functions?

yes

### Expected behavior

I should see some logs in the firebase functions console telling me the function executed. like this:

> Function execution started
> Received an update for request b4f957737e2633ba4ea1eb2467f5efb5 
> Function execution took 10 ms, finished with status: 'ok'

### Actual behavior

I see no error logs, no logs at all for that function.

**Comment by laurenzlong** [comment]
Hi, your code is inaccurate, it should be export const firebaseUpdateTrigger = region('europe-west1') .firestore .document(...) .onUpdate(...)

**Comment by laurenzlong** [comment]
Hi @bgorriz I can't reproduce your issue so it might be something project specific, can you file a support ticket at https://firebase.google.com/support/?
