### ISSUE TITLE
Since updating to firebase-functions 2.0.5, cannot deploy functions

### ISSUE THREAD

**Issue by rnh8wb** [firebase/firebase-functions#313]
**firebase-functions:** 2.0.5

**firebase-tools:** 4.2.1

**firebase-admin:** 6.0.0

**node**: 6.11.5

**npm**: 6.4.1

I've been trying for a week to get everything in order but I'm completely lost. All of my functions were previously deployed and working fine, but not anymore. When I try to deploy, none of the functions deploy properly, each giving this same error: 

Deployment error.
Build failed: exit status 254
npm WARN lifecycle node@6.14.4~preinstall: cannot run in wd %s %s (wd=%s) node@6.14.4 node installArchSpecificPackage /workspace/node_modules/.staging/node-378c0d58
functions@ /workspace
+-- apn@2.2.0 
| +-- debug@3.1.0 
| | `-- ms@2.0.0 
| +-- http2@3.3.6 
| +-- jsonwebtoken@8.3.0 
| | +-- jws@3.1.5 
| | | +-- jwa@1.1.6 
| | | | +-- buffer-equal-constant-time@1.0.1 
| | | | `-- ecdsa-sig-formatter@1.0.10 
| | | `-- safe-buffer@5.1.2 
| | +-- lodash.includes@4.3.0 
| | +-- lodash.isboolean@3.0.3 
| | +-- lodash.isinteger@4.0.4 
| | +-- lodash.isnumber@3.0.3 
| | +-- lodash.isplainobject@4.0.6 
| | +-- lodash.isstring@4.0.1 
| | +-- lodash.once@4.1.1 
| | `-- ms@2.1.1 
| +-- node-forge@0.7.6 
| `-- verror@1.10.0 
|   +-- assert-plus@1.0.0 
|   +-- core-util-is@1.0.2 
|   `-- extsprintf@1.4.0 
`-- apns@0.1.0 
  `-- q@1.5.1 

npm ERR! Linux 4.4.0-133-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "--global-style" "--production" "--fetch-retries=5" "--fetch-retry-factor=2" "--fetch-retry-mintimeout=1000" "install" "/workspace"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! path /workspace/node_modules/node/bin/node
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/workspace/node_modules/node/bin/node'
npm ERR! enoent ENOENT: no such file or directory, chmod '/workspace/node_modules/node/bin/node'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log

I've tried rm -rf on the node modules (local and global), changing node versions, etc. etc. but I'm not making any headway.

**Comment by laurenzlong** [comment]
What does your package.json look like? And if you ran "npm install" locally, does it work?

**Comment by rnh8wb** [comment]
npm install works fine.

Package.json: 
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "./node_modules/.bin/eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "config": {
    "unsafe-perm": true
  },
  "dependencies": {
    "@google-cloud/logging": "^0.7.1",
    "apn": "^2.1.5",
    "apns": "^0.1.0",
    "express": "^4.16.3",
    "firebase-admin": "6.0.0",
    "firebase-tools": "^4.2.1",
    "fs": "0.0.1-security",
    "node": "^6.14.4",
    "simple-oauth2": "^1.6.0",
    "stripe": "^6.8.0",
    "firebase-functions": "2.0.5"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.8.0"
  },
  "private": true
}

**Comment by laurenzlong** [comment]
Your package.json looks fine, this may be a project-specific issue. Can you file a support ticket? https://firebase.google.com/support/contact/
