### ISSUE TITLE
Firebase Functions onCreate fires 2 or 3 times

### ISSUE THREAD

**Issue by brunoschuermans** [firebase/firebase-functions#315]
Functions from firebase are executed several times!

Related: https://github.com/firebase/firebase-functions/issues/62

Still not fixed guys :/
What a shame from Google engineers.. 
How a serious company could use this service as is!?

I know there are workaround by checking the id of the record but please fix it quickly.

Apreciated

**Comment by laurenzlong** [comment]
Thanks for your feedback! Please see my comment at https://github.com/firebase/firebase-functions/issues/62#issuecomment-419810195 

That being said, multiple firings from a single event should happen rarely, so if it is happening a lot in your project, then please file [a support ticket](https://firebase.google.com/support/contact/?category=troubleshooting) so we can look at your project specifically.

**Comment by jacobg** [comment]
It's definitely not rare. It happens a lot, even when the event handler function completes in under a second.
