### ISSUE TITLE
why can't I use async / await

### ISSUE THREAD

**Issue by npomfret** [firebase/firebase-functions#319]
If I try to use syntax like `async (req, res) => {...` in my firebase function I get the error below when deploying. I assume it's a language feature that's not supported yet?

`  
 error  Parsing error: Unexpected token =>
`

Removing the _async_ makes it go away...

However, I have a dependency in my package (ccxt) that does use the async / await syntax, and it works just fine.  Why is this?

**Comment by nathanjliu** [comment]
async/await is only supported in the Node 8 runtime, which was only recently added as a beta runtime in firebase functions.

You can use it by adding the following to your package.json.
`  "engines": {
    "node": "8"
  },`

**Comment by andrewspy** [comment]
I have similar issue with the following typescript code, targeting `es2017` and Node 8 runtime.

`index.ts`:-
```typescript
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';

admin.initializeApp();

export const someFunctionA = functions.database.ref('/sample')
  .onWrite(async (change, context) => {
    console.log(change, context);
    
    return 0;
  }
);
```

`tsconfig.json`:-
```json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "outDir": "lib",
    "sourceMap": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

`package.json`-
```json
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.3"
  },
  "devDependencies": {
    "tslint": "~5.8.0",
    "typescript": "~2.8.3"
  },
  "private": true
}
```

### Actual Result

```
!  functions[someFunctionA]: Deployment error.
Function load error: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/lib/index.js:7
    .onWrite(async (change, context) => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:391:24)
```

**Comment by andrewspy** [comment]
Just noticed that my firebase-tools was not updated to v4.0. Everything works fine now after updating firebase-tools to latest version.

**Comment by thechenky** [comment]
@npomfret closing this out as it seems like others have resolved this issue, but feel free to open another bug if you're still having problems.

**Comment by stamler** [comment]
If anybody else is continuing to receive this issue _after_ doing the updates, make sure that `"ecmaVersion": 8` is set in your .eslintrc.json as well.

**Comment by kiralikbeyin** [comment]
If anybody else is continuing to receive this issue _after_ doing everything, make sure that you are using node v8 in your computer :)

nvm ls

**Comment by bashizip** [comment]
This should be well documented in the official doc !!

**Comment by justinh00k** [comment]
Yep, fixed it for me and never would have found it on my own!

**Comment by bashizip** [comment]
Firebase functions just don't work!,

**Comment by kireerik** [comment]
@thechenky I think we should open this issue, because https://github.com/firebase/firebase-functions/issues/319#issuecomment-454063550 is only a workaround.

**Comment by viveky259259** [comment]
Update ecmaVersion to 8 like this in file .eslintrc.js

module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
   parserOptions: {
    "ecmaVersion": 8,
    "sourceType": "module"
  },
  extends: [
    "eslint:recommended",
    "google",
  ],
  rules: {
    quotes: ["error", "double"],
  },
};

**Comment by aatmansp** [comment]
There is a typo in function's package.json.
Given: 
"scripts": {
    "lint": "eslint .",
    ...
}

But it should be:
"scripts": {
    "lint": "eslint",
    ...
}

Note: "..." represents other scripts.

**Comment by iboxgithub** [comment]
aligned with @aatmansp, also described here: 
https://stackoverflow.com/questions/53735009/including-async-function-within-firebase-cloud-functions-eslint-parsing-error

**Comment by luiscarreramv** [comment]
This is the solution:

module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "google",
  ],
  rules: {
    quotes: ["error", "double"],
  },
  
  // Newly added property
  parserOptions: {
    "ecmaVersion": 2020,
  },
};
