### ISSUE TITLE
How can I deploy only additional code?

### ISSUE THREAD

**Issue by jormabs** [firebase/firebase-functions#324]
### Version info

**firebase-functions: 2.0.5**

**firebase-tools 4.2.1:**

**firebase-admin: 6.0.0**

Hi, how can i deploy "auxiliary function", without update "official" ones.

Let's say:

```
exports.function1 = functions.https.onCall(async (data, context) => {
 const value = getSomeData(1)
 ...
}

exports.function2 = functions.https.onCall(async (data, context) => {
 const value = getSomeData(2)
 ...
}

const getSomeData = f => {
 // I find an error here, so, i want to deploy just "getSomeData" 
 // without deploy function1 and function2
 return 'some data for function' + f 
}
```
### Expected behavior

Deploy just additional code

It's possible? Thank you

**Comment by laurenzlong** [comment]
Hi, unfortunately, this is not possible, sorry about that.
