### ISSUE TITLE
Postinstall script fails on Windows

### ISSUE THREAD

**Issue by kaleidagraph** [firebase/firebase-functions#327]
I am new to firebase and am wanting to host a page with integrations with firebase functions . Using the firebase-tools cli I have initialized the project. As then instructed I went to run `firebase deploy` which failed suggesting I run `npm install` in the functions directory.

So here I am running `npm install` in that directory which then fails:
```
npm ERR! errno 1
npm ERR! firebase-functions@2.0.5 postinstall: `node ./upgrade-warning`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebase-functions@2.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

In some of the output it says `'node' is not recognized as an internal or external command,
operable program or batch file.` which is not true as it is a path variable and works running `node` in the same command line. 

The line `This is probably not a problem with npm` as well as not finding any answers for this on the rest of the internet leads me to posting this issue here. I have the attached the complete log file at the end as well for more detailed info.

[Log File](https://github.com/firebase/firebase-functions/files/2438440/2018-10-02T14_40_58_329Z-debug.log)

**Comment by laurenzlong** [comment]
Hi, it seems like the post-install script failed (this would normally warn you about breaking changes in the update). So it's not a big deal that it failed, since it seemed like the install still was successful, are you able  to run `firebase deploy` now?

**Comment by kaleidagraph** [comment]
Nope, still getting the same error
```
Error: Error parsing triggers: Cannot find module 'firebase-functions'

Try running "npm install" in your functions directory before deploying.
```

**Comment by laurenzlong** [comment]
Could you provide more details on:
- your platform 
- result of `npm --version`
- result of `node --version`

**Comment by kaleidagraph** [comment]
```
$ npm --version
5.0.3
$ node --version
v8.11.3
```

**Comment by laurenzlong** [comment]
Thanks for the info! This is a real bug, since our postinstall script appears to be failing on Windows. For now, you can try `npm install --ignore-scripts` inside the functions folder, let me know if that works. 

I renamed this issue to track the root cause, and we will work on a fix.

**Comment by kaleidagraph** [comment]
On further investigation I have found that this bug is "only" present in bash and not in powershell. I'm not an expert on shells but it seems there is some difference between the way the cli runs in the shells.

Current Findings:

- `npm install` faults in bash *but* works within powershell
- the rest of the firebase cli commands works without fault in bash
- node.js commands are environment variables
- the node commands are present in bash

**Comment by laurenzlong** [comment]
Thanks for the update! This is insightful. Did `npm install --ignore-scripts` work in Bash?

**Comment by kaleidagraph** [comment]
On further inspection this seems to be a problem with my installation of bash and is not on the firebase end. This thread can now be closed.

**Comment by kevinajian** [comment]
Thanks for the update! Will close out.
