### ISSUE TITLE
Can not read "functions.config()" with`firebase serve`

### ISSUE THREAD

**Issue by BrentDietrich** [firebase/firebase-functions#328]
OS: macOS Sierra v10.12.6

### Version info
- firebase-tools: v4.2.1
```
"firebase-admin": "6.0.0",
"firebase-functions": "2.0.5",
```

**firebase-functions:**

### Test case

- I set the environment configs
`firebase functions:config:set mockservice.value="something"`
- I check that they were set
`firebase functions:config:get`
  - results
```
{
  "mockservice": {
    "value": "something"
  }
}
```

### Actual behavior

- When I run `firebase serve` with " functions.config()" in my code they always come up empty.

I checked both past issues ([264](https://github.com/firebase/firebase-functions/issues/264), [282](https://github.com/firebase/firebase-functions/issues/282)) and stackoverflow nobody seems to be having problems getting env configs locally.

I've deleted and re-installed node_modules, uninstalled and reinstalled firebase-tools and now I've resorted to a hacky workaround. Any help would be greatly appreciated. Thanks in advance.

**Comment by laurenzlong** [comment]
Hi, you'll need to run `firebase functions:config:get > .runtimeconfig.json` in the functions directory, see https://firebase.google.com/docs/functions/local-emulator#serve_http_functions_from_the_command_line. (You can also manually create a .runtimeconfig.json file and put in test config values) This is to prevent you from accidentally using real API keys during testing without realizing it and having unintended consequences.

**Comment by BrentDietrich** [comment]
@laurenzlong, I have been able to set and get config values from the command line using `config:set` and `config.get > .someconfig.json`. Everything I've tried has been conducted within the 'functions' folder. But, as mentioned in the "Test case" section above, I have only received an empty object in code when using `firebase serve`. Nothing I've tried has worked yet.

**Comment by laurenzlong** [comment]
The file has to be named `.runtimeconfig.json`, anything else won't work. As well, if you are on Windows Powershell, you need to run: `firebase functions:config:get | ac .runtimeconfig.json` (This is documented in https://firebase.google.com/docs/functions/local-emulator)

**Comment by alexandervlpl** [comment]
I had a similar problem when running the firebase emulator. Turns out `functions:config:get` doesn't output valid JSON. There are a bunch of wierd bytes containing "Firebase CLI" at the beginning:

$ firebase functions:config:get | hexdump -C
00000000  1b 5d 30 3b 46 69 72 65  62 61 73 65 20 43 4c 49  |.]0;Firebase CLI|
...

So parsing the resulting `.runtimeconfig.json` fails silently and my config is empty. Should make another issue for this.

**Comment by alexandervlpl** [comment]
Ah, here's the issue:
https://github.com/firebase/firebase-tools/issues/1774
