### ISSUE TITLE
Unable to run Typescript project after creating it

### ISSUE THREAD

**Issue by briantq** [firebase/firebase-functions#330]
### Version info

**firebase-functions:** 2.0.5

**firebase-tools:** 5.0.0

**firebase-admin:** 6.0.0

OS: Windows 10

### Test case

Create a new Functions project and serve it

### Steps to reproduce

`firebase init functions`
`firebase serve`

Below is the output I get when trying to run a project after creating it

I found a couple other people with similar issues on this repo and have tried a variety of different things:

- Creating the project multiple times
- Going into the functions directory and running `npm install`

### Were you able to successfully deploy your functions?

Didn't get there yet

### Expected behavior

I should be able to run the project I just created

### Actual behavior

`C:\dev\njs-gigday-fbcf>firebase init functions

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\dev\njs-gigday-fbcf

Before we get started, keep in mind:

  * You are currently outside your home directory

? Are you ready to proceed? Yes

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Select a default Firebase project for this directory: XXX-XXX (XXX-XXX)

=== Functions Setup

A functions directory will be created in your project with a Node.js
package pre-configured. Functions can be deployed with firebase deploy.

? What language would you like to use to write Cloud Functions? TypeScript
? Do you want to use TSLint to catch probable bugs and enforce style? Yes
+  Wrote functions/package.json
+  Wrote functions/tslint.json
+  Wrote functions/tsconfig.json
+  Wrote functions/src/index.ts
? Do you want to install dependencies with npm now? Yes

> grpc@1.15.1 install C:\dev\njs-gigday-fbcf\functions\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\dev\njs-gigday-fbcf\functions\node_modules\grpc\src\node\extension_binary\node-v48-win32-x64-unknown\grpc_node.node" is installed via remote

> protobufjs@6.8.8 postinstall C:\dev\njs-gigday-fbcf\functions\node_modules\protobufjs
> node scripts/postinstall

> firebase-functions@2.0.5 postinstall C:\dev\njs-gigday-fbcf\functions\node_modules\firebase-functions
> node ./upgrade-warning

======== WARNING! ========

This upgrade of firebase-functions contains breaking changes if you are upgrading from a version below v1.0.0.

To see a complete list of these breaking changes, please go to:

https://firebase.google.com/docs/functions/beta-v1-diff

functions@ C:\dev\njs-gigday-fbcf\functions
+-- firebase-admin@6.0.0
| +-- @firebase/app@0.3.4
| | +-- @firebase/app-types@0.3.2
| | +-- @firebase/util@0.2.2
| | +-- dom-storage@2.1.0
| | `-- xmlhttprequest@1.8.0
| +-- @firebase/database@0.3.6
| | +-- @firebase/database-types@0.3.2
| | +-- @firebase/logger@0.1.1
| | `-- faye-websocket@0.11.1
| |   `-- websocket-driver@0.7.0
| |     +-- http-parser-js@0.4.13
| |     `-- websocket-extensions@0.1.3
| +-- @google-cloud/firestore@0.16.1
| | +-- @google-cloud/projectify@0.3.0
| | +-- bun@0.0.12
| | | `-- readable-stream@1.0.34
| | |   +-- core-util-is@1.0.2
| | |   +-- isarray@0.0.1
| | |   `-- string_decoder@0.10.31
| | +-- deep-equal@1.0.1
| | +-- extend@3.0.2
| | +-- functional-red-black-tree@1.0.1
| | +-- google-gax@0.18.0
| | | +-- @grpc/proto-loader@0.3.0
| | | | `-- @types/node@9.6.34
| | | +-- globby@8.0.1
| | | | +-- array-union@1.0.2
| | | | +-- dir-glob@2.0.0
| | | | | `-- path-type@3.0.0
| | | | +-- fast-glob@2.2.3
| | | | | +-- @mrmlnc/readdir-enhanced@2.2.1
| | | | | | +-- call-me-maybe@1.0.1
| | | | | | `-- glob-to-regexp@0.3.0
| | | | | +-- @nodelib/fs.stat@1.1.2
| | | | | +-- glob-parent@3.1.0
| | | | | | +-- is-glob@3.1.0
| | | | | | `-- path-dirname@1.0.2
| | | | | +-- is-glob@4.0.0
| | | | | | `-- is-extglob@2.1.1
| | | | | +-- merge2@1.2.2
| | | | | `-- micromatch@3.1.10
| | | | |   +-- arr-diff@4.0.0
| | | | |   +-- array-unique@0.3.2
| | | | |   +-- braces@2.3.2
| | | | |   | +-- arr-flatten@1.1.0
| | | | |   | +-- extend-shallow@2.0.1
| | | | |   | | `-- is-extendable@0.1.1
| | | | |   | +-- fill-range@4.0.0
| | | | |   | | +-- extend-shallow@2.0.1
| | | | |   | | +-- is-number@3.0.0
| | | | |   | | | `-- kind-of@3.2.2
| | | | |   | | +-- repeat-string@1.6.1
| | | | |   | | `-- to-regex-range@2.1.1
| | | | |   | +-- isobject@3.0.1
| | | | |   | +-- repeat-element@1.1.3
| | | | |   | +-- snapdragon-node@2.1.1
| | | | |   | | +-- define-property@1.0.0
| | | | |   | | | `-- is-descriptor@1.0.2
| | | | |   | | |   +-- is-accessor-descriptor@1.0.0
| | | | |   | | |   `-- is-data-descriptor@1.0.0
| | | | |   | | `-- snapdragon-util@3.0.1
| | | | |   | |   `-- kind-of@3.2.2
| | | | |   | `-- split-string@3.1.0
| | | | |   +-- define-property@2.0.2
| | | | |   | `-- is-descriptor@1.0.2
| | | | |   |   +-- is-accessor-descriptor@1.0.0
| | | | |   |   `-- is-data-descriptor@1.0.0
| | | | |   +-- extend-shallow@3.0.2
| | | | |   | +-- assign-symbols@1.0.0
| | | | |   | `-- is-extendable@1.0.1
| | | | |   |   `-- is-plain-object@2.0.4
| | | | |   +-- extglob@2.0.4
| | | | |   | +-- define-property@1.0.0
| | | | |   | | `-- is-descriptor@1.0.2
| | | | |   | |   +-- is-accessor-descriptor@1.0.0
| | | | |   | |   `-- is-data-descriptor@1.0.0
| | | | |   | +-- expand-brackets@2.1.4
| | | | |   | | +-- define-property@0.2.5
| | | | |   | | +-- extend-shallow@2.0.1
| | | | |   | | `-- posix-character-classes@0.1.1
| | | | |   | `-- extend-shallow@2.0.1
| | | | |   +-- fragment-cache@0.2.1
| | | | |   | `-- map-cache@0.2.2
| | | | |   +-- kind-of@6.0.2
| | | | |   +-- nanomatch@1.2.13
| | | | |   | `-- is-windows@1.0.2
| | | | |   +-- object.pick@1.3.0
| | | | |   +-- regex-not@1.0.2
| | | | |   | `-- safe-regex@1.1.0
| | | | |   |   `-- ret@0.1.15
| | | | |   +-- snapdragon@0.8.2
| | | | |   | +-- base@0.11.2
| | | | |   | | +-- cache-base@1.0.1
| | | | |   | | | +-- collection-visit@1.0.0
| | | | |   | | | | +-- map-visit@1.0.0
| | | | |   | | | | `-- object-visit@1.0.1
| | | | |   | | | +-- get-value@2.0.6
| | | | |   | | | +-- has-value@1.0.0
| | | | |   | | | | `-- has-values@1.0.0
| | | | |   | | | |   `-- kind-of@4.0.0
| | | | |   | | | +-- set-value@2.0.0
| | | | |   | | | | `-- extend-shallow@2.0.1
| | | | |   | | | +-- to-object-path@0.3.0
| | | | |   | | | | `-- kind-of@3.2.2
| | | | |   | | | +-- union-value@1.0.0
| | | | |   | | | | `-- set-value@0.4.3
| | | | |   | | | |   `-- extend-shallow@2.0.1
| | | | |   | | | `-- unset-value@1.0.0
| | | | |   | | |   `-- has-value@0.3.1
| | | | |   | | |     +-- has-values@0.1.4
| | | | |   | | |     `-- isobject@2.1.0
| | | | |   | | |       `-- isarray@1.0.0
| | | | |   | | +-- class-utils@0.3.6
| | | | |   | | | +-- arr-union@3.1.0
| | | | |   | | | +-- define-property@0.2.5
| | | | |   | | | `-- static-extend@0.1.2
| | | | |   | | |   +-- define-property@0.2.5
| | | | |   | | |   `-- object-copy@0.1.0
| | | | |   | | |     +-- copy-descriptor@0.1.1
| | | | |   | | |     +-- define-property@0.2.5
| | | | |   | | |     `-- kind-of@3.2.2
| | | | |   | | +-- component-emitter@1.2.1
| | | | |   | | +-- define-property@1.0.0
| | | | |   | | | `-- is-descriptor@1.0.2
| | | | |   | | |   +-- is-accessor-descriptor@1.0.0
| | | | |   | | |   `-- is-data-descriptor@1.0.0
| | | | |   | | +-- mixin-deep@1.3.1
| | | | |   | | | +-- for-in@1.0.2
| | | | |   | | | `-- is-extendable@1.0.1
| | | | |   | | `-- pascalcase@0.1.1
| | | | |   | +-- define-property@0.2.5
| | | | |   | | `-- is-descriptor@0.1.6
| | | | |   | |   +-- is-accessor-descriptor@0.1.6
| | | | |   | |   | `-- kind-of@3.2.2
| | | | |   | |   +-- is-data-descriptor@0.1.4
| | | | |   | |   | `-- kind-of@3.2.2
| | | | |   | |   `-- kind-of@5.1.0
| | | | |   | +-- extend-shallow@2.0.1
| | | | |   | +-- source-map@0.5.7
| | | | |   | +-- source-map-resolve@0.5.2
| | | | |   | | +-- atob@2.1.2
| | | | |   | | +-- decode-uri-component@0.2.0
| | | | |   | | +-- resolve-url@0.2.1
| | | | |   | | +-- source-map-url@0.4.0
| | | | |   | | `-- urix@0.1.0
| | | | |   | `-- use@3.1.1
| | | | |   `-- to-regex@3.0.2
| | | | +-- ignore@3.3.10
| | | | +-- pify@3.0.0
| | | | `-- slash@1.0.0
| | | +-- google-auth-library@1.6.1
| | | | +-- axios@0.18.0
| | | | | +-- follow-redirects@1.5.8
| | | | | | `-- debug@3.1.0
| | | | | `-- is-buffer@1.1.6
| | | | +-- gcp-metadata@0.6.3
| | | | +-- gtoken@2.3.0
| | | | | `-- google-p12-pem@1.0.2
| | | | +-- lru-cache@4.1.3
| | | | | +-- pseudomap@1.0.2
| | | | | `-- yallist@2.1.2
| | | | `-- retry-axios@0.3.2
| | | +-- grpc@1.15.1
| | | | +-- nan@2.11.1
| | | | +-- node-pre-gyp@0.10.3
| | | | | +-- detect-libc@1.0.3
| | | | | +-- mkdirp@0.5.1
| | | | | | `-- minimist@0.0.8
| | | | | +-- needle@2.2.2
| | | | | | +-- debug@2.6.9
| | | | | | | `-- ms@2.0.0
| | | | | | +-- iconv-lite@0.4.23
| | | | | | | `-- safer-buffer@2.1.2
| | | | | | `-- sax@1.2.4
| | | | | +-- nopt@4.0.1
| | | | | | +-- abbrev@1.1.1
| | | | | | `-- osenv@0.1.5
| | | | | |   +-- os-homedir@1.0.2
| | | | | |   `-- os-tmpdir@1.0.2
| | | | | +-- npm-packlist@1.1.11
| | | | | | +-- ignore-walk@3.0.1
| | | | | | `-- npm-bundled@1.0.3
| | | | | +-- npmlog@4.1.2
| | | | | | +-- are-we-there-yet@1.1.5
| | | | | | | +-- delegates@1.0.0
| | | | | | | `-- readable-stream@2.3.6
| | | | | | |   +-- core-util-is@1.0.2
| | | | | | |   +-- isarray@1.0.0
| | | | | | |   +-- process-nextick-args@2.0.0
| | | | | | |   +-- string_decoder@1.1.1
| | | | | | |   `-- util-deprecate@1.0.2
| | | | | | +-- console-control-strings@1.1.0
| | | | | | +-- gauge@2.7.4
| | | | | | | +-- aproba@1.2.0
| | | | | | | +-- has-unicode@2.0.1
| | | | | | | +-- object-assign@4.1.1
| | | | | | | +-- signal-exit@3.0.2
| | | | | | | +-- string-width@1.0.2
| | | | | | | | +-- code-point-at@1.1.0
| | | | | | | | `-- is-fullwidth-code-point@1.0.0
| | | | | | | |   `-- number-is-nan@1.0.1
| | | | | | | +-- strip-ansi@3.0.1
| | | | | | | | `-- ansi-regex@2.1.1
| | | | | | | `-- wide-align@1.1.3
| | | | | | `-- set-blocking@2.0.0
| | | | | +-- rc@1.2.8
| | | | | | +-- deep-extend@0.6.0
| | | | | | +-- ini@1.3.5
| | | | | | +-- minimist@1.2.0
| | | | | | `-- strip-json-comments@2.0.1
| | | | | +-- rimraf@2.6.2
| | | | | +-- semver@5.5.0
| | | | | `-- tar@4.4.6
| | | | |   +-- chownr@1.0.1
| | | | |   +-- fs-minipass@1.2.5
| | | | |   +-- minipass@2.3.3
| | | | |   +-- minizlib@1.1.0
| | | | |   +-- safe-buffer@5.1.2
| | | | |   `-- yallist@3.0.2
| | | | `-- protobufjs@5.0.3
| | | |   +-- ascli@1.0.1
| | | |   | +-- colour@0.7.1
| | | |   | `-- optjs@3.2.2
| | | |   +-- bytebuffer@5.0.1
| | | |   | `-- long@3.2.0
| | | |   +-- glob@7.1.2
| | | |   | +-- fs.realpath@1.0.0
| | | |   | +-- inflight@1.0.6
| | | |   | | `-- wrappy@1.0.2
| | | |   | +-- inherits@2.0.3
| | | |   | +-- minimatch@3.0.4
| | | |   | | `-- brace-expansion@1.1.11
| | | |   | |   +-- balanced-match@1.0.0
| | | |   | |   `-- concat-map@0.0.1
| | | |   | +-- once@1.4.0
| | | |   | `-- path-is-absolute@1.0.1
| | | |   `-- yargs@3.32.0
| | | |     +-- camelcase@2.1.1
| | | |     +-- cliui@3.2.0
| | | |     | `-- wrap-ansi@2.1.0
| | | |     +-- decamelize@1.2.0
| | | |     +-- os-locale@1.4.0
| | | |     | `-- lcid@1.0.0
| | | |     |   `-- invert-kv@1.0.0
| | | |     +-- string-width@1.0.2
| | | |     | +-- code-point-at@1.1.0
| | | |     | `-- is-fullwidth-code-point@1.0.0
| | | |     |   `-- number-is-nan@1.0.1
| | | |     +-- window-size@0.1.4
| | | |     `-- y18n@3.2.1
| | | +-- is-stream-ended@0.1.4
| | | `-- retry-request@4.0.0
| | +-- google-proto-files@0.16.1
| | | `-- power-assert@1.6.1
| | |   +-- define-properties@1.1.3
| | |   | `-- object-keys@1.0.12
| | |   +-- empower@1.3.1
| | |   | +-- core-js@2.5.7
| | |   | `-- empower-core@1.2.0
| | |   |   `-- call-signature@0.0.2
| | |   +-- power-assert-formatter@1.4.1
| | |   | +-- power-assert-context-formatter@1.2.0
| | |   | | `-- power-assert-context-traversal@1.2.0
| | |   | +-- power-assert-context-reducer-ast@1.2.0
| | |   | | +-- acorn@5.7.3
| | |   | | +-- acorn-es7-plugin@1.1.7
| | |   | | +-- espurify@1.8.1
| | |   | | `-- estraverse@4.2.0
| | |   | +-- power-assert-renderer-assertion@1.2.0
| | |   | | +-- power-assert-renderer-base@1.1.1
| | |   | | `-- power-assert-util-string-width@1.2.0
| | |   | |   `-- eastasianwidth@0.2.0
| | |   | +-- power-assert-renderer-comparison@1.2.0
| | |   | | +-- diff-match-patch@1.0.4
| | |   | | +-- stringifier@1.4.0
| | |   | | | `-- traverse@0.6.6
| | |   | | `-- type-name@2.0.2
| | |   | +-- power-assert-renderer-diagram@1.2.0
| | |   | `-- power-assert-renderer-file@1.2.0
| | |   `-- universal-deep-strict-equal@1.2.2
| | |     +-- array-filter@1.0.0
| | |     `-- indexof@0.0.1
| | +-- is@3.2.1
| | +-- lodash.merge@4.6.1
| | +-- protobufjs@6.8.8
| | | +-- @protobufjs/aspromise@1.1.2
| | | +-- @protobufjs/base64@1.1.2
| | | +-- @protobufjs/codegen@2.0.4
| | | +-- @protobufjs/eventemitter@1.1.0
| | | +-- @protobufjs/fetch@1.1.0
| | | +-- @protobufjs/float@1.0.2
| | | +-- @protobufjs/inquire@1.1.0
| | | +-- @protobufjs/path@1.1.2
| | | +-- @protobufjs/pool@1.1.0
| | | +-- @protobufjs/utf8@1.1.0
| | | +-- @types/long@4.0.0
| | | +-- @types/node@10.11.4
| | | `-- long@4.0.0
| | `-- through2@2.0.3
| |   `-- readable-stream@2.3.6
| |     +-- isarray@1.0.0
| |     +-- process-nextick-args@2.0.0
| |     +-- string_decoder@1.1.1
| |     `-- util-deprecate@1.0.2
| +-- @google-cloud/storage@1.7.0
| | +-- @google-cloud/common@0.17.0
| | | +-- array-uniq@1.0.3
| | | +-- ent@2.2.0
| | | +-- google-auto-auth@0.10.1
| | | +-- log-driver@1.2.7
| | | +-- methmeth@1.1.0
| | | +-- modelo@4.2.3
| | | +-- retry-request@3.3.2
| | | +-- split-array-stream@1.0.3
| | | `-- string-format-obj@1.1.1
| | +-- arrify@1.0.1
| | +-- async@2.6.1
| | +-- compressible@2.0.15
| | | `-- mime-db@1.36.0
| | +-- concat-stream@1.6.2
| | | +-- buffer-from@1.1.1
| | | +-- readable-stream@2.3.6
| | | | +-- isarray@1.0.0
| | | | `-- string_decoder@1.1.1
| | | `-- typedarray@0.0.6
| | +-- create-error-class@3.0.2
| | | `-- capture-stack-trace@1.0.1
| | +-- duplexify@3.6.0
| | | +-- end-of-stream@1.4.1
| | | +-- readable-stream@2.3.6
| | | | +-- isarray@1.0.0
| | | | `-- string_decoder@1.1.1
| | | `-- stream-shift@1.0.0
| | +-- gcs-resumable-upload@0.10.2
| | | `-- configstore@3.1.2
| | |   +-- dot-prop@4.2.0
| | |   | `-- is-obj@1.0.1
| | |   +-- graceful-fs@4.1.11
| | |   +-- make-dir@1.3.0
| | |   +-- unique-string@1.0.0
| | |   | `-- crypto-random-string@1.0.0
| | |   `-- write-file-atomic@2.3.0
| | |     +-- imurmurhash@0.1.4
| | |     `-- signal-exit@3.0.2
| | +-- hash-stream-validation@0.2.1
| | +-- mime@2.3.1
| | +-- mime-types@2.1.20
| | +-- once@1.4.0
| | | `-- wrappy@1.0.2
| | +-- pumpify@1.5.1
| | | `-- pump@2.0.1
| | +-- request@2.88.0
| | | +-- aws-sign2@0.7.0
| | | +-- aws4@1.8.0
| | | +-- caseless@0.12.0
| | | +-- combined-stream@1.0.7
| | | | `-- delayed-stream@1.0.0
| | | +-- forever-agent@0.6.1
| | | +-- form-data@2.3.2
| | | | +-- asynckit@0.4.0
| | | | `-- combined-stream@1.0.6
| | | +-- har-validator@5.1.0
| | | | +-- ajv@5.5.2
| | | | | +-- co@4.6.0
| | | | | +-- fast-deep-equal@1.1.0
| | | | | +-- fast-json-stable-stringify@2.0.0
| | | | | `-- json-schema-traverse@0.3.1
| | | | `-- har-schema@2.0.0
| | | +-- http-signature@1.2.0
| | | | +-- assert-plus@1.0.0
| | | | +-- jsprim@1.4.1
| | | | | +-- extsprintf@1.3.0
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.10.0
| | | | `-- sshpk@1.14.2
| | | |   +-- asn1@0.2.4
| | | |   +-- bcrypt-pbkdf@1.0.2
| | | |   +-- dashdash@1.14.1
| | | |   +-- ecc-jsbn@0.1.2
| | | |   +-- getpass@0.1.7
| | | |   +-- jsbn@0.1.1
| | | |   +-- safer-buffer@2.1.2
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- oauth-sign@0.9.0
| | | +-- performance-now@2.1.0
| | | +-- qs@6.5.2
| | | +-- tough-cookie@2.4.3
| | | | +-- psl@1.1.29
| | | | `-- punycode@1.4.1
| | | +-- tunnel-agent@0.6.0
| | | `-- uuid@3.3.2
| | +-- safe-buffer@5.1.2
| | +-- snakeize@0.1.0
| | +-- stream-events@1.0.4
| | | `-- stubs@3.0.0
| | `-- xdg-basedir@3.0.0
| +-- @types/google-cloud__storage@1.7.2
| | `-- @types/request@2.47.1
| |   +-- @types/caseless@0.12.1
| |   +-- @types/form-data@2.2.1
| |   `-- @types/tough-cookie@2.3.3
| +-- @types/node@8.10.34
| +-- jsonwebtoken@8.1.0
| | +-- jws@3.1.5
| | | `-- jwa@1.1.6
| | |   +-- buffer-equal-constant-time@1.0.1
| | |   `-- ecdsa-sig-formatter@1.0.10
| | +-- lodash.includes@4.3.0
| | +-- lodash.isboolean@3.0.3
| | +-- lodash.isinteger@4.0.4
| | +-- lodash.isnumber@3.0.3
| | +-- lodash.isplainobject@4.0.6
| | +-- lodash.isstring@4.0.1
| | +-- lodash.once@4.1.1
| | +-- ms@2.0.0
| | `-- xtend@4.0.1
| `-- node-forge@0.7.4
+-- firebase-functions@2.0.5
| +-- @types/cors@2.8.4
| +-- @types/express@4.16.0
| | +-- @types/body-parser@1.17.0
| | | `-- @types/connect@3.4.32
| | +-- @types/express-serve-static-core@4.16.0
| | | +-- @types/events@1.2.0
| | | `-- @types/range-parser@1.2.2
| | `-- @types/serve-static@1.13.2
| |   `-- @types/mime@2.0.0
| +-- @types/jsonwebtoken@7.2.8
| +-- @types/lodash@4.14.116
| +-- cors@2.8.4
| | +-- object-assign@4.1.1
| | `-- vary@1.1.2
| +-- express@4.16.3
| | +-- accepts@1.3.5
| | | `-- negotiator@0.6.1
| | +-- array-flatten@1.1.1
| | +-- body-parser@1.18.2
| | | +-- bytes@3.0.0
| | | +-- http-errors@1.6.3
| | | +-- iconv-lite@0.4.19
| | | +-- qs@6.5.1
| | | `-- raw-body@2.3.2
| | |   `-- http-errors@1.6.2
| | |     +-- depd@1.1.1
| | |     `-- setprototypeof@1.0.3
| | +-- content-disposition@0.5.2
| | +-- content-type@1.0.4
| | +-- cookie@0.3.1
| | +-- cookie-signature@1.0.6
| | +-- debug@2.6.9
| | +-- depd@1.1.2
| | +-- encodeurl@1.0.2
| | +-- escape-html@1.0.3
| | +-- etag@1.8.1
| | +-- finalhandler@1.1.1
| | | `-- unpipe@1.0.0
| | +-- fresh@0.5.2
| | +-- merge-descriptors@1.0.1
| | +-- methods@1.1.2
| | +-- on-finished@2.3.0
| | | `-- ee-first@1.1.1
| | +-- parseurl@1.3.2
| | +-- path-to-regexp@0.1.7
| | +-- proxy-addr@2.0.4
| | | +-- forwarded@0.1.2
| | | `-- ipaddr.js@1.8.0
| | +-- qs@6.5.1
| | +-- range-parser@1.2.0
| | +-- safe-buffer@5.1.1
| | +-- send@0.16.2
| | | +-- destroy@1.0.4
| | | `-- mime@1.4.1
| | +-- serve-static@1.13.2
| | +-- setprototypeof@1.1.0
| | +-- statuses@1.4.0
| | +-- type-is@1.6.16
| | | `-- media-typer@0.3.0
| | `-- utils-merge@1.0.1
| +-- jsonwebtoken@8.3.0
| | `-- ms@2.1.1
| `-- lodash@4.17.11
+-- tslint@5.8.0
| +-- babel-code-frame@6.26.0
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- has-ansi@2.0.0
| | | | `-- ansi-regex@2.1.1
| | | +-- strip-ansi@3.0.1
| | | `-- supports-color@2.0.0
| | +-- esutils@2.0.2
| | `-- js-tokens@3.0.2
| +-- builtin-modules@1.1.1
| +-- chalk@2.4.1
| | +-- ansi-styles@3.2.1
| | | `-- color-convert@1.9.3
| | |   `-- color-name@1.1.3
| | +-- escape-string-regexp@1.0.5
| | `-- supports-color@5.5.0
| |   `-- has-flag@3.0.0
| +-- commander@2.18.0
| +-- diff@3.5.0
| +-- glob@7.1.3
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | +-- inherits@2.0.3
| | `-- path-is-absolute@1.0.1
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- resolve@1.8.1
| | `-- path-parse@1.0.6
| +-- semver@5.5.1
| +-- tslib@1.9.0
| `-- tsutils@2.29.0
`-- typescript@2.8.4

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

C:\dev\njs-gigday-fbcf>firebase serve

=== Serving from 'C:\dev\njs-gigday-fbcf'...

i  functions: Preparing to emulate functions.
!  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
!  functions: Error from emulator. Error parsing triggers: Cannot find module 'C:\dev\njs-gigday-fbcf\functions'

Try running "npm install" in your functions directory before deploying.`

**Comment by briantq** [comment]
I tried creating a JS based project and that was able to run fine.  Seems like this might be related to creating a Typescript project.

**Comment by laurenzlong** [comment]
@briantq Does `'C:\dev\njs-gigday-fbcf\functions'` have a `package.json`? If it does, does it have a `main` field? And what's in that field?

**Comment by briantq** [comment]
@laurenzlong The file does exist along with the field you referenced.  I figured I would post the entire thing in case it gave more clues.

`{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.3"
  },
  "devDependencies": {
    "tslint": "~5.8.0",
    "typescript": "~2.8.3"
  },
  "private": true
}
`

Also, is there a node version that is required for the firebase-tool?  I ask because I believe I was using 6.X as Google Cloud Functions requires 6.X.  I was wondering if the min version for firebase might be higher and that could be the issue.

**Comment by laurenzlong** [comment]
Did you run `npm run build` prior to running `firebase serve`? (Since it's TypeScript, you'll have to compile your code first, otherwise `lib/index.js` will not exist or will not be up to date). For convenience, you can also run `npm run serve` inside the functions directory, and it will do both.

**Comment by briantq** [comment]
I did not, but if I run that in the functions directory that does appear to resolve the issue.  Did I miss that step in the documentation?  I believe I was going off this site and didn't see it https://firebase.google.com/docs/functions/typescript

**Comment by laurenzlong** [comment]
It's not unique to Firebase, all TypeScript code needs to be compiled first to JavaScript. But I've filed an internal documentation bug to make that more clear in our documentation, for new TypeScript users. Thanks for the recommendation!

**Comment by briantq** [comment]
@laurenzlong Thanks for the help and for updating the documentation.  You might also consider doing the compilation as part of the serve command in Firebase.  I love Typescript and have been using it on Angular projects for years.  The serve command for the Angular CLI automatically compiles the JS before serving the content.  Taking that approach would eliminate confusion and greatly reduce the configuration for developers trying to leverage Typescript to script around the CLI to run Typescript then the FB CLI.

**Comment by laurenzlong** [comment]
Thanks! We've added this as a feature request to our backlog. In the meanwhile, you can simulate the effect by running `tsc watch` in a separate terminal while running the emulator. But this approach does have limitations in Linux (see https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/207)
