### ISSUE TITLE
Firebase deploy should list deployed functions in a consistent (alphabetical order)

### ISSUE THREAD

**Issue by joelgetaction** [firebase/firebase-functions#334]
### Version info

**firebase-functions:**
2.0.5

**firebase-tools:**
5.0.0

**firebase-admin:**
5.12.1

### Test case

`firebase deploy --only functions`

### Steps to reproduce

`firebase deploy --only functions`

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

Firebase deploy when it's listing functions deployed, should do so in a consistent (preferably alphabetical order).

### Actual behavior

Functions are listed in random order and the order varies from one deploy to the next.

Why do we need this?  See https://github.com/firebase/firebase-functions/issues/333 .  The problem is that we have 45 functions, say `function1,...,function45`.  So when we deploy them the first time, we see lines like:
```
✔  functions[function27(us-central1)]: Successful update operation.
✔  functions[function1(us-central1)]: Successful update operation.
✔  functions[function16(us-central1)]: Successful update operation.
✔  functions[function33(us-central1)]: Successful update operation.
...
✔  functions[function45(us-central1)]: Successful update operation.
```
At least one of them fails in the deploy above.

Now, we go and deploy a second time (because a function failed last time) and we see output like:
```
✔  functions[function45(us-central1)]: Successful update operation.
✔  functions[function1(us-central1)]: Successful update operation.
✔  functions[function33(us-central1)]: Successful update operation.
✔  functions[function16(us-central1)]: Successful update operation.
...
✔  functions[function27(us-central1)]: Successful update operation.
```
Notice how the functions are listed in a totally different order from the first example?  This makes it very difficult to visually cross-reference the two lists of functions and see which functions failed between the two deploys or to verify if functions that failed in the first deploy did actually succeed in the second deploy.  It's hard to verify because a function listed at one spot in the first list can be at a totally different spot in the second list.

It seems like you could sort by function name and deploy in that order.  Even if you're deploying async, you could sort the final list showing successes/failures for display.

I'm filing this as a bug because along with https://github.com/firebase/firebase-functions/issues/333 it makes firebase deploys very unreliable and frustrating and that is definitely a bug in the user experience.

Thanks!

**Comment by mbleigh** [comment]
Thanks for the feedback -- functions are deployed in parallel, and their results are printed in the order completed. This generally seems like the correct thing to me, since otherwise we would need to hold back on providing useful output until all functions were done deploying.

Would a reasonable solution to this problem be to print (for a second time) all functions that failed to deploy as a last step before exiting the command? That way, they wouldn't be lost in the shuffle.

**Comment by joelgetaction** [comment]
Hi @mbleigh thanks for responding.  Yes, I think if you printed (in alphabetical order) all the functions that failed to deploy as a last step before exiting that would work!  As a bonus, could you print something like the following:
```
We're sorry but the following functions failed to deploy:

functionA
functionC
functionD
functionG

If you'd like to deploy those functions now please use the following command:

firebase deploy --only functions:functionA,functions:functionC,functions:functionD,functions:functionG
```
In other words, list the actual command to redeploy just the failed functions so that I can copy and paste it into the terminal and hit enter instead of having to type out the command myself.  That would be really convenient for users and make us feel less sad about the functions failing to deploy ... :-)

Would that be possible?

**Comment by kevinajian** [comment]
We've added the failed function retry in https://github.com/firebase/firebase-tools/pull/1005. Hope that will help address your issue.
