### ISSUE TITLE
CF error: "the gm/convert binaries can't be found"

### ISSUE THREAD

**Issue by mrnagydavid** [firebase/firebase-functions#337]
### Version info

**firebase-functions:** 2.0.5

**firebase-tools:** 4.2.1

**firebase-admin:** 6.0.0

### Test case

I use Imagick to scale images and to check their dimensions. Everything worked okay until yesterday, when CF started throwing errors when running Imagick commands using the npm module `gm`.

### Steps to reproduce

Use Imagick in code. The code deploys successfully. But after some deploys the imagick cannot be used, and after some deploys, it can be.

```typescript
const im = gm.subClass({ imageMagick: true });
// ...
im(tmpFilePath).identify('%w', (err, result) => {
// ...
})
// ...
im(tmpFilePath).scale(size, 0).write(targetFileName, err => {
// ...
})
// ...
```

### Were you able to successfully deploy your functions?

Yes. No errors during deploy.

### Expected behavior

Imagick binary is available. NPM module `gm` can be used. Just like two days ago.

### Actual behavior

Using `gm` the following error occurs

```
Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%w" "/tmp/photo_1540550839532" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/srv/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Sometimes, after redeploy (with no change to the code whatsoever) it works, until there is a new deploy that brakes it. There is no way to tell if the deploy will have this problem without actually running the code.

**Comment by thechenky** [comment]
Hi @mrnagydavid, thanks for your feedback! Can you check that you're using the latest imagemagick and graphicsmagick packages? See comment here: https://github.com/aheckmann/gm/issues/455#issuecomment-426593315. 

Additionally, make sure to use the latest version of firebase-tools.

**Comment by mrnagydavid** [comment]
I upgraded the firebase-tools to 6.0.0.
The `gm` package has already been up to date (@1.23.1).

I redeployed 3 times with `firebase deploy --only functions`. The gm package worked fine after each deploy.

I was/am also using Bitbucket CI. I reran the pipeline too, and it worked fine after that, too. (Not suprisingly.)

The Bitbucket CI is/was always pulling the latest firebase-tools, so the version of the local firebase-tools package couldn't have been the issue in my opinion. Maybe it had something to do with the 6.0.0 version release 3 days ago, or maybe the Google Engineers fixed some mistakes during the weekend.

Thanks for the help anyway. I will comment if this problem reappears, otherwise the ticket will be closed after some inactivity I suppose.

**Comment by thechenky** [comment]
@mrnagydavid thanks for the update! Glad things are working now. I'm going to close this out, but please open another issue if you encounter this problem again.

**Comment by Flucadetena** [comment]
Hi I'm running into the same issue. I've updated everything and theres now way I can solve the problem.

My dependencies:
```
"dependencies": {
    "@google-cloud/vision": "^2.1.2",
    "@sendgrid/mail": "^7.3.0",
    "@types/cors": "^2.8.8",
    "@types/gm": "^1.18.9",
    "@types/express": "4.17.7",
    "axios": "^0.21.0",
    "cors": "^2.8.5",
    "firebase-admin": "^9.3.0",
    "firebase-functions": "^3.11.0",
    "gm": "^1.23.1",
    "log4js": "^6.3.0"
  },
  "devDependencies": {
    "@types/node": "^14.14.2",
    "firebase-functions-test": "^0.2.2",
    "tslint": "^6.1.3",
    "typescript": "^4.0.3"
  }, 
```
The error:

```
Error treating the img and resizing: Error: Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-quality" "50" "/tmp/original.jpg" "-fill" "rgb(247,247,247)" "-fuzz" "5%" "-opaque" "rgb(255,255,255)" "-resize" "1000x^" "+profile" "\"*\"" "+comment" "/tmp/1000.webp" this most likely means the gm/convert binaries can't be found
```

In local works perfectly. Thanks

**Comment by Jbz797** [comment]
Same : 
```
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-density" "100x100" "-quality" "75" "-[0]" "-resize" "600x600!" "-compress" "jpeg" "./images/untitled.1.jpg" this most likely means the gm/convert binaries can't be found
```

**Comment by Flucadetena** [comment]
Hey @Jbz797 I did find the errors in my case. I opened two new issues that may help you.

[Import gm with ES6](https://github.com/firebase/firebase-functions/issues/806)
&
[Use .webp](https://github.com/firebase/firebase-functions/issues/805)

Hope it helps! ;)

**Comment by maranmaran** [comment]
This still isn't resolved.. ?
