### ISSUE TITLE
60 sec timeout for helloWorld function on version 2.1.0 

### ISSUE THREAD

**Issue by elebitzero** [firebase/firebase-functions#338]
### Summary

I tried to use firebase functions to my angular webapp that is hosted with firebase.   I got a prototype setup where clicking a button in my webapp would call a "sendMessage" firebase functions using the angular/fire package.   I can see in the firebase console that the "sendMessage" function is called, but it is timing out every time after 60 seconds.

I saw a Closed bug which seems to describe this exact same problem "version 2.0.0 causes timeout everywhere " ( #283 ).   Supposedly, that issue was fixed in 2.0.1.  I am using 2.1.0.   I notice in the #283, someone said they saw the problem in 2.0.5.

### Version info

 repo/package.json
  "@angular/fire": "^5.1.0",
  "firebase": "^5.5.6",
  "firebase-tools": "^6.0.0",

 repo/functions/package.json
 "firebase-admin": "~6.0.0",
 "firebase-functions": "^2.1.0"

  node v8.11.4

  The project is on Blaze (Pay as you go) account plan.

### Test case

The test case is almost the same as the hello world example, except I had to add support for CORS. Otherwise, the browser would prevent the call to the "sendMessage" function.

```
import * as functions from 'firebase-functions';

// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript
//
// export const helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });


export const sendMessage = functions.https.onRequest((request, response) => {

  if (request.method === `OPTIONS`) {
    response.set('Access-Control-Allow-Origin','myapp.firebaseapp.com')
      .set('Access-Control-Allow-Methods', 'GET, POST')
      .status(200);
    return;
  }

  console.log('Hello World!');
  
  response.send("Hello World");
});
```

### Steps to reproduce

1. Deploy above function.
2. In angular webapp hosted in firebase, use angular/fire package to call "sendMessage". (This part works).
3. Look in firebase console. 
```
9:17:04.147 PM sendMessage Function execution started
9:17:04.077 PM | outlined_flag | sendMessage | Function execution took 60003 ms, finished with status: 'timeout' | more_vert
```

### Were you able to successfully deploy your functions?

YES.  

### Expected behavior

Function should run, print "Hello World!" in log, and return "Hello World!" response back to the UI.

### Actual behavior

See above.

**Comment by elebitzero** [comment]
I found my problem was I did not chain .send() at the end of the OPTIONS response.
```
 if (request.method === `OPTIONS`) {
    response.set('Access-Control-Allow-Origin','myapp.firebaseapp.com')
      .set('Access-Control-Allow-Methods', 'GET, POST')
      .status(200)***.send();****;
    return;
  }
```

So, you can chalk this up to user-error.   But I do think the documentation could be improved.
The http firebase functions doc page tells you to use express's cors module to handle the cors requests. (See https://firebase.google.com/docs/functions/http-events)   But I am not using express, so that is not a good suggestion.  It would be better if you showed an example of how to do it without using 3rd party modules.   Because I am not using express, I googled for an alternative solution, and that is where I went wrong.

Compare the above doc page to the Google Compute Functions page which has a much better example.  I don't think I would have made the error if I had followed the example of this page:
See https://cloud.google.com/functions/docs/writing/http

Please consider updating the documentation.

Also, the  https://firebase.google.com/docs/functions/http-events documentation page should also contain the same warning that is on https://firebase.google.com/docs/functions/terminate-functions that:

> It's important to manage the lifecycle of a function to ensure that it resolves properly. By terminating functions correctly, you can avoid excessive charges from functions that run for too long or loop infinitely...Terminate HTTP functions with res.redirect(), res.send(), or res.end().

The above warning is definitely worthy of being repeated, because it is not obvious.  I would have thought returning from a function should automatically do a send() for you.

Thanks.

**Comment by thechenky** [comment]
Hi @elebitzero thank you for your feedback. I'm glad you were able to get your issue resolved. I have noted your documentation suggestions in our internal bug tracker, thank you for taking the time to improve our product! Internal bug reference: 121128402
