### ISSUE TITLE
Handle multiple conversion event by using analytics trigger

### ISSUE THREAD

**Issue by soichisumi** [firebase/firebase-functions#339]
I want to handle many conversion events, and send it to appsflyer. But, as far as I investigated, cloud functions seems that it cannot handle multiple conversion events by one analytics trigger function.

Is there any way to handle multiple conversion events by one cloud function?

### Version info
**firebase-functions:**
2.0.5

**firebase-tools:**
5.1.1

**firebase-admin:**
6.0.0

### Expected behavior
I want to handle multiple conversion events like:
```
exports.HandleConversionEvent = firebase.functions.analytics.event(['app_open', 'event1', 'event2' .. ]).onLog(async (event, ctx) => { ... });
```

### Actual behavior
I'm using the following work around:
```
const sendEvent = require('./sendEvent');
exports.SendEvent1 = firebase.functions.analytics.event('event1').onLog(sendEvent.handleEventFunction);
exports.SendEvent2 = firebase.functions.analytics.event('event2').onLog(sendEvent.handleEventFunction);
exports.SendEvent3 = firebase.functions.analytics.event('event3').onLog(sendEvent.handleEventFunction);

// handleEventFunction : (event, ctx) => {  ...  }
```

**Comment by kevinajian** [comment]
Hi @soichisumi, we don't have any plans for having multiple events as of now, so your workaround is the intended use case. I will forward this feedback though and close this out. Thanks!
