### ISSUE TITLE
how i use multiple parameters to equalto method - node js

### ISSUE THREAD

**Issue by Thilinam93** [firebase/firebase-functions#340]
### Version info

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

**Comment by kevinajian** [comment]
Hi @Thilinam93, can you provide more feedback on your issue here?

**Comment by puf** [comment]
@Thilinam93 Please fill out all fields in the issue template. But most likely you're looking for this: http://stackoverflow.com/questions/26700924/query-based-on-multiple-where-clauses-in-firebase
