### ISSUE TITLE
@google-cloud/storage package and typescript 2 error

### ISSUE THREAD

**Issue by galki** [firebase/firebase-functions#341]
just by installing `@google-cloud/storage` and running `npm run build` i got the following error:

```
node_modules/google-auth-library/build/src/auth/oauth2client.d.ts(291,55): error TS1039: Initializers are not allowed in ambient contexts.
```
fixed by updating `typescript` (from 2 to 3) and `tslint` packages... perhaps it was just the reinstall but can we get firebase functions to initialize with typescript 3 from the start? 

_**firebase-tools version:**_ 6.0.1
**_os:_** windows 10

**Comment by LetsSupport** [comment]
I had the same issue. However, I did have typescript 3+ installed. Updating the tslint from 5.8 to 5.11 fixed the it for me.

**Comment by soyanakagawa** [comment]
I think, this issue should be closed.
