### ISSUE TITLE
Argument "data" is not a valid Document

### ISSUE THREAD

**Issue by Binghammer** [firebase/firebase-functions#344]
I am trying to write an object to the Firestore. I am getting this error: 

`Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object.`

This is a kotlin multi-platform project. I stripped out other modules for brevity. 

This is the [kotlin2Js](https://kotlinlang.org/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.html) generated code that demonstrates the issue:

```   
function FooBar(s, i, b) {
  this.s = s;
  this.i = i;
  this.b = b;
}

var fooBar = new FooBar("We Didn't Start the Fire", 1989, true);
console.dir(fooBar);
(new TestFirebaseEnv()).firestore.collection('test').doc('id').set(fooBar);
```

And the original Kotlin code:

```
class FooBar(val s: String, val i: Int, val b: Boolean)

class SampleTest {
    @Test
    fun writeObject() {
        val fooBar = FooBar("We Didn't Start the Fire", 1989, true)
        console.dir(fooBar)
        TestFirebaseEnv().firestore.collection("test").doc("id").set(fooBar)
    }
}
```
 
### Version info

**firebase-functions:** 2.0.5

**firebase-functions-test:** 0.1.4

**firebase-admin:** 6.0.0

### Steps to reproduce
* Checkout my [sample project](https://bitbucket.org/chadbingham/firebase-error-demo/src/master/)
* Add a json file with firebase test environment credentials at `js-module/`
* Replace `JSON_FILE` and other credentials in `/js-module/src/test/kotlin/sample/TestFirebaseEnv.kt`
* Install node modules:

    `cd js-module/functions && npm install && cd -`

* Run test:

    `./gradlew :js-module:build`

The full generated file will be located at `js-module/functions/src/test/index_test.js`
___________________
_Edit_

Work around
----
To solve this, I utilized [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization). I had to create an instance of their `AbstractSerialFormat` and a `dynamic` JS map. 

**JsMap.kt**
```
class JsMap<V> {
    @JsName("map")
    private val map: dynamic = js("({})")

    operator fun get(key: String): V = map[key] as V

    operator fun set(key: String, value: V?) {
        map[key] = value
    }

    @Suppress("UNUSED_PARAMETER", "UnsafeCastFromDynamic")
    fun contains(key: String): Boolean = js("key in this.map")

    fun toJs(): dynamic = map
}

```

**JsMapper.kt**
```
class JsMapper : AbstractSerialFormat() {

    fun <T> map(strategy: SerializationStrategy<T>, obj: T): JsMap<Any> {
        val m = OutMapper()
        m.encode(strategy, obj)
        return m.map
    }

    fun <T> unmap(strategy: DeserializationStrategy<T>, map: JsMap<Any?>): T {
        val m = InMapper(map)
        return m.decode(strategy)
    }

    inner class OutMapper : NamedValueEncoder() {
        init {
            this.context = this@JsMapper.context
        }

        override fun beginCollection(
            desc: SerialDescriptor,
            collectionSize: Int,
            vararg typeParams: KSerializer<*>
        ): CompositeEncoder {
            encodeTaggedInt(nested("size"), collectionSize)
            return this
        }

        private var _map: JsMap<Any> = JsMap()

        val map: JsMap<Any>
            get() = _map

        override fun encodeTaggedValue(tag: String, value: Any) {
            _map[tag] = value
        }

        override fun encodeTaggedNull(tag: String) {
            _map[tag] = null
        }
    }

    inner class InMapper(val map: JsMap<Any?>) : NamedValueDecoder() {
        init {
            this.context = this@JsMapper.context
        }

        override fun decodeCollectionSize(desc: SerialDescriptor): Int {
            return decodeTaggedInt(nested("size"))
        }

        override fun decodeTaggedValue(tag: String): Any = map[tag]!!

        override fun decodeTaggedNotNullMark(tag: String): Boolean {
            return map.contains(tag) || // in case of complex object, its fields are
                    // prefixed with dot and there are no 'clean' tag with object name.
                    // Invalid tags can be handled later, in .decodeValue
                    map[tag] != null
        }
    }

    companion object {
        val default = JsMapper()

        fun <T> map(strategy: SerializationStrategy<T>, obj: T): JsMap<Any> = default.map(strategy, obj)

        fun <T> unmap(strategy: DeserializationStrategy<T>, map: JsMap<Any?>): T = default.unmap(strategy, map)

    }
}
```

The following test passes: 
```  
@Test 
fun writeObjectJsMap() {
  val map = JsMapper.map(FooBar.serializer(), fooBar).toJs()
  testEnv.firestore.collection("test").doc("id").set(map)
}
```

This could probably use a bit of clean up. But it is working now. I am concerned about the overhead to serialize everything, but for the time being this is better than nothing.

**Comment by thechenky** [comment]
Hi @Binghammer thanks for taking the time to provide this feedback. I'm a bit confused - I don't see firebase-functions usage here - are you actually creating and deploying Cloud Functions? I only see usage of the Firestore SDK, in which case this should be routed to the Firestore SDK team. If you are using firebase-functions, can you please share the Javascript code as opposed to the Kotlin code, as it would be much easier to debug without having the compiler in the middle.
