### ISSUE TITLE
Make it easier to access the `firestore` instance

### ISSUE THREAD

**Issue by schmidt-sebastian** [firebase/firebase-functions#346]
It's currently pretty involved to write code that accesses the Firestore API from functions. The FIrestore instance can be extracted from the DocumentedReference that is part of  `change` (such as `change.after.ref.firestore`), but it would be nice if I `functions.firestore` was a proper Firestore instance.

A lot of our users "solve" this problem by including their own dependency on Firestore, but mixing different instances is not fully supported.

**Comment by schmidt-sebastian** [comment]
RE: https://github.com/googleapis/nodejs-firestore/issues/452#event-1963142012

**Comment by thechenky** [comment]
@schmidt-sebastian thank you for the suggestion! I have filed this internally as an improvement to the SDK. I'll close this out as we don't have the resources to work on this in the near future, but do know that it's in our tracker.

Internal bug reference: 121147849.
