### ISSUE TITLE
https functions error not according to spec 

### ISSUE THREAD

**Issue by mad-it** [firebase/firebase-functions#350]
### Version info

**firebase-functions:**
2.1.0
**firebase-tools:**
6.1.1

### Test case

According to the protocol specified [here](https://firebase.google.com/docs/functions/callable-reference#response_body)

> error - If this field is present, then the request is considered failed, regardless of the HTTP status code or whether data is also present. The value of this field should be a JSON object in the standard Google Cloud HTTP Mapping format for errors, with fields for status, **message**, and (optionally) details.

As you can see in the following line in the https-functions [here](https://github.com/firebase/firebase-functions/blob/master/src/providers/https.ts#L167) "message" is an optional field which if left out crashes on any other SDK. 

### Steps to reproduce

Create a function and throw an error where message parameter is left out and try to call the function with for example Android SDK.

**Comment by thechenky** [comment]
Hi @mad-it thanks for flagging! I'm going to look into this as soon as I find some time to reproduce the issue. Stay tuned for updates.

**Comment by joehan** [comment]
Fixed! Thanks for bringing this to our attention @mad-it
