### ISSUE TITLE
Path must be a string error from firebase, firebase-functions

### ISSUE THREAD

**Issue by fabienthiombiano** [firebase/firebase-functions#352]
This is a bizarre issue I am facing with such basic cloud function. I have looked at everywhere and I don't know what is wrong with the path package. Anyone has a solution to this? I am on MacOS HighSierra. Thanks

### Version info

**firebase-functions:**
`2.1.0`

**firebase-tools:**
6.1.2

**firebase-admin:**
6.0.0

### Steps to reproduce

    const functions = require('firebase-functions');
    const os = require('os');
    const path = require('path'); 
    const { Storage } = require('@google-cloud/storage');

    const gcs = new Storage ({});
    exports.onImageUpload = functions.storage.object().onFinalize(event => {
    console.log(event);

    const fileBucket = event.bucket;
    const contentType = event.ContentType;
    const filePath = event.filePath;
    console.log('file changes detected!');

    const destBucket = gcs.bucket(fileBucket);
    const tmpFilePath = path.join(os.tmpdir(), path.basename(filePath)); 
  
    const metaData = {
    contentType: contentType
     };

     return destBucket.file(filePath).download({
        destination : tmpFilePath, 
     }).then(() => {
      console.log("Image downloaded to the local destination");
      destBucket.file(filePath).upload({
          destination: "renamed-" + path.basename(filePath), 
          metaData: metaData
      });
      });
     });

### Actual behavior - Firebase error 
        TypeError: Path must be a string. Received undefined
       at assertPath (path.js:7:11)
       at Object.basename (path.js:1361:5)
       at exports.onImageUpload.functions.storage.bucket.object.onFinalize.event                 (/user_code/index.js:30:53)
       at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
       at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
      at /var/tmp/worker/worker.js:768:24
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by thechenky** [comment]
Hi @fabienthiombiano, it looks like you're using the wrong property to access the filepath from the event object - you should use `event.name` instead of `event.filePath` as per this documentation: https://firebase.google.com/docs/storage/extend-with-functions. Can you try that and let me know if that solves your issue?

**Comment by Joshrlear** [comment]
> Hi @fabienthiombiano, it looks like you're using the wrong property to access the filepath from the event object - you should use `event.name` instead of `event.filePath` as per this documentation: https://firebase.google.com/docs/storage/extend-with-functions. Can you try that and let me know if that solves your issue?

they seem to be using Google cloud storage, not firebase.
