### ISSUE TITLE
Error: Error parsing triggers: Cannot find module 'example'

### ISSUE THREAD

**Issue by inmogr** [firebase/firebase-functions#353]
I have an issue at the stage of deployment, I can only share portion of the code.
I have setup some global paths in the `tsconfig.json` like this
```
        "baseUrl": "./",
        "paths": {
            "example": [
                "example/path"
            ]
        },
```

and then added these to the `tslint.json` not for implicit module dependency like this
```

        "no-implicit-dependencies": [
            true,
            [
                "example",
                "example/index",
                "example/undefined",
            ]
        ],
```

when running `firebase deploy` it start compiling then when almost ready to deploy im getting this error

```
+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'example'
```

**Comment by thechenky** [comment]
Hi @inmogr, can you provide your `firebase.json` file? I'm also curious to see how your `package.json` is set up particularly in the `scripts` section. Are you compiling your code as part of the predeploy script? Your `firebase.json` should contain something like this:

```
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}
```

Let me know if this helps.

**Comment by inmogr** [comment]
Hi @thechenky , thanks for replying to my issue, I thought no one will.

my `firebase.json` is exactly as the code you have shared, regarding the `package.json` I'd say it is not relevant to the issue because the `example` is not a package but a global path. In my `tsconfig.json` I have registered the path and in `tslint.json` I have add it to the implicit packages.

Also, here is a response to my question that I found earlier https://stackoverflow.com/a/44369473/8801730 so I guess when the `CLI` compiles `TS` into `JS` it compiles it using the very old `Node.JS` versions which does not support this new feature in TypeScript

**Comment by inmogr** [comment]
@thechenky dear you have closed the issue tooo soon
please clone the following and play around the issue by yourself to know what im talking about

https://github.com/inmogr/sample-error-fire-funcs

**Comment by inmogr** [comment]
here is the error im getting on this repo

```
> tsc

+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
!  functions: missing necessary APIs. Enabling now...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module '@example'

Try running "npm install" in your functions directory before deploying.

Having trouble? Try firebase deploy --help
```
