### ISSUE TITLE
Error: Error parsing triggers: Cannot find module 'example'

### ISSUE THREAD

**Issue by inmogr** [firebase/firebase-functions#368]
The following issue was closed before even providing support on it:

https://github.com/firebase/firebase-functions/issues/353#issuecomment-448542420

Please review the issue and provide a solution for it.

Thanks

**Comment by thechenky** [comment]
Please follow the guidelines I outlined in your previous issue. Also, I'd like to ask you to be respectful with the way you address developers on this forum - ie, referring to someone as "dear" is considered condescending.

**Comment by inmogr** [comment]
Ok, sorry about "dear" literally I meant the straight forward "dear" not what may be understood indirectly.

for the response you gave me last time i'll try to break it into chunks and see what did I miss there, If i made something wrong please let me know.

Part 1:
```
@inmogr I would suggest using import and export, that should resolve the errors you're seeing
``` 
Response to part 1:
I'm using `import` and `export` as you can see in the repo link I have provdied

Part 2
```
In the stackoverflow post you linked, looks like using incompatible require/export statements is what is causing the module not to be found
```
Response to part 2
Thanks that's probably the issue (I just shared that error bcz it is similar in terms of console error but that stackoverflow is not by me)

Part 3
```
As the post alludes, this is not a functions SDK issue but a matter of correct nodejs usage.
```
Response to part 3
You might be right but really you need to view the same error repo first, if you checked it could you pls give me a reference to the place i made a mistake at 
the same link once again https://github.com/inmogr/sample-error-fire-funcs

Thanks

**Comment by thechenky** [comment]
@inmogr your `.tsconfig` looks odd with `@example`, make sure you are following the instructions here https://www.typescriptlang.org/docs/handbook/tsconfig-json.html.

**Comment by inmogr** [comment]
Thanks, I'll have a look and compare to check out on what could have gone wrong
