### ISSUE TITLE
onCall with runWith type mismatch

### ISSUE THREAD

**Issue by jaycosaur** [firebase/firebase-functions#369]
### Version info

**firebase-functions:**
6.1.0

**firebase-tools:**
6.1.2

### Test case

Declare two onCall functions one using runWith and one without, typings are not compatible. runWith().https.onCall type seems to not include the functions.Runnable<any> interface.

### Expected behavior

Would expect the typings of functions.runWith(opts).https.onCall to match functions.https.onCall.

### Actual behavior

Using functions.https.onCall:

`onCall(handler: (data: any, context: functions.https.CallableContext) => any): functions.TriggerAnnotated & ((req: functions.Request, resp: functions.Response) => void) & functions.Runnable<any>`

Using functions.runWith(...).https.onCall:

`onCall: (handler: (data: any, context: functions.https.CallableContext) => any) => functions.HttpsFunction`

**Comment by thechenky** [comment]
@jaycosaur thanks for the feedback! At first look this does look like a bug, which I've filed in our tracker. Internal bug reference: 122323911.

We'll take a look and try to repro as soon as we get around to this.

**Comment by kevinajian** [comment]
Fixed in https://github.com/firebase/firebase-functions/pull/372.
