### ISSUE TITLE
Using database's set with an object with two properties will not trigger function which listenes to one of the properties

### ISSUE THREAD

**Issue by Portals** [firebase/firebase-functions#37]
### Version info
firebase-admin: 4.1.2,
firebase-functions: 0.5

### Test case & Steps to reproduce

https://github.com/Portals/firebase_functions_database_bug

Bug in summary: 

This will trigger a function listening to /path/1

```
        firebase.database().ref("/path").set({
          1: "Sweden",
          2: "Hello World"
        });
```

This will trigger a function listening to /path/1
`        firebase.database().ref("/path").remove();
`

This will **not** trigger a function listening to /path/1

```
        firebase.database().ref("/path").set({
          1: null,
          2: "Hello World"
        });
```

This will trigger a function listening to /path/1
```
        firebase.database().ref("/path").set({
          1: null,
          2: null
        });
```

This is the function which listens to /path/1
```
var functions = require('firebase-functions');

exports.updateSweden = functions.database.ref("/path/1").onWrite(event => {
  const oldData = event.data.previous.val();
  const newData = event.data.val();

  console.log("oldData: " + oldData);
  console.log("newData: " + newData);
});
```

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

The function which listens to /path/1 doesn't run.

### Actual behavior

The function which listens to /path/1 should run

**Comment by mbleigh** [comment]
In the scenario where the function doesn't trigger, is there already a
value when you do the set or is it null?

**Comment by Portals** [comment]
There is a value before ref.set(object) when the function doesn't run.
object[1] is null. object[2] a= 'Hello World'. The function listens to
/path/1.

Den 16 apr. 2017 12:31 fm skrev "Michael Bleigh" <notifications@github.com>:

> In the scenario where the function doesn't trigger, is there already a
> value when you do the set or is it null?
>

**Comment by laurenzlong** [comment]
Hey @Portals, I've reproduced it myself, thanks for the detailed instructions. This does not appear to be a bug with the SDK, but a bug with the database integration. I've filed a bug report to the respective team internally, and will keep you posted on the progress of the fix. Thanks for bringing this to our attention!

**Comment by Portals** [comment]
Thank you for your help Lauren! Firebase functions rocks! 👍

**Comment by laurenzlong** [comment]
Thanks for the kind words! The fix is in production now. I'm going to close this issue, please reopen it if you experience it again.
