### ISSUE TITLE
Firestore onWrite trigger callback has undefined context

### ISSUE THREAD

**Issue by miickel** [firebase/firebase-functions#381]
### [REQUIRED] Version info

**firebase-functions:** ^2.1.0

**firebase-tools:** 6.2.2

**firebase-admin:** ^6.5.0

### [REQUIRED] Test case

index.js:

    exports.handleWrite = functions
      .firestore
      .document('collection/{doc}')
      .onWrite((data, context) => {
        // context === undefined
      })

### [REQUIRED] Steps to reproduce

Create Firestore onWrite trigger, check `context` param in callback.

### Were you able to successfully deploy your functions?

Yes, unless I use object destructuring of the context in the callback signature. 

### [REQUIRED] Expected behavior

As it says in the [documentation](https://firebase.google.com/docs/reference/functions/functions.firestore.DocumentBuilder#onWrite), I expect `context` to be a non-null, defined value.

### [REQUIRED] Actual behavior

Context is `undefined`. If using ES object destructuring in the callback signature, like `(data, { eventId })`, it's not possible to upload the function.

**Comment by puf** [comment]
Also posted on: https://stackoverflow.com/questions/54144439/firestore-onwrite-trigger-callback-has-undefined-context

**Comment by thechenky** [comment]
hi @miickel thanks for the feedback, we are looking into this now and trying to reproduce but having trouble. When did this start happening for you? Which zone are your functions deployed in?

**Comment by thechenky** [comment]
I'm also confused as to why you can't deploy your functions if the context is undefined, which if so, would only surface at function execution time. Would you mind sharing logs of your function and logs of your deploy?

**Comment by joehan** [comment]
@miickel Hey mickell, per those docs that you linked, it looks like you are using the wrong params for document.onWrite(). document.onWrite expects a function to handle a Change (https://firebase.google.com/docs/reference/functions/functions.Change) ie (change)=>{}. If you replace your code with the following, I think it should start working as you intend:

`exports.handleWrite = functions
  .firestore
  .document('collection/{doc}')
  .onWrite((change) => {
    // do things with change.after or change.before
  })`

I totally understand where your confusion stems from, however - document.onCreate() and document.onDelete() expect a handler function that takes (data, context) [ or more accurately, a Document Snapshot and an EventContext]. I've filed an internal bug to take a look at making these API's more consistent. (ref 122527860)

**Comment by miickel** [comment]
@thechenky Hi, thanks for looking in to this! My CFs deploy to us-central-1. I haven't encountered this with any other Firestore triggers, only onWrite.

@joehan thanks, using a function is what I'm doing, please see my example. On the page I linked the signature looks like this `function(functions.Change containing non-null functions.firestore.DocumentSnapshot, optional non-null functions.EventContext)`.

The issue I'm having is that the 2nd argument (`optional non-null functions.EventContext`) in my callback function always seems to be undefined. So either there's a bug, or the documentation is wrong.

Anyway, today when I deploy the exact same function, **it works**! I have no idea why.

**Comment by miickel** [comment]
Checked my git log - Shit sorry, this was totally my mistake. 🙈 I use a double fn design for "dependency injection" (to enable reuse of resources between function executions), like:

`({ depA: getDepA(), depB: getDepB() }) => (change, ctx) => { // handler }`

and I accidentally placed the ctx param in my deps function.

**Comment by thechenky** [comment]
@miickel I'm so glad it's working for you again! Thanks for following up to let us know how you resolved the issue.
