### ISSUE TITLE
Include `context.auth` for Cloud Storage triggers

### ISSUE THREAD

**Issue by fenixsolorzano** [firebase/firebase-functions#395]
As fas as I've tested there's no `auth` object in Cloud Storage triggers, that object should be in every trigger in fact.

Docs only mention that `auth` object is available for Realtime database

**Comment by thechenky** [comment]
Hi @fenixsolorzano please follow the issue template next time. Yes context.auth is currently only supported for real-time database as the docs say. If you would like storage to support  this as well please  file a feature request through our support page. Thanks!

**Comment by thechenky** [comment]
I've noted your feature request. In the meantime here's a workaround that might help: https://stackoverflow.com/questions/53723687/firebase-cloud-functions-how-to-get-user-that-uploads-a-file. I'll close out this issue now as we don't track feature requests in GitHub.
