### ISSUE TITLE
i am receiving val is undefined i dont see any thing wrong with this , i am doing what is exactly on firebase documentation so i dont know

### ISSUE THREAD

**Issue by onaty** [firebase/firebase-functions#405]
import * as functions from 'firebase-functions';

 export const updateUser = functions.databasecode 
 .ref('users/{userId}/')
 .onUpdate((change, context) => {
 const gou = change.after.val();//i am receiving the error here
  })

**Comment by kevinajian** [comment]
What is the error message that you are getting? Can you please follow the template to include the debug logs?

Also it looks like you're not returning anything. Try adding a value or promise.

**Comment by kevinajian** [comment]
Hi @onaty, did that resolve your issue?

**Comment by kevinajian** [comment]
Will close this out. If you're still getting the error after returning a value, please update this issue. Thanks!
