### ISSUE TITLE
Error: TS2304 - Cannot find name 'SetOptions'

### ISSUE THREAD

**Issue by babkouew** [firebase/firebase-functions#406]
### Related issues
**Topic not found here nor on Stackoverflow**

### Version info

**node:**
v11.6.0

**firebase-functions:**
2.2.0

**firebase-tools:**
6.3.1

**firebase-admin:**
7.0.0

**TypeScript**
3.2.2

### Test case

**This test case builds a simple HTTP function that writes a string value in a firestore database reference.**

### Steps to reproduce

**Create two typescript files in your CLI function directory: (1) function.ts, (2) index.ts

Copy paste the below code in (1) function.ts:**
```

import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

export const WriteData = functions.https.onCall(async(data,context)=>{

    const DataRef = admin.firestore().collection('data').doc('id')
   
    return DataRef.set({data:"data value"},SetOptions.merge())

});
```

Copy paste the below line of code in (2) index.ts

`export {WriteData} from './function';`

Finally compile the function by running the command 'npm run build' from your function folder in Firebase CLI then deploy it by running 'deploy --only functions:WriteData'

### Expected behavior

The function should compile normally in TypeScript without error.

Upon depolyment, the function should write the string value "data value" at the document location specified in DataRef. If data is already present at the DataRef location, SetOptions will prevent data override by forcing a merge with existing data.

### Actual behavior

The TypeScript function does not compile and logs the following error in CLI:

`error TS2304: Cannot find name 'SetOptions'.`

### Were you able to successfully deploy your functions?

Trying to deploy the function returns the same error

`error TS2304: Cannot find name 'SetOptions'.`

**I have followed firebase function documentation to the letter on how to add data on an already existing document.**

 https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document

**The function works perfectly fine until I specify 'SetOptions.merge()' in the set method.
I am at a loss here. It is an unexpected and crippling error for my project, please help.
Here is the complete error output in CLI:**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle functions@~prebuild: functions@
6 info lifecycle functions@~build: functions@
7 verbose lifecycle functions@~build: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Boubi\FirebaseFunctions\project\functions\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\sqlite;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Boubi\AppData\Local\Microsoft\WindowsApps;C:\Users\Boubi\AppData\Local\Android\Sdk\platform-tools;C:\Users\Boubi\AppData\Roaming\npm;C:\Users\Boubi\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle functions@~build: CWD: C:\Users\Boubi\FirebaseFunctions\project\functions
10 silly lifecycle functions@~build: Args: [ '/d /s /c', 'tsc' ]
11 silly lifecycle functions@~build: Returned: code: 2  signal: null
12 info lifecycle functions@~build: Failed to exec build script
13 verbose stack Error: functions@ build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid functions@
15 verbose cwd C:\Users\Boubi\FirebaseFunctions\project\functions
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 2
22 error functions@ build: `tsc`
22 error Exit status 2
23 error Failed at the functions@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by thechenky** [comment]
Hi @babkouew thanks for your feedback, and sorry this issue is causing you so much pain! Your versions look off for functions and admin (functions does not go up to 6, the latest is 2.2.0) Can you paste the correct versions for both of those? Also I see you are using node 11 locally - what are you using when you deploy your functions? Cloud Functions currently only supports node 6 and node 8 so I would recommend using the same node version as the one you're planning to deploy with.

**Comment by joehan** [comment]
Hey @babkouew, just took a look at your code. It looks like you may be following the Java example instead of the NodeJS one. Could you try this instead:

```DataRef.set({
  data: 'dataValue'
}, {merge: true});
```

Let me know if that helps!

**Comment by babkouew** [comment]
Hi @joethan, Excellent that was it, problem solved! I now see the NodeJS example burried in a tab on the left of the example code in the documentation. 

Hi @thechenky, thanks for pointing this out I have edited my post for the right versions of firebase modules and downgraded my NodeJS version to 6.

Thanks to both of you for your help!

**Comment by thechenky** [comment]
@babkouew Happy to help and glad your issue is resolved! As always, please open a new issue if you see any other problems.
