### ISSUE TITLE
Unable to batch write more than 250 items when using FieldValue.serverTimestamp()

### ISSUE THREAD

**Issue by dsl101** [firebase/firebase-functions#408]
### [REQUIRED] Version info

**node:**
v11.9.0

**firebase-functions:**

**firebase-tools:**
6.3.1

**firebase-admin:**

### [REQUIRED] Test case

Define the following function and run via `firebase functions:shell`, assuming packages (including firebase-admin and lodash) are installed and configured.
```
exports.mockBatchUpdate = functions.https.onCall(async data => {
  const projectRef = firestore.collection('projects').doc('batchUpdates')
  const batchSize = data.batchSize

  // Example data to be stored per document
  const output = _.times(batchSize, n => ({
    url: `http://nowhere.com/${n}`,
    index: n,
    other: `This is item ${n}`
  }))

  const batch = firestore.batch()
  _.forEach(output, item => {
    batch.set(projectRef.collection('output').doc(String(item.index)), {
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      ...item
    })
  })

  return batch.commit()
})
```

### [REQUIRED] Steps to reproduce

Call with `mockBatchUpdate({batchSize: 250})`, and no error is returned
Call with `mockBatchUpdate({batchSize: 251})`, and `Error: 3 INVALID_ARGUMENT: maximum 500 writes allowed per request` is returned

### [REQUIRED] Expected behavior

Up to 500 items could be written in a single batch.

### [REQUIRED] Actual behavior

It would seem from testing that including `updatedAt: admin.firestore.FieldValue.serverTimestamp()` in the objects to be written is counted as an extra 'write'. If that is removed or replaced with a static data member, up to 500 items can be successfully written.

### Were you able to successfully deploy your functions?

No error messages on deployment, only on execution.

**Comment by joehan** [comment]
Hi @dsl101, thanks for finding this! I believe this is intended behavior - however, this seems like an issue with firebase-admin(https://github.com/firebase/firebase-admin-node). Do you mind reopening this issue over there? They should be able to give you a clearer answer.

If you take a look at the documentation for [FieldValue] (https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue), it mentions that it is a ['Sentinel Value'](https://en.wikipedia.org/wiki/Sentinel_value). Creating a sentinel value involves writing a 'dummy' value to the database, which is where the extra write is coming from.

**Comment by dsl101** [comment]
Sure—I wasn’t entirely sure where to put it. I also suspected it might be a
documentation issue (it’s pretty obscure as described tbh). Perhaps either
discount the timestanp in the write count or make it explicit in the batch
documentation?

Many thanks!

**Comment by joehan** [comment]
No problem, and thanks for passing it along to the other repo. You are absolutely right that this should be more clearly documented though - I had to look around wikipedia to figure out what was happening here. I'll file a internal bug to improve our docs on this.

**Comment by joehan** [comment]
Internal Bug Reference: 124449660

**Comment by dsl101** [comment]
Reopened here: https://github.com/firebase/firebase-admin-node/issues/456
