### ISSUE TITLE
firebase-functions v2.2.0 firestore trigger Date instead of Timestamp

### ISSUE THREAD

**Issue by dbacinski** [firebase/firebase-functions#409]
### Related issues

https://github.com/firebase/firebase-functions/issues/285

### [REQUIRED] Version info

**firebase-functions:**
v2.2.0

### [REQUIRED] Test case
I have upgraded from functions v2.1.0 to v2.2.0 and my triggers have started returning Date instead of Timestamp.
I would expect it to be another way around after breaking changes announced in v2.2.0.

```
export const markStats = functions.firestore
  .document("/workBites/{markId}")
  .onWrite((snap, context) => {
    const previousData: DocumentData = snap.before.data() || {}
    const newData: DocumentData = snap.after.data() || {}

  const timestamp: Date = actionType.isDelete
    ? previousData.timestamp && previousData.timestamp.toDate() // <- this is not returning Timestamp anymore, but Date?
    : newData.timestamp && newData.timestamp.toDate()
}
```

### [REQUIRED] Expected behavior

onWrite -> snap.before.data() should contain `timestamp` types as Timstamp

Log from v2.1.0: 
```
3:07:26.913 PM
markStats
Function execution took 6929 ms, finished with status: 'ok'
3:07:19.986 PM
markStats
Function execution started
```

### [REQUIRED] Actual behavior

onWrite -> snap.before.data() contains `timestamp` types as Date

Log from v2.2.0:
```
Function execution took 7 ms, finished with status: 'error'
3:00:51.346 PM
markStats
TypeError: previousData.timestamp.toDate is not a function at processMarkData (/user_code/lib/listener/markStats.js:29:60) at exports.markStats.functions.firestore.document.onWrite (/user_code/lib/listener/markStats.js:20:12) at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23) at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20) at /var/tmp/worker/worker.js:779:24 at process._tickDomainCallback (internal/process/next_tick.js:135:7)
3:00:51.343 PM
markStats
Function execution started
```
### Were you able to successfully deploy your functions?

yes

**Comment by jaschaio** [comment]
Getting the same error:

`TypeError: newData.created_at.toDate is not a function`

Especially as this should have already been fixed within [2.0.2](https://github.com/firebase/firebase-functions/releases/tag/v2.0.2)

**Comment by dbacinski** [comment]
It was fixed in 2.0.2, it is working well for me in 2.1.0, 
but in 2.2.0 it seems that we have a regression of the same issue.

**Comment by developcodeza-matthew** [comment]
Same, noticed that all my .toDate() calls were breaking.

Its correctly saved as a Timestamp in firestore: 
![screen shot 2019-02-18 at 1 52 43 pm](https://user-images.githubusercontent.com/26629247/52949295-8d401e80-3384-11e9-9c8e-50112bbb4ab3.jpg)

But being retuned as a ISO datestring in my cloud functions listener:
![screen shot 2019-02-18 at 1 54 45 pm](https://user-images.githubusercontent.com/26629247/52949373-c6788e80-3384-11e9-84f8-6aaa043580ef.jpg)

**Comment by developcodeza-matthew** [comment]
Downgrading back to 2.1.0 has fixed this issue for now. 

Would like to hear whether 2.2.0 behaviour is a bug or if this is intended.

**Comment by joehan** [comment]
Hey all, I'm looking into this issue right now, thanks a ton for bringing it to our attention. In the last release, we upgraded our peer dependency to [firebase-admin v7.0.0](https://github.com/firebase/firebase-admin-node/releases/tag/v7.0.0), which should have changed the default behavior of Firestore to {timestampsInSnapshots: true}. Because of this, we removed [a few lines where fiurebase-functions was manually setting this:](
https://github.com/firebase/firebase-functions/commit/d12c7d5bd8f7eaac4a33f9f8132cf0b2b410a6a2). I'm going to do some testing to see if that is what's causing this issue.

**Comment by jaschaio** [comment]
@joehan I noticed yesterday that I am using `firebase-functions v2.2.0` with `firebase-admin v6.5.1`. This might be the reason for this? I will upgrade `firebase-admin` to `v7.0.0` later today and see if it resolves the problem.

**Comment by dbacinski** [comment]
I am using admin 6.4.0 with functions 2.2.0 and timestamp enforcement:
```
const firestore = admin.firestore()
firestore.settings({ timestampsInSnapshots: true })

**Comment by thechenky** [comment]
@dbacinski we updated the peer dependency in the 2.2.0 release to point to v7.0.0 of firebase-admin. You should have gotten a warning if using functions with a noncompatible peer dependency like 6.4.0. Can you try upgrading to 7.0.0 to see if that fixes the issue?

**Comment by dbacinski** [comment]
I have updated dependencies to:
    "firebase-admin": "7.0.0",
    "firebase-functions": "2.2.0",
    "@google-cloud/firestore": "^1.0.0",

No Timestamp is returned correctly. But I am getting an error message:
`The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.`

Even thou:
```

**Comment by developcodeza-matthew** [comment]
@dbacinski I think that is just a warnign saying that 

    firestore.settings({ timestampsInSnapshots: true })

is now redundant as it its the default

**Comment by dbacinski** [comment]
I was not getting this error message for functions 2.1.0, but only if `firestore.settings({ timestampsInSnapshots: true })` was set.

**Comment by thechenky** [comment]
Hi @dbacinski glad you got it working when you upgraded firebase-admin! Yes, @developcodeza-matthew is correct, this is just a warning. This change was made in `firebase-admin v.7.0.0` so that you no longer need to provide `firestore.settings({ timestampsInSnapshots: true })` in your code - it will default to this behavior with `firebase-admin v.7.0.0`. I hope this clears things up!

**Comment by dbacinski** [comment]
I have removed all the redundant `firestore.settings({ timestampsInSnapshots: true })` configurations from my project and there are no error messages.

Solved. Thank you!

**Comment by thechenky** [comment]
@dbacinski awesome, glad to hear that! If you encounter any other problems, please don't hesitate to open a new issue.
