### ISSUE TITLE
node 8 not work 

### ISSUE THREAD

**Issue by WaldenH** [firebase/firebase-functions#411]
### [REQUIRED] Version info
I am to try a very simple case, but the node 8 seems not work. "async/await" is not supported.

node version v10.15.0
"firebase-admin": "~7.0.0",
"firebase-functions": "^2.2.0"
firebase-tools  6.4.1

**node:**

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

### [REQUIRED] Steps to reproduce
firebase init
add "engines": { "node": "8" }, to functions/package.json

### Were you able to successfully deploy your functions?

Debug information

============index.js============
const functions = require('firebase-functions');

const foo = async () => { };

exports.helloWorld = functions.https.onRequest((request, response) => {
  foo(); 

  response.send("Hello from Firebase!");
});

============package.json============
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1"
  },
  "engines": {
    "node": "8"
  },
  "private": true
}

============Terminal============(firebase deploy --only functions)
i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/Home/Desktop/prj/express/t1/functions
> eslint .

/Users/Home/Desktop/prj/express/t1/functions/index.js
  3:22  error  Parsing error: Unexpected token =>

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Home/.npm/_logs/2019-02-20T14_29_03_328Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1

============debug.log============
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/Home/Desktop/prj/express/t1/functions',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle functions@~prelint: functions@
6 info lifecycle functions@~lint: functions@
7 verbose lifecycle functions@~lint: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Home/Desktop/prj/express/t1/functions/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle functions@~lint: CWD: /Users/Home/Desktop/prj/express/t1/functions
10 silly lifecycle functions@~lint: Args: [ '-c', 'eslint .' ]
11 silly lifecycle functions@~lint: Returned: code: 1  signal: null
12 info lifecycle functions@~lint: Failed to exec lint script
13 verbose stack Error: functions@ lint: `eslint .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid functions@
15 verbose cwd /Users/Home/Desktop/prj/express/t1
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "/Users/Home/Desktop/prj/express/t1/functions" "run" "lint"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error functions@ lint: `eslint .`
22 error Exit status 1
23 error Failed at the functions@ lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by joehan** [comment]
Hey @WaldenH, could you post the actual error message that you are getting? It helps us figure out exactly what is going on. ESlint could be the cause of your issues - could you make sure that "ecmaVersion": 8 is in your eslint.rc?

**Comment by WaldenH** [comment]
> Hey @WaldenH, could you post the actual error message that you are getting? It helps us figure out exactly what is going on. ESlint could be the cause of your issues - could you make sure that "ecmaVersion": 8 is in your eslint.rc?

Hi, I have updated the debug information, hope it is useful.

**Comment by WaldenH** [comment]
@joehan thanks, it works now!!!

**Comment by Mauratay** [comment]
What was the solution here? I'm having a similar problem, it gets fixed if I remove the space after the dot though.

**Comment by joehan** [comment]
Hey @Mauratay - The issue here was that eslint was looking for an older version of ecmascript than was actually being used. The fix was to make sure that in `eslint.rc` included ```"ecmaVersion": 8```.

Also, we don't always see new messages on closed issues - if you are still having trouble, feel free to open a new issue in this repo that describes your issue and includes the exact error you're seeing (and maybe include a link to this issue as well if it is similar).
