### ISSUE TITLE
Allowing empty HTTPS Callable calls for warmup

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-functions#412]
Some time ago we've made the choice to use Firebase HTTPS callable functions for a new service. At this time it was not obvious what the call pattern was. 

Although the pattern might still change, we are noticing periods were only a few calls are performed per hours. As a result, HTTPS callables trigger a new Firebase Function deployment with a cold start, which is really bad from a user experience.

Since the pattern might still change and because of the refactoring time required we do not want to rework the implementation to move calls to provisioned instances. Instead, we made the choice to have a CRON that periodically performs a raw HTTP GET request to HTTPs Callable functions we want to keep warm.

This solution works quite well. However, since we send a raw HTTP GET request and not a POST with data matching the [SDK filter](https://github.com/firebase/firebase-functions/blob/master/src/providers/https.ts#L287), logs are polluted with some error code.

Would you accept a pull-request that returns an HTTP 204 for an HTTP HEAD request sent to a callable function? This would simplify manual warmup and prevent log pollution without constructing requests based on SDK internals which may change in the future.

**Comment by thechenky** [comment]
Hi @lpellegr thank you for your feedback and really appreciate the PR offer! Before we look at changing which requests the SDK accepts for callable functions, can you paste the error messages that you're getting in the logs?

**Comment by lpellegr** [comment]
Hi @thechenky. 

Thanks for your answer.

> can you paste the error messages that you're getting in the logs?

Logs are polluted with errors that look like the following:

> Function execution took X ms, finished with status code: 400
> Request has invalid method. GET
> Invalid request IncomingMessage {...}

We could most probably get rid of these errors by creating a fake POST request that satisfies the filter function I pointed out in the previous message but this may easily break in the future.

**Comment by samtstern** [comment]
> Function execution took X ms, finished with status code: 400

While the error is bad and I agree it would be nice to make this smoother, I wonder if this is actually working fine right now.  This seems to show that the function executed (and then 400-ed) which means it was "warmed up" as desired.  @thechenky is that true?

**Comment by thechenky** [comment]
@samtstern yep, that's correct, the function should have executed and thus warmed up - I think the problem here is just the pollution of the errors in the logs since this warming up happens periodically.

**Comment by lpellegr** [comment]
I confirm the issue is only about logs pollution. Would you accept a pull request that addresses this problem?

**Comment by thechenky** [comment]
Hi @lpellegr this might take more thinking. I understand your use case and that warming functions is generally a pattern that many of our developers have to use right now, as unfortunate as that is. I'm afraid that adding support for another method to callable function solely for the purpose of warming it up without log pollution is not the best approach. Is there a way you could do a POST with some kind of "dummy" data that your function understands as a no op, and that way your function gets warmed up but the logs don't show errors?

**Comment by lpellegr** [comment]
@thechenky That's a possibility but in that case, the issue is with the internal requirements set by `firebase-functions`. The warmup is performed on the server side, using the client SDK is not a solution. Sending an HTTP POST requires to fake your assertions. I am afraid your code may change and break the POST in the future, especially since there is a TODO as a comment in your filter:

https://github.com/firebase/firebase-functions/blob/master/src/providers/https.ts#L325

I understand you do not want to ease warmups. That's sad, we'll find another solution.

**Comment by thechenky** [comment]
@lpellegr I don't think this is a no-go, but just requires a bit more time to make sure we're being careful about changing the callable interface. Give us some time to discuss this option internally, and I'll get back to you with an update.

**Comment by lpellegr** [comment]
@thechenky Great. Thanks.

**Comment by thechenky** [comment]
Hi @lpellegr, apologies for the late response. We reviewed your proposal but seeing as your use case is still working as desired (minus the logs pollution), it is not a strong enough case for altering the API surface of the callable interface. Additionally, if our interface changes (which is unlikely) in a way that breaks existing users, it will be a major version upgrade so you will be protected from the breaking change until you have time to make the necessary changes to your calls. Thanks again though for your kind offer to implement the PR, we really appreciate community support!
