### ISSUE TITLE
Cloud function not triggered when array set to empty in parallel with other values

### ISSUE THREAD

**Issue by crystalneth** [firebase/firebase-functions#42]
### Version info

**firebase-functions:** 0.5.3

**firebase-tools:** n/a

**firebase-admin:** 4.1.3

### Test case

Deploy this cloud function:

```
exports.testFiring = functions.database.ref('/testFire/someThing/{thingId}/tags').onWrite(event => {
  return admin.database().ref('/testFire/firedAt').set(new Date().getTime());
});

```

Observe the value at /testFire/firedAt while entering the following in a REPL or elsewhere:

`root.child('testFire/someThing/123').set( { foo: 1, tags: ['someTag'] })`

(function fires)

`root.child('testFire/someThing/123').set( { foo: 2, tags: [] }`

BUG: Function does not fire

For reference the function does fire when foo is not also set:

`root.child('testFire/someThing/123').set( { foo: 1, tags: ['someTag'] })`

(function fires)

`root.child('testFire/someThing/123').set( { tags: [] })`

(function fires)

### Steps to reproduce

1) Deploy cloud function above

2) Run commands on REPL or elsewhere. Observe firedAt value.

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

Function should always fire on array change.

### Actual behavior

Function does not fire when array emptied.

**Comment by puf** [comment]
Please indicate when you cross-post: https://groups.google.com/forum/#!topic/firebase-talk/-udC4weRFO0 Closing it here, since a team member already followed up in firebase-talk.

**Comment by crystalneth** [comment]
I realized firebase-talk was not for bugs after posting there. This seemed more appropriate for tracking and updates. However handle as you do. :)

**Comment by katowulf** [comment]
Either place is fine, just link them and pick one for discussion, so we don't duplicate effort.
