### ISSUE TITLE
Node 8 not working

### ISSUE THREAD

**Issue by leads** [firebase/firebase-functions#421]
Hi all.
Having a sad time here! Seen a couple of issues around this. I believe I have tried all the suggested and working fixes. 

Using https://console.firebase.google.com *not* Cloud

Using node v 8.9.0 locally, as suggested in another issue.

firebase version: 6.40

This is my package.json
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1"
  },
  "engines": {
    "node": "8"
  },
  "private": true
}
```

eslintrc.json content now includes the following:
```
"parserOptions": {
    // Required for certain syntax usages
    "ecmaVersion": 8,
    "sourceType": "module"
  }
```

and this is the content of my function (index.js)
```
const functions = require('firebase-functions');

import config from './config'

// Create and Deploy Your First Cloud Functions
// https://firebase.google.com/docs/functions/write-firebase-functions

exports.helloWorld2 = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});

```

`firebase serve` and `firebase deploy` errors with: `SyntaxError: Unexpected token import` (caused by the import line)

Very much hope I'm missing something easy here. Would prefer not to faff around with webpack if I don't have too.

**Comment by leads** [comment]
and some further info after I run `firebase serve`

i functions: Preparing to emulate functions.
Warning: You're using Node.js v8.9.0 but Google Cloud Functions only supports v6.11.5.
⚠ functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠ functions: Error from emulator. Error occurred while parsing your function triggers

**Comment by leads** [comment]
You know what. I'm an idiot, aren't I?
import isn't supported by Node yet, is it? F M L.

Removed that code, it deployed fine and it says Node8 as the runtime.

**Comment by divyesm** [comment]
Hi I think this answer may also help https://github.com/eslint/eslint/issues/8366
