### ISSUE TITLE
Not depending on latest firebase-admin

### ISSUE THREAD

**Issue by kitfit-dave** [firebase/firebase-functions#423]
### Related issues

#354 
(#163)

### [REQUIRED] Version info

**node:**
Any

**firebase-functions:**
2.2.0

**firebase-tools:**
N/A

**firebase-admin:**
^7.1.0

### [REQUIRED] Test case

`npm init`

### [REQUIRED] Steps to reproduce

install as per docs:
`npm install firebase-functions@latest firebase-admin@latest --save`

### [REQUIRED] Expected behavior

To not see a warning

### [REQUIRED] Actual behavior

We see a warning:
`npm WARN firebase-functions@2.2.0 requires a peer of firebase-admin@~7.0.0 but none is installed. You must install peer dependencies yourself.`

### Were you able to successfully deploy your functions?

Yep

### Information

Looks firebase-functions need to be updated to require the correct minor revision of firebase-admin as per linked issue (#354)

**Comment by kevinajian** [comment]
Hey David,

Thanks for the feedback. We will look to address this in https://github.com/firebase/firebase-functions/pull/424.

**Comment by kevinajian** [comment]
This is updated in the 2.2.1 release. Will close this out.
