### ISSUE TITLE
Not loading .runtime.config.js when using pnpm

### ISSUE THREAD

**Issue by ChrisBrownie55** [firebase/firebase-functions#438]
### [REQUIRED] Version info

**node:**

v8.16.0

**firebase-functions:**
^2.3.0

**firebase-tools:**

6.8.0

I'm using 6.8.0 because `firebase functions:shell` doesn't work past this version

**firebase-admin:**
^7.0.0

### [REQUIRED] Test case

Here is a repro of this problem. The README file explains how to reproduce it yourself and includes screenshots of the issue failing and it sort of not failing when a fix is introduced.
https://github.com/ChrisBrownie55/firebase-functions-repro

### [REQUIRED] Expected behavior

I expect the following json value when I set the environment value of `"test"` to `"value"`. And the extra config variables:
```json
{
  "test": "value",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com",
  "projectId": "projectId"
}
```

### [REQUIRED] Actual behavior

```json
{}
```

### Were you able to successfully deploy your functions?

No error messages at deploy time but I always get `FIREBASE_CONFIG environment variable is missing` at run time.

**Comment by thechenky** [comment]
Hi @ChrisBrownie55 to set config variables for your function, please use `firebase functions:config:set KEY=VALUE` as explained in the [Set Environment Configuration docs](https://firebase.google.com/docs/functions/config-env#set_environment_configuration_for_your_project). Using `FIREBASE_CONFIG` variable and modifying `.runtimeconfig.json` file is not a supported way to configure your function. Closing this out.
