### ISSUE TITLE
Drop support for Node.js 6

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-functions#441]
All Google libraries are now dropping support for Node.js 6. It would be useful to drop it in this library too, as there are some Node.js 6-specific workarounds in the codebase that might cause some pain in modern environments, such as https://github.com/firebase/firebase-functions/blob/18c01cbdc25d8f4fccb8847f6a4be86b6c7d4960/src/providers/https.ts#L180, which prevent this class from being extend easily.

I'd be happy to bake a PR, let me know what you guys think.

**Comment by joehan** [comment]
Hey @merlinnot, thanks for the suggestion - this is something we are planning to do in the future. However, we are required to follow the deprecation timelines from Cloud Functions: https://cloud.google.com/functions/docs/concepts/nodejs-6-runtime, which states that it will be supported until April 22, 2020.

**Comment by merlinnot** [comment]
Did you consider maintaining v2 with security patches/bugfixes only and still releasing v3?

**Comment by thechenky** [comment]
What do you mean by V2 and V3?

**Comment by thechenky** [comment]
As long as Google Cloud Functions is still supporting Node 6, we cannot drop support in functions SDK. Thanks for the suggestion, though @merlinnot, let's come back to this in the future!

**Comment by merlinnot** [comment]
Hm, I forgot to reply to this one. This package is currently at major version 2. We could release v3 that drops support for Node.js 6. Node.js 6 users could still use v2 of this library.

All other libraries that Google offers did exactly that in the recent weeks.

**Comment by thechenky** [comment]
Thanks for the reply @merlinnot yeah I'm aware that other libraries are dropping support but since this library deals with user code that may still be written in Node 6 we cannot do that until GCF drops support in 2020.

**Comment by thechenky** [comment]
Hi @merlinnot after some discussion and in light of one of our main dependencies, `firebase-admin` dropping node 6 support, we are going to follow suit and update our peer dependency to `firebase-admin 8.0.0` effectively dropping Node 6 support in the `firebase-functions` SDK as well. We will need to communicate in our documentation that if someone wants to use Node 6 functions, they will need to use version <3.0.0 of the functions SDK. I realize this is pretty much what you were proposing, haha, sorry for the long turnaround. But yes, we'll be dropping Node 6 support in v3.0.0 release! Thanks for filing this issue :)

**Comment by thechenky** [comment]
@merlinnot also regarding your offer for a PR, we'd be glad to take you up on that :)
