### ISSUE TITLE
Promise not handled in https.onRequest

### ISSUE THREAD

**Issue by danprince** [firebase/firebase-functions#442]
### [REQUIRED] Version info
**node:** 8.12.0
**firebase-functions:** 2.2.0

### [REQUIRED] Test case

```js
let functions = require("firebase-functions");
let { HttpsError } = functions.https;

// This works fine and the error is presented to the caller
exports.onCallExample = functions.https.onCall(async () => {
  throw new HttpsError("permission-denied");
});

// This goes uncaught and the user sees a 500 error
exports.onRequestExample = functions.https.onRequest(async () => {
  throw new HttpsError("permission-denied");
});
```

### [REQUIRED] Steps to reproduce
Create two functions with the code above, then try calling both of them.

### [REQUIRED] Expected behavior
I would expect both types of HTTPS functions to handle errors in the same way, regardless of how they are invoked.

### [REQUIRED] Actual behavior
* `https.onCall` handles the promise rejection correctly.
* `https.onRequest` ignores the promise

It's either a bug or just confusing design that `https.onCall` wraps the handler and `https.onRequest` doesn't. It's a shame to have to switch programming styles when jumping between the functions in our codebase.

Don't think that fixing this would be a breaking change (as it's not specified what should happen if your handler returns a promise currently), so I'm happy to open a PR.

Here's what I'm using in the meantime (for anyone else running into this):

```js
let functions = require("firebase-functions");
let { HttpsError } = functions.https;

functions.https.onAsyncRequest = handler => {
  return functions.https.onRequest(async (req, res) => {
    try {
      await handler(req, res);
    } catch (error) {
      if (!(error instanceof HttpsError)) {
        console.error('Unhandled error', error);
        error = new HttpsError('internal', 'INTERNAL');
      }

      let status = error.httpStatus;
      let body = { error: error.toJSON() };
      res.status(status).send(body);
    }
  });
}

// Then elsewhere in your codebase you keep parity between the handlers

exports.onCallExample = functions.https.onCall(async () => {
  throw new HttpsError("permission-denied");
});

exports.onRequestExample = functions.https.onAsyncRequest(async () => {
  throw new HttpsError("permission-denied");
});
```

**Comment by thechenky** [comment]
This is quite possible, the `onCall` method does wrap `onRequest` as you mentioned. I have not yet looked closely at this but this might indeed be a bug.

**Comment by kevinajian** [comment]
Hey @danprince, I haven't had a chance to look into this yet, so if you have a PR ready in the meantime feel free to open that. Sorry for the delay here.

**Comment by mbleigh** [comment]
Hi Dan, this is working as intended. `onRequest` provides a standard Node.js HTTP handler endpoint -- it will not terminate unless you send something on the response or have a non-async exception.

This works just like if you have an Express handler (because it is an Express handler. You'll need to handle the errors by sending a response yourself.

```js
exports.asyncRequest = functions.https.onRequest(async (req, res) => {
  try {
    await doThing();
  } catch (e) {
    console.error('Unexpected error:', e);
    res.status(500).send('An error occurred');
  }
});
```

**Comment by danprince** [comment]
Understood, just a shame to have to remember that all `onRequest` handlers need to be wrapped in try-catch blocks. Will just stick to using my own `onAsyncRequest` handler for now.

Might be worth adding a note to the docs to explain that the `HttpsError` class won't do anything if thrown in `onRequest` handlers.
