### ISSUE TITLE
500 errors using Axios to consume server response json data

### ISSUE THREAD

**Issue by chriseickemeyerGH** [firebase/firebase-functions#443]
### [REQUIRED] Version info

**node:** v10.15.3
**firebase-functions:** ^2.2.0
**firebase-tools:** 6.6
**firebase-admin:** ~7.0.0

### [REQUIRED] Test case
Trying to perform a basic Ajax request using Axios in my React front end to consume some json data sent from my Express-Cloud function backend. Getting 500 errors

root/functions/index.js - basic json response
```
const functions = require("firebase-functions");
const express = require("express");
const app = express();
const cors = require("cors");
const admin = require("firebase-admin");
admin.initializeApp();
app.use(cors({ origin: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

app.get("/tester", (req, res) => {
  res.status(200).json({ serverData: "Hello" });
});
exports.app = functions.https.onRequest(app);
```

React component 
```
function App() {
  const [I, setI] = useState("");
  const onClick = () => {
    axios.get("/tester").then(res => {
      setI(res.data.serverData);
      console.log(I);
    });
  };
  return (
    <div>
      <button onClick={onClick}>click</button>
      <div>{I}</div>
    </div>
  );
}
```
hosting rewrites
```
 "hosting": {
    "public": "build",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "function": "app"
      }
    ]
  }
```

### [REQUIRED] Steps to reproduce

1. set up a basic FE/BE Ajax request and try to consume server data

### [REQUIRED] Expected behavior
Data is mapped to the DOM. (if this type of behavior is even possible in Cloud Functions)

### [REQUIRED] Actual behavior

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
createError.js:17 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.p.<computed> (xhr.js:78)
```

### Were you able to successfully deploy your functions?
yes

**Comment by thechenky** [comment]
This is more of a Stackoverflow question :) lots of moving parts and functions SDK is not the only dependency here. Closing this out.
