### ISSUE TITLE
Proper way to use functions triggers with TypeScript

### ISSUE THREAD

**Issue by theochampion** [firebase/firebase-functions#444]
Hi,

I'm using typescript with cloud functions triggers but I'm having trouble with TypeScript typing rules.

In fact, when I create a function trigger for storage for example:

```javascript
export const generateThumbs = functions.storage
	.bucket(PP_BUCKET_URL)
	.object()
	.onFinalize(async obj => {});
```

I keep getting typescript error for `obj` 

```bash
Parameter 'obj' implicitly has an 'any' type.ts(7006)
```

I've tried looking at the docs for the specific type of `obj` here but it's not specified -> https://firebase.google.com/docs/functions/gcp-storage-events

Would it be possible to create example usage for typescript?

I'd be happy to help on that :)

Cheers!

**Comment by thechenky** [comment]
Hi there, the type for obj is ObjectMetadata as defined here: https://github.com/firebase/firebase-functions/blob/master/src/providers/storage.ts. Adding this type annotation to your code should fix the issue for you.

**Comment by thechenky** [comment]
@theochampion I think my comment should resolve your issue. Closing this out. Please open new issue if you're still having problems.
