### ISSUE TITLE
Node 10: Cannot deploy with private packages and .npmrc 

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-functions#446]
### Related issues

None

### [REQUIRED] Version info

**node:** v10.14.1

**firebase-functions:** 2.3.1

**firebase-tools:** 6.9.2

**firebase-admin:** 7.3.0

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

Change `"engines": {
    "node": "8"
  }` to `"engines": {
    "node": "10"
  }` in `package.json`

### [REQUIRED] Expected behavior

Functions deploy as they did on `"engines": {
    "node": "8"
  }`

### [REQUIRED] Actual behavior

All functions fail to deploy. Changing the engine back to 8 results in a successful deploy. 
From the error it seems like `.npmrc` is not being detected.
```
⚠  functions[stripeWebhook(us-central1)]: Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/@firebase/util-8f596d13/dist/index.d.ts'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/@firebase/util-8f596d13/dist/index.esm.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/@firebase/util-71bc1ea3/dist/index.d.ts'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/@firebase/util-71bc1ea3/dist/index.esm.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/acorn-86ae4ed8/dist/acorn.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/functions/node_modules/.staging/@types/node-585a004e/inspector.d.ts'\nnpm ERR! code E404\nnpm ERR! 404 Not Found: @adamduren/firebase-interfaces@0.0.39\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2019-05-16T20_51_21_310Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @ preinstall: `npm --prefix functions install`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @ preinstall script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2019-05-16T20_51_27_612Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "E5138ACA"}}
```

### Were you able to successfully deploy your functions?

No

**Comment by thechenky** [comment]
Hi, this is related to the issue of missing FIREBASE_CONFIG variable and has to do with a but in Node 10 runtime where hidden files are not being uploaded properly. The fix should be rolling out to production next week. Thanks for reporting!

**Comment by kevinajian** [comment]
Since this is probably related to https://github.com/firebase/firebase-functions/issues/433 as thechenky mentioned, will close this out. Please follow the issue there, and the fix should be rolled during this week.

**Comment by vroussel35** [comment]
Hi @adamduren - don't know if you are still stuck with your issue but just in case (or for future readers) : delete the package-lock.json in your functions folder and your deployment should be working again.
