### ISSUE TITLE
firebase-admin v8.0.0 drops node v6 support

### ISSUE THREAD

**Issue by ambrice** [firebase/firebase-functions#448]
firebase-admin was updated recently to 8.0.0.  If you install per the docs, with:

npm install firebase-functions@latest firebase-admin@latest --save

You will get a warning about needing firebase-admin ^7.0.0.  But also, firebase-admin 8.0.0 dropped support for node v6, so presumably that could cause problems.  Not sure what the fix is, but maybe update the docs to install firebase-admin@7.4.0 until firebase-functions also drops v6 support?

**Comment by thechenky** [comment]
Hi @ambrice thanks for bringing this to our attention. Yes, you're right that firebase-admin 8.0.0 drops Node 6 support. We are planning to release a new major version of firebase-functions v3.0.0 in the next couple weeks where we update our admin dependency to 8.0.0, effectively dropping Node 6 support in our SDK as well.

**Comment by thechenky** [comment]
Since we're going to address this in the next release, I'm going to go ahead and close this out. Thanks again for filing!
