### ISSUE TITLE
Drop unnecessary backwards compatibility workarounds

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-functions#452]
Since we're working on a v3 release, we might want to address some deprecations/backwards compatibility workarounds. I saw some names that suggest these functionalities might no longer be necessary in newer environments, but the documentation/comments are not enough to be sure.

Someone with a better understanding of Firebase internals could look at it and see what we can do. An example: support for `LegacyEvent`.

**Comment by thechenky** [comment]
Thanks @merlinnot, this is definitely a good cleanup for us to do. I'm going to file some internal bugs for this work and keep this open.

**Comment by thechenky** [comment]
LegacyEvent has been dropped in https://github.com/firebase/firebase-functions/pull/460. Closing this out.
