### ISSUE TITLE
Peer Dependency Issue

### ISSUE THREAD

**Issue by h36ahmed** [firebase/firebase-functions#453]
### [REQUIRED] Version info

**node:**
v8.12.0

**firebase-functions:**
2.3.1
**firebase-tools:**
6.10.0

**firebase-admin:**
8.0.0
### [REQUIRED] Steps to reproduce

When I upgraded firebase-admin and firebase-functions, this is the error I get 
npm WARN firebase-functions@2.3.1 requires a peer of firebase-admin@^7.0.0 but none is installed. You must install peer dependencies yourself.

### Were you able to successfully deploy your functions?
Yes

**Comment by thechenky** [comment]
Hi @h36ahmed this will be fixed in the next major release of functions SDK. Admin SDK has dropped support for Node 6 in their latest release (8.0.0), and we cannot depend on that without dropping Node 6 support. Please use admin v7 for now.

**Comment by h36ahmed** [comment]
thank you for replying! Will do.

**Comment by keithnbrown** [comment]
What's the ETA on the next version of functions SDK? as i was struggling with this exact issue until i found this issue ticket.

Probably worth noting that this will be caused if you follow the instructions at https://firebase.google.com/docs/functions/get-started and run the command "npm install firebase-functions@latest firebase-admin@latest --save" as instructed under heading "2 - Set up Node.js and the Firebase CLI"

**Comment by thechenky** [comment]
@keithnbrown v3 has been released, so the versioning should be compatible now if you do `npm install firebase-functions@latest firebase-admin@latest --save`.
