### ISSUE TITLE
The default timezone for a scheduled function is not 'UTC' as the docs says

### ISSUE THREAD

**Issue by salah3x** [firebase/firebase-functions#461]
### Related issues
Didn't find any

### [REQUIRED] Version info

**node:**
`v10.15.3`

**firebase-functions:**
`2.3.0`

**firebase-tools:**
`6.10.0`

**firebase-admin:**
`7.0.0`
### [REQUIRED] Steps to reproduce

```
import * as functions from 'firebase-functions';
export const scheduledFunction = functions.pubsub
  .schedule('0 0 * * *')
  .onRun(handler);
```

### [REQUIRED] Expected behavior

The timezone of the scheduler should  be `UTC` as specified in the [docs](https://firebase.google.com/docs/functions/schedule-functions)

### [REQUIRED] Actual behavior
The timezone was set to `America/Los_Angeles`.
> The default region for the `scheduledFunction` function is `us-central1`

### Were you able to successfully deploy your functions?
Yep, everything is working just fine.

And I was able to set the correct timezone by explicitly setting it

```
import * as functions from 'firebase-functions';
export const scheduledFunction = functions.pubsub
  .schedule('0 0 * * *')
  .timeZone('UTC')
  .onRun(handler);
```

**Comment by joehan** [comment]
Hey @salah3x, thanks for reporting this. Sorry for the trouble here, it looks we dropped the ball when communicating with our docs writers on this one. I'm going to chat with the team to see what the default should be, and this should be fixed up soon. 

In the meantime, scheduled functions will default to America/Los_Angeles and you should be able to choose any timezone you need using ```.timeZone()```

**Comment by joehan** [comment]
Hey @salah3x, just talked with the team - the current default (America/Los_Angeles) is going to stay, and we will update the docs shortly to reflect this. Thanks again for finding this inconsistency!

**Comment by salah3x** [comment]
No problem @joehan 
I'll leave this issue opened until the docs are updated (or you can close it once the update took place)

**Comment by joehan** [comment]
Thanks again for finding this! I've submitted the fix to our docs, and they should be accurate tomorrow morning. Closing this.

**Comment by quantuminformation** [comment]
Note, all zones here

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by Appkidd** [comment]
How do we actually tell a function to at UTC? I tried setting the timezone to `Etc/UTC` but Firebase will fail to deploy.

**Comment by JamesDonnelly** [comment]
Not sure if this is something which can be changed, but I ended up on [this April 2019 Firebase Blog article](https://firebase.blog/posts/2019/04/schedule-cloud-functions-firebase-cron) when looking up how to schedule a function for midnight UTC.

The end of the article has this example, which I happily copied over:

```js
export scheduledFunctionCrontab =
functions.pubsub.schedule('5 11 * * *').onRun((context) => {
    console.log('This will be run every day at 11:05 AM UTC!');
});
```

The comment here is incorrect as it will instead use the server's default timezone. If running this on a us-central1 server, this will actually run at 6:05 PM UTC without `timeZone('UTC')` specified.
