### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mtzfactory** [firebase/firebase-functions#528]
### Related issues

https://github.com/firebase/firebase-functions/issues/457
https://github.com/firebase/firebase-functions/issues/447

All the related issues are closed...

### [REQUIRED] Version info

**node:** 10

**firebase-functions:** 2.2.0

**firebase-tools:** 7.1.0

**firebase-admin:** 6.0.0

```bash
$ yarn list --pattern firebase
yarn list v1.13.0
├─ @firebase/app-types@0.3.5
├─ @firebase/app@0.3.10
├─ @firebase/database-types@0.3.6
├─ @firebase/database@0.3.13
├─ @firebase/logger@0.1.7
├─ @firebase/util@0.2.8
├─ firebase-admin@6.0.0
├─ firebase-functions@2.2.0
└─ firebase-tools@7.1.0
```

### [REQUIRED] Test case

It was working months ago... Yesterday I switched to node 10 and it stop working, then switched to version 8 and it works...

### [REQUIRED] Steps to reproduce

Function is triggered after a Firestore action (onCreate)

### [REQUIRED] Expected behavior

Work normally (o_O)

### [REQUIRED] Actual behavior

```log
"TypeError: Cannot read property 'name' of undefined
    at snapshotConstructor (/srv/functions/node_modules/firebase-functions/lib/providers/firestore.js:126:72)
    at cloudFunctionNewSignature (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:104:28)
    at cloudFunction (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
    at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)"  
```

### Were you able to successfully deploy your functions?

Yes.

**Comment by thechenky** [comment]
@mtzfactory you need to update your functions to >3.0.1 to get Node 10 support.

**Comment by mtzfactory** [comment]
Firebase-functions 3.1.0 and node 10 works perfectly.

Sorry for the inconvenience...

**Comment by leranp** [comment]
I have the same problem , tried to switch to node 10, but didn't worked
