### ISSUE TITLE
user.create function not triggered for Phone Auth

### ISSUE THREAD

**Issue by eliezedeck** [firebase/firebase-functions#54]
### Version info

**firebase-functions:** 0.5.7

**firebase-tools:** 3.9.0

**firebase-admin:** 4.2.1

### Test case

This is the function `index.js`

```javascript
const functions = require('firebase-functions')
const admin = require('firebase-admin')

// Initialize Admin with configuration
admin.initializeApp(functions.config().firebase)


exports.fillInitialUserProfile = functions.auth.user().onCreate((event) => {
  const user = event.data
  const db = admin.database()

  return db.ref(`users/${user.uid}`).set({
    displayName: user.displayName || `Member (${user.phoneNumber})`,
    roles: []
  })
})
```

### Steps to reproduce

- Deploy the functions
- Remove existing users in the Console so that it starts anew (like a new user being created)
- Authenticate using Phone number and be sure that login was successful

### Were you able to successfully deploy your functions?

There was **no error** during deployment of the functions

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (931 B) for uploading
✔  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: updating function fillInitialUserProfile...
✔  functions[fillInitialUserProfile]: Successful update operation. 
✔  functions: all functions deployed successfully!

✔  Deploy complete!
```

### Expected behavior

- Logs should at least report errors if my function is doing something wrong
- Under functions Dashboard, the executions count should be incremented to 1.
- In the database, the users/.../* should be populated for the user

### Actual behavior

- No logs whatsoever recorded
- Under functions Dashboard, the executions count remains 0.
- In the database, the `users/.../*` is empty

**Comment by rjhuijsman** [comment]
Thanks for the report! You're entirely correct, we're currently not triggering functions for phone auth. This is a server-side bug, we'll work to get it fixed ASAP.

**Comment by cmartin81** [comment]
+1

**Comment by calebd** [comment]
I'm also not getting `user.create` events, using custom token auth here.

**Comment by rjhuijsman** [comment]
Ah, I'm sorry about that: we don't yet support triggering Cloud Functions (like `auth.user().onCreate`) on custom tokens auth. We do want to support that in the future, but we chose to launch without it so we could already bring the other forms of Auth triggers out. The same goes for login using anonymous tokens, which is also a future feature.

I also just realized that our [documentation](https://firebase.google.com/docs/auth/extend-with-functions) on Cloud Functions for Auth is very misleading in this regard; I'll fix that. Sorry about that!

**Comment by eliezedeck** [comment]
@rjhuijsman, if implementations are going to take a long time, I suggest to clarify things in the documentations first. Like what works, and which feature is missing for some parts.

It's really not cool to get excited about a new feature announcement, only to find-out it's not fully supported **yet**. I'd rather hear warnings along with the announcement, or in the documentations, than to spend time aligning my app to use the feature, and spend hours on why it's not working as expected; and then someone officially announce it's not fully supported yet.

**Comment by laurenzlong** [comment]
Thanks so much for the feedback @eliezedeck. It was not our intention to not support phone auth functions out of the gate with the launch, it was a mis-communication between teams. You are absolutely right in saying that it is better to document what is being supported and not rather than to have users spend time discovering gaps experimentally. We are sorry for the disappointment and time waste you experienced. This was not intentional, and we hope to prevent things like this from happening in the future!

**Comment by eliezedeck** [comment]
Thank you @laurenzlong for your being professional. I also appreciate you taking the time for talking to us developers as I know you lead the Firebase team in the "Firebase Functions" area. It really shows your commitment to making developer experiences better.

Please, do let us know if there are things we can help you guys with. I personally, would love to help in any way I can.

I'm developing an app on the weekends which will be used by Seventh-day Adventist church members, hopefully all over the world, running 100% on Firebase, for church management, member communications, etc... It's just starting-up, but I'll keep bug reports and inconsistencies coming so we can all have a better platform for our apps; I also have some feature requests and I'll report them next time.

@laurenzlong and @rjhuijsman, what I would love is to have all bug reports here on Github if possible, not just for Functions feature. Like having Firebase functions here is really a breeze. Github is accessible, it's more open, and easy for us developers to interact with, and we're more accustomed to it (less formality is a huge bonus). I think that's important for a platform that needs actual feedbacks from more people using it like very often.

I know it's a bit off-topic, much of this post and I'm sorry about that, but I really hope it helps in some ways.

**Comment by rjhuijsman** [comment]
Thanks again @eliezedeck! If you have any bug reports for Cloud Functions for Firebase, please do feel free to open issues here. We now also have [open-sourced client SDKs](https://opensource.googleblog.com/2017/05/open-sourcing-firebase-sdks.html) for many of the other Firebase features, please also do report any bugs for those! 

It's great to know that the public GitHub issues are appreciated, I think everybody on the Firebase team also likes the direct communications!

As for the documentation, we're working on fixing that right now. Thanks!

**Comment by laurenzlong** [comment]
Thanks for the patience kind words @eliezedeck, and that's a cool use case! 
 
I actually don't lead Cloud Functions for Firebase, that would be @inlined :) I do lead our efforts on the SDK and CLI, and definitely appreciate Github as a transparent forum to hear feedback from supportive developers like you!

**Comment by rjhuijsman** [comment]
Phone Auth now triggers Cloud Functions, as intended. Here's an example of the UserRecord object (in `event.data`) that you might receive:
```
{
  "metadata": {
    "createdAt": "2017-06-01T23:01:23.000Z",
    "lastSignedInAt": "2017-06-01T23:01:23.000Z"
  },
  "phoneNumber": "+1555123456",
  "providerData": [
    {
      "providerId": "phone",
      "uid": "+1555123456"
    }
  ],
  "uid": "C6simWCCNlO3Mdyq9PYyY1O8qPJ3"
}
```
For TypeScript users, the catch is that the `phoneNumber` field isn't in our TypeScript definition for the `UserRecord` yet. I've [filed an issue](https://github.com/firebase/firebase-admin-node/issues/34) to track that. In the mean time, consider getting the phone number from `providerData.uid` field instead.

Thanks again for the reports everyone.

**Comment by eljass** [comment]
@rjhuijsman Is there any ETA for trigger to work when creating user with custom token?

**Comment by rjhuijsman** [comment]
I'm sorry, I can't give you any timelines. I'll let the team know you asked though!

**Comment by gspuzic** [comment]
I also need triggers for custom tokens

**Comment by dylanjmcdonald** [comment]
@rjhuijsman An `onCreate` event handler for custom auth tokens is definitely something I'd love to see implemented as well. I understand it's not a simple implementation, so thanks for keeping it in mind.

**Comment by dylanjmcdonald** [comment]
@rjhuijsman An onCreate event handler for custom auth tokens is definitely something I'd love to see implemented as well. I understand it's not a simple implementation, so thanks for keeping it in mind.

**Comment by ayush97123** [comment]
> Thanks for the report! You're entirely correct, we're currently not triggering functions for phone auth. This is a server-side bug, we'll work to get it fixed ASAP.

Hey, do you guys support phone auth now?

**Comment by Infinitism** [comment]
Want to clarify, the website doesn't say phone auth is supported! But @rjhuijsman mentioned it works in 2017. Did things change since then? 

https://firebase.google.com/docs/functions/auth-events

**Comment by katowulf** [comment]
Phone Auth supported as a trigger per [this comment](https://github.com/firebase/firebase-functions/issues/54#issuecomment-305648052). Closing this out to prevent more follow ons. Custom token support should be tracked in a separate issue and debugging issues should be handled by creating a minimal repro demonstrating an issue and contacting [support](http://firebase.google.com/support).
