### ISSUE TITLE
No client info inside request

### ISSUE THREAD

**Issue by buryo** [firebase/firebase-functions#541]
I simply want to get the `fastly-client` or `fastly-client-ip` but they are undefined

### Related issues

https://stackoverflow.com/questions/57104165/not-all-headers-are-shown-with-firebase-onrequest

### Version info
**firebase-functions:** 3.1.0
**firebase-tools:** 7.1.0
**firebase-admin:** 7.2.1
**node:** 10.15.0

### Test case
```
exports.getPolls = functions.region('europe-west1').https.onRequest((req, res) => {
     console.log(util.format(req.headers))
});
```

> Result:
```
headers:
   { host: 'localhost:5001',
     connection: 'keep-alive',
     'upgrade-insecure-requests': '1',
     'user-agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3370.152 Safari/537.36',
     accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
     'accept-encoding': 'gzip, deflate, br',
     'accept-language': 'en,nl;q=0.9,tr;q=0.8',
     cookie: 'io=AVNO7ouAHOYCkVK8ADSD',
     'if-none-match': 'W/"5-qvTGHdzV6LKavt4PO0gs2a6pQ00"' 
    },
```

### Expected behavior

I expect a result given like in this [Gist](https://gist.github.com/katowulf/6fffffb45ee5cbfbca6c3511e5d19528#gistcomment-2674393)

I want to get the client-ip

### Were you able to successfully deploy your functions?
`Firebase serve` runs without errors

**Comment by buryo** [comment]
I have created a super new Firebase project and files, just tried to `console.log(request)` like this:
```
exports.helloWorld = functions.https.onRequest((request, response) => {
    console.log(util.format(request.headers));
});
```
Got the same result

**Comment by kevinajian** [comment]
Hi @buryo,

I noticed you said you're doing `firebase serve`, and it looks like your headers are from the emulator, which won't have the information you're expecting. Have you tried doing `firebase deploy` with the same function and testing the URL? On my end with your `helloWorld` I am getting the expected headers, so hopefully that works for you.

**Comment by buryo** [comment]
Hi @kevinajian,

Thank you for taking the time to help!
I noticed when I am doing `firebase deploy` and checking the `logs` on firebase console I am getting quite different headers.

The headers I got:
```
{ 
host: 'europe-west1-vote-app-23.cloudfunctions.net',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3301.100 Safari/537.36',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en,nl;q=0.9,tr;q=0.8',
  'cache-control': 'max-age=0',
  forwarded: 'for="***ip adress here***";proto=https',
  'function-execution-id': 'rtxgo65hbdgl',
  'if-none-match': 'W/"135-kGXhF5pBHxN0aGaNmODCZG8/bic"',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'none',
  'sec-fetch-user': '?1',
  'upgrade-insecure-requests': '1',
  'x-appengine-city': 'amsterdam',
  'x-appengine-citylatlong': '*****',
  'x-appengine-country': 'NL',
  'x-appengine-default-version-hostname': '*****-tp.appspot.com',
  'x-appengine-https': 'on',
  'x-appengine-region': '**',
  'x-appengine-request-log-id': '5d4f155b00ffff0bbd11cf07e0b2bf80001657a44383531656434623739634535353239362d7470000134356434653237363666338656165323133374032661339303639353834643531653a34020100',
  'x-appengine-user-ip': '***ip adress here***',
  'x-cloud-trace-context': 'acab95fa7fd12h8cfe4c09a8fcf1c10f/142654856727641423157;o=1',
  'x-forwarded-for': '***ip adress here***',
  'x-forwarded-proto': 'https',
  connection: 'close' 
}
```

`x-forwarded-for` is what I was looking for, thank you

**Comment by koistya** [comment]
@buryo, @kevinajian while the client's IP is detected correctly, I'm always getting `"x-appengine-country": "ZZ"` header. It seems like Firebase doesn't pass the client's ID to the app engine correctly.
