### ISSUE TITLE
Trigger a function when hosting is complete

### ISSUE THREAD

**Issue by Rafi993** [firebase/firebase-functions#546]
Is there a way to trigger cloud function when Firebase hosting has succeeded ? I need to update a collection with latest build version when Firebase hosting has succeeded so that I could ask users to refresh their app to update it. Is there a way to do this now other than manually triggering cloud function.

**Comment by thechenky** [comment]
Hello @Rafi993 thanks for the question. Hosting triggers unfortunately are not currently supported. However, I will relay this as a feature request into our internal tracker. FYI @Memeriaj 😄
