### ISSUE TITLE
After following your sample code below to fix CORS problem in our web app, the CORS still happened in our web app on Firebase calling our Firebase Cloud Functions file 

### ISSUE THREAD

**Issue by eGlobeBizCom** [firebase/firebase-functions#548]
### Related issues

I reported this bug/issue on another page, but it is not solved. I just let you know that this issue below may be a bug.
https://github.com/firebase/firebase-js-sdk/issues/2072

My past tech issues sent to Firebase Support Team have not been solved yet.

**Comment by blakezeisler** [comment]
One change that caught me is that when creating a cloud function it used to set the default permission to allUsers to invoke the function, but it no longer has that set by default. It’s not the most secure option, but you can try to set your permission on the function to allow allUsers to invoke the function (and later lock it down for security).

**Comment by taeold** [comment]
Hey @eGlobeBizCom. We are few years late on responding to this issue.

If you are still having problems, please let us know. It would help us if you can share your latest code and configuration if different from what is posted at https://github.com/firebase/firebase-js-sdk/issues/2072.
