### ISSUE TITLE
No permission to view the "datastore provider" access request form

### ISSUE THREAD

**Issue by agonbina** [firebase/firebase-functions#55]
This is not really an issue with the functions SDK but since the form to request access to the datastore provider is listed in the README I am reporting it here. 

This is what I am seeing in the form page:

```
You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. Learn More.
```

Thanks!

**Comment by laurenzlong** [comment]
It's been fixed! Here's the link: https://services.google.com/fb/forms/firebasealphaprogram/

**Comment by agonbina** [comment]
Hi @laurenzlong, it seems like my account was whitelisted for the "firebase alpha" program and I am able to create functions that (should) respond to google cloud datastore events, using the undocumented API for this provider. 

However the functions never trigger when I create a new entity in the datastore. Do I need to request some special access permissions to have the google cloud datastore integration with firebase functions enabled?

Thanks :)
