### ISSUE TITLE
"View all from this execution" doesn't capture all logs

### ISSUE THREAD

**Issue by nfarina** [firebase/firebase-functions#554]
### [REQUIRED] Version info

**node:**

"v10 beta" (cloud)

**firebase-functions:**

3.2.0

**firebase-tools:**

7.2.4

**firebase-admin:**

8.3.0

### [REQUIRED] Test case

This is more of a question based on an incident that happened in production.

### [REQUIRED] Steps to reproduce

I can work to make a reproducible test case if this behavior is not "by design".

### [REQUIRED] Expected behavior

I would expect that all logs related to a single function execution would be tagged with the same execution ID.

### [REQUIRED] Actual behavior

Most of the time, the logs captured by our Firebase Functions in production are all tagged with the correct execution ID.

However, we have observed one case where a log entry (critically, a stack trace) was tagged with a subsequent unrelated execution ID.

I can imagine this happening if the execution ID is simply time-based; our functions operate asynchronously so many functions could be running at once. I'd imagine you would have to use something like continuation local storage to keep multiple async executions separated logically.

My question is - is the execution ID expected to be correct even if parallel async functions are operating? 

### Were you able to successfully deploy your functions?

Yes

**Comment by nfarina** [comment]
Following up with the specific incident that occurred. 

Here's an execution `ztbdi86gt660` that failed:

<img width="1090" alt="Screen Shot 2019-09-04 at 8 57 47 AM" src="https://user-images.githubusercontent.com/117280/64271431-2afad580-cef2-11e9-9c82-59840ec02a8a.png">

Note that there is no error here, even though an exception was raised and logged and the functions returned a `500` error.

"Later" (about 1 second later), the exception shows up in another unrelated execution `ztbd3qh9nhpm`:

<img width="1472" alt="Screen Shot 2019-09-04 at 8 57 59 AM" src="https://user-images.githubusercontent.com/117280/64271594-6eedda80-cef2-11e9-98ac-154c83550ea8.png">

**Comment by elvisun** [comment]
Sorry for the late response, we don't think what you experienced is WAI. But since this issue is pretty old, we think it might have been fixed by the google cloud functions team already. If you are still experiencing this, please reach out to Google Cloud's support team.

https://cloud.google.com/functions/docs/getting-support
