### ISSUE TITLE
FIREBASE_CONFIG and GCLOUD_PROJECT aren't set in Node.js v10 function environment

### ISSUE THREAD

**Issue by kossnocorp** [firebase/firebase-functions#563]
### Related issues

Here are a couple of similar issues that were closed few months back:

- https://github.com/firebase/firebase-functions/issues/433
- https://github.com/firebase/firebase-functions/issues/437

### [REQUIRED] Version info

**node:**

Node.js v10 (v10.16.0 locally, but that's unrelated)

**firebase-functions:**

`firebase-functions@3.2.0`

**firebase-tools:**

`firebase-tools@7.3.2`

**firebase-admin:**

`firebase-admin@8.2.0`

### [REQUIRED] Test case

Not applicable. Firebase project id is `backup-fire-staging`.

### [REQUIRED] Steps to reproduce

I deploy my barebone Firebase app and get in the Functions logs:

```
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail
```

### [REQUIRED] Expected behavior

I expect to not get the error and have a bunch of environment variables in `process.env` such as `FUNCTION_NAME`, `GCLOUD_PROJECT`, `FIREBASE_CONFIG`, etc.

### [REQUIRED] Actual behavior

I get the error:

```
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail
```

...and also the `process.env` lacks variables accessible in other functions:

```
{
  "NO_UPDATE_NOTIFIER": "true",
  "FUNCTION_TARGET": "ping",
  "NODE_OPTIONS": "--max-old-space-size=256",
  "NODE_ENV": "production",
  "PWD": "/srv/functions",
  "HOME": "/root",
  "DEBIAN_FRONTEND": "noninteractive",
  "PORT": "8080",
  "K_REVISION": "6",
  "K_SERVICE": "ping",
  "SHLVL": "1",
  "FUNCTION_SIGNATURE_TYPE": "http",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "OLDPWD": "/srv",
  "_": "../start-functions-framework"
}
```

### Were you able to successfully deploy your functions?

Nope, all good here. Also, the functions execute and return HTTP response without any trouble.

**Comment by kossnocorp** [comment]
I found the source of the problem. I use [`@zeit/ncc`](https://github.com/zeit/ncc) to compile server code and before it was working fine but after some update, it broke. The solution for me was to mark Firebase dependencies as externals.

**Comment by manwithsteelnerves** [comment]
Is FUNCTION_NAME set automatically now? I don't see it defined. Can someone please confirm this?

**Comment by mbleigh** [comment]
It is not set. I believe only FIREBASE_CONFIG is set in node 10

**Comment by manwithsteelnerves** [comment]
I just noticed the change log. FUNCTION_NAME is replaced by K_SERVICE

Thanks mbleigh!
