### ISSUE TITLE
Unable to connect Cloud SQL with Firebase Functions (access denied error)

### ISSUE THREAD

**Issue by irohitb** [firebase/firebase-functions#564]
### [REQUIRED] Version info

**node:** 10

**firebase-functions:** 7.2.4

**firebase-tools:** 7.2.4

**firebase-admin:** 8.5.0

### [REQUIRED] Test case

In my SQL (index.js) file, I am doing something like this. The instructions here are very indentical to what is mention in [offical docs of using cloud functions with cloud SQL](https://cloud.google.com/functions/docs/sql)

```
const connectionName = config.DB_CONNECTION_NAME
console.log(`Connection name: ${config.DB_CONNECTION_NAME}`)
const configSQL = {
	host: config.DB_HOST,
	user: config.DB_USER,
	password: config.DB_PASSWORD,
	database: config.DB_DATABASE,
}

// Connection to cloud sql in production

if (!process.env.dev) {
	configSQL.socketPath = `/cloudsql/${connectionName}`
}

//SQL Config
const pool = mysql.createPool(configSQL)

// Checking if it was connected sucessfully or not on server startup
pool.getConnection((err, connection) => {
	if (err) {
		console.error('error connecting: ' + err)
		return
	}
	console.log('connected as id ' + connection.threadId)
	connection.release()
	return
})
```

And then in my main Index.js file, I am importing it and creating an endpoint like this
```
const functions = require('firebase-functions')
const admin = require('firebase-admin')
admin.initializeApp()
const glob = require("glob");
const camelCase = require("camelcase");
const mysql = require('./src/database/sql/index') // eslint-disable-line no-unused-vars
const files = glob.sync('./**/*.f.js', { cwd: __dirname, ignore: './node_modules/**'});
for(let f=0,fl=files.length; f<fl; f++){
  const file = files[f];
  const functionName = camelCase(file.slice(0, -5).split('/').join('_')); // Strip off '.f.js'
  if (!process.env.FUNCTION_NAME || process.env.FUNCTION_NAME === functionName) {
    exports[functionName] = require(file);
  }
}
```

On deploying it when I got to logs of firebase functions, it shows me the following error in my functions log 

<img width="1132" alt="Screenshot 2019-09-27 at 6 08 30 PM" src="https://user-images.githubusercontent.com/32276134/65769709-ddb8ff00-e151-11e9-8010-ff5d8812511e.png">

<img width="1355" alt="Screenshot 2019-09-27 at 6 17 19 PM" src="https://user-images.githubusercontent.com/32276134/65770260-58cee500-e153-11e9-9d97-69d4831c247d.png">

**Note: 1** I am pretty sure that my username and password are correct 
**Note: 2** I have only created the user and database in my cloud SQL settings and haven't done anything else (like setting up SSL, or whitelisting anything)
**Note: 3** Project backend, Readme.md in the repo contains some info about initializing (just in case)
**Note: 4** Yes, I am setting up my environment variables

### [REQUIRED] Steps to reproduce

```firebase deploy --only functions```

Check the function logs, This function above should log error on an error and successful thread on the connection 

```
pool.getConnection((err, connection) => {
	if (err) {
		console.error('error connecting: ' + err)
		return
	}
	console.log('connected as id ' + connection.threadId)
	connection.release()
	return
})
```

### [REQUIRED] Expected behavior

it should successfully connect to firebase 

### [REQUIRED] Actual behavior
 It should have Deployed functions 

### Were you able to successfully deploy your functions?
Yes

**Comment by andrianabeltran** [comment]
I've peaked at the issue on stackoverflow here https://stackoverflow.com/questions/58117314/er-access-denied-error-cloudsql. I'm closing this issue, but please create a customer support issue if you weren't able to configure your instance correctly. https://cloud.google.com/sql/docs/mysql/configure-ssl-instance
