### ISSUE TITLE
Question: Add max instances to runtimeOptions?

### ISSUE THREAD

**Issue by alexlouden** [firebase/firebase-functions#566]
I've been reading through #425 (@merlinnot's proposal to add `retry` to `runtimeOptions`) and I was wondering whether it would make sense to add [`max-instances`](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1beta2#google.cloud.functions.v1beta2.CloudFunction.FIELDS.int32.google.cloud.functions.v1beta2.CloudFunction.max_instances) too? Or should this wait until max-instances is out of beta?

```js
interface RuntimeOptions {
  maxInstances?: number;
  retry?: FailurePolicy | boolean ;
  memory?: '128MB' | '256MB' | '512MB' | '1GB' | '2GB';
  timeoutSeconds?: number;
}
```

At the moment all our firebase cloud functions are deployed via CD - we try and avoid using the gcloud CLI or the web console. (I've actually only recently discovered that retry and max-instances existed!)

**Comment by antonyharfield** [comment]
I was looking for this today +1

**Comment by jeffwhelpley** [comment]
I would love to have this. Is it just a matter of updating the typing? I can enter a PR if it would help.

**Comment by andrianabeltran** [comment]
Hi there, thanks for request! We don't have plans to implement this, but I'm happy to discuss your idea with the team. Can you provide more details for this proposal and implementation?

**Comment by jeffwhelpley** [comment]
@andrianabeltran I am not sure about `retry` or `runtimeOptions` but for `maxInstances` I believe the idea is to simply pass whatever value that is set to the function configuration on GCP per this spec:

https://cloud.google.com/functions/docs/max-instances

**Comment by alexlouden** [comment]
> Hi there, thanks for request! We don't have plans to implement this, but I'm happy to discuss your idea with the team. Can you provide more details for this proposal and implementation?

Hey @andrianabeltran, sorry for my delayed reply - had my laptop away for the holidays!

At the moment [you can specify](https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation) `timeoutSeconds` and `memory` for a cloud function by using:

```js
exports.myLongRunningFunction = functions
    .runWith({
        timeoutSeconds: 540,
        memory: '2GB'
    })
    ...
```

When you edit the deployed cloud function via the GCP Cloud Functions web interface in addition to the above there are the following options - you can enable "Retry on failure", and specify "Maximum function instances":

![image](https://user-images.githubusercontent.com/1332954/71866282-9541b200-3140-11ea-8162-3233596cc9c8.png)

The ability to specify a failure policy (basically a way to enable "Retry on failure") was just added - see https://github.com/firebase/firebase-functions/pull/482 and https://github.com/firebase/firebase-tools/pull/1858 (@samtstern is working on this).

I'd like to be able to specify timeout, memory, retry and also maximum function instances all via the `runWith` runtimeOptions - e.g.

```js
exports.myLongRunningFunction = functions
    .runWith({
        timeoutSeconds: 540,
        memory: '2GB',
        retry: true,
        maxInstances: 15
    })
    ...
```

The aim is to make the source code the source of truth for the cloud function's config, so we don't have to manually edit functions' config via the web interface at all - this proposal would mean the GUI, [CLI](https://cloud.google.com/functions/docs/max-instances) and the runtime options would all be at parity :)

I hope this makes sense! Please let me know if you have any more questions :)

**Comment by mbleigh** [comment]
This seems reasonable. There's an internal process for approving new API changes, and I've just kicked it off to take a look at this. I can't guarantee when we'll be able to implement, but if anyone in the community has the time to make PRs we'd be happy to review :smile:

**Comment by alexlouden** [comment]
Thanks for that @mbleigh! Is there a way to stop the bot from automatically marking this as stale?

**Comment by samtstern** [comment]
Sorry about that!  The bot will back off now.

**Comment by StatusQuo** [comment]
this feature would be great for us to handle with contingents and limit the progress of work of pubsub topic

**Comment by efiShtain** [comment]
I've patched the code to support max instances
if any one needs the patches I can share them
it requires a patch to firebase-functions and firebase-tools 
and can be easily applied using the npm patch-package module

**Comment by rafaelrene** [comment]
Adding this to runtime options would be incredibly useful. Can we do that @efiShtain?

**Comment by efiShtain** [comment]
@rafaelrene 
That's exactly what I did

I use it like this:
```
export const eosPolling = functions
    .runWith({ maxInstances: 1 })
    .pubsub.schedule('every 1 minutes')
    .onRun(PollingService.Run);
```

**Comment by StatusQuo** [comment]
@efiShtain that sounds great did you make a pull request? Maybe reference it from here would be great. Thank you 🙏

**Comment by efiShtain** [comment]
@StatusQuo 
I've opened 2 pull requests on firebase-functions and firebase-tools
It's my first time creating a pull request for google code, so not sure about the process
but you can just look and copy the copy, not so many changes

**Comment by bolds07** [comment]
any news on that?

**Comment by efiShtain** [comment]
@bolds07 
I'm waiting for reviewers to approve the pull request, out of my hands

**Comment by samtstern** [comment]
@efiShtain I am really sorry about the delays here, I ran into some technical issues on the backend with a different but similar PR (the one to enable `retryOptions`) and I am trying to get those resolved as I think they will affect this to.

**Comment by samtstern** [comment]
This issue was fixed by #624, so I am closing it.  Thank you again to everyone for your contributions and your patience, we should have moved faster and we will try and do better in the future.

**Comment by bolds07** [comment]
How does google server take in consideration the maxInstances value?
imho this is just a placebo parameter... there isnt any side effects of changing it...

I've a function with maxInstances set to 1... this function does simple return the currentTimeMillis so takes maximum 0.3 seconds to run (worst case).

**AND STILL GCF HAS 200 INSTANCES OF IT**

![Clipboard01](https://user-images.githubusercontent.com/19866062/80213795-19e10f00-8610-11ea-94e1-140b2d00fcd7.jpg)

so what is the point of that?
Documentation says that infrastructure will "try the best" to reach the `maxInstances `set but with no garantee and SOMETIMES the current instances value will exced it...

well as my graph shows THERE WASNT ANY TIME wihtout exceeding the `maxInstances ` set... and most of the time it was 15.000% over the desired value...
15.000% in what plannet this is an acceptable deviation?

im sorry if i'm being rude but it is clear that this whole parameter is just a waste of time for either you engineer team as for any developer trying to use your infrastructure

**Comment by ianitsky** [comment]
> How does google server take in consideration the maxInstances value?
> imho this is just a placebo parameter... there isnt any side effects of changing it...
> 
> I've a function with maxInstances set to 1... this function does simple return the currentTimeMillis so takes maximum 0.3 seconds to run (worst case).
> 
> **AND STILL GCF HAS 200 INSTANCES OF IT**
> 
> ![Clipboard01](https://user-images.githubusercontent.com/19866062/80213795-19e10f00-8610-11ea-94e1-140b2d00fcd7.jpg)
> 
> so what is the point of that?
> Documentation says that infrastructure will "try the best" to reach the `maxInstances `set but with no garantee and SOMETIMES the current instances value will exced it...
> 
> well as my graph shows THERE WASNT ANY TIME wihtout exceeding the `maxInstances ` set... and most of the time it was 15.000% over the desired value...
> 15.000% in what plannet this is an acceptable deviation?
> 
> im sorry if i'm being rude but it is clear that this whole parameter is just a waste of time for either you engineer team as for any developer trying to use your infrastructure

For me worked without problem. Verify any typo mistake.
