### ISSUE TITLE
Unable to resolve "path" in providers/firestore.js

### ISSUE THREAD

**Issue by IljaDaderko** [firebase/firebase-functions#567]
### [REQUIRED] Version info

**node:** 10.16.3

**firebase-functions:** 3.3.0

**firebase-tools:** 7.4.0

**firebase-admin:** 8.6.0

### [REQUIRED] Test case

Just using `firestore().collection('/myCollection').get()` throws this error

### [REQUIRED] Steps to reproduce

See `Test case`

### [REQUIRED] Expected behavior

Shouldn't error, path should be probably added in package.json?

### [REQUIRED] Actual behavior

> bundling failed: Error: Unable to resolve module `path` from `packages/my-project-firebase/functions/node_modules/firebase-functions/lib/providers/firestore.js`: path could not be found within the project.

### Were you able to successfully deploy your functions?

Yes

**Comment by IljaDaderko** [comment]
Issue is with latest babel dependencies

**Comment by sommeshEwall** [comment]
@IljaDaderko  So how you fixed this issue? Could you please share on how you fixed this.

**Comment by IljaDaderko** [comment]
@sommeshEwall It's not an issue related to functions modules like `path` and `fs` come from node env. In my case I was in a monorepo project that imported a bit of code from my functions into client, since my client didn't run in node env, path was not available to it while it was parsing that function.

I re-structured my logic and extracted "shared" code from functions into a separate file that didn't use `firestore` where path was originally coming from.
