### ISSUE TITLE
getting an Error: not supported

### ISSUE THREAD

**Issue by Industrial** [firebase/firebase-functions#570]
Hi.

I'm opening this ticket because I can't get Server Side Rendering to work with firebase.

I've searched the interwebs and found https://github.com/googleapis/nodejs-pubsub/issues/570 which said to open a new ticket in the appropriate repo, so I made this one.

#### Environment details

  - OS: Ubuntu 19.04
  - Node.js version: 10.x (Firebase)
  - npm version: 6.9.0
  - "@firebase/app": "^0.4.12",
  - "@firebase/firestore": "^1.6.2",
  - "@firebase/functions": "^0.4.21",

#### Steps to reproduce
As this comment states https://github.com/googleapis/nodejs-pubsub/issues/570#issuecomment-484081575

putting the firebase import *before* the SSR process supposedly fixes the process, but that doesn't work for me.

I've used require here instead of import to show that if you load one after the other specifically, the problem persists:
```
import express from 'express'
const { https } = require('firebase-functions')
const { serverSideRendering } = require('./middleware/server-side-rendering')
const appExpress = express()
appExpress.use(serverSideRendering)
export const app = https.onRequest(appExpress)
```

The `server-side-rendering` module imports a third party library (TradingView's charting_library) that is bundled and minified and changes the `window` scope.

What to do?

**Comment by michelepatrassi** [comment]
@Industrial a stack would help. Btw, that's exactly the error is had from `protobuf.js`. I solved it by adding process to a fake window (from `domino`) in the `server.ts` file
```
win.process = process;
```
[You can find more info in this article](https://medium.com/@michele.patrassi/angular-ssr-firebase-save-days-of-debugging-by-reading-these-fixes-fcb060e248bb?source=friends_link&sk=62bebf17f7250c3a47d43bfb38f03786), with also other errors I encountered with Angular SSR + Firebase
