### ISSUE TITLE
Can you use node's experimental-modules flag with firebase functions?

### ISSUE THREAD

**Issue by Dean-NC** [firebase/firebase-functions#573]
I'm aware that you can use node's experimental-modules flag if you're running node from the command-line, but for firebase functions, where can I put the flag...firebase.json? functions\package.json?

I've read all the documentation I can find for firebase, and searched the issues for the functions, tools, and js-sdk on github looking for this, but I can't find any info on it.

Thanks.

**Comment by GitTom** [comment]
I doubt this is possible, but would be great if it were so I could use "--icu-data-dir=" flag (and provide the corresponding data) so that locales could be supported in the Intl and Date javascript API's.

**Comment by samtstern** [comment]
Sorry for the very late response here but this was discussed elsewhere and resolved:
https://github.com/firebase/firebase-tools/issues/1752
