### ISSUE TITLE
Functions is still using v1beta of Google Endpoints

### ISSUE THREAD

**Issue by TeamRainless** [firebase/firebase-functions#580]
### [REQUIRED] Version info

**node: 12.13.0**

**firebase-functions: 3.3.0**

**firebase-tools: 7.7.0**

**firebase-admin: 8.7.0**

### [REQUIRED] Test case

https://stackoverflow.com/questions/58759895/firebase-sendmessage-function-update-to-v1-google-cloud-endpoint

### [REQUIRED] Steps to reproduce

Today I received an email stating that calls to v0.1 and v1 beta endpoints will no longer function in January.  Firebase Functions still use these endpoints undec spec/fixtures/http.ts

```
export function mockCredentialFetch(tokenToReturn: AccessToken): nock.Scope {
  return nock('http://metadata.google.internal')
    .get('/computeMetadata/v1beta1/instance/service-accounts/default/token')
    .reply(200, tokenToReturn);
}
```

This should, of course, be updated to v1.

https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server

### [REQUIRED] Expected behavior

v1

### [REQUIRED] Actual behavior

v1beta

### Were you able to successfully deploy your functions?

Functions deployed successfully.

No.

**Comment by samtstern** [comment]
@TeamRainless sorry for the delayed response here.  The code you have referenced is actually only in tests so it should not affect your functions in production (although we should update the tests).

Have you deployed your functions since you updated to `firebase-functions` 3.x?  That should fix the metadata calls to the old API.

**Comment by TeamRainless** [comment]
I have... But I have no idea how to check if the old endpoint is still
being triggered. The email gave no method for how to check this with
firebase functions...

**Comment by samtstern** [comment]
@TeamRainless that's true it's hard to know!  I am fairly sure your issue will just be solved, if it's not you will get another email from the same automated system.  Please let me know if that happens.

Will leave this bug open mostly to track the tests fixing.
