### ISSUE TITLE
Web page for running Firebase Functions locally is missing information on custom configuration 

### ISSUE THREAD

**Issue by jbstewart** [firebase/firebase-functions#583]
### Related issues
https://github.com/firebase/firebase-functions/issues/294
https://github.com/firebase/firebase-functions/issues/476

### [REQUIRED] Version info
**node:**
v8.16.1

**firebase-functions:**

**firebase-tools:**
7.4.0

**firebase-admin:**

### [REQUIRED] Test case
The linked issues call out that directions for supplying custom configuration variables can be found on the web page for ***Run functions locally***, however at this time, there is no reference to this, and specifically no reference to the `.runtimeconfig.json` file on that page. 

### [REQUIRED] Steps to reproduce
Look on the web page:
https://firebase.google.com/docs/functions/local-emulator#serve_http_functions_from_the_command_line
for instructions on using the `functions:config:get > .runtimeconfig.json` command to supply custom configuration to Firebase Functions running locally.

### [REQUIRED] Expected behavior
The web page should include these instructions.

### [REQUIRED] Actual behavior
The web page does not include these instructions.

### Were you able to successfully deploy your functions?
N/A

**Comment by samtstern** [comment]
@jbstewart thanks for calling this out!  I will get the docs updated.  Going to close this issue here since there's nothing to be done in this repo.
