### ISSUE TITLE
When unit-testing, process.env.GCLOUD_PROJECT is not set.

### ISSUE THREAD

**Issue by rudolfolah** [firebase/firebase-functions#585]
### Related issues

- https://github.com/firebase/firebase-functions/issues/437
- https://github.com/firebase/firebase-functions/issues/433

### [REQUIRED] Version info

**node:** v10.17.0

**firebase-functions:**

**firebase-tools:** 7.6.2

**firebase-admin:**

### [REQUIRED] Test case

Code:

```javascript
exports.hello = functions.auth.user().onCreate(async (user) => {
  /* ... */
  return ref.set({ a: 1 });
});
```

Test Case:

```javascript
describe('hello', () => {
    it('do stuff', (done) => {
      const wrapped = test.wrap(myFunctions.hello);
      wrapped(user).then(snapshot => {
        done();
      });
    });
  });
```

It seems to be fixed when I do not return the Promise from `ref.set` and instead do an await and then return whatever the result is supposed to be:

```javascript
exports.hello = functions.auth.user().onCreate(async (user) => {
  /* ... */
  const result = await ref.set({ a: 1 });
  return result;
});
```

### [REQUIRED] Steps to reproduce

Run the unit test, sometimes it will show the error but on a subsequent run the tests will run without fail.

### [REQUIRED] Expected behavior

Don't have the error message?

### [REQUIRED] Actual behavior

```
1) Cloud Functions onFirstLogin should set the initial data for a user
  Message:
    Error: process.env.GCLOUD_PROJECT is not set.
  Stack:
    Error: process.env.GCLOUD_PROJECT is not set.
        at UserBuilder (functions/node_modules/firebase-functions/lib/providers/auth.js:41:19)
        at Function.get (functions/node_modules/firebase-functions/lib/cloud-functions.js:148:17)
        at hasPath functions/node_modules/lodash/lodash.js:6131:24)
        at Function.has (functions/node_modules/lodash/lodash.js:13159:32)
        at Object.wrap (functions/node_modules/firebase-functions-test/lib/main.js:28:19)
        at UserContext.it (frontend/functions/spec/index.spec.js:53:28)
        at <Jasmine>
```

**Comment by Lucas-Geitner** [comment]
[same here]

**Comment by mbleigh** [comment]
How are you executing your tests? The functions execution environment expects certain variables to be set to be able to work. Are you following the guidance in: https://firebase.google.com/docs/functions/unit-testing

**Comment by rudolfolah** [comment]
@mbleigh  I'll try and run some tests today and let you know. Though I don't see GCLOUD_PROJECT mentioned on that documentation page.

**Comment by rudolfolah** [comment]
I found a nice way around this by running the Firebase emulators like this:

```json
    "test": "firebase emulators:exec 'jasmine'"
```

Documentation for that is here: https://firebase.google.com/docs/functions/local-emulator#run_the_emulator_suite
