### ISSUE TITLE
Function not firing on auth user delete. User is deleted on auth but my the trigger never occurs.

### ISSUE THREAD

**Issue by jamie-chapman** [firebase/firebase-functions#586]
### [REQUIRED] Version info

**node:**

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

**Comment by kevinajian** [comment]
Thanks for filing.

This is an issue when using firebase admin to delete users. There's a fix on the way, will update this when it hits prod.

Internal tracking 145006195

**Comment by raulcontrerasrubio** [comment]
Using the web sdk to delete a user is also not firing the trigger. It only removes the user from auth.

**Comment by red42** [comment]
Please refer to the discussion here: https://groups.google.com/forum/#!msg/firebase-talk/ROXTbooVzlM/vY1kh9TqAQAJ

I'm observing the exact same behavior as the users on the thread: onCreate() is triggered instead of onDelete()

The last onDelete trigger was fired on my project on Nov.21st at 7:07:47.579 PM UTC

**Comment by aphichat** [comment]
> I'm observing the exact same behavior as the users on the thread: onCreate() is triggered instead of onDelete(). The deletion was executed using the client SDK on Android, NOT the admin SDK.

I have the same behaviour as triggering `onCreate()` instead of `onDelete()`
Executed from Firebase Functions as `functions.auth.user().onCreate()`

Last onDelete trigger fired on: Nov 17 2019 2:18:38.190 PM

package.json

```
"firebase-admin": "^8.3.0",
"firebase-functions": "^3.2.0",
```

**Comment by red42** [comment]
As of 2019-11-29 the onDelete triggers started firing again on my project.

**Comment by jamie-chapman** [comment]
Looking good for me too!
