### ISSUE TITLE
Error: Error parsing triggers: Cannot find module

### ISSUE THREAD

**Issue by vitaly87** [firebase/firebase-functions#59]
I am trying to deploy my firebase function to cloud but getting an error:

> Error: Error parsing triggers: Cannot find module 'EmailData'

1.I compile my ts file to js.

2.the build of ts ok... my code looks like:

the ts that importing the file...

`var EmailDataClass = require("EmailData");`
and the file it self:

```
class EmailData {....
}export = EmailData;
```
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'EmailData'

**Comment by laurenzlong** [comment]
@vitaly87 Please reopen if @mbleigh 's suggestion doesn't solve the issue. And please use the template next time.

**Comment by vitaly87** [comment]
Thank yes you right I did mixed with typescript and es 6....
