### ISSUE TITLE
Depoying Functions fails with the message  "Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "npm_install..."

### ISSUE THREAD

**Issue by mtsap** [firebase/firebase-functions#592]
### [REQUIRED] Version info

**node:** 10.16.2 / 8.11.1

**firebase-functions:** 3.3.0

**firebase-tools:** 7.8.1 / 7.9.0

**firebase-admin:** 8.7.0 /8.8.0

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

Trying to deploy one specific function from my project should not fail

### [REQUIRED] Actual behavior

Deploying one specific function from my project fails. 
Tries to deploy different functions.
Tried with  `"engines": { "node": "8" }` and `"engines": { "node": "10" }`  but it failed . again.
Delete package-lock.json and reinstalled node_modules with the same result.

`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"mich.tsap@gmail.com"},"requestMetadata":{"requestAttributes":{},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/actisense-dev/locations/europe-west1/functions/groupE-hiFiLoFiCalculationsHttps"}`

### Were you able to successfully deploy your functions?

When deploying i get the following error in my console.

```⚠  functions[groupE-hiFiLoFiCalculationsHttps(europe-west1)]: Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/yargs-b279f6c4/LICENSE'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/yargs-b279f6c4/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@google-cloud/firestore-8f58c2ea/README.md'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/stackframe.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/LICENSE.txt'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/stacktrace.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/date-fns-1ff3f002/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/lite.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/reactnative.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/AsyncGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/status.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/README.md'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncGeneratorDelegate.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/thread.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncIterator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/transport.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/mongodb-291237d0/lib/async/async_iterator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncToGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/user.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@types/node-f1c8db24/globals.d.ts'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@firebase/auth-1b85ce5b/dist/auth.esm.js.map'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/awaitAsyncGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/wrappedfunction.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/AwaitValue.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/breadcrumb.d.ts.map'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/mongodb-291237d0/lib/operations/bulk_write.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/firebase-admin-a1197e24/lib/auth/auth-api-request.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/classCallCheck.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/breadcrumb.js.map'\nnpm WARN tar ENOENT: no such file or directory, open


Functions deploy had errors with the following functions:
	groupE-hiFiLoFiCalculationsHttps


To try redeploying those functions, run:
    firebase deploy --only functions:groupE-hiFiLoFiCalculationsHttps


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.```

**Comment by antoarva** [comment]
+1

**Comment by mbleigh** [comment]
Is this issue still occurring?

**Comment by wwwsolutions** [comment]
> ### Related issues
> ### [REQUIRED] Version info
> **node:** 10.16.2 / 8.11.1
> 
> **firebase-functions:** 3.3.0
> 
> **firebase-tools:** 7.8.1 / 7.9.0
> 
> **firebase-admin:** 8.7.0 /8.8.0
> 
> ### [REQUIRED] Test case
> N/A
> 
> ### [REQUIRED] Steps to reproduce
> N/A
> 
> ### [REQUIRED] Expected behavior
> Trying to deploy one specific function from my project should not fail
> 
> ### [REQUIRED] Actual behavior
> Deploying one specific function from my project fails.
> Tries to deploy different functions.
> Tried with `"engines": { "node": "8" }` and `"engines": { "node": "10" }` but it failed . again.
> Delete package-lock.json and reinstalled node_modules with the same result.
> 
> `{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"mich.tsap@gmail.com"},"requestMetadata":{"requestAttributes":{},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/actisense-dev/locations/europe-west1/functions/groupE-hiFiLoFiCalculationsHttps"}`
> 
> ### Were you able to successfully deploy your functions?
> When deploying i get the following error in my console.
> 
> ```
> Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/yargs-b279f6c4/LICENSE'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/yargs-b279f6c4/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@google-cloud/firestore-8f58c2ea/README.md'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/stackframe.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/LICENSE.txt'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/stacktrace.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/date-fns-1ff3f002/index.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/lite.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/reactnative.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/AsyncGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/status.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/algoliasearch-1012c148/README.md'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncGeneratorDelegate.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/thread.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncIterator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/transport.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/mongodb-291237d0/lib/async/async_iterator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/asyncToGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/user.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@types/node-f1c8db24/globals.d.ts'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@firebase/auth-1b85ce5b/dist/auth.esm.js.map'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/awaitAsyncGenerator.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/wrappedfunction.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/AwaitValue.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/breadcrumb.d.ts.map'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/mongodb-291237d0/lib/operations/bulk_write.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/firebase-admin-a1197e24/lib/auth/auth-api-request.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@babel/runtime-a76c0d53/helpers/esm/classCallCheck.js'\nnpm WARN tar ENOENT: no such file or directory, open '/workspace/node_modules/.staging/@sentry/types-bc7c5fb7/dist/breadcrumb.js.map'\nnpm WARN tar ENOENT: no such file or directory, open
> 
> 
> Functions deploy had errors with the following functions:
> 	groupE-hiFiLoFiCalculationsHttps
> 
> 
> To try redeploying those functions, run:
>     firebase deploy --only functions:groupE-hiFiLoFiCalculationsHttps
> 
> 
> To continue deploying other features (such as database), run:
>     firebase deploy --except functions
> 
> Error: Functions did not deploy properly.```
> ```

 I have exactly the same problem. With the same setup.

**Comment by antoarva** [comment]
Usually this error occurred when you try to deploy a function with a custom node module which is located in a private repository and firebase cannot have access to that.

**Comment by MNorgren** [comment]
Also encountering this. How do we get around it?

**Comment by jpinilloslr** [comment]
@MNorgren It looks like you have to provide an .npmrc file inside your functions folder.
https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#using_private_modules

**Comment by danipralea** [comment]
Hello guys. I am also having this issue.
@jpinilloslr I was going crazy over this, because I didn't even knew what was wrong. I can narrow it down to a private package, but distributed via GitHub Packages. I did the instructions here [https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#authenticating-with-a-personal-access-token](url) but I am still having the error.
![Screenshot 2020-05-15 13 32 05](https://user-images.githubusercontent.com/768893/82041223-8059ca00-96b0-11ea-89af-d3974d1b725b.png)
And I also have my `.npmrc` file with the instructed lines:
![Screenshot 2020-05-15 13 34 09](https://user-images.githubusercontent.com/768893/82041398-c9118300-96b0-11ea-986c-531e5c50e214.png)

And I still get the error. I event re-init the firebase project, cleaned everything that I could

**Comment by mbleigh** [comment]
If anyone else runs into an issue like this, please [contact support](https://firebase.google.com/support/troubleshooter/contact) as this is not an issue with the `firebase-functions` SDK and we won't be able to help much here.
