### ISSUE TITLE
Firebase.json redirects send POST request to GET

### ISSUE THREAD

**Issue by abdellahaski** [firebase/firebase-functions#594]
### Version info

**node:** v10.16.3

**firebase-functions:** 3.3.0

**firebase-tools:** 7.9.0

**firebase-admin:** 8.8.0

### [REQUIRED] Test case
index.js : 
```
const app = express();
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  res.header("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE");
  res.header("Content-Type", "application/json");
  res.header("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
  res.header("Pragma", "no-cache"); // HTTP 1.0.
  res.header("Expires", "0"); // Proxies.

  next();
});
app.use(compression());
app.use(responseTime());
app.use(express.static("public"));

app.get("/api/test", (req, res) => {
  res.send("GET");
});
app.post("/api/test", (req, res) => {
  res.send("POST");
});
exports.app = functions.region('europe-west1').https.onRequest(app);
```

Firebase.json:

```
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "/api/**",
        "function": "app"
      }
    ],
    "redirects": [
      {
        "source": "/api/:any*",
        "destination": "https://europe-west1-[PROJECT-ID].cloudfunctions.net/app/api/:any", // <--------
        "type": 301
      },
    ]
  }
}
```

### Steps to reproduce

Sending a POST http request via Postman or an other client

### Expected behavior
Getting response from app.post(....

### Actual behavior
Getting response from app.get(....

### Were you able to successfully deploy your functions?
Yes it has been deployed successfully

I'll explain why I'm using that redirect in the first place, Well you might notice that I'm deploying the function on a specific region (functions.region('europe-west1').https.onRequest(app))
If I don't use that redirect (firebase.json) all request to this function using the normal Firebase domain name get me to https://us-central1-[PROJECT_ID].cloudfunctions.net/... and since the function is on another region the request fail, so the solution that I found is that I can manualy redirect all request to my function directly to https://europe-west1-[PROJETC_ID].cloudfunctions.net/...
Yes it's a silly solution but it works and it's the only one that I found working.
This happens because Firebase hosting is only on us-central [https://github.com/firebase/firebase-tools/issues/842](https://github.com/firebase/firebase-tools/issues/842)

**Comment by mbleigh** [comment]
It is not possible to redirect a `POST` request. Redirects work via the `Location` header being recognized in the browser, and only GET is supported. See e.g. [this SO post](https://softwareengineering.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect).

**Comment by devlucem** [comment]
UPDATE: As of August, POST rewrites are now supported!

**Comment by devatlantis** [comment]
Are there any plans to implement 308 redirects preserving the original request method and body?

**Comment by gediminas-eldorado** [comment]
Are there any plans to implement 308 redirects preserving the original request method and body?

**Comment by devlucem** [comment]
All redirects maintain their initial configurations

**Comment by gediminas-eldorado** [comment]
Hm... you're right. Sorry. Had some confusion about how redirects work, but now I've read up on them, and it seems clear that whether the original method is respected, has nothing to do with the redirector (in this case firebase), but how the client chooses to act on the 301 response.

Thanks.
