### ISSUE TITLE
Firestore: ReadTime not populated

### ISSUE THREAD

**Issue by schmidt-sebastian** [firebase/firebase-functions#599]
See https://github.com/firebase/firebase-js-sdk/issues/2459

It looks like `data.value.readTime` does not exist for a Firestore Event. When testing, this causes `snapshotConstructor` [to set the readTime argument](https://github.com/firebase/firebase-functions/blob/master/src/providers/firestore.ts#L157) to `undefined`. If the read time is not available, we should use the update or create time of a document.

**Comment by iwikal** [comment]
Not sure what "when testing" means - this happens to me in production.

**Comment by schmidt-sebastian** [comment]
@laurenzlong Is this something you could take care of?

**Comment by iwikal** [comment]
I've created a pull request that fixes this. Anyone care to take a look?

**Comment by schmidt-sebastian** [comment]
cc @inlined

**Comment by inlined** [comment]
Wouldn't one conceivably argue that "readTime" is the event timestamp?

**Comment by schmidt-sebastian** [comment]
Will this make a difference in practice? Functions should only be invoked if the updateTime changes, at which point the updateTime and the eventTime might be the same. If the eventTime is newer, the document on the backend could have changed again. In this case, we should err on the side of caution and use the older timestamp as we want the snapshot data and the read time to be consistent.

**Comment by iwikal** [comment]
I don't really know anything, but the way I see it the purpose of these fields is to guarantee the user that the document was definitely known to be in this state as represented by the snapshot, from updateTime until readTime. So if there's any risk that the document has updated again before eventTime, we best not use it.

Said another way: updateTime is the earliest point in time at which we can be sure that the document was in this state on the database, and readTime is the latest.
