### ISSUE TITLE
Firestore .onWrite context.auth data

### ISSUE THREAD

**Issue by Karman40** [firebase/firebase-functions#600]
https://firebase.google.com/docs/reference/functions/cloud_functions_.eventcontext.html#auth

This would be a very useful feature if it were available for Firestore as well. Do you have any plans for this?

**Comment by Karman40** [comment]
**Any comments?**

**Comment by rphlmr** [comment]
@Karman40 
Hi, firestore trigger has this : https://github.com/firebase/firebase-functions/blob/8039e0286eebb054275dae6763e50e76c2e05d02/src/providers/firestore.ts#L195

Or maybe it's something else ?

**Comment by alixaxel** [comment]
@rphlmr That's it, but the `EventContext.auth` is not populated for Firestore sadly. :disappointed: 

https://github.com/firebase/firebase-functions/blob/8039e0286eebb054275dae6763e50e76c2e05d02/src/cloud-functions.ts#L62-L77

**Comment by wceolin** [comment]
Unfortunately, this feature won't be implemented. See https://github.com/firebase/firebase-functions/issues/300#issuecomment-465471983

**Comment by andrianabeltran** [comment]
Closing this out, please refer to the issue linked above
