### ISSUE TITLE
[FR] Clarification on multiple DataSnapshot types, and nullable ref for snapshot

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-functions#602]
When typing the snapshot I am not clear on what type to use from the following:

![image](https://user-images.githubusercontent.com/216566/71663005-3d7c0300-2d5c-11ea-983e-3066e8727592.png)

Also I am not clear why snapshot ref is nullable:

![image](https://user-images.githubusercontent.com/216566/71663044-60a6b280-2d5c-11ea-9f4c-dea8b5915e18.png)

**Comment by samtstern** [comment]
@quantuminformation sorry for the very very slow response here!

1. You should use the types from `firebase-admin` wherever possible.  Don't import the `DataSnapshot` type from `firebase-functions/lib`.
2. `ref.parent` is nullable because the root ref (`/`) does not have a parent.

**Comment by quantuminformation** [comment]
many thx
