### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by piuccio** [firebase/firebase-functions#61]
When I install this package I get the warning

`npm WARN firebase-functions@0.5.7 requires a peer of firebase-admin@~4.2.1 but ...` 

...but `firebase-admin` is already at version `5.0.0`

**Comment by laurenzlong** [comment]
Hey @piuccio it's actually a strict dependency requirement (that's why there's ~ instead of >), so firebase-admin must be 4.2.x, nothing higher, nothing lower. Make sure you run 
[npm install --save firebase-admin@4.2.1 ](url)
in your functions directory.

**Comment by piuccio** [comment]
I guess my point was that it's probably time for this package to update to `firebase-admin 5`. Any plans for that update?

**Comment by laurenzlong** [comment]
Gotcha, thanks for the clarification. Will add this to my to-do list. The reason why we don't update our dependencies automatically every time there's a new version of firebase-admin is because there can be breaking changes so we want to test extensively before upgrading.

**Comment by laurenzlong** [comment]
Submitted PR for this: https://github.com/firebase/firebase-functions/pull/66
