### ISSUE TITLE
Firestore transaction failing with error TS2532 inside cloud function

### ISSUE THREAD

**Issue by Alfie-AD** [firebase/firebase-functions#613]
Trying to update a field in a document with transaction via cloud function like so ...

```
export const updatePrime = functions.https.onCall(async (data) => {
 
    const docRef = db.doc(`/Path/toDocument`);
    await db.runTransaction(t => {
        return t.get(docRef)
            .then(doc => {
                if (doc.data().prime === null) {
                    t.update(docRef, {
                        "prime": 1
                    });
                }
            });
    }).then(result => {
        console.info('Transaction success!', result)
    })
        .catch(err => {
            console.error('Transaction failure:', err)
        });
});
```
This is how all the samples i've come across on stackoverflow looks like.
I am unable to deploy though and i get a pesky little error.
![Screenshot (183)](https://user-images.githubusercontent.com/45766571/72764290-5c451b00-3bdf-11ea-8aa7-27bd1170e170.png)

PLEASE HELP

**Comment by swftvsn** [comment]
Looks like typescript problem more than firebase - maybe ask in stackoverflow?

**Comment by Alfie-AD** [comment]
Solve it by changing "strict" type checking to false in the tsconfig.json file.
Explanation on [stackoverflow](https://stackoverflow.com/questions/55882515/cloud-functions-typescript-object-is-possibly-undefined-ts2532). Thanks @swftvsn
