### ISSUE TITLE
Firebase Console - Functions Logs viewer loads indefinitely

### ISSUE THREAD

**Issue by JamieCurnow** [firebase/firebase-functions#614]
### [REQUIRED] Version info

**node: 10**

**firebase-functions:**
"^3.3.0"
**firebase-tools:**
7.8.0

**firebase-admin:**
"^8.8.0"
### [REQUIRED] Test case

I have a strange intermittent issue on the firebase console for functions logs at this address:(https://console.firebase.google.com/u/0/project/YOUR_PROJECT_NAME/functions/logs?severity=DEBUG)

The spinner spins forever as the logs are attempting to be retrieved. In my network panel I get a load of POST requests returning a 500 code. The requests are to url:
https://logging.clients6.google.com/v2/entries:list?key=***Actual***Key***Here***&alt=json

The response I'm getting from all of these requests is:
```
{
  "error": {
    "code": 500,
    "message": "Failed to convert server response to JSON",
    "status": "INTERNAL"
  }
}
```
This is preventing me from debugging any errors in production as I can not see any error logs or debug logs for my Cloud functions.

I also get the same error when trying to view cloud function logs in the google cloud console logs viewer at this address:
https://console.cloud.google.com/logs/viewer

We're using Bunyan for logging, which we also use in other projects without any issues.

I've attached a screenshot for context.
<img width="1438" alt="Screenshot 2020-01-22 at 12 34 52" src="https://user-images.githubusercontent.com/29151736/72894675-c65edc80-3d13-11ea-9561-969c047902e0.png">

### [REQUIRED] Steps to reproduce
Deploy a cloud function that logs to console or logs or throws an error. Basically anything that you would expect to show in the Firebase Console for Functions Logs
Initiate the function to produce said log.
Check the log viewer here:
https://console.firebase.google.com/u/0/project/YOUR_PROJECT_NAME/functions/logs?severity=DEBUG

### [REQUIRED] Expected behavior
Log should be shown in log viewer

### [REQUIRED] Actual behavior
Log viewer spinner spins indefinitely and mentioned 500 errors are found in the console.

### Were you able to successfully deploy your functions?
Yes, functions deploy as expected

**Comment by andrianabeltran** [comment]
Hi @JamieCurnow! You should be able to view logs and errors in that viewer for your project using that url you provided (replacing the project id with YOUR_PROJECT_NAME). There might have been a bug in the console at the time you experienced the error. 

If you are still experiencing this, can you submit a support ticket to https://firebase.google.com/support/troubleshooter/report/bugs/ and close this ticket out? Thanks!
