### ISSUE TITLE
Unable to call local server/db from cloud functions

### ISSUE THREAD

**Issue by sambhav2612** [firebase/firebase-functions#621]
Hi,

We have a firebase setup on our server and service to start a new instance and communicate with the local DB as and whenever required. We added cloud functions yesterday and have been stuck on **how to import and call any exported function outside the `functions/` directory/scope**. 

The server is based on Keystone v5 and we start firebase while migrating data, so that as soon as the app starts the firebase instance initializes as well.

Here's our directory structure to help you guys understand:

```
-- api
  -- controllers
  -- services
-- functions
  -- index.js
-- models
-- utils
  -- firebaseService
```

Now we need to call an exported function in `firebaseService` from `functions/index.js` so that we may save in local DB whenever some event is triggered on the deployed cloud function.

Right now while deploying (the boilerplate function that is provided on initialization i.e., `helloWorld` using the command: `firebase deploy --only functions:helloWorld`), we get the following error:

```
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '../utils/firebaseService'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:7:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

When I remove the line where I'm trying to import the exported functions, it deploys like a charm.

I'm not sure what's wrong, it's become a nightmare for us and it'd surely be a rather big help if any of you guys can help us with this issue :smile:

**Comment by andrianabeltran** [comment]
Hi @sambhav2612, how are you importing functions? Can you share a code snippet? Thanks!

**Comment by sambhav2612** [comment]
@andrianabeltran I can't, it's under my NDA.

**Comment by joehan** [comment]
Hey @sambhav2612, I think the issue you are running into is that when you deploy functions with firebase, we only upload the ./functions folder. If you go to the Function Details page of Cloud Console and click edit, you'll see that only code contained within the functions folder has been uploaded. 

To fix your issue, you have a few options:
 - Move utils and any other files/directories you need to access from your function code to within your functions directory.
- If you aren't comfortable changing your directory structure like that, you can
  move the package.json that is in your functions folder up 1 level, change the "main" field of your package.json from "index.js" to "functions/index.js" and add the following to your firebase.json:

`"functions": {
  "source": ".",
 // Anything else that was previously in your functions block.
}`

Hope this helps a bit!

**Comment by sambhav2612** [comment]
@joehan I had to merge the inner package.json in `functions` with the global one that was a level above it. It seems to work now without any issues. Thanks!
