### ISSUE TITLE
Adjustment of acknowledgement deadline for pubsub functions

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-functions#626]
When deploying a function the ack deadline is set to 10 mins (and cannot be changed in GCP) - is there anyway to change this and could it be added in to the `.topic()` function builder?

As a side note I also tried to change it with `glcoud` and got the following error:

```
> gcloud pubsub subscriptions update projects/<projectId>/subscriptions/<subscriptionId> --ack-deadline=180

ERROR: (gcloud.pubsub.subscriptions.update) INVALID_ARGUMENT: The supplied AppEngine URL project does not match the subscription's parent project (url="https://<some-random-uuid>.appspot.com/_ah/push-handlers/pubsub/projects/<projectId>/topics/<topicId>?pubsub_trigger=true", project_id="<projectId>").
```

**Comment by andrianabeltran** [comment]
Hi, can you submit a feature request to https://cloud.google.com/support/docs/issue-trackers#feature_requests?

**Comment by rhodgkins** [comment]
Done https://issuetracker.google.com/issues/152149355

**Comment by IFM-Myron** [comment]
I am getting this error also. I deleted the subscription and recreated it with the exact same vaules and now it give this error:
The supplied AppEngine URL project does not match the subscription's parent project
Those values had been working for the last year. Has anyone figured out a work around?

**Comment by rhodgkins** [comment]
https://issuetracker.google.com/issues/152149355 I'm getting "Access denied" for this link now...

Anyone any ideas why the ack deadline is set to 10 mins and not something just above the timeout of the function?

**Comment by inlined** [comment]
Ooof. This is a bug that got lost in backlogs. We'll try to do better moving foward.

It's not clear to me that there's ever a problem if the timeout is too _long_. If you NACK the Pub/Sub push subscription request, Pub/Sub's exponential backoff process kicks in immediately, not after that timeout expires.

The Functions Framework wraps all of your code in catches and will NACK the request if anything goes wrong. If there's a catastrophic failure or the scheduler has to kill your request for exceeding the timeout then the connection gets closed uncleanly, which is a form of NACKing.

The only time the subscription length can be a problem is when it's shorter than the function timeout (actually happened for a bit during the V2 alpha!). The current behavior should be functionally OK.

Unless someone is observing behavior contrary to what is described here, this bug doesn't need fixing.

**Comment by inlined** [comment]
Sorry this bug has taken so long to get to. We are not going to add a timeout option to the `topic` function; you shouldn't have to manually configure two different timeouts (function and subscription). We're also going to leave the deadline at 600s.

Instead, we're working on the Pub/Sub infrastructure so that it notices hangups as a NACK. This means that any function which times out will be killed by our scheduler and cause a NACK on the pub/sub topic which will schedule the re-delivery immediately. This fix is currently rolling out to production.
