### ISSUE TITLE
Unable to deploy to europe-west3 region

### ISSUE THREAD

**Issue by quantumdream** [firebase/firebase-functions#631]
### [REQUIRED] Version info

**node:**
10.19.0

**firebase-functions:**
3.3.0
**firebase-tools:**
7.15.1

**firebase-admin:**
8.6.0
### [REQUIRED] Test case

Deploy any function with .region('europe-west3')
### [REQUIRED] Steps to reproduce

    export const europeWest3Fn= functions.region('europe-west3').auth.user().onCreate(userRecord 
    => 'I am not deployed');                                                            
### [REQUIRED] Expected behavior

Function gets deployed to europe-west3 region because google cloud functions support europe-west3 since february
### [REQUIRED] Actual behavior
Function is not deployed to europe-west3 region because of the check for available regions in src/function-configuration.ts -> SUPPORTED_REGIONS

### Were you able to successfully deploy your functions?

I am able to successfully deploy if I add 'europe-west3' to the SUPPORTED_REGIONS array myself

**Comment by andrianabeltran** [comment]
Hi, thanks for the feedback. Looks like it needs to be added to the SUPPORTED_REGIONS array - if you'd like, you can submit a PR and we can get that reviewed. Thanks!

**Comment by laurenzlong** [comment]
https://github.com/firebase/firebase-functions/pull/627
