### ISSUE TITLE
Error: maxretry

### ISSUE THREAD

**Issue by agungjati** [firebase/firebase-functions#635]
### Related issues

Error : MaxRetry
I dont know about this error, i have searched almost entire keyword, and there solution is precison decimal number.
https://stackoverflow.com/questions/37002255/firebase-is-giving-maxretry-error

but i still getting same error, its onle maxretry, please describe about detail error
### [REQUIRED] Version info
![image](https://user-images.githubusercontent.com/21965071/77054386-506cae00-6a02-11ea-94f6-95946e8c815a.png)

![image](https://user-images.githubusercontent.com/21965071/77053998-bc024b80-6a01-11ea-95c4-9f76a55ef01a.png)

### Were you able to successfully deploy your functions?
yes

**Comment by laurenzlong** [comment]
Even though you are using a Cloud Function, this error is actually coming from the Real Time Database SDK. So we do not have the expertise to help you here. Please file a support ticket at https://firebase.google.com/support
