### ISSUE TITLE
TypeScript 3.7 is required while package.json points to 3.5

### ISSUE THREAD

**Issue by dotdoom** [firebase/firebase-functions#647]
### [REQUIRED] Version info

**node:**
v8.17.0

**firebase-functions:**
3.5.0

**firebase-tools:**
None

**firebase-admin:**
None

### [REQUIRED] Test case

```
$ mkdir typescript-version
$ cd typescript-version
$ npm install firebase-functions typescript@3.5.2
$ echo "import * as functions from 'firebase-functions';" > index.ts
$ node_modules/.bin/tsc --init
$ node_modules/.bin/tsc -p .
```

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

Either typescript install fails, or tsc passes.

### [REQUIRED] Actual behavior

Found 32 errors.

**Comment by laurenzlong** [comment]
This has been fixed in v3.6.1. Thanks fo reporting!
