### ISSUE TITLE
CORS issue with one onCall cloud function but not another - both functions have similar code

### ISSUE THREAD

**Issue by rishbhs** [firebase/firebase-functions#648]
### Related issues

I found the following issues similar:
1. https://github.com/firebase/firebase-functions/issues/645
2. https://github.com/firebase/firebase-functions/issues/548
3. https://www.reddit.com/r/Firebase/comments/c4js7u/cors_issue_with_one_cloud_function_but_not/

### [REQUIRED] Version info

```
Node: v10.15.3
firebase-admin: ~6.0.0
firebase-functions: 2.1.0
```

### [REQUIRED] Test case

Node:
```
const admin = require('firebase-admin');
const functions = require('firebase-functions');
admin.initializeApp();
const cors = require('cors')({ origin: true });
let db = admin.firestore();
var users = db.collection("userbase");

exports.postRating = functions.https.onCall((data, context) => {
    const uid = context.auth.uid;
    const ruid = data.ruid;
    const timestamp = Date.now();
    const postid = data.pid;
    const score = data.score;
    return db.collection("social").doc(postid).collection("rating").add({
        created: timestamp,
        uid: uid,
        score: score
    }).then(() => {
        return users.doc(ruid).collection("coins").add({
            created: timestamp,
            value: 100
        }).then(() => {
            return { code: 200 };
        }).catch((err) => {
            return { code: 300, err: err };
        })
    }).catch((err) => {
        return { code: 300, err: err };
    });
});
```
Web/JavaScript:
```
    var postRating = firebase.functions().httpsCallable("postRating");
    postRating({
        pid: postid,
        ruid: ruid,
        scrore: score
    }).then((result) => {
        if (result.data.code == 200) {
            console.log("rating posted");
        } else {
            console.log("error occured", result.data);
        }
    }).catch((err) => {
        console.log(err);
    });
```

### [REQUIRED] Steps to reproduce

1. deploy function
2. run client-side javascript

### [REQUIRED] Expected behavior

The function should add two documents in two different collections in firestore and return `{ code: 200 }`;

### [REQUIRED] Actual behavior

The function is throwing the following error on the client-side:

`Access to fetch at 'https://us-central1-appname.cloudfunctions.net/postRating' from origin 'http://127.0.0.1:1111' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`Error: internal`

### Were you able to successfully deploy your functions?

There were no issues while deploying the function.

**Comment by jennmueng** [comment]
Having the same issue since last night. Deleting and redeploying does not work.

**Comment by jennmueng** [comment]
If I visit the trigger URL from my browser I get the response

```
Error: Forbidden
Your client does not have permission to get URL
```
and the function on the Firebase console does not register the invocation at all.

Where on other functions I actually get the JSON response.

**Comment by rishbhs** [comment]
Hi @jennmueng,

[this](https://github.com/firebase/firebase-functions/issues/645#issuecomment-605835353) worked for me as well, thanks!

**Comment by welligtonporto** [comment]
Thanks a lot

**Comment by welligtonporto** [comment]
> Hi @jennmueng,
> 
> [this](https://github.com/firebase/firebase-functions/issues/645#issuecomment-605835353) worked for me as well, thanks!

Thanks a lot!

**Comment by yoni333** [comment]
@jennmueng 
the solution to add permission for all users as function invoker is not work any more...

**Comment by juokavom** [comment]
If you still have issue(s) with firebase denying your function invocations due to CORS errors, **THIS IS HOW TO SOLVE THEM**:

1.  **Error**:
![cors_err](https://user-images.githubusercontent.com/47061836/203447954-266443ab-ea59-4028-90df-0da6a651952f.png)
**Solution**:
Set region in your client where your function is hosted. For example:
When importing function package:
`
export const functions = getFunctions(app, "europe-central2") <--- region of your function;
`
Then you can call your function:
`
        const doSomething= await httpsCallable(functions, 'doSomething');
`
2.  **Error**:
![cors_err_2](https://user-images.githubusercontent.com/47061836/203447972-8e134eaf-240a-49ab-8bb8-2751458eab63.png)
**Solution**:
Set all users principal in google cloud console for this particular function. More here: https://github.com/firebase/firebase-functions/issues/645#issuecomment-605835353
