### ISSUE TITLE
after.data() is partial on updates

### ISSUE THREAD

**Issue by KrisBraun** [firebase/firebase-functions#654]
My understanding is that `after.data()` in the document snapshot of `onWrite` represents the full state of the document after the write. However (in `3.6.0`) I'm seeing that when a client `update` doesn't include a particular field that already exists in the doc, that field is not in `after.data()`, even though it remains in the document after write.

Is this a bug, or a misunderstanding on my part? If the latter, perhaps this could be stated more clearly in the docs.

**Comment by joehan** [comment]
Hey @KrisBraun, thanks for filing this. This is working as intended: from this page in the docs https://firebase.google.com/docs/functions/firestore-events?hl=en:

```
// Listen for changes in all documents in the 'users' collection and all subcollections
exports.useMultipleWildcards = functions.firestore
    .document('users/{userId}/{messageCollectionId}/{messageId}')
    .onWrite((change, context) => {
      // If we set `/users/marie/incoming_messages/134` to {body: "Hello"} then
      // context.params.userId == "marie";
      // context.params.messageCollectionId == "incoming_messages";
      // context.params.messageId == "134";
      // ... and ...
      // change.after.data() == {body: "Hello"}
    });
```
The feedback is appreciated tho - its always helpful to know where users are getting confused. I'll pass this along to our tech writer who maintains those docs, and see if theres a good place to clarify this further.

**Comment by fightbulc** [comment]
Hey @joehan,

as a reminder: its 2023 and the docs still don't reflect that we will receive only the changed part and not the whole document.

Best
Tino
