### ISSUE TITLE
PROPFIND - 405 Method Not Allowed in functions

### ISSUE THREAD

**Issue by 0xF6** [firebase/firebase-functions#660]
### [REQUIRED] Version info
**node: 10**
**firebase-functions: 3.3.0**
**firebase-tools: 8.0.1**
**firebase-admin: 8.9.0**

### [REQUIRED] Test case

```typescript
import { https } from 'firebase-functions';
exports.test = https.onRequest((req, res) => {
    console.log(req);
    res.sendStatus(200);
});
```

### [REQUIRED] Steps to reproduce

Deploy code from Test case
Call GET https://project_id.web.app/test
And we get result `HTTP 200` (normal behavior)

Call PROPFIND https://project_id.web.app/test, 
And we get:
```
405. That’s an error.
The request method PROPFIND is inappropriate for the URL
```
(not normal behaviour)

### [REQUIRED] Expected behavior

PROPFIND https://project_id.web.app/test -> HTTP 200

### [REQUIRED] Actual behavior

PROPFIND https://project_id.web.app/test -> HTTP 405

## etc
nginx has supported PROPFIND call, or maybe do the firebase functions configure it differently?
![image](https://user-images.githubusercontent.com/13326808/79067113-e58f5980-7cc5-11ea-99b7-b5ba1e1022f7.png)

**Comment by tinaliang** [comment]
The firebase-functions SDK is built on Express, which supports PROPFIND, thus so does the firebase-functions SDK. 

However, this is not true is if your project also uses Firebase Hosting, which it looks like your project does. Firebase Hosting does not support proxying uncommon method calls (like PROPFIND) to the function.

**Comment by 0xF6** [comment]
hm, okay~ 😢 
Where should I go with this problem?

**Comment by tinaliang** [comment]
I'll pass along the feedback to the Firebase Hosting team. For now, can you look into moving off of using PROPFIND?

As there's nothing else we can do at this moment, I'll be closing this issue.
