### ISSUE TITLE
pubsub message is ack-ed for pubsub.topic.onPublish when function completes with error

### ISSUE THREAD

**Issue by stari4ek** [firebase/firebase-functions#661]
### [REQUIRED] Version info

**node:**

local: `v12.4.0`
Deployed with
```
  "engines": {
    "node": "8"
  },
```
**firebase-functions:**
`"firebase-functions": "^3.6.0",`

**firebase-tools:**

`8.0.2`

**firebase-admin:**
`"firebase-admin": "^8.10.0",`

### [REQUIRED] Steps to reproduce

I have `functions.pubsub.topic('foo').onPublish` function exported.
When it returns rejected promise - there is no retries with same message => message was acknowledged despite failed function.

### [REQUIRED] Expected behavior

I was googling around (SA, github issues) and I'm seeing different information. Some of them states that message is always acknowledged regardless function result, other states that it's acknowledged only after successful execution.

### [REQUIRED] Actual behavior

Log from firebase functions console shows error for pubsub function:
```
5:51:46.877 PM play-realtimeNotifications
Function execution took 832 ms, finished with status: 'error'
5:51:46.864 PM play-realtimeNotifications
OtherError: <REDACTED_LONG_HTML>
    at Function.convertPlayAPIErrorToLibraryError (/srv/src/services/play-billing/PurchaseManager.ts:562:30)
    at playDeveloperApiClient.purchases.subscriptions.get.then.catch.err (/srv/src/services/play-billing/PurchaseManager.ts:439:55)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

So it's execution failed, but no retries performed.
I'd expect that message should be not-acked, and re-delivered once again.
I have checked Logs Viewer, filtering by function name around time of execution - there is only single execution and no retries for same message (I do log message for each one)

![pubsub-no-retries](https://user-images.githubusercontent.com/327778/79505611-507dbf00-803d-11ea-8250-ac16721f625a.png)

### Were you able to successfully deploy your functions?

not related

**Comment by laurenzlong** [comment]
Hi @stari4ek You can enable function retries using the Cloud Console: https://cloud.google.com/functions/docs/bestpractices/retries#using_the

**Comment by stari4ek** [comment]
So does it mean, that the subject of issue is correct, and any execution (success/failed) will acknowledge pubsub message?

I think that it works differently from cloud functions. And honestly speaking it looks like api design fail.

**Comment by TanguyDucky** [comment]
I'd love a yes/no answer to this affirmation:
_A firebase cloud-function triggered by a PubSub topic will always acknowledge the received message._

I also would like the documentation to state it explicitly. Acknowledgment is an important part of PubSub and there is no mention of it anywhere in the [Firebase Function documentation](https://firebase.google.com/docs/functions).

**Comment by manwithsteelnerves** [comment]
> So does it mean, that the subject of issue is correct, and any execution (success/failed) will acknowledge pubsub message?
> 
> I think that it works differently from cloud functions. And honestly speaking it looks like api design fail.

Did you find a solution? Ack with failure is a true failure.

**Comment by stari4ek** [comment]
@manwithsteelnerves, not really.
I've added bunch of additional things to be able to recover from it. auto-retries, snapshots for `pubsub` to be able to replay them. Plus there is client-driven flow which forces to "retry" it.

**Comment by manwithsteelnerves** [comment]
Do you mean push https end point?

**Comment by ninjz** [comment]
Bump
