### ISSUE TITLE
Firebase function (onRequest) fires more than once

### ISSUE THREAD

**Issue by blakezeisler** [firebase/firebase-functions#663]
### Related issues

Unique case for onRequest functions

### [REQUIRED] Version info

Node v10.14.2

Firebase 6.2.2

### [REQUIRED] Test case

**In the client code:**
```
this.getHotels(hotelSearchId);

 async getHotels(hotelSearchId) {
    return await new Promise((resolve, reject) => {
      this.http.post('https://endpint.cloudfunctions.net/getHotels', hotelSearchId)
      .subscribe((hotelResults) => {
        const listOfHotels = JSON.parse(hotelResults['_body']);
        resolve(listOfHotels);
      });
    });
  }
```
**In the Firebase Function (calling a 3rd party API):**
```
exports.getHotels = functions.https.onRequest((req, res) => {
    return cors(req, res, () => {
	const hotelSearchId = req.hotelSearchId;
        var request = require('request');
        var headers = {
	     'Content-type': 'application/json',
	     'Accept-Encoding': 'gzip,deflate,sdch'
	};	
	var options = {
	     url: 'http://hotelAPI/api/v2/search/getResult.json?' + 'searchId=' + hotelSearchId
	     method: 'GET',
	     gzip: true,
             headers: headers,
        };

        let getHotelResults = (options => {
            return new Promise(
                (resolve, reject) => {
                    request.get(options, function(error, response, data){
                        if(error) {
                            reject(error);
                        }
                        resolve(data);
                    })
                });
        });
        getHotelResults(options).then(
            data => {
                const hotelResults = JSON.parse(data);
		res.send(hotelResults);
        })
        .catch(error => console.log(error));
    });  
});
```

### [REQUIRED] Steps to reproduce

1. Set a hotelSearchId in client
2. The client calls the firebase function with hotelSearchId param
3. Firebase function getHotels sends a onRequest call to hotelAPI **<-- ISSUE: this function is called more than once (almost always twice in a row).**
4. The function resolves the hotelResults to the client
5. The client sets the results from the function to a listOfHotels array 

### [REQUIRED] Expected behavior

**The Firebase Function should only be called once.**

### [REQUIRED] Actual behavior

The Firebase Function is called more than once immediately and causes the 3rd party API to deny the return because their API has not completed the original search with the hotelSearchId before the next call is fired, so they send back an error.

### Were you able to successfully deploy your functions?

The Firebase function is successfully deployed and works only sometimes when the function is only fired once.

**Comment by joehan** [comment]
Hey @blakezeisler, sorry to hear that you are having trouble here. Problems like this are usually caused by something on the client side, and it looks to me like your cloud function code is correct.
I would need to see more of your client code to be certain, but it looks like you might be running into the same issue described here: https://stackoverflow.com/questions/55379651/firebase-cloud-function-executing-twice-when-triggered-over-http

Could you check the headers that your client is sending with the call to your onRequest function? If `content-type` is set to `application/json`, try switching it to `application/x-www-form-urlencoded`.

**Comment by blakezeisler** [comment]
Sorry for not getting back here, this project got put on hold for a while. I found out that it was my client code causing the issue. Firebase is only sending the call once as intended. The above code is correct.
