### ISSUE TITLE
GCLOUD_PROJECT environment variable missing from the Node 10 runtime

### ISSUE THREAD

**Issue by skhaz** [firebase/firebase-functions#669]
See: https://github.com/firebase/firebase-functions/issues/437

**Comment by laurenzlong** [comment]
@skhaz what firebase-tools version are you running? What does `firebase --version` print?

**Comment by joehan** [comment]
I've been investigating the new reports of this, and I haven't been to reproduce it on firebase-tools@8.2.0 and firebase-function@3.6.1. If you experience this bug using these versions, please let us know. For now, if you are having trouble with this, try the workaround suggested in https://github.com/firebase/firebase-functions/issues/437#issuecomment-619834021
