### ISSUE TITLE
Functions: the following filters were specified but do not match any functions in the project

### ISSUE THREAD

**Issue by davidevaliante** [firebase/firebase-functions#672]
### Version info

**node:** 12.16.0

**firebase-functions:** 3.6.0

**firebase-tools:** 8.1.1

**firebase-admin:** 8.10.0

### Test case
firebase deploy --only functions:myFunction doesn't find the function in the index file and thus doesn't deploy it without throwing any error. 

###  Steps to reproduce
init firebase function in a new project
Made a test deploy of the template "helloWorld" function and it deploys correctly and works correctly. Made another function "myFunction" and tried to deploy it but got the message 
"!  functions: the following filters were specified but do not match any functions in the project: myFunction"
Tried to swap names between the two Functions and it deploys correctly. Long story short i'm apparently able to deploy only a function name helloWorld

###  Expected behavior

should be able to deploy functions with any name, not only helloWorld...as i said the project already has other functions properly deployed

### Actual behavior

This is the output if i try to deploy the template function after adding an "y" to the end just to change the name

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (36.28 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: current functions in project: cleanUpConversionStatus(us-central1), cleanUpUploadStatus(us-central1), copyVideoToFirestore(us-central1), deleteVideoInFirestore(us-central1), 
editVideoInFirestore(us-central1), everyFiveMinutes(us-central1), everyMinute(us-central1), everyTwoHours(us-central1), everyWeek(us-central1), generateThumbs(us-central1), helloWorld(us-central1), imageToJPG(us-central1), onBonusAdded(us-central1), onBonusUpdated(us-central1), onProducerAdded(us-central1), onSlotAdded(us-central1), onSlotUpdated(us-central1), sendInstantNotification(us-central1), sendInstantReplyNotificationFromAdmin(us-central1), sendMailFromAdmin(us-central1), sendNewVideoNotification(us-central1), sendVideoCollectionToAlgolia(us-central1), updateAlgoliaIndex(us-central1)
!  functions: the following filters were specified but do not match any functions in the project: helloWorldy
+  scheduler: required API cloudscheduler.googleapis.com is enabled

### Were you able to successfully deploy your functions?

No

**Comment by tinaliang** [comment]
Could you rerun `firebase deploy --only functions:myFunction --debug` of the function that is failing and post the output here?

Also, I see that you're deploying a scheduled function - is that the function that is failing?

**Comment by SeanGillen** [comment]
![Capture](https://user-images.githubusercontent.com/48034936/85935497-6feb6080-b8a6-11ea-9d88-1e1139d74b74.PNG)

Happens when I do this:
```javascript
//index.js
const functions = require("firebase-functions");

exports.Obby = require("./Obby.js");

// ./Obby.js
const functions = require("firebase-functions");

exports.GetObby = functions.https.onRequest((request, response) => {

});
```

**Comment by gavinchebor** [comment]
Make sure your are building the functions project before deploying
`"build": 'tsc'`

**Comment by HenningKuehl** [comment]
@gillern You have to use dots to specify sub groups 😊 
`firebase deploy --only functions:Obby.GetObby`

Here I found the solution: https://stackoverflow.com/a/43998935
