### ISSUE TITLE
Firebase functions cannot be executed when created

### ISSUE THREAD

**Issue by paulsharratt0** [firebase/firebase-functions#673]
It makes no sense at all that http functions created with _firebase deploy_ no longer have Cloud Functions Invoker permissions awarded to allUsers by default. Why would anyone want to create a http function which can't be executed? This is slowing down development, and I doubt doing much to improve security. It's one more thing where I deploy, try to run the function, it doesn't work, debug, oh crap it's that stupid html page that is displayed because permissions aren't set up by default any more. Then I have to go into console and add the allUsers permission again, like 99% of use cases will.

**Comment by mbleigh** [comment]
@paulsharratt0 this is the result of a recent change in the Google Cloud Functions infrastructure that defaults HTTP functions to private. This provides greater security and access controls for organizations that want to limit exposing of endpoints on the public internet (a common request for Google Cloud customers) at the expense of requiring additionally strict permissions to do so for all customers. The Firebase use case is for public endpoints, so I definitely get your frustration.

That being said, if you are on CLI version `>= 8.1.0` new functions should be created with a correct policy applied to them automatically and there should be a helpful error message if you don't have the correct permissions on the project.

Can you provide details as to what is happening (including CLI version and `--debug` logs) that causes you to end up with a new function that does not have `allUsers` set properly? Note that the policy is only set on new function creation, so existing functions created through old CLI versions or other tools will not be automatically made public.

Thanks!

**Comment by paulsharratt0** [comment]
My CLI was behind v8.1.0, will try out the newer version with the next deploy I do. I appreciate you taking the time to leave this helpful response!
