### ISSUE TITLE
Change region http trigger

### ISSUE THREAD

**Issue by MatthiasVervaet** [firebase/firebase-functions#68]
Is it possible to deploy an http trigger cloud function to a region other than us-central1? 
We experience latency due to interregional requests.

**Comment by laurenzlong** [comment]
Hey @MatthiasVervaet not yet.

**Comment by Dipen-Dedania** [comment]
@laurenzlong How about now?

**Comment by laurenzlong** [comment]
Thanks for following up. Not yet. This is something that I know the core Google Cloud Functions team is working on, and here are some ways to get in touch with them: https://cloud.google.com/functions/docs/support

**Comment by xemasiv** [comment]
SAD

**Comment by WooWapDaBug** [comment]
How about now?

**Comment by laurenzlong** [comment]
We just launched regional support 2 weeks ago! Learn more at https://firebase.google.com/docs/functions/locations

**Comment by whollacsek** [comment]
That's a good milestone but unfortunately it's not compatible with firebase
hosting, which is the reason I use firebase functions.
