### ISSUE TITLE
When deploying the functions, the execution tells me that the functions are in a previous version, even though source code is up to date

### ISSUE THREAD

**Issue by nicoletapopepix** [firebase/firebase-functions#687]
### [REQUIRED] Version info

**node:**

13.6.0

**firebase-functions:**
3.6.1

**firebase-tools:**

8.2.0

**firebase-admin:**

8.12.1

### [REQUIRED] Test case

added a new console.log in a function and when I check logs it is not there anymore

### [REQUIRED] Steps to reproduce

run firebase deploy --only functions and the source code seems to be up to date, but after I updated firebase-functions to the latest, I don't receive errors from now inexistent functions (that existed in previous versions of my functions)

### [REQUIRED] Expected behavior

execute all code as it should, without lack of addition of previous deleted code

### [REQUIRED] Actual behavior

<img width="1283" alt="Screenshot 2020-05-12 at 14 16 28" src="https://user-images.githubusercontent.com/61005442/81680070-63788900-945b-11ea-9e3e-9e56ac894661.png">

these errors had absolutely no sense taking into account that I have received them while developing the app and since two days ago I randomly receive them after my last check on friday when they were fine. Could you please check if somehow the versions are merging on the execution side? 

### Were you able to successfully deploy your functions?

Sometimes I didn't because errors from previos versions of the functions were caught, but after updated to latest firebase-functions, I didn't receive errors

Thank you for your attention. Please try to help me asap, as my users will start to suffer from this.

**Comment by mbleigh** [comment]
There's not enough information here for us to help. It's not clear what your problem is exactly, nor what might be causing it. If you can construct an [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue you're experiencing, we might be able to help.
