### ISSUE TITLE
Functions frequently fail to deploy with puppeter error

### ISSUE THREAD

**Issue by Poliziano** [firebase/firebase-functions#688]
### [REQUIRED] Version info

**node:** 8.15.0

**firebase-functions:** 3.5.0

**firebase-tools:** 8.1.0

**firebase-admin:** 8.6.1

**puppeteer:** 2.1.1

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

Deploy a function or group of functions with `puppeteer` as a dependency.

### [REQUIRED] Expected behavior

Functions deploy consistently.

### [REQUIRED] Actual behavior

Frequently (> 50% of the time) one function randomly fails to deploy - we deploy in batches of 5.

```
{
    "error": {
        "canonicalCode": "INVALID_ARGUMENT",
        "errorMessage": "`npm_install` had stderr output:\nnode-pre-gyp WARN Using request for node-pre-gyp https download \nERROR: Failed to download Chromium r722234! Set \"PUPPET
        EER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\nError: end of central directory record signature not found\n    at /workspace/node_modules/yauzl/index.js:167:14\n    at /workspace/node_modules/yauzl/index.js:473:5\n    at
        /workspace/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymo
        us> (/workspace/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12
        )\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppe
        teer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm
        ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-12T11_54_46_653Z-debug.log\n\nerror: `npm_install` returned code: 1",
        "errorType": "InternalError",
        "errorId": "1B6FC802"
    }
}

```

### Were you able to successfully deploy your functions?

Not consistently.

**Comment by Quo0** [comment]
Hi, Firebase team!
Had the same issue, i think.

**Environment:** Windows 10, local Node v8.17.0 

![image](https://user-images.githubusercontent.com/35816504/82037868-68cc1280-96ab-11ea-807f-58daa3a856e6.png)

![image](https://user-images.githubusercontent.com/35816504/82037752-3fab8200-96ab-11ea-8dd7-65844892754c.png)

**package.json**
`{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1",
    "nodemailer": "^6.4.6",
    "puppeteer": "^3.0.4"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
`

**Function:**

```
const functions = require('firebase-functions');
const puppeteer = require('puppeteer');

exports.helloWorld = functions.runWith({ memory: '2GB' }).https.onRequest(async (_request, response) => {

  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.goto('http://google.com');
  const content = await page.content();

  response.send(content);
});
```

**Comment by laurenzlong** [comment]
@Poliziano @Quo0 Only the Node 8 and Node 10 runtimes of Cloud Functions support puppeteer. (This is not related to what version of Node you have locally on your computer). Please ensure that the "engines" field of package.json specifies Node 8 or 10. You'll also want to increase the memory allocation for your functions. 

 Please see https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version for how to do both of these.

**Comment by Poliziano** [comment]
Hi, thanks for your response. We are already setting the engine version (8 in our case). I will try increasing the memory for the cloud functions which use puppeteer - but note that this issue occurs for functions which have _no_ usages of puppeteer. We have 2 which use it, but another 15 which do not but can still fail for the same reason.

**Comment by laurenzlong** [comment]
It looks like puppeteer now requires Node 10: https://github.com/puppeteer/puppeteer/blob/master/package.json#L8

Please try upgrading your functions to Node 10.

**Comment by Poliziano** [comment]
We are using puppeteer version `2.1.1` which supports node 8.16, so that should not be the problem. It is not a viable option for our team to update cloud functions to node 10 at this time.

**Comment by laurenzlong** [comment]
Thanks for the update, since this is a server-side issue, and not an issue with deployment or the SDK (which is what this repo is) could you please file a support ticket? https://firebase.google.com/support
