### ISSUE TITLE
Investigate textPayload population and double-quoting in logger

### ISSUE THREAD

**Issue by mbleigh** [firebase/firebase-functions#697]
See comments in #665.

**Comment by mbleigh** [comment]
@sk- I believe this is working as intended...ish...in that `textPayload` is populated if there is no structured data added as a final argument to the log. In the Cloud Logging console I believe the double-quotes are there when the message is being lifted from `jsonPayload` generally, not as any kind of actual extra quoting happening (the "classic" view doesn't do the same so it seems to be a UX choice).

Can you describe how you have your metrics set up now so I can think through how we might be able to make `compat` more...compatible? Perhaps `compat` should not use structured data at all and just put everything into the textPayload trying to better mimic what we have today in Node 8...

**Comment by sk-** [comment]
You are right about 1). I missed the constructor check, which for the case of `Error`s is not `Object`.

With respect to 3) I agree that is much better, but if you use compat then you don't have an alternative, other than manually splitting the entry. Note that I prefer this behavior, but may be surprising for someone using compat. Maybe in the notes, you could add a warning.

**Comment by kitfit-dave** [comment]
If I could chime in here are about (2) I would agree that it would be most reasonable for compat to never do structured data - for me the compat stuff should be for people just wanting their old console.log stuff to go back to working like it did on node 8. If they want structured logging they should use the logging sdk. I.e. go for less magic. And I do agree that stuff like `console.log('Messsage', data)` is horrible and stuctured logging is objectively better, but realistically, it's what a lot of us will be working with.

My game plan here for out firebase functions code would be: use compat for now so our existing stuff works again; for new functions make sure to use the logging SDK; eventually circle back and change everything to the new shiny structured logging (an easier(er) sell once everyone sees how good the new logs look).

**Comment by kitfit-dave** [comment]
Oh, and if it wasn't obvious, I do still think that (3) is rightly "as intended" and should be a basic functionality/requirement of compat - make multiline logs come out at as single line. This is just to restore the pre node 10 funtionality. Anyone wanting them to come out as multiple log entries should not use compat.

**Comment by mbleigh** [comment]
This has been released in `v3.7.0` with as much Node 8 compat as we can muster. See release notes: https://github.com/firebase/firebase-functions/releases/tag/v3.7.0

**Comment by jankalthoefer** [comment]
Hey everyone :) 
I am struggling right now with getting structured logs when using the firebase emulator.
I tried with firebase-functions@3.7.0 and also updated to @3.11.0, without improvements.

Does the logs in the emulator maybe differ from those in the cloud environment.

Thanks in advance for any help!
