### ISSUE TITLE
functions.auth.user().onCreate() is triggered when user is anonymous

### ISSUE THREAD

**Issue by victor-sarda** [firebase/firebase-functions#70]
### Version info

**firebase-functions: 0.5.9**

**firebase-tools: 3.9.1**

**firebase-admin: 4.2.1**

### Steps to reproduce

Sign in first time anonymously from iOS or Android

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

functions.auth.user().onCreate() shouldn't be triggered according to this [documentation](https://firebase.google.com/docs/auth/extend-with-functions)  

> The following account creation methods do not currently trigger Cloud Functions events: A user signs in for the first time using a custom token. A user signs in to a new anonymous auth session for the first time.

### Actual behavior
functions.auth.user().onCreate() is triggered

**Comment by laurenzlong** [comment]
Hey Victor, this seems like a server-side issue with Firebase auth, could you please file a [support ticket ](https://firebase.google.com/support/contact/troubleshooting/), include the output from "console.log(event.data)" inside the function, and ask for it  to be routed to the Firebase auth team.
