### ISSUE TITLE
New structured logger not applying labels

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-functions#703]
This is using the new `require('firebase-functions').logger` in Node 10.

According to the [container logs contract](https://cloud.google.com/run/docs/logging#special-fields) we should be able to write [`labels` for a `LogEntry`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) by using the [special field `logging.googleapis.com/labels`](https://cloud.google.com/logging/docs/agent/configuration#special-fields). However these labels just get applied to the `jsonPayload` in the Logs Viewer (in GCP).

I've also tried just a plan `labels` field with no success.

### Reproduction

Deploy a function that contains the following and run the function:

```js
const { logger } = require('firebase-functions')

logger.write({
    severity: 'INFO',
    message: 'Should include labels (via labels)',
    labels: {
      label1: 'some value'
    }
})


logger.write({
    severity: 'INFO',
    message: 'Should include labels (via logging.googleapis.com/labels)',
    'logging.googleapis.com/labels': {
      label1: 'some value'
    }
})
```

Logs Viewer output:
![image](https://user-images.githubusercontent.com/1810588/84257663-98850380-ab0d-11ea-943f-cea57b33d706.png)

I'd expect the `jsonPayload[labels]` and `jsonPayload[logging.googleapis.com/labels]` to be included under the `labels` at the root.

It might be the case its not supported but wanted to check as other special fields from the [list](https://cloud.google.com/logging/docs/agent/configuration#special-fields) (i.e. `message`, `timestamp`) are being converted correctly!

**Comment by rhodgkins** [comment]
@mbleigh its been a few months so I thought I'd check in and see if its been fixed? Thanks in advance

**Comment by rhodgkins** [comment]
@mbleigh went to check on this and with the original above code `logging.googleapis.com/labels` are now completely dropped...

![image](https://user-images.githubusercontent.com/1810588/109173627-f466e980-777b-11eb-9b58-9598b2106561.png)

**Comment by voxmaster** [comment]
Same issue with
- [Cloud Run](https://cloud.google.com/run)
- [Cloud Functions](https://cloud.google.com/functions)  

Cross all languages and any Structured Logs

**Comment by rhodgkins** [comment]
> Same issue with
> 
> * [Cloud Run](https://cloud.google.com/run)
> * [Cloud Functions](https://cloud.google.com/functions)
> 
> Cross all languages and any Structured Logs

I haven't tried Cloud Functions (but Firebase functions are built on top of these so I imagine its the same as this issue), but labels are showing for me with Cloud Run when using the `logging.googleapis.com/labels` key.

**Comment by taeold** [comment]
2021 update: Cloud Functions backend is working on a fix to this issue. I will come back in another week to provide an update.

**Comment by taeold** [comment]
I'm reading from internal tracking bug that the fix should land in a week or so. Will provide another update in a few weeks.

**Comment by taeold** [comment]
Personally I'm seeing the log labels being correctly applied in Cloud Monitoring. The rollout is only ~90% done, but you may also start to see the label being applied correctly. Rollout should be fully completed in the next couple of days.

**Comment by rhodgkins** [comment]
Yep all working for me now too thanks @taeold
