### ISSUE TITLE
Circular Import Errors

### ISSUE THREAD

**Issue by TomPridham** [firebase/firebase-functions#706]
### [REQUIRED] Version info

**node:** 10

**firebase-functions:** ^3.6.1

**firebase-tools:** 8.2.0

**firebase-admin:** ^8.11.0

### [REQUIRED] Test case

https://github.com/TomPridham/firebast-function-circular

### [REQUIRED] Steps to reproduce

The issue is with file `one.ts` importing `b` from `two.ts` while `two.ts` is importing `a` from `one.ts`. The imports from `two.ts` will fail and return undefined for anything in that file. Running the pubsub function will write undefined to the console when it should be the function

### [REQUIRED] Expected behavior

To be able to import circular dependencies and have my functions work correctly.

### [REQUIRED] Actual behavior
Function deploys fine, but fails at runtime because the function I am importing is `undefined`.

**Comment by mbleigh** [comment]
Can you explain how this problem interacts with the `firebase-functions` SDK? I don't think this is an issue with the SDK but rather a more general problem with TypeScript and Node.js circular dependencies.

Happy to reopen if there's a clear way to fix this in the SDK.

**Comment by TomPridham** [comment]
you are correct. i hadn't encountered it before and assumed it was a problem with how the firebase functions were being deployed rather than an intrinsic issue with node.
