### ISSUE TITLE
[TypeScript] Argument of type '(snapshot: DataSnapshot)' is not assignable to parameter of type '(a: DataSnapshot, b?: string | null | undefined)'.

### ISSUE THREAD

**Issue by jasperswallen** [firebase/firebase-functions#707]
### Related issues

https://github.com/firebase/firebase-functions/issues/602

### [REQUIRED] Version info

**node:** 14.4.0

**firebase-functions:** 3.7.0

**firebase-tools:** 8.4.2

**firebase-admin:** 8.12.1

### [REQUIRED] Test case

Using TypeScript:
```
import { DataSnapshot } from 'firebase-functions/lib/providers/database'
database.ref('/').once('value', (snapshot: DataSnapshot) => {}))
```

### [REQUIRED] Steps to reproduce

With `snapshot: DataSnapshot`, run `npm run build`

### [REQUIRED] Expected behavior

Successful compilation and creation of `index.js`

### [REQUIRED] Actual behavior

`npm run build` fails with the following error:
```
src/index.ts:95:52 - error TS2345: Argument of type '(snapshot: DataSnapshot) => void' is not assignable to parameter of type '(a: DataSnapshot, b?: string | null | undefined) => any'.
  Types of parameters 'snapshot' and 'a' are incompatible.
    Type 'DataSnapshot' is missing the following properties from type 'DataSnapshot': instance, _ref, _path, _data, and 4 more.

95     database.ref('/').once('value', (snapshot: DataSnapshot) => {
```

### Were you able to successfully deploy your functions?

No, although if I use `(snapshot: any) => {}` I can compile and deploy.

### Other info

Other types work. For example `UserRecord` is a correct type, so I can do something like
```
import { UserRecord } from 'firebase-functions/lib/providers/auth'
auth.getUser(user).then((userRecord: UserRecord) => {}
```

**Comment by jasperswallen** [comment]
When I use `admin.database.DataSnapshot` it works as expected (also for other types), so should I just use the `admin` typings instead of the `firebase-functions` typings?

**Comment by mobibob** [comment]
I believe I am experiencing this since upgrading Firebase and refactoring some old code.  I have been unable to resolve or work around to get my project to build and deploy, so I am interested to know if anyone has made any investigative progress.

**Comment by samtstern** [comment]
@jasperswallen sorry for the slow response here but yes you should use `admin.database.DataSnapshot` and generally use the types from the `admin` SDK.  The internal types within `firebase-functions/lib` are not meant for external use.

**Comment by rami-alloush** [comment]
Can someone please share the exact working `import` statement?
