### ISSUE TITLE
Error: function crashed out of request scope Function killed.

### ISSUE THREAD

**Issue by Karthi-R** [firebase/firebase-functions#71]
I'm using database **onWrite()** function. Getting the below error randomly,

> Error: function crashed out of request scope Function killed.

Couldn't find more detail regarding this error. Code inside the function block is working fine, when I run at local machine. Getting this error only after deploying my function in server.

Appreciate your help on this.

**Comment by laurenzlong** [comment]
This is a server-side issue, please use https://firebase.google.com/support/ so we can help you better.

**Comment by kartikgreen** [comment]
I have the same issue. Did you resolve it?
