### ISSUE TITLE
'firebase deploy' command deploys successfully but when viewed in the browser, shows a 404 not found error

### ISSUE THREAD

**Issue by nspeedzy** [firebase/firebase-functions#712]
### [REQUIRED] Version info

**node:** 13.8.0

**firebase-functions:** 3.6.1

**firebase-tools:** 8.4.3

**firebase-admin:** 8.10.0

### [REQUIRED] Test case

In the command line, I typed `firebase deploy`. It showed that the deployment of the app was successful but when i click the url (Which is the firebase hosting url), It gives me a 404 not found error.

### [REQUIRED] Steps to reproduce

1. Built my app
2. Ran `firebase deploy`
3. Clicked on the link
4. Found a big screen with a 404 error

### [REQUIRED] Expected behavior

Firebase should have deployed the app properly without a 404 error on my screen

### [REQUIRED] Actual behavior

Firebase gives me a 404 error in the browser

### Were you able to successfully deploy your functions?

No

**Comment by mbleigh** [comment]
This is not enough information for us to help debug. We need to know more
information about your firebase.json, the contents of your public
directory, the specific 404 page you're encountering, and a specific
minimum reproducible version of the problem.

**Comment by nspeedzy** [comment]
@mbleigh Alright, Here are the files:

### `firebase.json`
```json
{
  "hosting": {
    "public": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [{
      "source": "**",
      "function": "app"
    }]
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  }
}
```
### `index.js`
```js
var functions = require('firebase-functions');
var express = require('express');
var app = express();
//
app.get('/', (req, res) => {
    res.send("Hello from route one");
});
app.get('/test', (req, res) => {
    res.send("Hello from route 2");
});
//
exports.app = functions.region("asia-east2").https.onRequest(app);
```
**Please note**: I am not creating a static web app but instead a dynamic node.js and express app.
If there is anymore info you need, then please tell me

**Comment by mbleigh** [comment]
Firebase Hosting is currently only able to connect to functions in the
us-central1 region. That is why you are seeing 404s

**Comment by nspeedzy** [comment]
@mbleigh So, in order to fix this issue, Should I change the region to `us-central1`?

**Comment by mbleigh** [comment]
@nspeedzy yes changing the region to `us-central1` should fix the issue. Please [file a feature request](https://firebase.google.com/support/troubleshooter/report/features) for Firebase Hosting if you'd like to see support for other regions in the future.
