### ISSUE TITLE
Firebase cloud function error logs

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-functions#721]
### Related issues
Not sure

### [REQUIRED] Version info

**node: 10**

**firebase-functions: ^3.1.0**

**firebase-tools:8.4.3**

**firebase-admin:^8.0.0**

### [REQUIRED] Test case

Do not know since it just show up on some function after triggering events in Cloud Firestore document

### [REQUIRED] Steps to reproduce

Do not know since it just show up on some function after triggering events in Cloud Firestore document

### [REQUIRED] Expected behavior

Explanation in log why and when the error may occur.

### [REQUIRED] Actual behavior

After triggering the function, these errors will show up in a few minutes and I do not know what these each error log all about.

1. Failed to send user notification. { Error: Error while making request: Client network socket disconnected before secure TLS connection was established. Error code: ECONNRESET 
       
2. at FirebaseAppError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:88:28) 
       
3. at new FirebaseAppError (/workspace/node_modules/firebase-admin/lib/utils/error.js:122:28) 

These two error however seems I need to add something in my index.js. I am not sure why these happening as all my function are just simple that listen a changes in document on Cloud Firestore. The total function I have now in **index.js** is **20**, is this the reason why I need to increase the max listener like what in this SO question discussed?  

4. (node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit 

5. (node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit 

### Were you able to successfully deploy your functions?

Yes

**Comment by samtstern** [comment]
@ArcherEmiya05 sorry for the slow response here but could you show the code of the function that's failing?

**Comment by samuel-pp** [comment]
I have the same issue. My schedule function logs the error when I use `firebase-functions/logger/compat`

<img width="804" height="238" alt="Image" src="https://github.com/user-attachments/assets/42e1ae9d-0f44-4340-9c51-9d0e1236b952" />

It's a compat package error or something?
