### ISSUE TITLE
Logs on Node 10 update very large 

### ISSUE THREAD

**Issue by svhen** [firebase/firebase-functions#723]
### [REQUIRED] Version info

**node:**
Node 10

v11.15.0
**firebase-functions:**
"^3.7.0"

**firebase-tools:**
"^1.1.1"

**firebase-admin:**
8.4.3

### [REQUIRED] Test case

I just try this https://github.com/firebase/firebase-functions/releases/tag/v3.7.0 and get Cannot read property 'debug' of undefined

### [REQUIRED] Steps to reproduce

Create a function with this code: https://github.com/firebase/firebase-functions/releases/tag/v3.7.0 

### [REQUIRED] Expected behavior

A log in a JSON format, more short, like the Node 8 does

### [REQUIRED] Actual behavior
A very large JSON format

Cannot read property 'debug' of undefined

### Were you able to successfully deploy your functions?
No

Thanks

**Comment by mbleigh** [comment]
We're going to need more information to be able to help here. Where are you running the code, in the emulators or on the server? What is the exact code you're calling, what do you expect to happen, and what is actually happening?
