### ISSUE TITLE
FIREBASE_CONFIG not set in Node.js v10 function environment

### ISSUE THREAD

**Issue by taycaldwell** [firebase/firebase-functions#724]
### Related issues

Here are a couple of similar issues that were closed few months back:

#433
#563
#630

### [REQUIRED] Version info

**node:**

10.21.0

**firebase-functions:**

3.7.0

**firebase-tools:**

8.4.3

**firebase-admin:**

8.13.0

### [REQUIRED] Test case

Not applicable. Firebase project id is `canvus-8fbe1`

### [REQUIRED] Steps to reproduce

I deploy my barebone Firebase app and get in the Functions logs:

`Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail `

### [REQUIRED] Expected behavior

I expect to not get the error and have environment variables in process.env such as FIREBASE_CONFIG, etc.

### [REQUIRED] Actual behavior

I deploy my barebone Firebase app and get in the Functions logs:

`Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail `

### Were you able to successfully deploy your functions?

Yes.

**Comment by samtstern** [comment]
@laurenzlong you've investigated similar issues in the past, could you take a look?

**Comment by taycaldwell** [comment]
I further debugged this issue and realized it's an issue on my side, and everything seems to be working as intended. Closing bug.
