### ISSUE TITLE
Firestore trigger crash

### ISSUE THREAD

**Issue by purusho95** [firebase/firebase-functions#725]
**Environment details:** 
firebase-tools : "8.4.3"
firebase-admin  :  "^8.12.1"
firebase-functions : "^3.6.1"
node : 10
trigger: onCreate

Code: 
```js
exports.newForm = functions.runWith({
  memory:'2GB',
  timeoutSeconds: 540
}).firestore.document('forms/{formId}').onCreate(async (snap, context) => {
  console.log('pdf document :'+snap.id);
  return this.printpdf(snap).then((res) => {
      return {};
  }).catch(e => {
    console.log(JSON.stringify(e));
    console.error(new Error(JSON.stringify(e)));
    return {};
  });
});
```

**Error Message:** 
Function execution took 425 ms, finished with status: 'crash'

**Description:**
I am trying to execute the promise function on every new document added in firestore collection. Sometimes it's crashing without throwing any error message and logs.

**Comment by samtstern** [comment]
@purusho95 this is not enough information to debug.  Not all of the code is here (what happens in `printPdf`) and there are no logs provided at all.  We can't guess why your function is crashing!

Please provide logs or a simple way for us to reproduce this issue.

**Comment by purusho95** [comment]
Except for this **Function execution took 425 ms, finished with status: 'crash'**
I am getting nothing.
It's not happing all the time. I couldn't exactly say.
There is 3 or 5 failure every day.

`exports.newForm = functions.runWith({
  memory:'2GB',
  timeoutSeconds: 540
}).firestore.document('forms/{formId}').onCreate(async (snap, context) => {
  console.log('pdf document :'+snap.id);
  return this.printpdf(snap).then((res) => {
      return {};
  }).catch(e => {
    console.log(JSON.stringify(e));
    console.error(new Error(JSON.stringify(e)));
    return {};
  });
});`

In the above function, we have  console.log('pdf document :'+snap.id); 
Even this I couldn't see in the firebase function log.

Here in `printPdf` I am using **html-pdf** node_module to create a pdf.

**Comment by samtstern** [comment]
@purusho95 I'm sorry but I don't think there is anything else I can do here if we can't see any logs or reproduce this error.  My guess would be that you're experiencing a crash within the `html-pdf` module but it's hard to say.

If you really believe this is a backend issue with Cloud Functions you could contact Firebase Support and ask someone to look into the logs, but I don't have access to do that:
https://firebase.google.com/support

**Comment by samtstern** [comment]
Also you may want to follow along with this issue:
https://issuetracker.google.com/155215191

That could explain the lack of logs when the function crashes.

**Comment by purusho95** [comment]
@samtstern 
https://issuetracker.google.com/155215191
This is what exactly I am facing.
