### ISSUE TITLE
user.tenantId is not populated for firebase auth onCreate trigger 

### ISSUE THREAD

**Issue by ngradet-airinai** [firebase/firebase-functions#728]
### [REQUIRED] Version info

**node:**

$ node --version
v10.16.0

**firebase-functions:**
3.7.0
**firebase-tools:**
8.4.3

$ firebase --version
8.4.3

**firebase-admin:**
8.13.0
### [REQUIRED] Test case

import * as functions from 'firebase-functions'

export const authOnUserCreate = functions.auth.user().onCreate( (user, context) => {
    console.log({tenantId: user.tenantId, context});
    return Promise.resolve();
});

### [REQUIRED] Steps to reproduce

(Steps 1-5 are from this guide: https://cloud.google.com/identity-platform/docs/multi-tenancy-quickstart)

1. Create a new google cloud project
2. Enable Cloud Identity Platform
3. Enable Multi-tenancy
4. Create a Tenant 'test'
5. Switch to Tenant 'test'
6. Deploy above function and ensure function is deployed before proceeding to (7)
7. Create a user through cloud console under tenant=test
8. Examine the log and find tenantId=undefined

$ firebase functions:log --only authOnUserCreate
2020-07-08T21:46:08.930876807Z D authOnUserCreate: Function execution started
2020-07-08T21:46:09.066Z ? authOnUserCreate: { tenantId: undefined,
2020-07-08T21:46:09.066Z ? authOnUserCreate:   context:
2020-07-08T21:46:09.066Z ? authOnUserCreate:    { eventId: '8fd2fc06-6f34-482e-8928-904b4c208261',
2020-07-08T21:46:09.066Z ? authOnUserCreate:      eventType: 'google.firebase.auth.user.create',
<snip>

Note: tenantId is not set in onCreate handler not only when user is created from the GCP console, but also when client attempts a first anonymous or SAML sign-in (both cause new account to be created and onCreate triggered). Client makes sure to set firebase.auth().tenantId = 'test' prior to singIn sequence, yet onCreate still reports tenantId=undefined

### [REQUIRED] Expected behavior

user.tenantId should be populated  when functions.auth.user().onCreate triggers for a specific tenant

### [REQUIRED] Actual behavior

tenantId = undefined

### Were you able to successfully deploy your functions?

Deployment was successful

**Comment by mbleigh** [comment]
Hi, this is the GitHub repository for the Firebase SDK for Cloud Functions. If `tenantId` is not being populated in the event payload, that is going to be an issue with the GCIP backend. Please file a support request with Firebase / GCP to follow up on this issue, as there is nothing we can do in the SDK to fix it. Thanks!

**Comment by ngradet-airinai** [comment]
Great thanks for quick analysis!

I raised a defect report to GCIP; hopefully it will get traction. Providing link here for reference: https://issuetracker.google.com/issues/160809045
