### ISSUE TITLE
[FR] a trigger for when the users email is updated

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-functions#732]
**Is your feature request related to a problem? Please describe.**
It would be good to have a trigger for when the users email is updated
**Describe the solution you'd like**
Similar to how that `functions.auth.user().onCreate` works
**Describe alternatives you've considered**
Creating a cloud function that is called from my client when they update the email using client sdk
**Additional context**

I want this to happen on update too

```js
/**
 * when user is created we create a hash of the email for use with gravitat
 */
export const onCreate = functions.auth.user().onCreate(async (user) => {
    await addGravatarURLtoUserData(user.uid, user.email)
})

export const addGravatarURLtoUserData = async (uid, email) => {
    const hash = crypto.createHash("md5").update(email).digest("hex")
    await admin.database().ref(`users/${uid}`).update({ gravatarURL: uid })
}
```

**Comment by samtstern** [comment]
@quantuminformation thanks for filing this!  This is a somewhat common feature request, in general users are asking us for an `.onUpdate` function for users.

Since this is a request for the Cloud Functions backend (a new trigger) and not the Functions SDK I will close it here and report it internally.

**Comment by quantuminformation** [comment]
Any feedback?

**Comment by samtstern** [comment]
@quantuminformation we agree this would be useful but we're not currently adding new trigger sources.  If we do start to invest in new trigger sources again, this will likely be high on the list.
