### ISSUE TITLE
Firebase Codelab: Firebase Cloud Functions

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-functions#738]
### [REQUIRED] Version info

**node:** 12.16.3

**firebase-functions:** 3.8.0

**firebase-tools:**

**firebase-admin:** 7.12.1
### [REQUIRED] Test case

https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#7

### [REQUIRED] Steps to reproduce

Copied and pasted the same code for the `addWelcomeMessages` function 

### [REQUIRED] Expected behavior

After running `firebase deploy --only functions`, should get a success message. 
### [REQUIRED] Actual behavior

<img width="1548" alt="Screen Shot 2020-07-15 at 10 47 21 AM" src="https://user-images.githubusercontent.com/4000076/87559652-92dc8980-c688-11ea-88b4-6f58b119c222.png">

```json
{
    "name": "friendlychat-codelab",
    "description": "Firebase SDK for Cloud Functions codelab",
    "dependencies": {
        "firebase-admin": "^9.0.0"
    },
    "devDependencies": {
        "eslint": "^7.4.0",
        "eslint-plugin-promise": "^4.2.1",
        "firebase-functions": "^3.8.0"
    },
    "engines": {
        "node": "10"
    },
    "private": true,
    "version": "2.1.0",
    "main": "index.js",
    "license": "MIT"
}
```
.
     

### Were you able to successfully deploy your functions?
No 

<img width="1183" alt="Screen Shot 2020-07-15 at 10 51 44 AM" src="https://user-images.githubusercontent.com/4000076/87560179-2e6dfa00-c689-11ea-8fb2-3d0f8d43710d.png">

**Comment by samtstern** [comment]
@JamesVanWaza looks like you have `"firebase-functions": "^3.8.0"` in your `devDependencies` but it needs to be in your `dependencies`

In the sample repo this is correct, so looks like you just need to apply the fix on your side:
https://github.com/firebase/codelab-friendlychat-web/blob/master/cloud-functions-start/functions/package.json#L6
