### ISSUE TITLE
Firebase addValueEventListener not firing onDatachanged with two instances of app with same package name

### ISSUE THREAD

**Issue by yourappsgeek** [firebase/firebase-functions#74]
### Version info

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

**Comment by yourappsgeek** [comment]
I'm able to add and able to get data onDataChanged within same app when data changed but when I try to listen to data change by adding node from one app and listening from another. If I post child with values from both apps and listen data changed , two children with same same are created in firebase DB and each one app listener is only listening to its own created node

**Comment by laurenzlong** [comment]
Can you please follow the issues template?
