### ISSUE TITLE
[Typescript] Argument of type '(req: Request, res: Response<any>) => Promise<Response<any>>' is not assignable to parameter of type...

### ISSUE THREAD

**Issue by nico75005** [firebase/firebase-functions#747]
I'm updating my npm packages from an old version to the latest one. There are a lot of breaking changes but one that I can't figure out is the following:

I used to have this kind of cloud functions
```
export const updateLot = functions.https.onRequest(async (req, res) => {
... some code ...

    return res.status(404).json({ message: 'there was an error' })

... some code ...

    return res.status(200).json({ results: my_object })
}
```
It was compiling fine. Then with the update I get the following error:
```
Argument of type '(req: Request, res: Response<any>) => Promise<Response<any>>' is not assignable to parameter of type '(req: Request, resp: Response<any>) => void | Promise<void>'.
  Type 'Promise<Response<any>>' is not assignable to type 'void | Promise<void>'.
    Type 'Promise<Response<any>>' is not assignable to type 'Promise<void>
```

I tried to replace the function by:
```
export const updateLot = functions.https.onRequest(async (req, res: Response<{ message: string }>) => { ... }
```
but that's obviously not the right way as `return res.status(200).json({ results: my_object })` will not compile:
```
Argument of type '{ results: Lot; }' is not assignable to parameter of type '{ message: string; }'.
  Object literal may only specify known properties, and 'results' does not exist in type '{ message: string; }'
```

I'm running out of ideas and I couldn't find any documentation or issues on Github with similar problem.

Thanks for your help.

**Comment by jeriscc** [comment]
I am facing a similar issue. Code:
```typescript
const app = express();
...
export const auditionee = functions.https.onRequest(app);
```

Error Message:
```
Argument of type 'Express' is not assignable to parameter of type '(req: Request, resp: Response<any>) => void | Promise<void>'.
  Types of parameters 'res' and 'resp' are incompatible.
    Type 'Response<any>' is not assignable to type 'Response | ServerResponse'.
      Type 'Response<any>' is missing the following properties from type 'ServerResponse': statusCode, statusMessage, writableFinished, assignSocket, and 48 more.
```

**Comment by Ralpharoo** [comment]
@jeriscc Any luck with resolving this?

**Comment by nico75005** [comment]
@Ralpharoo Basically the version of Typescript I used before updating the npm packages for Firebase was happy to compile with a returning something else than null or void, in that case a response.
You just need to do like:

```
export const updateLot = functions.https.onRequest(async (req, res) => {
... some code ...

    res.status(404).json({ message: 'there was an error' })
    return null

... some code ...

    res.status(200).json({ results: my_object })
    return null
}
```

**Comment by Flucadetena** [comment]
In my case, if anyone comes after, I had to return void. So the same solution but instead of null, just return;

```
export const updateLot = functions.https.onRequest(async (req, res) => {
... some code ...

    res.status(404).json({ message: 'there was an error' })
    return;

... some code ...

    res.status(200).json({ results: my_object })
    return;
}
```

**Comment by ANDRUXUIS** [comment]
You can directly send the result to the client or whatever who invoke the function, using the `res.send` or `res.json`
```

export const updateLot = functions.https.onRequest(async (req, res) => {
... some code ...

    return res.status(404).json({ message: 'there was an error' })

... some code ...

    // remove the return key word and it should be fine 
    res.status(200).json({ results: my_object })
}

```

**Comment by jonah-cod** [comment]
You need to import the types - `import express from 'express';
import { Express, Request, Response} from 'express';

const app: Express = express()
const PORT: Number = 4040;


app.get('/', (req: Request, res: Response)=>{

})`

**Comment by KyorCode** [comment]
> You need to import the types -
> 
> ```
> import express from 'express';
> import { Express, Request, Response} from 'express';
> 
> const app: Express = express()
> const PORT: Number = 4040;
> 
> 
> app.get('/', (req: Request, res: Response)=>{
> 
> })
> ```

100% what fixed my issue, by default de Request and Response types are taken from @types/node. Just make sure you take those from Express.

**Comment by vitaminsofsalem** [comment]
> In my case, if anyone comes after, I had to return void. So the same solution but instead of null, just return;
> 
> ```
> export const updateLot = functions.https.onRequest(async (req, res) => {
> ... some code ...
> 
>     res.status(404).json({ message: 'there was an error' })
>     return;
> 
> ... some code ...
> 
>     res.status(200).json({ results: my_object })
>     return;
> }
> ```

if you don't want to return void you can simple put `as any` 
```
return res.json(data) as any
```
worked for me :)

**Comment by John-H-Smith** [comment]
> > You need to import the types -
> > ```
> > import express from 'express';
> > import { Express, Request, Response} from 'express';
> > 
> > const app: Express = express()
> > const PORT: Number = 4040;
> > 
> > 
> > app.get('/', (req: Request, res: Response)=>{
> > 
> > })
> > ```
> 
> 100% what fixed my issue, by default de Request and Response types are taken from @types/node. Just make sure you take those from Express.

Thanks, fixed it for me.

**Comment by adminInfocerv** [comment]
![image](https://github.com/firebase/firebase-functions/assets/171039291/74b12f08-ef46-4aba-b443-341ddbc503d0)
![image](https://github.com/firebase/firebase-functions/assets/171039291/698b4570-f783-49b8-b00c-8b396fbfb6a0)
kindly take a look at this image I'm using these as Middleware.

**Comment by juangs8712** [comment]
I was facing this error and fix this by addin a `: Promise<any>`  as return type.
My bad code was:
```
app.get('/',[...some middlewares] (req: Request, res: Response)=>{
    // some code
    return res.json({msg: 'ok');
})
```
Then I add a return type to my function:
```
app.get('/',[...some middlewares] (req: Request, res: Response):Promise<any>=>{
    // some code
    return res.json({msg: 'ok');
})
```
That fix my problem

**Comment by lawrence415610** [comment]
> I was facing this error and fix this by addin a `: Promise<any>` as return type. My bad code was:
> 
> ```
> app.get('/',[...some middlewares], (req: Request, res: Response)=>{
>     // some code
>     return res.json({msg: 'ok');
> })
> ```
> 
> Then I add a return type to my function:
> 
> ```
> app.get('/',[...some middlewares], (req: Request, res: Response):Promise<any>=>{
>     // some code
>     return res.json({msg: 'ok');
> })
> ```
> 
> That fix my problem

Thanks! I had the same issue, and it's hard to understand the error message prompt by the console, you saved my day!

**Comment by juangs8712** [comment]
You are welcome.
It's a pleasure helping you.

**Comment by Raushan0303** [comment]
Aah i had also the same problem, and got resolved by adding that :Promise<any> as return type, Thanks for your tips

**Comment by persodev0** [comment]
> I was facing this error and fix this by addin a `: Promise<any>` as return type. My bad code was:
> 
> ```
> app.get('/',[...some middlewares], (req: Request, res: Response)=>{
>     // some code
>     return res.json({msg: 'ok');
> })
> ```
> 
> Then I add a return type to my function:
> 
> ```
> app.get('/',[...some middlewares], (req: Request, res: Response):Promise<any>=>{
>     // some code
>     return res.json({msg: 'ok');
> })
> ```
> 
> That fix my problem

Woahh, thank you so much buddy, you were very helpful :3

**Comment by me-mahmads** [comment]
If anybody still facing, here is what I found. The function should be of "void" return type. we can first set response and then return from them function
export const LoginUser = async (req: Request, res: Response) => {
  const { email, password } = req.body;
  // Some code
    res.status(200).json({ ok: true, message: "Login success" });
    return;
  } catch (ex) {
    res.status(500).json({ ok: false, message: (ex as Error).message });
    return;
  }
};

**Comment by vnshas** [comment]
> > In my case, if anyone comes after, I had to return void. So the same solution but instead of null, just return;
> > ```
> > export const updateLot = functions.https.onRequest(async (req, res) => {
> > ... some code ...
> > 
> >     res.status(404).json({ message: 'there was an error' })
> >     return;
> > 
> > ... some code ...
> > 
> >     res.status(200).json({ results: my_object })
> >     return;
> > }
> > ```
> 
> if you don't want to return void you can simple put `as any`
> 
> ```
> return res.json(data) as any
> ```
> 
> worked for me :)

Worked 100% here TY!

**Comment by himanshuraimau** [comment]
well my working solution for this:
```  
import express, { type Request, type Response } from 'express';
app.post("/", async (req: Request, res: Response): Promise<any>=>{
      

}
