### ISSUE TITLE
Deployment error when updating Node 8 to 10

### ISSUE THREAD

**Issue by wsplou** [firebase/firebase-functions#748]
Hi,

Have followed the guide https://medium.com/firebase-developers/migrate-your-firebase-cloud-functions-to-node-js-10-d9c677933ee to upgrade Node.js 8 to 10

I have the following error when deploy with `"engines": {
    "node": "10"
  }`, change it back to `"node": "8"` is deployed fine without any error.

```
!  functions[test(us-central1)]: Deployment error.
Build failed: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
npm ERR! code ELIFECYCLE
npm ERR! errno 128
```

The following is my global package:
```
$ npm list -g --depth=0
+-- @google-cloud/functions-emulator@1.0.0-beta.6
+-- commitizen@4.1.2
+-- cross-env@7.0.2
+-- eslint@6.8.0
+-- firebase-tools@8.6.0
+-- node-firestore-import-export@0.14.1
+-- node-inspect@1.11.6
+-- npm@6.14.5
+-- tsuml@0.0.1-alpha.8
`-- typescript@3.8.3
```

Cat

**Comment by ffacal** [comment]
I'm having the same issue while trying to upgrade from Node 8 to Node 10. Any findings?

**Comment by taeold** [comment]
Sorry we are late to respond. Are you still seeing a problem? If so, can you give updating your firebase-tools to version >9.0.0 and let us know if the issue persis?

**Comment by taeold** [comment]
Marking the issue as closed. Feel free to re-open if you continue experience problems.
