### ISSUE TITLE
Support for latest version of firebase-admin

### ISSUE THREAD

**Issue by thien-do** [firebase/firebase-functions#755]
### Related issues

None found

### [REQUIRED] Version info

**node:** 12

**firebase-functions:** 3.9.0

**firebase-tools:** 8.7.0

**firebase-admin:** 8.0.0 (this is the problematic one)

### [REQUIRED] Test case

Not applicable

### [REQUIRED] Steps to reproduce

```
npm install firebase-functions@latest firebase-admin@latest
```

### [REQUIRED] Expected behavior

I think it's better if firebase-functions requires latest version of firebase-admin instead of the previous one.

I'm sorry if there is expected behaviour. I saw that firebase-admin was updated to 9.0.0 somewhere a month ago so I'm wondering when can I use it with firebase-functions

### [REQUIRED] Actual behavior

firebase-functions requires firebase-admin 8.0.0

### Were you able to successfully deploy your functions?

I can still deploy my functions when rolling back firebase-admin to 8.0.0

Thank you

**Comment by lmadhuranga** [comment]
Not support to node latest version, I can't use node 8 for this project only 
![image](https://user-images.githubusercontent.com/3930563/90080204-a6325180-dd27-11ea-83ec-c0e3cbe1db33.png)

**Comment by joehan** [comment]
Hey all, we are planning on updating to firebase-admin@9.0.0 with out next major release. Firebase-admin@9.0.0 dropped support for node 8, and we're not quite ready to do so yet.

**Comment by samtstern** [comment]
@joehan is this still an issue?
https://github.com/firebase/firebase-functions/blob/master/package.json#L81

**Comment by joehan** [comment]
Nope, this was fixed by https://github.com/firebase/firebase-functions/commit/d1432c50863dec4b27834241279180f12f6148d5, it looks like we forgot to close this.
