### ISSUE TITLE
tenantId missing in authentication triggers

### ISSUE THREAD

**Issue by major-mann** [firebase/firebase-functions#762]
### Related issues
None

### [REQUIRED] Version info

**node:**
10

**firebase-functions:**
3.9.1

**firebase-tools:**
7.12.1

**firebase-admin:**
8.13.0

### [REQUIRED] Test case

A single cloud function attached to the user create authentication trigger using `functions.auth.user().onCreate`, and a user created manually through the web interface (inside of a tenant)

### [REQUIRED] Steps to reproduce

1. Tie up an event using `functions.auth.user().onCreate`
2. Create a user inside of a tenant
3. When the event fires, the tenantId should be attached to the UserRecord

### [REQUIRED] Expected behavior

The tenantId should be attached to the user record

### [REQUIRED] Actual behavior

There is no tenantId attached to the user record

### Were you able to successfully deploy your functions?

Yes, no errors, the event runs as expected, but does not receive the expected tenantId in the UserRecord

**Comment by major-mann** [comment]
Is there any response to this issue? It has now been a full quarter without any response in a paid service.

**Comment by ocularity** [comment]
Also looking to implement this, did you find a solution / workaround? Will share anything I find here.

**Comment by mbleigh** [comment]
I believe that this has been fixed, and `tenantId` should now show up in the payload. I'm just realizing that we may need to update TypeScript typings in the SDK to reflect this, but please try to experiment with something like:

```
exports.newUser = functions.auth.user().onCreate(user => {
  console.log(user.tenantId);
});
```

**Comment by mbleigh** [comment]
Closing as I actually believe this is fully working now - please comment if it's not.

**Comment by ocularity** [comment]
Brilliant, thanks for the update Michael -- had just tried that and was validating before reporting back, glad to see you've got it resolved!
