### ISSUE TITLE
Error 401 while calling the callable function from Postman

### ISSUE THREAD

**Issue by susahnthmshetty** [firebase/firebase-functions#769]
Followed https://firebase.google.com/docs/functions/callable-reference to call a callable function using Axios. while testing in firebase emulator things work fine but the same code throws Unauthorized error while calling the cloud function.

URL https://us-central1XXXXXXXX.cloudfunctions.net/callableFunction2
Type: POST
Headers:
Authorization: Bearer <TOKEN>
Content-Type: application/json

Response: {
    "error": {
        "message": "Unauthenticated",
        "status": "UNAUTHENTICATED"
    }
}

"node": "10"
"firebase-admin": "^8.10.0",
"firebase-functions": "^3.11.0",

**Comment by mbleigh** [comment]
You have `Authorization: Bearer` without a token afterwards -- callable functions look for an Authorization header and try to parse a valid JWT ID token from it for the Firebase project. You need to either remove the header (to call it unauthenticated) or provide a valid ID Token in the header.
