### ISSUE TITLE
Default maxInstances changed to 1?

### ISSUE THREAD

**Issue by op** [firebase/firebase-functions#774]
Just upgraded to nodejs12. Set it in `firebase.json` instead of `engines`.

Noticed that the default maximum active instances is now `1` instead of not set. It could of course be something we have fiddled with but by looking at the graph for "active instances" in the cloud console it do look like a new change.

Adding a `.runWith({ maxInstances: x })` overrides this of course.

Can this be true, and is this deliberately?

**Comment by taeold** [comment]
Hi @op. Thanks for filing the issue.

Can you share a little bit more about how I can reproduce the issue? I'm unsure about what you've done in the `firebase.json`, instead of `functions/package.json`, to update the runtime.

AFAIK, I'm not aware of any changes to change the default value for max instances that affects only the nodejs12 runtime.
I've tried deploying a nodejs12 function by modifying the `engine` field in the `functions/package.json`, and I'm not seeing `maxInstance` being set to any default value.

**Comment by taeold** [comment]
NVM, I've found how I can set runtime in `firebase.json`.

I'm unable to reproduce the behavior described here:

<img width="388" alt="Screen Shot 2020-09-10 at 10 47 22 AM" src="https://user-images.githubusercontent.com/14897098/92672171-11853880-f353-11ea-9e86-ec85773fc5d7.png">

Are you aware of any organization policy that may be affecting the max instance count in your deployed function?

**Comment by op** [comment]
I'm not aware of any organization policy. Nothing intentional at least. We have 3 exposed http endpoints in 3 environments, they all have the same max instances now after the upgrade.

We set them up with `functions.https.region(REGION).onRequest(...)`.

We upgraded `firebase-functions` from 3.3.0 to 3.11.0. The former version did not have `maxInstances` at all.

Feel free to investigate our projects if interested. I'll send all project ids separately.

**Comment by taeold** [comment]
Thanks for the update @op!

Yeah this is truly odd. I've tried creating several functions with the conditions you've mentioned:

1) Set runtime to nodejs12 on `firebase.json` 
2) Define functions using `functions.regions(REGION).https.onRequest(...)`
3) Using `firebase-functions` version 3.11.0

Looks like I'm still missing some condition that you've stepped on. I don't have any more special privilege to access your projects. Do you mind trying out few more scenarios like updating your firebase cli client, using nodejs10 runtime, using different regions, etc.?

**Comment by op** [comment]
@taeold Really sorry, but I don't have time to look into this more. Sounds like there's is something with our setup. Thanks for looking into it though!
