### ISSUE TITLE
auth trigger onCreate() does not provide email etc.

### ISSUE THREAD

**Issue by dflorey** [firebase/firebase-functions#775]
When creating a new user, the provider data and email is not present, even though it appears in the dashboard.

```
export const newUser = functions.auth.user().onCreate(user => {
    console.log(`New User detected ${JSON.stringify(user)} with with email=${user.email} and uid=${user.uid}`)
}
```

**Comment by huangjeff5** [comment]
Hello @dflorey,

Could you post the entire code sample? Could you also share the code sample you are using, for creating the users?

FWIW, I modified your code slightly to get it to compile on a fresh copy of `firebase init functions`. After testing it out, my function seemed to get the provider data and email to pass through.

This is the `index.js`:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

exports.newUser = functions.auth.user().onCreate(user => {
    console.log(`New User detected ${JSON.stringify(user)} with with email=${user.email} and uid=${user.uid}`)
})
```

I then manually tested adding a user and found this in the logs, as expected:
```
New User detected {"uid":"WqsnBH5uIzZpxgGdPvB3GTbVDlq1","email":"123123@gmail.com","emailVerified":false,"displayName":null,"photoURL":null,"phoneNumber":null,"disabled":false,"passwordHash":null,"passwordSalt":null,"tokensValidAfterTime":null,"metadata":{"creationTime":"2020-09-16T00:49:15Z"},"customClaims":{},"providerData":[{"email":"123123@gmail.com","providerId":"password","uid":"123123@gmail.com"}]} with with email=123123@gmail.com and uid=WqsnBH5uIzZpxgGdPvB3GTbVDlq1 |  
-- | --
```

Perhaps changing `export const newUser` to `exports.newUser` would solve your problem. If not, it may be related to the specific mechanism for how you are adding a user. (Perhaps there are possible bugs when adding users in bulk or other scenarios).

**Comment by joehan** [comment]
Closing this issue due to lack of response.
