### ISSUE TITLE
error TS5033: Could not write file '/Users/usr/Desktop/Yoveo/functions/lib/index.js': EACCES: permission denied, open '/Users/user/Desktop/Yoveo/functions/lib/index.js'.    error TS5033: Could not write file '/Users/user/Desktop/Yoveo/functions/lib/index.js.map': EACCES: permission denied, open '/Users/user/Desktop/Yoveo/functions/lib/index.js.map'.

### ISSUE THREAD

**Issue by makinggainz** [firebase/firebase-functions#783]
### Related issues

https://www.reddit.com/r/Firebase/comments/ivmntu/npm_err_failed_at_the_functions_lint_script_npm/

### [REQUIRED] Version info

**node:**

 
v12.2.0

**firebase-functions:** Latest

**firebase-tools:** Latest

8.10.0

**firebase-admin:**
Yes

### [REQUIRED] Test case
**Dont believe I can do this.** 

### [REQUIRED] Expected behavior

Functions deploy successfully to firebase

### [REQUIRED] Actual behavior

Errors, see bellow: 

Update:

new errors: 
error TS5033: Could not write file '/Users/usr/Desktop/Yoveo/functions/lib/index.js': EACCES: permission denied, open '/Users/user/Desktop/Yoveo/functions/lib/index.js'.

error TS5033: Could not write file '/Users/user/Desktop/Yoveo/functions/lib/index.js.map': EACCES: permission denied, open '/Users/user/Desktop/Yoveo/functions/lib/index.js.map'.

---------

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/me/Desktop/Yoveo/functions',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle functions@~prelint: functions@
6 info lifecycle functions@~lint: functions@
7 verbose lifecycle functions@~lint: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/me/Desktop/Yoveo/functions/node_modules/.bin:/Users/me/miniconda3/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/me/miniconda3/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin
9 verbose lifecycle functions@~lint: CWD: /Users/me/Desktop/Yoveo/functions
10 silly lifecycle functions@~lint: Args: [ '-c', 'tslint --project tsconfig.json' ]
11 silly lifecycle functions@~lint: Returned: code: 2  signal: null
12 info lifecycle functions@~lint: Failed to exec lint script
13 verbose stack Error: functions@ lint: `tslint --project tsconfig.json`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid functions@
15 verbose cwd /Users/me/Desktop/Yoveo
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "/Users/me/Desktop/Yoveo/functions" "run" "lint"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error functions@ lint: `tslint --project tsconfig.json`
22 error Exit status 2
23 error Failed at the functions@ lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

### Were you able to successfully deploy your functions?
NO

When you ran `firebase deploy`, did you see any error messages?
YES

**Comment by makinggainz** [comment]
Initialy I had forgotten to add express to my dependencies in the packadge.json file. After adding I am left with those 2 new errors

**Comment by inlined** [comment]
This is a permissions issue. For some reason you don't have write access to your lib folder, so the TypeScript compiler is failing to turn your TypeScript into JavaScript. If I had to guess, I'd say that this is because you ran `firebase` with `sudo` before and you're not running with it now (as you shouldn't). The following command will get rid of the lib folder for you. If your project folder has sane permissions, then it'll get recreated with sane permissions:

```
sudo rm -r /Users/usr/Desktop/Yoveo/functions/lib
```

If that doesn't work, you can take ownership of your functions folder with

```
sudo chown -R Yoveo /Users/usr/Desktop/Yoveo/functions
```

**Comment by tarungarg05** [comment]
Faced same issue, resolved by adding npm lib path to environement variables.

**Comment by tympo-tech** [comment]
I had this issue on NestJS project. When I deleted the `dist` folder of the project and re-build it using `nest build`. Worked fine arfter that.
