### ISSUE TITLE
Fix onWrite docs. Fix Functions upload error handling.

### ISSUE THREAD

**Issue by bsmith418** [firebase/firebase-functions#784]
Looking at:
https://firebase.google.com/docs/functions/firestore-events

With document path:
Writing Cloud Firestore-triggered functions > Define a function trigger

You'll find the example code:
exports.myFunction = functions.firestore
  .document('my-collection/{doc-id}')

However, {doc-id} will break your functions, and it will furthermore spit out a useless error message. The hyphen breaks it. It should be {docID} in the docs, and the error message should be improved.

**Comment by joehan** [comment]
Thanks for pointing this out @bsmith418! I just corrected this, you should see be able to see the correction soon.

**Comment by joehan** [comment]
Reopening this since the error message hasn't been fixed yet.

**Comment by taeold** [comment]
Firebase CLI deploy no longer print any error messages and directs users to look directly at Google Cloud console to debug deployment issues. Will close this issue - if there is a FR to make error messages clearer, let's file them in https://github.com/firebase/firebase-tools.
