### ISSUE TITLE
EventContext.authType is not defined for Firestore DB triggers

### ISSUE THREAD

**Issue by wujekbogdan** [firebase/firebase-functions#785]
### [REQUIRED] Version info

**node:**

`v10.16.3`

**firebase-functions:**

`8.10.0`

**firebase-tools:**

`8.10.0`

**firebase-admin:**

`7.4.0`

### [REQUIRED] Test case

``` js
import * as functions from 'firebase-functions';

export const dbUsersOnUpdate = functions.firestore
  .document('users/{userId}')
  .onUpdate((change, context) => {
    console.log(typeof context.authType); // undefined
  });
```

### [REQUIRED] Steps to reproduce

Read the `authType` property from `EventContext` object that's provided by all DB triggers.

### [REQUIRED] Expected behavior

`authType` to be `"ADMIN" | "USER" | "UNAUTHENTICATED"`

### [REQUIRED] Actual behavior

`authType` is `undefined`;

### Were you able to successfully deploy your functions?

Yes.

---

I know that `EventContext.auth` is not available in Firestore. [The documentation is explicit about it](https://firebase.google.com/docs/reference/functions/cloud_functions_.eventcontext#auth), but the [docs don't say anything about `authType` being unavailable in Firestore](https://firebase.google.com/docs/reference/functions/cloud_functions_.eventcontext#optional-authtype). So this is either a bug in `firebase-functions` or, more likely, a bug in the docs.

**Comment by adotnusiyan** [comment]
Same thing with `context.auth`, it's always `undefined`

**Comment by mbleigh** [comment]
Firestore does not currently support passing auth context through to events, so this is expected. There is nothing that can be done in this repo to address this, but I encourage you to [file a feature request](https://firebase.google.com/support/troubleshooter/report/features) so that we can prioritize it internally. Thanks!

**Comment by wujekbogdan** [comment]
@mbleigh 

> Firestore does not currently support passing auth context through to events, so this is expected. There is nothing that can be done in this repo to address this, but I encourage you to file a feature request so that we can prioritize it internally. Thanks!

As I wrote in my comment - I expect it to be a bug in the docs. The documentation says that `EventContext.auth` is `undefined` in Firestore, but the documentation for `EventContext.authType` is not clear about it. So It would be great if you updated your docs because it's confusing at the moment.
