### ISSUE TITLE
Middleware not working in onRequest 

### ISSUE THREAD

**Issue by rahulserver** [firebase/firebase-functions#786]
### [REQUIRED] Version info

**node:**

12.18.2
**firebase-functions:**
^3.6.1
**firebase-tools:**
8.4.3

**firebase-admin:**
^8.10.0
### [REQUIRED] Test case

I created this repo here: https://github.com/rahulserver/cfmiddlewaretest/
### [REQUIRED] Steps to reproduce

Just create a simple cloud function(index.js): 

```
const functions = require('firebase-functions');
const cors = require('cors');
exports.myFn = functions.https.onRequest((req, res) => {
  console.log("hit this");
  return cors(req, res, () => {
    // ...
    console.log("inside cors");
    res.send(200);
  });
});
```
### [REQUIRED] Expected behavior
When called using postman, it must send 200 status code and print "inside cors" on the console.

### [REQUIRED] Actual behavior
Just "hit this" is printed in console and "inside cors" is never called.
I get the error: `Function execution took 60002 ms, finished with status: 'timeout'`

### Were you able to successfully deploy your functions?
Yes

No errors.

**Comment by mbleigh** [comment]
You need to initialize cors first, you are passing the factory method
instead of a configured instance

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/questions/64080764/middleware-in-firebase-cloud-function-using-onrequest-never-gets-hit
