### ISSUE TITLE
Error in 'lint' scipt

### ISSUE THREAD

**Issue by mnegabriel** [firebase/firebase-functions#788]
### [REQUIRED] Version info

**node:**

v12.18.3

**firebase-functions:**
Default function that comes with `firebase init functions`, choosing Typescript, Yes for Eslint

**firebase-tools:**

8.11.2

**firebase-admin:**

### [REQUIRED] Test case

[https://github.com/mnegabriel/testing-firebase-functions](https://github.com/mnegabriel/testing-firebase-functions)

### [REQUIRED] Steps to reproduce

1. run `firebase login`
2. run `firebase init functions`
3. add to existing project
4. Choose Typescript
5. Choose 'y' for Eslint file
6. Choose 'y' to install dependencies
7. inside de src/index.ts file, uncomment the default test function
8. run `firebase deploy`

### [REQUIRED] Expected behavior

[Getting Started with Cloud Functions for Firebase using TypeScript - Firecasts - Youtube](https://youtu.be/DYfP-UIKxH0?t=476)
![image](https://user-images.githubusercontent.com/29488692/94684519-8ae2cc00-02fe-11eb-9842-11786033087b.png)

### Were you able to successfully deploy your functions?

```
C:\Users\gabri\GitHub\functions>firebase deploy

=== Deploying to 'afazer-app'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint C:\Users\gabri\GitHub\functions
> eslint 'src/**/*'


Oops! Something went wrong! :(

ESLint: 7.10.0

No files matching the pattern "'src/**/*'" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ lint: `eslint 'src/**/*'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gabri\AppData\Roaming\npm-cache\_logs\2020-09-30T12_24_40_035Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code2
```

PS: I'm trying to make a To Do web app by myself, trying to practice my front end (React) and back end (NodeJs api) skills whilst trying to learn to work with the cloud (for now, only auth and storage for this app). What i'm trying to do here is to make my API accessible online with firebase functions, not sure if it's the best solution. Struggling but not giving up. Thanks for any help.

**Comment by mnegabriel** [comment]
I noticed the problem with `firebase serve`, it was the node version

**Comment by panchoggit** [comment]
[](https://stackoverflow.com/questions/64082945/firebase-deploy-no-files-matching-the-pattern-src-were-found)

[](https://github.com/firebase/firebase-tools/pull/2651/commits/ad1dfbce572f42582bd5bebbd199259e96ed7c28)

**Comment by panchoggit** [comment]
https://github.com/firebase/firebase-tools/pull/2651/commits/ad1dfbce572f42582bd5bebbd199259e96ed7c28
