### ISSUE TITLE
Deploy Issue code 13 Failed to retrieve function source code

### ISSUE THREAD

**Issue by dash7ou** [firebase/firebase-functions#790]
when I have updated my functions code get this error and I send an email to firebase support with debug details and no response?

{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Failed to retrieve function source code"},"authenticationInfo":{"principalEmail":"x@gmail.com"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"x"}

**Comment by joehan** [comment]
Hi @dash7ou - we've seen this error a few times lately with Node 8 deploys. It usually goes away if you try to redeploy, and the Cloud Functions team is working on a fix for it. Could you try to redeploy your functions? If that doesn't work, I'd recommend trying to deploy on Node 10 instead if you are on a blaze plan.

**Comment by dash7ou** [comment]
@joehan  I am using Node 10 and I had email firebase support and replay email not help me or solve the issue.

**Comment by joehan** [comment]
Sorry to hear that @dash7ou. If you share your projectID, I can open a bug for the Cloud Functions team to look into what is happening here. Unfortunately, with the info provided here, I won't be able to investigate this further.

**Comment by seekgetgo** [comment]
Facing the same issue. Using node v12.18.2

**Comment by joehan** [comment]
Thanks for reporting @seekgetgo ! As far as I can tell, this is an issue with the Cloud Functions API, and we won't be able to fix it in this repo. I'm going to raise this again to the Cloud Functions team - if anyone can provide a project ID where this issue happened, I'll also pass that along to the Cloud Functions to help them investigate.

**Comment by dash7ou** [comment]
@joehan google firebase support ignore us 💯

**Comment by subhendukundu** [comment]
I am getting the same error, even after deleting all functions and trying ti redeploy I am getting an error shouting
```{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"Failed to retrieve function source code"
```
Was there a fix? @dash7ou

**Comment by dash7ou** [comment]
Yup, my issue solved after I solved my app issue with twillio check your paid API's

**Comment by CorbsReyes** [comment]
I'm also getting the same error, Tried renaming function and deleting it but it just showing me the error over and over again. May i know what is the fix for this error?

**Comment by dash7ou** [comment]
This might be an issue with the Cloud Functions Configuration. In order to fix this issue, please try resetting your Cloud Functions configuration by:
Going to the Cloud Console > Cloud Functions List and delete all of the deployed functions.
Go to API Manager and disable the Google Cloud Functions API (don't forget to select the correct project you want to reset the configurations to).
Update to the latest version of the CLI by running `npm i -g firebase-tools`.
Re-deploy your functions with `firebase deploy --only functions --debug`

**Comment by utkarsh-var** [comment]
> I'm also getting the same error, Tried renaming function and deleting it but it just showing me the error over and over again. May i know what is the fix for this error?

@CorbsReyes I had a similar issue, but it was fixed after moving from the default Spark plan to the Blaze plan.

**Comment by kelvinchot** [comment]
I had this issue while on the Blaze plan. What worked for me was deleting all my functions, downgrading to Spark and then upgrading back to Blaze. After that I initialized functions and redeployed my functions, voila!
