### ISSUE TITLE
Error: Internal when calling firebase functions

### ISSUE THREAD

**Issue by ehunde** [firebase/firebase-functions#791]
Hi guys

I get the following error :

Error: internal
    at new y (error.ts:66)
    at w (error.ts:175)
    at A.<anonymous> (service.ts:263)
    at tslib.es6.js:100
    at Object.next (tslib.es6.js:81)
    at r (tslib.es6.js:71)

When I try to call the function "addPerson" in Firebase.

Index.html

` <input type ="text" id="fName" placeholder="First Name">
         <input type ="text" id="lName" placeholder="Last Name">
         <button  onclick="addEmployee()"> Add Person </button>

         <script>
            function addEmployee(){
                var firstName = document.getElementById("fName").value;
                var lastName  = document.getElementById("lName").value;
        
                var addPerson  = functions.httpsCallable('addPerson');
                addPerson({
                    firstName:firstName,
                    lastName:lastName
                }).then(function(result){
                console.log(result);
                }).catch(function(error){
                console.log(error);
                })
            }
    
        </script>`

Index.js

`

const functions = require('firebase-functions');

exports.addPerson = functions.https.onCall((data, context) => {

    var firstName = data.firstName;
    var lastName  = data.lastName;
    return {

        firstName: firstName,
        lastName : lastName,
        fullName : firstName + " "+ lastName
    }
});

`

**Comment by moaaz-bhnas** [comment]
Check the error log in firebase dashboard. You may find something more specific there.

**Comment by samtstern** [comment]
@ehunde sorry for the slow response but this is not the right place to file issues about Functions failing in production.  @moaaz-bhnas is right, this means your callable function is crashing in your code before you return the result.
