### ISSUE TITLE
Getting "Failed to initialize region" when I try to deploy a function

### ISSUE THREAD

**Issue by moaaz-bhnas** [firebase/firebase-functions#794]
### Related issues
[https://github.com/firebase/firebase-tools/issues/592](https://github.com/firebase/firebase-tools/issues/592)

###  Version info

**node:** 10

**firebase-functions:** 3.11.0

**firebase-tools:** 8.0.3

**firebase-admin:** 8.13.0

### Steps to reproduce

Deploy this function (or actually any function) which should handle app requests in my NextJS project:
```node
const server = functions.https.onRequest((request, response) => {
  return app.prepare().then(() => handle(request, response));
});
```

### Expected behavior

The function gets deployed sucessfully.

### Actual behavior

The function doesn't get deployed due to **failure to initialize region**.
#### Error log:
```
!  functions[nextjs-server(us-central1)]: Deployment error.
Failed to initialize region (action ID: 4891ccb9283ae125)


Functions deploy had errors with the following functions:
        nextjs-server
```

### Were you able to successfully deploy your functions?

No

**Comment by iscojin** [comment]
Same here
I never face this one issue before, even if I work with Node.js 8 or 10
But at this time, just take me the initialize region error.
Who can help me?
Here is my deployment screenshot. 
![image](https://user-images.githubusercontent.com/60736395/101966960-c4ca2b80-3be7-11eb-849f-23a0049d7d8c.png)

Then another one is a screenshot of used firebase project.
![image](https://user-images.githubusercontent.com/60736395/101967026-196da680-3be8-11eb-88d6-7e3fb797b41b.png)

Thank you!!!

**Comment by taeold** [comment]
This is most likely an temporary issue with the specific region Google Cloud Function.

I suspect the issue has long been resolved. Please re-open the ticket and let us know if any of you two are still experiencing a similar issue.
