### ISSUE TITLE
Process exited with code 16 error

### ISSUE THREAD

**Issue by huma11farheen** [firebase/firebase-functions#796]
### Related issues
The bugs reported on console when using cloud scheduler -
1) `Process exited with code 16`
2) `Firestore: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded`

### [REQUIRED] Version info

**node:**
v12.18.0

**firebase-functions:**
3.11.0
**firebase-tools:**
8.9.2

**firebase-admin:**
9.2.0

### [REQUIRED] Steps to reproduce
```
import * as admin from 'firebase-admin'
import * as functions from 'firebase-functions'
import { PubSub } from "@google-cloud/pubsub"
const db = admin.firestore()

const maxNumberOfDocsToDeleteInABatch = 500;
//Schedule everyday at 2
export const deleteUsersPassed30daysScheduler = asiaRegionFunctions.pubsub
	.schedule('0 2 * * *')
	.onRun(async () => {
        const pubsub = new PubSub();
        
        //Fetching users accordint to some condition to delete
        const query = db.collection('users');
        const usersToDelete =  await query.get();
        for (const user of usersToDelete.docs) {
			await Promise.all(
				[
					admin.auth().deleteUser(user.id),
					pubsub.topic("deleteMessageGroups")
						.publishJSON({ "user": user })
				]
			)
		}
	})

export const deleteMessageGroups = asiaRegionFunctions.pubsub
	.topic("deleteMessageRoomsPassed30daysTopic")
	.onPublish(async (context) => {
		const uid = context.json.user.id
		const query = db.collection('users').where('Some_condition', 'array-contains', uid)
		await recursiveDeleteForQuery(query, maxNumberOfDocsToDeleteInABatch, async (doc) => {
			await recursiveDeleteForQuery(doc.ref.collection("Some_collection"), maxNumberOfDocsToDeleteInABatch)
			await recursiveDeleteForQuery(doc.ref.collection("Some_collection"), maxNumberOfDocsToDeleteInABatch)
		})
    })
    
    export const recursiveDeleteForQuery = async (query: admin.firestore.Query, limit: number, iterator?: (s: admin.firestore.QueryDocumentSnapshot) => void) => {
        const snapshot = await query.limit(limit).get()
        if (snapshot.size > 0) {
            const batch = admin.firestore().batch()
            snapshot.forEach(doc => {
                if (iterator) iterator(doc)
                batch.delete(doc.ref)
            })
            await batch.commit()
            await recursiveDeleteForQuery(query, limit, iterator)
        }
    }
```

### [REQUIRED] Expected behavior
Finish executing without error

### [REQUIRED] Actual behavior
Error are being logged-
1) `Process exited with code 16`
2) `Firestore: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded`

<img width="889" alt="Screenshot 2020-10-16 at 1 00 03" src="https://user-images.githubusercontent.com/56956749/96155692-2e60ed00-0f4b-11eb-8a79-7255318592b3.png">

<img width="1218" alt="Screenshot 2020-10-15 at 14 21 20" src="https://user-images.githubusercontent.com/56956749/96155598-11c4b500-0f4b-11eb-96dd-72ac0c6f4b29.png">

### Were you able to successfully deploy your functions?

Yes

**Comment by aravindvnair99** [comment]
@huma11farheen Does setting to `490` instead of `500` work? You can do `490` first and once that's done, do the next batch.

**Comment by huma11farheen** [comment]
@aravindvnair99 
But we are allowed to write a maximum of 500 right?

**Comment by aravindvnair99** [comment]
> @aravindvnair99
> But we are allowed to write a maximum of 500 right?

@huma11farheen It's supposed to be 500 as far as I know. But one of my friends got it working this way. I'm not sure if it will help you or if it is the right solution.

**Comment by taeold** [comment]
It looks like your function is timing out. Cloud Functions will kill any process that runs for more than the default timeout (60 seconds):

https://cloud.google.com/functions/docs/concepts/exec#timeout

You can try extending the timeout (up to 9minutes) using the `runWith` option:

```
const fn = functions
    .region('us-east1')
    .runWith({
      timeoutSeconds: 60 * 9 // 9 minutes,
    })
```

If you are still having issues, let us know by re-opening the issue.

**Comment by sasirekha06** [comment]
Still we are facing same kind of issue even though the time is 540 seconds in code does we have any other solution from infrastructure point of view?
