### ISSUE TITLE
Cloud Functions: "Client network socket disconnected before secure TLS connection was established" occurs when googleapis used

### ISSUE THREAD

**Issue by NaveenJayaram94** [firebase/firebase-functions#799]
### [REQUIRED] Version info

**node: v10.22.0**

**firebase-functions: ^3.11.0**

**firebase-tools: 8.10.0**

**firebase-admin: ~5.11.0**

### [REQUIRED] Test case

We have developed an express server and deployed it to cloud functions. In our application, we have a feature to download a bunch of files (around 100+ files)  from storage and upload them to Google drive ( using DRIVE API). While downloading the files or uploading to drive, an error occurs saying "Client network socket disconnected before secure TLS connection was established". 
After doing 3 months of research on the internet we come to know that, we can set the HTTP_PROXY  in the environment variable, we set HTTP_PROXY = www.googleapis.com in the .env file and deployed but we are still facing the same issue. It's been 3 months since we still not found the solution for this.

https://github.com/googleapis/google-api-nodejs-client#using-a-proxy

1. what could be the reason for this error which occurs uncertain
2. if setting HTTP_PROXY will help us, how to set and what value to set

### [REQUIRED] Steps to reproduce

- Create node express server which uses drive API's as mentioned above 
- deploy the app to cloud function using firebase deploy --only function

### [REQUIRED] Expected behavior
  Can be able to download or upload files without any connection reset issue as mentioned above

### [REQUIRED] Actual behavior
 Mentioned error occur

![Screenshot 2020-10-22 at 11 35 24 PM](https://user-images.githubusercontent.com/9761921/96912012-4a224100-14bf-11eb-9248-d2a8e3682544.png)

### Were you able to successfully deploy your functions? Yes

**Any Immediate help will be grateful.**

**Comment by samtstern** [comment]
@NaveenJayaram94 thank you for the feedback and sorry for the slow response.  This repo is only for issues with the `firebase-functions` SDK and it's not the right place to file issues about Cloud functions errors in production.

I'd suggest using either the Cloud Issue tracker or Firebase support to resolve this:
https://cloud.google.com/support/docs/issue-trackers
https://firebase.google.com/support
