### ISSUE TITLE
Google Cloud Vision Error: Codelab Tutorial

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-functions#800]
### [REQUIRED] Version info

**node:** 12.19.0

**firebase-functions:** 3.11.0

**firebase-tools:** 8.13.1

**firebase-admin:** 9.3.0

### [REQUIRED] Test case

Install the most current version of `npm install --save @google-cloud/vision`;

### [REQUIRED] Steps to reproduce

https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#8 

The example does not work with the most current version of Google Cloud Vision `**2.1.2**

### [REQUIRED] Expected behavior
The Cloud Vision To Work 

### [REQUIRED] Actual behavior
Cloud Vision didn't work even though I have the updated version of **2.1.2** instead of **0.12.0** 

### Were you able to successfully deploy your functions?

No. See the screenshot attached. 
<img width="1363" alt="Screen Shot 2020-10-23 at 7 01 46 PM" src="https://user-images.githubusercontent.com/4000076/97060708-34198c80-1562-11eb-891b-187b39a9feb7.png">

**Comment by taeold** [comment]
You'll need to adjust your code if you want to use the latest Cloud Vision library. There is at least 2 major version update, so the fact that the old code doesn't work against the latest Cloud Vision library isn't too surprising to me.

I think it's a good idea for us to update the codelab - I'll file an internal bug to see if there is anyone interested in giving the codelab an update.

**Comment by JamesVanWaza** [comment]
> You'll need to adjust your code if you want to use the latest Cloud Vision library. There is at least 2 major version update, so the fact that the old code doesn't work against the latest Cloud Vision library isn't too surprising to me.
> 
> I think it's a good idea for us to update the codelab - I'll file an internal bug to see if there is anyone interested in giving the codelab an update.

Let us know when the update posts @taeold

**Comment by JamesVanWaza** [comment]
@taeold did they update it on the codelab?
