### ISSUE TITLE
Firebase Functions exact Node.js version is missing in docs

### ISSUE THREAD

**Issue by serhiipalash** [firebase/firebase-functions#801]
Hi! Can you please tell what is the exact Node.js version in your Cloud when we use this config?
```
"engines": {"node": "12"}
```
We need it to configure `.nvmrc` in our monorepo as all our packages follow backend Node version.

We are on node 10 engine at the moment and use `v10.15.3` as default in nvm config, but we want to migrate on node 12.

**Comment by mbleigh** [comment]
It's currently `12.18.3` -- note that I determined this in the same way you can: I deployed a Node 12 function and looked at the output of `process.versions` 😄

**Comment by serhiipalash** [comment]
Great to know! Thank you @mbleigh !

**Comment by dominicbartl** [comment]
You can also check the logs in [Logs Explorer](https://console.cloud.google.com/logs/query;query=resource.type%3D%22build%22%0AtextPayload:%22Step%20%231%20-%20%5C%22build%5C%22:%20v%22). Cloud Build prints the version when building the containers and you can filter it using those values:

```
resource.type="build"
textPayload:"Step #1 - \"build\": v"
```

Though having it documented somewhere would be neat too.
