### ISSUE TITLE
Firebase Functions Error

### ISSUE THREAD

**Issue by Flucadetena** [firebase/firebase-functions#802]
### Related issues

Yes, there is a related Issue but it is closed. [#337](https://github.com/firebase/firebase-functions/issues/337)

### Version info

I'm using node 12, And have tried to downgrade to 10 and the same error occurred.

node: v12.16.3
"firebase-admin": "^9.3.0",
"firebase-functions": "^3.11.0",
"gm": "^1.23.1"
Firebase-tools: 8.13.1

### Test case

```
import * as functions from "firebase-functions";
import { createWriteStream } from "fs";
import axios from "axios";
import gm from "gm";

export const testTreatImage = functions.https.onRequest(async (req, res) => {
	try {
		const url = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/best-skincare-products-glowing-skin-1561735403.png";
		const originalPath = "/tmp/original.jpg";
		await downloadImage(url, originalPath);
		await treatImg(originalPath);

		res.status(200).send({ message: "OK" });
	} catch (err) {
		console.error(`Error saving the image: `, err.toString());
		res.status(400).send({ message: "ERROR" });
	}
});

async function downloadImage(url: string, originalPath: string) {
	try {
		const decodeUrl = decodeURIComponent(url);
		const res = await axios.get(decodeUrl, { responseType: "stream" });

		res.data.pipe(createWriteStream(originalPath));

		return new Promise<string>((resolve, reject) => {
			res.data.on("end", () => {
				resolve(originalPath);
			});

			res.data.on("error", () => {
				console.log("Err");
				reject();
			});
		});
	} catch (err) {
		console.error("Error downloading the img: ", err.toString());
		throw new Error();
	}
}

async function treatImg(originalPath: string) {
	try {
		const saveImg = (path: string, event: gm.State) => new Promise((resolve) => event.write(path, resolve));

		const oneMWebp = "/tmp/1000.webp";
		const oneWebpError: any = await saveImg(
			oneMWebp,
			gm(originalPath).fill("rgb(247,247,247)").fuzz(5, true).opaque("rgb(255,255,255)").quality(50).resize(1000, undefined, "^").strip(),
		);
		if (oneWebpError !== undefined) throw new Error(oneWebpError.toString());

		return null;
	} catch (err) {
		console.error("Error treating the img and resizing: ", err.toString());
		throw new Error();
	}
}

```
### Steps to reproduce

Call the http function.

### Expected behavior

Work and treat the image, as it does in local dev.

### Actual behavior

Error treating the img and resizing: Error: Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-quality" "50" "/tmp/original.jpg" "-fill" "rgb(247,247,247)" "-fuzz" "5%" "-opaque" "rgb(255,255,255)" "-resize" "1000x^" "+profile" "\"*\"" "+comment" "/tmp/1000.webp" this most likely means the gm/convert binaries can't be found

### Were you able to successfully deploy your functions?

Yes no problem at all.

Thanks a lot!

**Comment by mbleigh** [comment]
GraphicsMagick is not installed in the runtime container used by Cloud Functions (ImageMagick is). You will need to switch to a library that uses ImageMagick instead, as `gm` is not available.

**Comment by Flucadetena** [comment]
Hi @mbleigh Sorry to disagree but as stated in this tutorial from the documentation of cloud functions [tutorial](https://cloud.google.com/functions/docs/tutorials/imagemagick). `gm` is available. I did forget to add `gm.subClass({ imageMagick: true });` in the example, but not on the real code I use, and the result is the same.

Does `Cloud functions` have different installations than `Firebase functions`?

**Comment by mbleigh** [comment]
Ah, my mistake! I didn't realize `gm` could use ImageMagick. There is no difference between Firebase/Cloud here, but this issue also doesn't seem related to the `firebase-functions` SDK. The error message here is pretty opaque and could probably be a number of things -- have you checked to make sure the image is successfully downloaded to the specified `/tmp` path? Maybe something to try would be to use `spawn` or `exec` from [child_process](https://nodejs.org/api/child_process.html) to manually run the `convert` command so you can see the raw output.

I'm not going to follow up further in this issue since we try to keep GH on topic, but if you try some more experiments and still can't figure out what's going on, feel free to reach out to [Firebase support](https://firebase.google.com/support/troubleshooter/contact).

**Comment by Flucadetena** [comment]
Ok @mbleigh I'll try your suggestions and see if I can make it work. Thanks a lot for your time :)

**Comment by Flucadetena** [comment]
For anyone having the same problem, it has been solve in the latest reales of firebase-tools: 8.14.1
