### ISSUE TITLE
Support for webp in ImageMagick

### ISSUE THREAD

**Issue by Flucadetena** [firebase/firebase-functions#805]
It would be great to have `webp` support in the version of ImageMagick installed in functions. Or at least a way to add it. As webp is the best format for quality optimized images and it is develop by Google, I think it is a must.

We are one month away from launching our app and have already thousands of images to optimize in the storage. It would be great to launch the app with `webp` as Flutter supports it too.

Thanks!! :)

**Comment by samtstern** [comment]
@Flucadetena thanks for the feedback.  This is an issue with the Cloud Functions runtime and not something we can fix in the Firebase SDK for functions.

Please use the Google Cloud trackers to request this feature!
https://cloud.google.com/support/docs/issue-trackers
