### ISSUE TITLE
FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.

### ISSUE THREAD

**Issue by DMZakaria** [firebase/firebase-functions#810]
### Related issues

https://github.com/firebase/firebase-functions/issues/147

### [REQUIRED] Version info

**node:** 14.5.0

https://github.com/firebase/firebase-functions/issues/147

**firebase-functions:** 3.11.0
**firebase-tools:** 8.15.1

**firebase-admin:** 8.10.0

### [REQUIRED] Steps to reproduce

```
import {initializeApp} from 'firebase-admin';
initializeApp(functions.config().firebase);
exports.onCreateUser= onCreateUser;
```

### [REQUIRED] Expected behavior

Cloud functions should works as expected

### [REQUIRED] Actual behavior
We had this issue suddenly, I thought it was a service outrage but it seems not , all our cloud functions are returning this warning.

![image](https://user-images.githubusercontent.com/6096779/98452991-b30ee780-2154-11eb-9264-23c0db943c12.png)

I removed all of the cloud functions and disable the cloud API but it did not work.

### Were you able to successfully deploy your functions?

Yes, the deployment works fine

**Comment by DMZakaria** [comment]
A quick update, we did a manipulation on IAM, we needed to add cloud task Cloud task enqueuer as a role, couple of min after we got this issue. 

We removed the role but the issue persists.

**Comment by erikmartinjordan** [comment]
@DMZakaria Did you finally solve the issue? I'm having the same problem.

**Comment by DMZakaria** [comment]
@erikmartinjordan No, I created a a new environment and migrate my project

**Comment by taeold** [comment]
Sorry you had to migrate to a new project to get the issue resolved.

Q: Did the values you store in `functions.config().firebase` change for any reason?

Since migrating to the project seems to have resolved your issue, and there hasn't been any changes to the `functions.config()`, I suspect that its either firebae admin sdk or some other external changes like IAM settings. Please re-open the issue if you continue to have problems.
