### ISSUE TITLE
Support onUpdate for Auth.

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-functions#811]
Auth contains a DisplayName and PhotoURL.
We will use this as our own profile data, but no other user can access it.
When other users view my profile, they will store the data in the Cloud Firestore path.

```typescript
firestore().doc(`users/${uid}`).set(data)
````

But Auth doesn't have onUpdate, so if you want to update your data in Auth and CloudFirestore, we have no choice but to do a complex implementation.
If we want to update the data in Auth and CloudFirestore, we have to do a complex implementation.

**Comment by samtstern** [comment]
@1amageek thank you for the feedback.  This is a common feature request and something we'd definitely like to have one day!  But it's not something we can fix here in the Functions SDK.  To submit feature requests to Firebase, use this link:
https://firebase.google.com/support/troubleshooter/report/features
