### ISSUE TITLE
Can't request, it shows 'Invalid request, unable to process.' and return 'Bad Request'

### ISSUE THREAD

**Issue by zyflovelam** [firebase/firebase-functions#813]
firebase-tools version: 8.15.1

I call the cloud functions from the iOS client, no matter what the parameter is, how big it is, the console shows ‘Invalid request, unable to process.’, Can anyone help?

**Comment by zyflovelam** [comment]
![image](https://user-images.githubusercontent.com/19360803/98545991-410fdd00-22d1-11eb-9ed8-303a587839ed.png)
---
![image](https://user-images.githubusercontent.com/19360803/98546077-60a70580-22d1-11eb-860c-5ee1f2040917.png)

**Comment by zyflovelam** [comment]
![image](https://user-images.githubusercontent.com/19360803/98547244-d790ce00-22d2-11eb-9b3f-fa784ea52de1.png)

**Comment by zyflovelam** [comment]
Need help~~~~

**Comment by samtstern** [comment]
@zyflovelam this repo is only for the `firebase-functions` SDK, not for the iOS SDK or for issues with actually running Cloud Functions in production.

If you need help debugging this issue I would suggest either using StackOverflow or contacting Firebase support:
https://firebase.google.com/support

**Comment by zyflovelam** [comment]
Thanks
