### ISSUE TITLE
Inconsistent Firestore Types Between Firebase and Firebase Functions

### ISSUE THREAD

**Issue by asithade** [firebase/firebase-functions#817]
### [REQUIRED] Version info

**node:** 
10

**firebase-functions:**
"firebase-functions": "^3.11.0"

**firebase-tools:**
8.16.2

**firebase-admin:**
"firebase-admin": "^9.4.1",

### [REQUIRED] Test case

We are using Yarn Workspaces which house all our applications and one of our packages contain a shared library of Types for Typescript. In that package, we have the `firebase` v8.1.1 package installed in order to use the Firebase/Firestore's type definitions throughout our applications. 

In another package, we house our Firebase Functions and it makes reference to the types in the aforementioned library. However, it seems that Firebase Function's Firestore types are not in sync with the Firebase Firestore's types since Firebase Function uses google-cloud instead of firebase. One of the errors we're seeing in type definition is:

```
Argument of type 'FirebaseFirestore.DocumentReference<FirebaseFirestore.DocumentData>' is not assignable to parameter of type 'firebase.default.firestore.DocumentReference<firebase.default.firestore.DocumentData>'.
  Types of property 'firestore' are incompatible.
    Type 'Firestore' is missing the following properties from type 'Firestore': useEmulator, enablePersistence, app, clearPersistence, and 5 more.ts(2345)
```

```
Argument of type '(course: FirebaseFirestore.DocumentReference) => Promise<void>' is not assignable to parameter of type '(value: DocumentReference<DocumentData>, index: number, array: DocumentReference<DocumentData>[]) => void'.
  Types of parameters 'course' and 'value' are incompatible.
    Type 'DocumentReference<DocumentData>' is missing the following properties from type 'DocumentReference<DocumentData>': listCollections, createts(2345)
```

### [REQUIRED] Steps to reproduce

Try to reference from an external package that uses the `firebase` library and another that uses `firebase-functions`

### [REQUIRED] Expected behavior

The two type definitions should be in sync and not be missing any of the type definitions. 

### [REQUIRED] Actual behavior

It is giving type errors because of the inconsistencies

### Were you able to successfully deploy your functions?

No

**Comment by nc** [comment]
+1

**Comment by jaytavares** [comment]
I ran into this same issue. I solved it by importing `DocumentReference` directly from @google-cloud:

```javascript
import { DocumentReference } from '@google-cloud/firestore'
```

**Comment by inlined** [comment]
Catching up on some backlog and I need a bit more context here. Do you have a minimal reproduction of this error? `DocumentReference` and `DocumentData` doesn't appear anywhere in the `firebase-functions` SDK. Did [this change](https://github.com/firebase/firebase-functions/commit/df35c1b4b18b7f2cd6c2d0d21090793b3b153e8b#diff-4e75eb2af76c75a2dd8b4b2392bab86a1b42f908681558b73950de92f4c4eb58) fix your issue?

**Comment by inlined** [comment]
Internal bug number 187950727

**Comment by nibab-boo** [comment]
This is still persisting.
