### ISSUE TITLE
Functions.logger.log() and console.log() not outputting any logs in the console and CLI

### ISSUE THREAD

**Issue by neilcelesterara** [firebase/firebase-functions#821]
I tried a very simple function just to figure out what's causing the problem. No matter how I try, my logs made using functions.logger.log() and console.log() do not appear in the console and in the cli with firebase functions:log.

I tried to revert to Node v.8 and then back to v. 10, but the logs still do not appear. I also tried moving from one location to another but to no avail.

Here's what's inside by index.js in functions:

`
const functions = require('firebase-functions');

exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.log("This is a smple log.");
  console.log("This is a smple log.");
  response.send("Hello from Firebase!");
 });
`

No log whatsoever is displayed in the console and CLI.

**Comment by Polombo98** [comment]
Same issue here

**Comment by inlined** [comment]
I cannot reproduce this on Node 10 or 12; Node 8 isn't deployable anymore. Does this reproduce on the latest version of firebase-tools and firebase-functions?

**Comment by taeold** [comment]
Marking the issue as closed. Please re-open if you continue have problems.
