### ISSUE TITLE
@firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project. 

### ISSUE THREAD

**Issue by erikmartinjordan** [firebase/firebase-functions#826]
### Related issues

https://github.com/firebase/firebase-functions/issues/147

### Version info

**node:** "8"

**firebase-functions:** "^3.13.0"

**firebase-tools:** "8.18.0"

**firebase-admin:** "^9.4.1"

### Test case

**`index.js`**:

```javascript
const functions = require('firebase-functions');
const admin = require('firebase-admin');

var app = admin.initializeApp();

exports.addEndpoint = functions.https.onRequest((request, response) => { ... });
```

Deployment of **`index.js`** to a project and triggering `addEndpoint` via  `https://us-central1-${project}.cloudfunctions.net/addEndpoint` causes the following error: 

> @firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project. 

The function ends with timeout.

### Steps to reproduce

1. `firebase use ${project}`
2. `firebase deploy --only functions`
3. Access to `https://us-central1-${project}.cloudfunctions.net/addEndpoint`

### Expected behavior

Function returning a `200` response.

### Actual behavior

> @firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project. 

### Were you able to successfully deploy your functions?

Successful deployment.

**Comment by erikmartinjordan** [comment]
Ok, I could solve it. In my case the `${number}@cloudbuild.gserviceaccount.com` was missing in Google Cloud IAM. 

Steps to solve it:

1. Go to https://console.cloud.google.com/iam-admin/iam?project=${project-id}
2. Add member `${number}@cloudbuild.gserviceaccount.com`
3. Select role `Cloud Build Service Account`
4. Deploy functions

**Comment by jamiegood** [comment]
Hi Thanks to @erikmartinjordan above. That Adding of the Editor role to ${project}@appspot.gserviceaccount.com worked for me

**Comment by danielfowler** [comment]
Did not work for me, rats! If anyone else continues having this error in their logs, I'd be grateful for any insights.
