### ISSUE TITLE
Error reading config file set in the FIREBASE_CONFIG environment variable as mentioned in the documentation

### ISSUE THREAD

**Issue by RezaRahmati** [firebase/firebase-functions#830]
### [REQUIRED] Version info

**node:**

**firebase-functions:** 3.13.0

**firebase-tools:**

**firebase-admin:**

### [REQUIRED] Test case

Setup firebase config from a file path set in FIREBASE_CONFIG env variable

### [REQUIRED] Steps to reproduce

In the documentation [here ](https://firebase.google.com/docs/admin/setup#initialize-without-parameters) mentioned 
>  If the content of the FIREBASE_CONFIG variable begins with a { it will be parsed as a JSON object. Otherwise the SDK assumes that the string is the name of a JSON file containing the options.

But actual code is always treat the value as json object regardless of string starts with `{` or not

https://github.com/firebase/firebase-functions/blob/c69c9bc083a2ef55a3ea152839d6027b4bb20352/src/setup.ts#L41

### [REQUIRED] Expected behavior

Read and parse the file in the FIREBASE_CONFIG environment variable

### [REQUIRED] Actual behavior

Parse the path as json and throw invalid character at the position 0

**Comment by rpyn** [comment]
This is also occurring in our project too. After switching to development project from production project using `firebase use --add`, environment variable does not seem to be changed. I wonder if there is a problem with authentication system down from yesterday. I signed out from Firebase CLI, and logged in again. But nothing changed.
