### ISSUE TITLE
Default firebase-functions project setup is utterly broken for typescript projects

### ISSUE THREAD

**Issue by saevarb** [firebase/firebase-functions#831]
This is just a duplicate of #782 but since that has been ignored for 3 months(as have many other issues in this repository) I figured maybe creating a new one with a title that properly states the seriousness of this issue might get someone to look at this.

I really do believe this should be considered a very serious issue, unless the team is fine with no developers being able to use functions as per the documentation unless they are capable of and willing to wrangle with yarn and tsconfig settings.

**Comment by samtstern** [comment]
I'll take a look at #782, please don't file duplicate issues.
