### ISSUE TITLE
Cannot deploy any firebase functions on any project

### ISSUE THREAD

**Issue by stijnlw** [firebase/firebase-functions#832]
### [REQUIRED] Version info

**node:** 12.20

**firebase-functions:** 3.11 and 3.13

**firebase-tools:** 9.0.0

**firebase-admin:** 9.2.0

### [REQUIRED] Test case

just create a new firebase project, add billing, and then 'firebase init' with only functions, and then deploy

### [REQUIRED] Steps to reproduce

```
# Install dependencies
apt-get update
apt-get -y install apt-transport-https ca-certificates gnupg curl sudo gcc g++ make rsync git

# Add nodejs for firebase deploy
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get update && apt-get install -y nodejs

# Install firebase tools
npm install -g firebase-tools

#npm install cloud functions
cd $PROJECT_DIR/firebase/app
firebase init
cd functions
npm install

 # Deploy
cd $PROJECT_DIR/firebase/app
firebase deploy --debug --only functions
```

### [REQUIRED] Expected behavior

functions deploy

### [REQUIRED] Actual behavior

throws an error (the extra output here is from --debug ):

```
[2020-12-16T13:08:49.705Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/projects/XXX/locations/-/functions

[2020-12-16T13:08:50.408Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Wed, 16 Dec 2020 13:08:50 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2020-12-16T13:08:50.426Z] TypeError: checkForNode8 is not a function
    at /usr/lib/node_modules/firebase-tools/lib/deploy/functions/release.js:413:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```

### Were you able to successfully deploy your functions?

worked fine yesterday, not anymore

**Comment by ArcherEmiya05** [comment]
Same here there is always some function that did not deployed properly, I tried it more than twenty (20) time already but most deployment fails. Is this related to the down of services recently of Google services and products?

![image](https://user-images.githubusercontent.com/38008900/102355298-a2b91a80-3fe6-11eb-9d59-91246c4166bc.png)
![image](https://user-images.githubusercontent.com/38008900/102355307-a5b40b00-3fe6-11eb-9504-08c28cfab98d.png)
![image](https://user-images.githubusercontent.com/38008900/102355315-a77dce80-3fe6-11eb-8312-0a9e34cac98c.png)
![image](https://user-images.githubusercontent.com/38008900/102355324-a9e02880-3fe6-11eb-98ba-dabd3b8d6b28.png)
![image](https://user-images.githubusercontent.com/38008900/102355331-aba9ec00-3fe6-11eb-8740-a57d2fdead27.png)

It is constantly failing again and again since the down of services happened which is very frustrating as the development becomes thrice harder and time consuming.

**Comment by andrewpolemeni** [comment]
Having the same problem:
[debug] [2020-12-16T16:32:47.179Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Wed, 16 Dec 2020 16:32:47 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-16T16:32:47.335Z] TypeError: checkForNode8 is not a function
    at C:\Users\Andrew\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\release.js:413:13
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[error] 

=== Deploying to 'homedepotapi'...

i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log

**Comment by SnowBases** [comment]
Having the same problem when upgrading to the latest version of firebase-tools. then I downgrade from the latest to 8.16.2 `npm i firebase-tools@8.16.2` its working but not with latest version :\

**Comment by shubhangchourasia** [comment]
> Having the same problem when upgrading to the latest version of firebase-tools. then I downgrade from the latest to 8.16.2 `npm i -g firebase-tools@8.16.2` its working but not with latest version :\


**I was able to deploy one function 3 days ago. But now it is not deploying another function.**
I was running **firebase tools --version - 9.0.1**
Then I downgraded to version **8.16.2**

Tried to deploy prewritten function which was already present as a comment, here it is.

**exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});**


After deploying, here is the error


i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (24.59 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: current functions in project: customeClaims(us-central1), helloWorld(us-central1)
i  functions: uploading functions in project: helloWorld(us-central1)
i  functions: updating Node.js 12 function helloWorld(us-central1)...
!  functions[helloWorld(us-central1)]: Deployment error.
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

Functions deploy had errors with the following functions:
        helloWorld

To try redeploying those functions, run:
    firebase deploy --only "functions:helloWorld"


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
 
I don't know what to do next. Any help please ?

**Comment by stijnlw** [comment]
@shubhangchourasia do

```
firebase deploy --debug --only "functions:helloWorld"
```

that might give you more info, and determine if it's the same issue as the rest of us

**Comment by shubhangchourasia** [comment]
> @shubhangchourasia do
> 
> ```
> firebase deploy --debug --only "functions:helloWorld"
> ```
> 
> that might give you more info, and determine if it's the same issue as the rest of us

I deleted my previous reply.
Actually I am trying to integrate razorpay payment with my nuxt app.
I wrote below two lines in my index.js file.
**const Razorpay = require('razorpay')
const crypto = require('crypto')**


When I comment these lines, the function is deploying successfully. But when I uncomment 
**const Razorpay = require('razorpay')**
it still gives me error unable to deploy. Note that dependency for razorpay is already installed in my app.
I don't know what is the problem with these lines. Also my current firebase version is -8.16.2.

Also check if you have require lines other than
**const functions = require('firebase-functions')
const admin = require('firebase-admin')**
Try to comment them and deploy again. Waiting for reply.

**Comment by stijnlw** [comment]
@shubhangchourasia seems to be an unrelated issue, but again; adding --debug should give you more info

**Comment by shubhangchourasia** [comment]
> @shubhangchourasia seems to be an unrelated issue, but again; adding --debug should give you more info

I did that too but the debug data which I got is difficult for me to understand.

**Comment by stijnlw** [comment]
@shubhangchourasia it doesn't seem related to this issue at all, maybe ask for help on stackoverflow or superuser or something

**Comment by shubhangchourasia** [comment]
> @shubhangchourasia it doesn't seem related to this issue at all, maybe ask for help on stackoverflow or superuser or something

I asked the question on Stackoverflow. Also by that time try running this code 
npm install
Sometimes the code works by doing that. I just check all the files of node and install if any file is missing.

**Comment by ArcherEmiya05** [comment]
Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?

**Comment by shubhangchourasia** [comment]
> Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?

const functions = require('firebase-functions')
const admin = require('firebase-admin')
These are the two important lines we write in our functions. 
Is there any other dependency you are using in the firebase functions or just these two ?

**Comment by ArcherEmiya05** [comment]
> 
> 
> > Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?
> 
> const functions = require('firebase-functions')
> const admin = require('firebase-admin')
> These are the two important lines we write in our functions.
> Is there any other dependency you are using in the firebase functions or just these two ?

There is no problem with my index.js and yes there are some third library included but that is not the problem and supposed to be not a problem. The issue is the deployment gets terminated and failed but out of 20 trial most likely only 2 get success the rest always failed.

**Comment by oldirty91** [comment]
Had same issue since updating to latest version of firebase tools. 

Are you all checking your logs to confirm that the function did not deploy? I had same error in my terminal however functions always seem to deploy.

**Comment by ArcherEmiya05** [comment]
So far if someone is having same issue like this a temporary alternative is to deploy your updates manually with Google Cloud Console

https://console.cloud.google.com/functions/list?authuser=0&project=YOUR_PROJECT_ID

**Comment by shubhangchourasia** [comment]
> So far if someone is having same issue like this a temporary alternative is to deploy your updates manually with Google Cloud Console
> 
> https://console.cloud.google.com/functions/list?authuser=0&project=YOUR_PROJECT_ID

Agreed, this is the easiest alternative. But take a scenario when there is a small mistake in the function code itself. Even after deploying through cloud console if there is a mistake, the function will through errors or we can get unexpected results.

**Comment by shubhangchourasia** [comment]
> > > Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?
> > 
> > 
> > const functions = require('firebase-functions')
> > const admin = require('firebase-admin')
> > These are the two important lines we write in our functions.
> > Is there any other dependency you are using in the firebase functions or just these two ?
> 
> There is no problem with my index.js and yes there are some third library included but that is not the problem and supposed to be not a problem. The issue is the deployment gets terminated and failed, out of 20 trial most likely only 2 got it success the rest always failed. Some function get updated but others failed.

That's an issue. If one gets updated and other not. 
In my case I was using razorpay dependency. I did 

**npm i razorpay**

 at root directory. But while deploying it was unable to find razorpay.  But it was there in my package.json file. 
Then I changed my directory to /functions and again did npm i razorpay. This time it appeared in the package.json present inside the functions folder. And I was able to deploy the function.

**Comment by ArcherEmiya05** [comment]
> 
> 
> > > > Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?
> > > 
> > > 
> > > const functions = require('firebase-functions')
> > > const admin = require('firebase-admin')
> > > These are the two important lines we write in our functions.
> > > Is there any other dependency you are using in the firebase functions or just these two ?
> > 
> > 
> > There is no problem with my index.js and yes there are some third library included but that is not the problem and supposed to be not a problem. The issue is the deployment gets terminated and failed, out of 20 trial most likely only 2 got it success the rest always failed. Some function get updated but others failed.
> 
> That's an issue. If one gets updated and other not.
> In my case I was using razorpay dependency. I did
> 
> **npm i razorpay**
> 
> at root directory. But while deploying it was unable to find razorpay. But it was there in my package.json file.
> Then I changed my directory to /functions and again did npm i razorpay. This time it appeared in the package.json present inside the functions folder. And I was able to deploy the function.

I don't think so, as I said 2 out of 20 deployment only succeed and the rest was failed meaning its the server that is rejecting my updates as you can see as well from my above comment with tons of screenshots. This happens randomly also which implies that there is a server timeout at least on my project, if there is wrong with the third party library then there should be zero (0) success deployment in the first place. Everything works fine I just need to update again my functions but it seems I can only manage to deploy about 5 times a day then the rest are rejected. I already submit an issue directly with the Firebase Team here: https://firebase.google.com/support

**Comment by shubhangchourasia** [comment]
> > > > > Is the Firebase team here active or should we move and report this to Google Issue Tracker instead?
> > > > 
> > > > 
> > > > const functions = require('firebase-functions')
> > > > const admin = require('firebase-admin')
> > > > These are the two important lines we write in our functions.
> > > > Is there any other dependency you are using in the firebase functions or just these two ?
> > > 
> > > 
> > > There is no problem with my index.js and yes there are some third library included but that is not the problem and supposed to be not a problem. The issue is the deployment gets terminated and failed, out of 20 trial most likely only 2 got it success the rest always failed. Some function get updated but others failed.
> > 
> > 
> > That's an issue. If one gets updated and other not.
> > In my case I was using razorpay dependency. I did
> > **npm i razorpay**
> > at root directory. But while deploying it was unable to find razorpay. But it was there in my package.json file.
> > Then I changed my directory to /functions and again did npm i razorpay. This time it appeared in the package.json present inside the functions folder. And I was able to deploy the function.
> 
> I don't your case is completely different since you are having problem with third party package while I do not, as I said 2 out of 20 deployment only succeed and the rest was failed it's the server that is rejecting my updates as you can see as well from my above comment with tons of screenshots its says `Server Error. read ECONNRESET` . This happens randomly also which implies that there is a server timeout at least on my project, if there is wrong with the third party library then there should be zero (0) success deployment in the first place. Everything works fine with the two (2) success deployment mentioned and third party package works as well, I just need to update again my functions because the logic flow is incorrect but it seems I can only manage to deploy about 5 times a day then the rest are rejected. I already submit an issue directly with the Firebase Team where you can specify your project and what service is having an issue here: https://firebase.google.com/support

Possible, I guess there are limitation on deploying  number of times in a day. But 5 is too low. This is really an issue. I was able to deploy almost 25 times yesterday. I hope the firebase  support will solve your problem.

**Comment by taeold** [comment]
@ArcherEmiya05 @shubhangchourasia Sorry that no one has responded in this thread.

Did reaching out to support resolve your issue? If not, please feel free to re-open this issue and let us know about the latest problem you are seeing. Alternatively, feel free to open up a new issue describing your problem.

**Comment by jirawatee** [comment]
> Same here there is always some function that did not deployed properly, I tried it more than twenty (20) time already but most deployment fails. Is this related to the down of services recently of Google services and products?
> 
> ![image](https://user-images.githubusercontent.com/38008900/102355298-a2b91a80-3fe6-11eb-9d59-91246c4166bc.png)
> ![image](https://user-images.githubusercontent.com/38008900/102355307-a5b40b00-3fe6-11eb-9504-08c28cfab98d.png)
> ![image](https://user-images.githubusercontent.com/38008900/102355315-a77dce80-3fe6-11eb-8312-0a9e34cac98c.png)
> ![image](https://user-images.githubusercontent.com/38008900/102355324-a9e02880-3fe6-11eb-98ba-dabd3b8d6b28.png)
> ![image](https://user-images.githubusercontent.com/38008900/102355331-aba9ec00-3fe6-11eb-8740-a57d2fdead27.png)
> ![image](https://user-images.githubusercontent.com/38008900/102355644-1eb36280-3fe7-11eb-9ca4-1bc03e977e22.png)
> 
> It is constantly failing again and again since the down of services happened which is very frustrating as the development becomes thrice harder and time consuming.

Let you try to remove package-lock.json then deploy again.
