### ISSUE TITLE
Docs for failurePolicy are unclear

### ISSUE THREAD

**Issue by goleary** [firebase/firebase-functions#836]
We tried to enable retries on a few of our functions using this.

```
export default functions
  .runWith({ failurePolicy: true })
  .firestore.document(...)
  ...
```

First off, the docs say:

>Failure policy of the function, with boolean true being equivalent to providing an empty retry object.

It took me quite a bit of digging to figure out what "providing an empty retry object" meant.

I eventually found [this](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1#failurepolicy) which specifies: 

>`rety` - If specified, then the function will be retried in case of a failure.

It would be great to add some info in the Firebase docs that describes what is going on here and explains the config.  I've not worked with GCP cloud functions before, and even the docs over there are somewhat vague (not to mention setting `rety: {}` for retries is a bit of headscratcher to begin with).

Additionally, only after looking the GCP console did we see that this `  .runWith({ failurePolicy: true })` was not actually doing anything, despite nothing seeming to be amiss with our deployment.

Only after reading through several issues spread across two repos (this one & `firebase-tools`) did I figure out that even though the syntax was supported in the version of the `firebase-functions` package we were using, the deployment was _not_ supported in the version of `firebase-tools` that we were using.

Only after upgrading we able to get a deploy working and even so, only after it failed due to a `failurePolicy` update followed by running the deployment with `--force`.

All of this information would be awesome to include [here](https://firebase.google.com/docs/reference/functions/function_configuration_.failurepolicy).

Or some info on how to use this new config [here](https://firebase.google.com/docs/functions/retries).

### [REQUIRED] Version info

**node:** 12.19.1

**firebase-functions:** 3.13.0

**firebase-tools:** 9.1.0

**firebase-admin:**

### [REQUIRED] Test case
N/A

### [REQUIRED] Steps to reproduce
N/A

### [REQUIRED] Expected behavior
N/A

### [REQUIRED] Actual behavior
N/A

### Were you able to successfully deploy your functions?
N/A

**Comment by inlined** [comment]
There are two fundamental problems here, as I read it:

1. The docs were not clear
2. You were using a version of `firebase-tools` that was extremely outdated

I've filed an internal bug to improve our documentation. You should have been able to learn about `failurePolicy` using the docs on retries, not diving into arcane functions options docs.

RE using an old version of `fireabse-tools`, we have some vague ideas to detect this in the future, but I'm going to consider it working as intended that an old version of software gracefully handled code that it knew about and didn't throw on features it didn't know about. This is how SemVer is supposed to work.

**Comment by goleary** [comment]
Thanks for your response @inlined!

Awesome that you filed an internal bug. Is it the teams policy that gh issues are closed once they are tracked internally? I would've thought this issue would remain open until the docs are actually updated.  Am I able to track the "internal bug" in some way?

Yeah, it's nice that it didn't error, although some kind of warning that mentions that I'm providing options that are being ignored would be a really nice touch for developers 😁

**Comment by inlined** [comment]
I admit I'm being aggressive with closing bugs because I just re-joined the team and am trying to plow through our backlog. The docs improvement has already been committed in our codebase and is just waiting rollout. Watch https://firebase.google.com/docs/functions/retries for better docs on what you've already figured out on your own. I closed the bug because it seems that you are already aware of how to move forward.

**Comment by dreadjr** [comment]
@inlined Any update on more information in the documentation? It is still unclear here https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1#google.cloud.functions.v1.FailurePolicy.Retry, the Retry schema doesn't have fields just a description.

**Comment by inlined** [comment]
That's because "retry" is just an empty object with no fields. This is because we originally tried to define the API to be forwards compatible with more complex failure or retry policies. So In the wire protocol JSON it's literally `failurePolicy: { retry: {} }`, but you can just specify `failurePolicy: true` in the `firebase-functions` SDK.

**Comment by dreadjr** [comment]
> That's because "retry" is just an empty object with no fields. This is because we originally tried to define the API to be forwards compatible with more complex failure or retry policies. So In the wire protocol JSON it's literally `failurePolicy: { retry: {} }`, but you can just specify `failurePolicy: true` in the `firebase-functions` SDK.

Thanks. Yeah it is very confusing, I am using a function to fire on a message published to a topic. Which you can set retry backoff, etc on the subscription and setup dead lettering but the function just retries after 10-20 seconds up to the max number of retries on the subscription.
