### ISSUE TITLE
Function can't acces data in Firestore

### ISSUE THREAD

**Issue by jennerstrom** [firebase/firebase-functions#839]
### Version info

**node: v15.4.0**

**firebase:  9.0.1**

Relevant code:

### index.js

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();
exports.authOrgKey = functions.https.onCall((data, context) => {
    db = admin.firestore();
    functions.logger.log('data passed to function: ', data);
    return db.collection("Orgkeys")
        .get()
        .then(snapshot => {
            snapshot.forEach(doc => {
                functions.logger.log('OrgKey Checked: ', doc.orgKey);
                if (doc.orgKey == data) {return doc.userType}
            });
        return false;
    });
});
```

functions.logger shows that the function is receiving the input from the client.

### Expected behavior
The function returns a string if the orgKey exists in the database and false if not.

### Actual behavior
Function returns Null no matter what is passed to it.

### Were you able to successfully deploy your functions?

Yes.

**Comment by inlined** [comment]
`Array.forEach` doesn't return anything, so your "then" isn't returning anything. Your code sample is much easier to write with async. Also, note that I use a query here to avoid loading the entire collection in the function.

```js
exports.authOrgKey = functions.https.onCall(async (data, context) => {
  const db = admin.firestore();
  functions.logger.log('data passed to function: ', data);
  const doc = await db.collection('OrgKeys').where('orgKey', '==', data).get();
  if (!doc.exists) {
    return null;
  }
  return doc.data().userType;
});
```
