### ISSUE TITLE
firebase function always timeout when providing an argument via http.

### ISSUE THREAD

**Issue by rjpruitt16** [firebase/firebase-functions#847]
### [REQUIRED] Version info

**node:**

v14.15.4

**firebase-functions:**
^3.3.0
**firebase-tools:**
9.2.0 I am not sure about this. not sure how to see version.

9.2.0

**firebase-admin:**
9.4.2

### [REQUIRED] Test case

```
exports.newFunction = functions.https.onRequest(async (req, res) => {
    const { userId, classroomId, eventId } = req.query;
    console.log(`param:\nuserId: ${userId},\n classroomId: ${classroomId},\n eventId: ${eventId}`);
    return res.end();
});
```

### [REQUIRED] Steps to reproduce

Whenever you try to pass arguments through http, it will cause the function to execute until timeout. if you go to said url and put no arguments, it will work. If you add arguments for example ..../newFunction?classroomId=something&eventId=else, it will send back a 400 response and the function execute until timeout.

### [REQUIRED] Expected behavior

The expected behavior is the function logs the output as specifying such that the code correctly passes arguments through http.

### [REQUIRED] Actual behavior

It will cause a timeout error.

Error: Function timed out.
>      at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:640:19)
>      at listOnTimeout (internal/timers.js:554:17)
>      at processTimers (internal/timers.js:497:7)

### Were you able to successfully deploy your functions?

I was able to deploy function, but the same problem is occurring in emulator

**Comment by samtstern** [comment]
This was an emulator issue and is fixed here:
https://github.com/firebase/firebase-tools/issues/3032
