### ISSUE TITLE
KeepAlive Timeout? 

### ISSUE THREAD

**Issue by westside** [firebase/firebase-functions#856]
I just want to setup keep alive timeout.
From this doc(https://firebase.google.com/docs/functions/networking), I can only set keepAlive option.
Default value might be 5 seconds? from the doc? 
https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_settimeout_msecs_callback

**Comment by samtstern** [comment]
@westside can you explain more what you are trying to achieve?  There is no way to keep a function instance alive, that doc is about sharing network connections between invocations.
