### ISSUE TITLE
admin.auth().deleteUsers() does not Trigger auth.user().onDelete cloud function

### ISSUE THREAD

**Issue by waghD** [firebase/firebase-functions#860]
### Related issues

There has been a related issue with user deletion not triggering the onDelete hook in general here: [authentication trigger issue](https://groups.google.com/g/firebase-talk/c/ROXTbooVzlM/m/vY1kh9TqAQAJ).
This has been resolved for individual deletion of users, however when batch deleting with `admin.auth().deleteUsers()` the issue still occurs. 

#710 might also be related but was closed due to insufficient information

### [REQUIRED] Version info

**node:** v14.15.4
cloud functions: node 10 
node v14.15.4 in local development

I have updated to the latest version of all dependencies and still got the issue

**firebase-functions:** 3.13.1
also tried with 3.6.1

**firebase-tools:** 9.3.0
also tried with 8.4.0

**firebase-admin:** 9.4.2
also tried with 8.12.1

### [REQUIRED] Test case

```
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

export const cleanUserData = functions.region("europe-west1").auth.user().onDelete((user, context) => {
  // not called
  console.log(`deleting user: ${user.uid}`);
})

export const deleteTest = functions.region("europe-west1").https.onRequest(async (req, res) => {
  const {deleteIds} = req.body;

  await admin.auth().deleteUsers(deleteIds);

  res.sendStatus(200);
})
```

### [REQUIRED] Steps to reproduce

 - Create a cloud function with a auth onDelete trigger
 - Batch delete users with `admin.auth().deleteUsers()`

### [REQUIRED] Expected behavior

cloud function with `auth().onDelete` trigger is called for every deleted user when batch deleting users. Should be same behavior as it is when deleting every user individually with multiple calls to `admin.auth().deleteUser()`

### [REQUIRED] Actual behavior

onDelete cloud function trigger is not executed for any user when deleting multiple users in batch with `admin.auth().deleteUsers()`

### Were you able to successfully deploy your functions?

Functions deploy without any errors

**Comment by taeold** [comment]
I found an internal discussion where I discovered that batch operations like auth().deleteUsers() don't trigger async functions by design. I find this unfortunate, but it won't be something we can fix in this repo.

I'll post an update here if I discover anything else. For now, marking the issue as closed.

**Comment by taeold** [comment]
We'll soon update Firebase documentations to make sure others folks know about this limitation. Thank you all for highlighting the issue.
