### ISSUE TITLE
firebase function SSL pinning issue

### ISSUE THREAD

**Issue by yogskumar** [firebase/firebase-functions#881]
### Related issues

Hi i am trying to implement ssl pinning for my ios app. Where do I get my certificate for my firebase cloud functions endpoints? I want SSL pinning to prevent man in the middle attack. Thank you for the help.

### [REQUIRED] Version info
7.9.0

**node:**

**firebase-functions:** Yes

**firebase-tools:**

7.9.0

### [REQUIRED] Expected behavior

Integrate SSL pinning with Firebase function

### [REQUIRED] Actual behavior

how to implement this with firebase function with Hybrid platform(ionic, cordova etc.)

**Comment by taeold** [comment]
Frankly, I'm not sure what SSL pinning would look like in Firebase Functions. It sounds like it something that should be done on the client side,and isn't something that would be in the domain of Functions SDK.

Firebase Functions is backed by Cloud Functions. I found a similar question on [stackoverflow](https://stackoverflow.com/questions/64565711/firebase-cloud-functions-ssl-certificate-for-ssl-pinning) that might help you with your issue.

Just in case you aren't aware, most SSL certificate expire after sometime, and I suspect Cloud Function is no exception. You will have to periodically download and include the SSL certificate in your clients which sounds a bit painful and can break your old clients. I've found that Android specifically [recommends against certificate pinning](https://developer.android.com/training/articles/security-ssl#Pinning) for this reason.

If you must do this, then I'd point you to setup a Cloud Endpoint with your own SSL certificate (https://cloud.google.com/endpoints/docs/openapi/enabling-ssl).  You might also want to give a look at Firebase Hosting and contact Firebase Support to setup your dedicated SSL certificate (https://stackoverflow.com/questions/53473695/google-firebase-ssl-certificate-my-certificate-has-a-large-number-of-other-web).
