### ISSUE TITLE
Deploy error when using dependency from git

### ISSUE THREAD

**Issue by rfmejia** [firebase/firebase-functions#89]
### Version info

**firebase-functions:** 0.5.9
**firebase-admin:** 4.2.1

My functions are using an NPM dependency hosted on Github and `npm install` works in the local environment. However, running `firebase deploy --only functions` gives the following error:

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (32.34 KB) for uploading
✔  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: updating function test-function.
⚠  functions[test-function]: Deploy Error: Function load error: Code in file target/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'npm-dependency-from-git'
```

I can't find documentation that this feature is not supported, is this correct?

**Comment by justinrosenthal** [comment]
Hi, is `npm-dependency-from-git` listed in the `dependencies` section of your `package.json`?

See here: https://firebase.google.com/docs/functions/handle-dependencies
Specifically have a look at the `--save` flag for `npm install`.

**Comment by rfmejia** [comment]
Yes, it is listed in the dependencies section, for example `"npm-dependency-from-git": "github:username/npm-dependency-from-git"`. I use the command `npm install --save "username/npm-dependency-from-git"` to install from the command line.

One more thing, I am currently using the Spark plan tier on the project.

**Comment by justinrosenthal** [comment]
Ok, you should be able to install a dependency directly from Github as long as it's in a public repo.  For instance:
```json
  "dependencies": {
    "firebase-admin": "~4.2.1",
    "firebase-functions": "^0.5.7",
    "uuid": "git+https://git@github.com/kelektiv/node-uuid.git"
  }
```
If this is what you're doing, can you tell me what the dependency is so I can try to reproduce?

**Comment by rfmejia** [comment]
Here is a snippet of my package dependencies. The error occurs in `ts-serialize`.
```
  "dependencies": {
    "firebase-admin": "^4.1.2",
    "firebase-functions": "^0.5.9",
    "scalts": "1.0.1",
    "scalts-array": "0.4.0",
    "ts-json-definition": "0.0.2",
    "ts-serialize": "git+https://git@github.com/rfmejia/ts-serialize.git"
  },
```

**Comment by inlined** [comment]
In trying to debug your issue I ended up trigging the same error earlier on my local install. It seems the error message is an odd/poorly formed error message from the node runtime. The ts-serialize codebase doesn't check in its JS code nor does it have a postinstall script to compile the code to JS. Node is finding the package.json but it can't find the index.js listed in there.

While you're working on a fork, I recommend either checking in the javascript code or adding a postinstall script that runs "npm run build".
