### ISSUE TITLE
Firebase Environment Config removes characters from values

### ISSUE THREAD

**Issue by Spencer-Easton** [firebase/firebase-functions#898]
I had an API key "s&#h$318s*#hkfgG" when set an environment config with functions:config:set the value was converted to "s&#hs*#hkfgG". The "$318" was removed from the value.  Was fun discovering this :)

EDIT: I realized my firebase tools were running at 9.4.0 so I updated to 9.11.0 and string got truncated to "s&#h18s*#hkfgG"
the "$3" was removed.

NOTE: This API key is changed :)

**Comment by inlined** [comment]
The $ character may be having conflicts with environment variables. Can you verify that your variables are printing correctly when you run `firebase functions:config:get`? If not, make sure you use single quote marks (`'`) when setting the param in your terminal to turn off string interpolation.

If that doesn't reveal a problem we can dive deeper to see where we're accidentally performing string substitution.

**Comment by taeold** [comment]
I tried replicating the issue without success:

```
$ firebase functions:config:get 
{
  "foo": {
    "bar": "s&#h$318s*#hkfgG"
  },
  "someservice": {
    "key": "THE API KEY"
  }
}

// index.js
functions.logger.info(functions.config().foo.bar);
```

Deployed and executed the function, and here's what I get on the logs:

```
2021-05-24 14:53:31.162 PDT helloWorld mgr3eiwb91hq s&#h$318s*#hkfgG
```

@Spencer-Easton Can you help us clarify what's going wrong?
