### ISSUE TITLE
Callable function returns {status: success} and printing Callable request verification passed

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-functions#903]
### [REQUIRED] Version info

**node:** v12.13.0

**firebase-functions:** 3.14.1

**firebase-tools:** 9.12.1

**firebase-admin:** 9.9.0

### [REQUIRED] Steps to reproduce

I have the following function:

```typescript
import * as functions from 'firebase-functions'

export const fetchDashboardDataFunction = functions.https.onCall(
  (data, context) => {
    console.log('start')
    return { somekey: 'somedata' }
  }
)
```

The usage is as simple as:

```dart
    /// This is Dart/Flutter
    final result = await functions
        .httpsCallable('fetchDashboardData')
        .call<Map<String, dynamic>>({'version': '1'});
    debugPrint(result.data.toString());
```

The result returned is `{status: success}` instead of the expected `{ somekey: 'somedata' }`. The Cloud functions console prints the following:

<img width="619" alt="Callable request verification passed Firebase Cloud Function" src="https://user-images.githubusercontent.com/2883524/122183000-7c8c0e80-ce93-11eb-9b9c-4319549dbe83.png">

Note there's no `start` word printed out.

**Comment by taeold** [comment]
Hey @agordeev - thanks for submitting the issue.

I tried to reproduce to behavior but couldn't. Here's what I have:

```js
// lib/index.js (compiled from src/index.ts)
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fetchDashboardDataFunction = void 0;

const functions = require("firebase-functions");
exports.fetchDashboardDataFunction = functions.https.onCall((data, context) => {
    console.log("start");
    return { somekey: "somedata" };
});
//# sourceMappingURL=index.js.map
```
```json
// package.json
{
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts . --fix",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.22.0",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^3.8.0"
  },
  "private": true
}
```

After deploying the function, I've used `curl` command to call my function:

```
$ curl -X POST  https://us-central1-{MY_PROJECT}.cloudfunctions.net/fetchDashboardDataFunction \
  -H 'Content-type: application/json' \
  --data '{"data": { "version": "1"}}'

{"result":{"somekey":"somedata"}}%
```

<img width="879" alt="Screen Shot 2021-06-17 at 6 51 11 AM" src="https://user-images.githubusercontent.com/14897098/122299028-6dab6780-cf38-11eb-92ae-ee06899b3028.png">

I haven't tried using Flutter to make a call to my Callable function. Is it possible that's where the trouble lies?

Can you try making a `curl` request as I've done and let us know what happens? Would also help if you can share the Node.js runtime + share how the function is being deployed (are you running `tsc` before deploy?)

**Comment by agordeev** [comment]
@taeold thanks for your help. Indeed, there was an issue with `tsc`, it didn't compile for some reason.
