### ISSUE TITLE
functions.auth.user().onCreate() toJSON is not a function

### ISSUE THREAD

**Issue by richarddavenport** [firebase/firebase-functions#91]
### Version info

**firebase-functions:** 0.5.9

**firebase-tools:** none

**firebase-admin:** 4.2.1

### Test case

Here is my function: 
```
const functions = require('firebase-functions');

exports.userCreated = functions.auth.user().onCreate(event => {
  const uid = event.data.uid;
  const profile = event.data.toJSON();
  const userCreated = {
    [`users/${uid}/profile`]: profile,
    [`roles/user/${uid}`]: true
  }
  functions.database().ref().update(userCreated);
});

```

When the function is executed I see this in my firebase console:
```
TypeError: event.data.toJSON is not a function
    at exports.userCreated.functions.auth.user.onCreate.event (/user_code/auth/index.js:5:30)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```
I'm reading this documentation: [https://firebase.google.com/docs/reference/functions/functions.auth.UserRecord](https://firebase.google.com/docs/reference/functions/functions.auth.UserRecord)

And I can also look at the source code and see this in the firebase admin library:
```

  interface UserRecord {
    uid: string;
    email: string;
    emailVerified: boolean;
    displayName: string;
    photoURL: string;
    disabled: boolean;
    metadata: admin.auth.UserMetadata;
    providerData: admin.auth.UserInfo[];

    toJSON(): Object;
  }

```

### Steps to reproduce

Authenticate as a new user.

### Were you able to successfully deploy your functions?

Yes.

**Comment by laurenzlong** [comment]
Thanks for filing, you're right, this is something that we have not yet supported (and mis-documented). event.data has all of the other fields of UserRecord, but does not implement the toJSON function. I'll take this as a feature request for that function to be implemented.

**Comment by richarddavenport** [comment]
Thank you!

**Comment by turk-jk** [comment]
has toJSON function implemented yet ?
