### ISSUE TITLE
@firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"Error fetching access token: 404 page not found\n\"."}

### ISSUE THREAD

**Issue by Shaunmax** [firebase/firebase-functions#910]
I am seeing this WARNING message in my logs for couple of scheduled could functions? 
Can someone tell me whats going on? I didn't make any change in my project recently and everything was working fine till last week. I can also confirm that the scheduled could function didn't executed & threw a message : 
`Function execution took 60005 ms, finished with status: 'timeout' `

**Comment by Shaunmax** [comment]
just sharing a screenshot of the same from todays firebase clould function logs

<img width="1297" alt="firebase" src="https://user-images.githubusercontent.com/16576562/124713904-beeabd80-df1e-11eb-89a0-47250bb4c576.png">

**Comment by inlined** [comment]
It sounds like you are using a very old version of the Admin SDK, which queried for a pre-v1 version of the Google Metadata Service to fetch credentials. The v1 version of the SDK is more secure, so the v1beta1 version had a deprecation announcement and has finally been shut down. Updating your dependencies and redeploying will fix your issue.

**Comment by Shaunmax** [comment]
I am sharing package.json 

```
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "10"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^3.7.0"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
```
Could you please tell me what needs to done ?

**Comment by inlined** [comment]
After checking the [release notes](https://firebase.google.com/support/releases) for any breaking changes that might affect you, update your SDKs with:

```
npm install --save firebase-functions@latest firebase-admin@latest
```

You're also running on Node 10, which is nearing its end of life support. You can upgrade to use Node 14 by changing `"engines": {"node": 10}}` to `"engines": {"node": 14}` in your `package.json`

**Comment by Shaunmax** [comment]
Hello,

When running with node 14 I am unable to depoly the functions with following error :- 

`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"Build failed: npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.\nnpm ERR! \nnpm ERR! \nnpm ERR! Invalid: lock file's firebase-admin@9.8.0 does not satisfy firebase-admin@~7.0.0\nnpm ERR! Missing: tslint@^5.12.0\nnpm ERR! \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /www-data-home/.npm/_logs/2021-07-16T06_07_42_629Z-debug.log; Error ID: beaf8772"},"authenticationInfo":{"principalEmail":"myProject@company.com"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/projectName/locations/us-central1/functions/functionName"} `

after running `npm install` i got the following : 

```
up to date, audited 225 packages in 943ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I am still facing issues with my could functions, please help urgent

**Comment by inlined** [comment]
It's not clear how your `pacakge-json.lock` is out of sync with your `package.json`. Verify that your `package.json` has recent versions of `firebase-functions` and `firebase-admin`. Next you can try deleting your `package-lock.json` and `node_modules` folder and then re-running `npm install` in your `functions` folder.

FWIW, this is the type of issue that you might get help with faster at [firebase.google.com/support](https://firebase.google.com/support)

**Comment by Shaunmax** [comment]
Hello Thomas,

Thanks for the reply.

Seems like I figured out the issue. I ran npm install --save
***@***.*** ***@***.*** inside the project folder.
When I ran it inside the functions folder, the sync issue disappeared & I
was able to update node to version 14.

But again there was an error, which I was able to solve by adding
skipLibCheck": true, in tsconfig.json.

Hope the issues are fixed now & have successfully deployed the functions.

Appreciate your help.

Thanks & Regards
