### ISSUE TITLE
Equality of `HttpsError`: AssertionError: expected promise to be rejected with 'Error: uid-is-missing' but it was rejected with 'Error: uid-is-missing'

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/firebase-functions#920]
### [REQUIRED] Version info

**node:** v14.15.4

**firebase-functions:** 3.14.1

**firebase-tools:** - 

**firebase-admin:** 9.9.0

### [REQUIRED] Test case

`function.ts`
```ts
import * as functions from "firebase-functions";
import { HttpsError } from "firebase-functions/lib/providers/https";
import { region } from "../../../firebase_globals";

export function myFunction() {
    return functions.region(region).https.onCall(async (data, context) => {
        throw new HttpsError('unauthenticated', 'uid-is-missing');
    });
}
```

`function_test.ts`
```ts
import { expect, use } from "chai";
import * as chai from "chai-as-promised";
import { HttpsError } from "firebase-functions/lib/providers/https";
import { describe, it } from "mocha";
import { myFunction } from '../../../../src/application/myFunction';
import { testEnvironment } from "../../../test_environment";
use(chai);

describe.only("MyFunction", () => {
    describe("parameters", () => {
        describe("unauthenticated", () => {
            it("throws an error, if user is not authenticated", async () => {
                const onCall = testEnvironment.wrap(sendPreLobbyInvitation());
                await expect(onCall({})).to.be.rejectedWith(new HttpsError('unauthenticated', 'uid-is-missing'));
            });
        });
    })
});
```

### [REQUIRED] Steps to reproduce
1. Create Project
2. Copy `functions_test.ts`
3. Copy `functions.ts`
4. Try to run tests with `mocha --timeout 20000 --require ts-node/register --recursive \"test_e2e/**/*_test.ts\" --reporter spec -u tdd`

### [REQUIRED] Expected behavior
The test should pass, because the two `HttpsErrors` are the same.

### [REQUIRED] Actual behavior

```
AssertionError: expected promise to be rejected with 'Error: uid-is-missing' but it was rejected with 'Error: uid-is-missing'
      + expected - actual
```

The problem is the equality of `HttpsError`. If I store the `HttpsError` as a global variable, I can reuse it my tests. But this is only a workaround. Is there a way to achieve equality for `HttpsError` or to test `HttpsError` better?

### Were you able to successfully deploy your functions?
-

**Comment by taeold** [comment]
@nilsreichardt I don't think there are specific helper functions in Firebase Functions SDK that might help in your case.

I saw similar issue and suggested workaround on https://github.com/chaijs/chai/issues/1065. Can you give those a try and let us know if it helps with your case?

**Comment by nilsreichardt** [comment]
No, I couldn't get a workaround to work. Either the test always failed or the test always passed (even with wrong data).

**Comment by taeold** [comment]
(I'm going to close the issue, as I don't think this issue is related to code written in this repository. Feel free to re-open if you disagree)

Few more things I notice on second pass:

1. Is `onCall()` function returning a promise? If so, try including `eventually.be.` cluase (check out Chai doc for more examples):

```js
const onCall = testEnvironment.wrap(sendPreLobbyInvitation());
await expect(onCall({})).to.be.eventually.be.rejectedWith(...);
```

2. Instead of instantiating a new `HttpError` when comparing, give this a try:

```js
...rejectedWith(HttpError, "'uid-is-missing'");
```

**Comment by nilsreichardt** [comment]
This seems to work 🎉
```js
...rejectedWith(HttpsError, new RegExp("^uid-is-missing$"));
```
