### ISSUE TITLE
Calls to firebase functions mapped to hosting are cached even when response has Cache-Control:no-cache header

### ISSUE THREAD

**Issue by sluramod** [firebase/firebase-functions#932]
### [REQUIRED] Version info

**node:**

12

**firebase-functions:**

3.14.1

**firebase-tools:**

9.10.0

**firebase-admin:**

### [REQUIRED] Test case

map a functions.https.onRequest firebase function to hosting in fireabse.json, set Cache-Control: no-cache on response headers. Set headers in firebase.json to Cache-Control:no-cache as well:

"headers": {
"source": "/hosting-path",
"headers": [
            {
              "key": "Cache-Control",
              "value": "no-cache"
            }]
}

### [REQUIRED] Steps to reproduce

invoke the function by making a GET request to hosting.

### [REQUIRED] Expected behavior

Calls to function are not cached by CDN and instead always routed to the function.

### [REQUIRED] Actual behavior

Firebase function is not invoked, response is served from the Google Frontend cache instead. See response headers:

accept-ranges: bytes
**cache-control: no-cache**
content-encoding: gzip
content-length: 70
content-type: text/html; charset=utf-8
date: Thu, 05 Aug 2021 06:56:23 GMT
etag: W/"35-u/9t+Ukk2PGrnbNGztLDou/5EGM"
function-execution-id: 3lwimtgxpyc3
server: Google Frontend
vary: cookie,need-authorization, x-fh-requested-host, accept-encoding
**x-cache: HIT**
x-cache-hits: 2
x-cloud-trace-context: 1eddc3c3c1875c1383cb3d18d5f58e34;o=1
x-country-code: US
x-orig-accept-language: en-us
x-powered-by: Express
x-served-by: cache-pao17446-PAO

### Were you able to successfully deploy your functions?

yes

**Comment by inlined** [comment]
For better or worse, Hosting and Functions are disjoint products. When hosting defers to a function, it's using the "rewrite" feature to serve your response from another backend, Google Cloud Functions. That backend has its own caching layer, the Google Front-End. If you set cache control within Hosting, then the Hosting CDN will not cache the response but the GFE might. You can fix the behavior by calling `res.header('Cache-Control', 'no-cache')` in your express app as well.

Now, I'll fully admit that while the current behavior makes sense from an architectural point of view that it's disappointing. I'm going to internally propose ways where we could have smoothed out the rough edges.

**Comment by inlined** [comment]
I did some further digging. It seems Express.js sets `cache-control: private` by default, which is telling the GFE to cache the response. It seems this is working as intended and we will not be able to change anything for now.

**Comment by sluramod** [comment]
I don’t get it. I set cache-control:  no-cache in the function, and it’s still cached. How is it working as intended?

**Comment by inlined** [comment]
Architecturally, you have the Firebase Hosting CDN (Fastly), Firebase Hosting Origin Server, Google Front End, and Google Cloud Functions. Requests come in that order and leave in the opposite. If you serve a request that has a no-cache header at Hosting's origin server and a cache header at GCF then the GFE Will cache it and Fastly will not.

It seems possible, however, that you didn't intend to write a caching response in GCF. I created a repro which gets cached responses from Hosting's URL and uncached responses from GCF's URL. I'll forward this onto the right teams.

**Comment by inlined** [comment]
New changes will be rolling out soon to special-case `no-cache`.
