### ISSUE TITLE
console.error() severity level not showing as Error in firebase functions logs and GCP logs

### ISSUE THREAD

**Issue by GorvGoyl** [firebase/firebase-functions#944]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Win10
  * Firebase SDK version: 9.11.0
  * Firebase Product:  Firebase cloud functions (functions.pubsub.schedule().onRun())
  * Node.js version: 14
  * NPM version: 6.14.13

### [REQUIRED] Step 3: Describe the problem
`console.error()` severity level not showing as `Error` in firebase functions logs and GCP logs.

#### Steps to reproduce:

Inside a Firebase cloud function (`functions.pubsub.schedule().onRun()`) add below line:
```
console.error("hello from firebase function")
```
It should be shown with severity level as `Error` acc. to [Firebase docs](https://firebase.google.com/docs/functions/writing-and-viewing-logs#console-log):

```
console.log() commands have the INFO log level.
console.info() commands have the INFO log level.
console.warn() commands have the ERROR log level.
console.error() commands have the ERROR log level.
```
However it's showing with default severity:

#### From firebase logs:
![image](https://user-images.githubusercontent.com/7106086/129213543-4e1ff224-d8d2-49d9-b805-c52b8b8696af.png)

#### From GCP logs:
![image](https://user-images.githubusercontent.com/7106086/129214156-2c1ed9a8-67ed-434e-9b57-61331b7b60d6.png)

**Comment by mbleigh** [comment]
Hi, the documentation is a little outdated here - you need to either use `functions.logger` ([docs](https://firebase.google.com/docs/functions/writing-and-viewing-logs#logger-sdk)) or `require("firebase-functions/lib/logger/compat")` if you want to use `console.log()` with Cloud Functions for Firebase. All unpatched `console.log()` messages will show up with `INFO` level severity.
