### ISSUE TITLE
Discrepancy in cloud function runtime environment variables

### ISSUE THREAD

**Issue by DamianGlowala** [firebase/firebase-functions#945]
### Related issues
n/a

### [REQUIRED] Version info

**node:** 14

**firebase-functions:** 3.15.2

**firebase-tools:** 7.10.0

**firebase-admin:** 9.11.0

### [REQUIRED] Test case
n/a

### [REQUIRED] Steps to reproduce
Execute a callable function which interacts with admin SDK. I noticed the error in the Firebase Console logs. I got the following message: `Bucket name not specified or invalid. Specify a valid bucket name via the storageBucket option when initializing the app, or specify the bucket name explicitly when calling the getBucket() method.` I suspect there were some changes to how environment variables are structured and then read.

### [REQUIRED] Expected behavior
I assume there should be the same `FIREBASE_CONFIG` env var format between a recently redeployed cloud function and others I got in my project which all remain untouched for the time-being.

### [REQUIRED] Actual behavior
Recently redeployed function has the following format:
![image](https://user-images.githubusercontent.com/48835293/129280752-2dcc06bd-f215-480e-b0bf-6fd99906dd70.png)

An example of a different, correctly working function which hasn't been updated in the past couple of days:
![image](https://user-images.githubusercontent.com/48835293/129280807-ce551e36-013c-420d-ae3a-10a1c967e200.png)

### Were you able to successfully deploy your functions?
Yes, but this discrepancy affects a production application as even when I correctly call `initializeAdminApp(),` the function seems to struggle to locate the expected environment variable and throws the above error.

**Comment by mbleigh** [comment]
@DamianGlowala this was an issue in the Firebase CLI that should be fixed as of earlier today. Please see https://github.com/firebase/firebase-tools/issues/3667 for more information.
