### ISSUE TITLE
http.onCall now sends raw header and body in the first parameter

### ISSUE THREAD

**Issue by Acterion** [firebase/firebase-functions#947]
### [REQUIRED] Version info

**node:**
v14.17.3

**firebase-functions:**
3.15.2

**firebase-tools:**
9.10.0

**firebase-admin:**
9.11.0

### [REQUIRED] Test case
```ts
// functions/index.ts

import * as functions from 'firebase-functions';

export const myCallable = functions.region("europe-west1").https.onCall(async data => {
  console.log(data);
});```

// myApp/api.ts
import firebase from "firebase/app";
import "firebase/functions";

const firebaseApp = firebase.initializeApp(eval(process.env.VUE_APP_FIREBASE_CONFIG!!));
const functions = firebaseApp.functions("europe-west1");
const callMyFunction = functions.httpsCallable('myCallable');

const result = "";
callMyFunction({text: "Some text"}).then(r => result = r);
```

### [REQUIRED] Steps to reproduce

Call HTTP function from WebApp.

### [REQUIRED] Expected behavior

Expected to see `{text: "Some text"}` in firebase console -> functions -> logs

### [REQUIRED] Actual behavior
<img width="1158" alt="Screenshot 2021-08-13 at 18 00 04" src="https://user-images.githubusercontent.com/22852729/129386865-ad8c5f09-8f03-4ce2-a04b-d37de3665ee9.png">
It outputs a very long log of what seems to be header + body of a whole request.

### Were you able to successfully deploy your functions?
Functions were deployed successfully without any error messages.

**Comment by rburdet** [comment]
I faced the same issue today!. 

The only solution I found was to freeze `firebase-functions` to  "3.14.1"

**Comment by jhuleatt** [comment]
`console.log` is no longer the recommended way to log in Cloud Functions for Firebase. Instead, [use the Functions Logger SDK](https://firebase.google.com/docs/functions/writing-and-viewing-logs#logger-sdk).

To make the migration from `console.log` to `functions.logger` easier, [there is a compat library that allows `console.log` to work correctly](https://firebase.google.com/docs/functions/writing-and-viewing-logs#console-log).  But longer term, `functions.logger` is the way to go.

**Comment by Maistho** [comment]
@jhuleatt This issue is not about the console log though, it's about the argument to the callback handler passing the entire request object instead of just the json data.

This is a pretty nasty bug since it completely breaks the any https onCall functions when updating to this new minor version of the library. The affected versions should be unpublished from npm and a new version should be published which fixes the issue. This is pretty important.
