### ISSUE TITLE
Auth Trigger doesn't include displayName for email+password registration

### ISSUE THREAD

**Issue by codeofsumit** [firebase/firebase-functions#95]
Hey there,

so at the firebaseui login flow, I can provide a "first & lastname", which on the frontend login callback will be available through `displayName`.

![image](https://user-images.githubusercontent.com/2399810/29741518-1e69d66e-8a6f-11e7-97a2-4fbdd791da4f.png)
![image](https://user-images.githubusercontent.com/2399810/29741531-51490faa-8a6f-11e7-8e99-79696b7b1695.png)

However, when I want to access this data from a firebase cloud function on creation of a user, the `displayName` property is missing from the payload inside `event.data`.

```js
exports.saveUserData = functions.auth.user().onCreate(event => {
  const user = event.data; // The Firebase user.
  console.log(event);
  const uid = user.uid;
  const email = user.email; // The email of the user.
  const displayName = user.displayName; // The display name of the user.
  const photoURL = user.photoURL || 'https://firebasestorage.googleapis.com/v0/b/medaku-b583e.appspot.com/o/default_avatar.png?alt=media&token=4cb3410a-8bb4-4b48-be09-a2226f5584ad'; // The display name of the user.
  const [firstname, lastname] = displayName ? displayName.split(' ') : ['Fallback Name, as displayName might be missing', 'lastname'];

  console.log('new user registered: ', user);

  const newUser = {
    uid,
    profile: {
      firstname,
      lastname,
      photoURL,
      email: {
        address: email,
        verified: false,
      },
      createdAt: Date.now(),
    }
  }


  return admin.database().ref(`users/${uid}`).set(newUser);
});
```

the two `console.logs` output this data in the functions logs

```
{ data: 
   { email: 'lala@gmail.com',
     metadata: 
      { createdAt: 2017-08-26T12:59:48.000Z,
        lastSignedInAt: 2017-08-26T12:59:48.000Z },
     uid: 'XYRmB99wkpMZhQeJ84v1DTlj5oF3' },
  eventId: 'ad174ea3-e5d6-4e51-92b8-2b67dafbaf4c',
  eventType: 'providers/firebase.auth/eventTypes/user.create',
  notSupported: {},
  resource: 'projects/memema-lala',
  timestamp: '2017-08-26T12:59:48.535Z',
  params: {} }
```

```
new user registered:  { email: 'lala@gmail.com',
  metadata: 
   { createdAt: 2017-08-26T12:59:48.000Z,
     lastSignedInAt: 2017-08-26T12:59:48.000Z },
  uid: 'XYRmB99wkpMZhQeJ84v1DTlj5oF3' }
```

For the facebook login, the `displayName` property is available on the frontend callback and the cloud function. It's just the email flow that is different.

How can I access displayName from the email flow inside my cloud functions?

**Comment by nicolasgarnier** [comment]
cc @bojeil-google 

So what's happening here is that the account's profile, when it is created through password+email, only contains the email (it's always the case).

See the [`createUserWithEmailAndPassword` API call](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserWithEmailAndPassword). Only takes a password and an email to create the account which means that, when the account is created on Firebase Auth backend, only the email is known and part of the profile.

On the client, Firebase UI Web then updates the profile of the User using a subsequent [updateProfile](https://firebase.google.com/docs/reference/js/firebase.User#updateProfile) call.
You don't "see" this from your web app because Firebase UI  resorts to a "trick" to only fire the `onAuthStateChanged` of your FirebaseApp instance listener *after* the profile of the user has been updated. (technically: Firebase UI does the account creation and profile update in a separate Firebase App instance, then, when the user is fully ready it signs-the user in your original FirebaseApp instance)

However,  on Cloud Function, the trigger will get called right after the `createUserWithEmailAndPassword` call, before the profile is updated. This is why you only have the email.

@bojeil-google can comment and/or think about new features we could do to have a better experience on Functions. Ideas that come to mind:
 - Add a `profile` parameter to the [`createUserWithEmailAndPassword` API call] so that we create new accounts with a pre-populated profile.
 - Add a Cloud Function `functions.auth.user().onProfileUpdated` trigger. Although that may not entirely fix the issue @codeofsumit is having but could help work around the issue

**Comment by codeofsumit** [comment]
as this is a usecase promoted by firebase functions it'd be great to have it resolved so all infos provided during the Auth process are available inside the cloud functions (as they are for other auth providers).

My current workaround is that I'm setting the displayName to an empty string if it's not available inside the cloud function - then on the client check for an empty string in the DB and update the value with the displayName from the Auth callback.
Not ideal - but it works for now.

Thanks for the info and taking care of it 👍 .

**Comment by bojeil-google** [comment]
@nicolasgarnier analysis is correct. @codeofsumit  workaround is fine. 
There are no perfect ways to do this with the available API.
Here is another similar case with FirebaseUI: https://github.com/firebase/firebaseui-web/issues/197
The developer ended up calling `admin.auth().getUser(data.uid)` after the onCreate event fires (this is an additional RPC). This tends to resolve after the `updateProfile`. Though it is not guaranteed.
There are plans to add more events that could be helpful but I can't promise anything at the moment.

**Comment by dwilt** [comment]
@nicolasgarnier running into a similar issue myself here. Is there a security reason that passing up the profile to `createUserWithEmailAndPassword` would be bad? Something like this:

```js
firebase.auth().createUserWithEmailAndPassword(`name@domain.com`, `password`, {
  // profile props like displayName
});
```
I can't imagine why there would be if we're able to call `updateProfile` immediately after getting the success back. It'd save and extra round trip to the server too.

**Comment by bojeil-google** [comment]
I will relay your request to the Auth team. You are also welcome to file a [feature request](https://firebase.google.com/support/) for this.

There are no security reasons. It just doesn't scale from an API design. It is a common user operation that applies to all users during creation time.
In that case, we should add that to `signInAnonymously`, `signInWithPhoneNumber`, etc. We have new sign in methods on the way too. Those will need to add that too.

**Comment by dwilt** [comment]
@bojeil-google thanks for the reply. Yes, it would make total sense that those other authentication methods get the ability as well.

>  It just doesn't scale from an API design. It is a common user operation that applies to all users during creation time.
Can you elaborate on what you mean by this?

**Comment by bojeil-google** [comment]
Modifying every sign in method to take the same profile parameters is messy. In addition, 2 RPC calls are needed for each and they would still result in the early trigger you are seeing. So that would need to be updated. An `updateProfile` API seems better suited on the user with the existing backend API. This is why it was originally designed that way.

**Comment by codeofsumit** [comment]
@bojeil-google I think the bigger problem is that the displayName field is present in firebaseUI, the user fills it out, but then it's not available in cloud functions.
It's just very messy code now and the client does too much to work around this. Especially since it has to operate on the user without knowing if it's already created by cloud functions or not.

**Comment by farazhassan** [comment]
@bojeil-google whats currently happening is messier and on top of that, its not documented.
It makes no sense for other identity providers to work this way and email+password to have a totally different behavior. Is a fix still under consideration or do we have to live with this? Removes the point of building plug and play solutions.

**Comment by bojeil-google** [comment]
Just to explain, this is not unique to email/password creation. This is true for all non-OAuth based providers. This is true for email/password, email link, phone number, anonymous and custom auth providers/methods of sign in. All these providers can set display name after user creation (via `updateProfile` API) which means the display name will not be available when the event is triggered. 

While the display name is needed for many use cases, it is not a requirement for the creation event to block on this. Others may want the photo URL to be available too. Users can be asked to provide the photo URL when an account is created.

I will relay once again to the relevant folks the utility of having the display name on creation via some overloaded method or something of the like. I also suggest you file a [feature request](https://firebase.google.com/support/) for it.

**Comment by bojeil-google** [comment]
@liujin-google Yeah I personally agree we should support triggering events on user updates.

**Comment by farazhassan** [comment]
Yeah that completes the flow at least without any other dependencies.

**Comment by cfsmp3** [comment]
@bojeil-google Does it makes sense that this issue is closed if the problem is not solved? Is it a wont-fix thing?

**Comment by eclewlow** [comment]
userThis example basically doesn't work, according to this thread.

https://github.com/firebase/functions-samples/blob/62379ddeec765c44c21f88b53b2c8ef4077201a2/quickstarts/email-users/functions/index.js#L49

**Comment by eclewlow** [comment]
Oh nevermind.  It works with firebase-admin.
https://firebase.google.com/docs/auth/admin/manage-users#create_a_user

**Comment by justinh00k** [comment]
This is still annoying. Other login methods provide displayName on auth create, but email doesn't, even though the UI gets the display name the same time as the password.

**Comment by ITsolution-git** [comment]
Yeah it's annoying because it does not work just for email/password, while other providers are working fine.

My workaround is to 
```
export const createProfile = async userRecord => {
  let user = await admin.auth().getUser(userRecord.uid);
  user = user.toJSON();
  // user.displayName is valid while userRecord.displayName is undefined.
```

**Comment by matteocarpi** [comment]
> fix displayname from auth mariacasancho/feedback#9

I also used that as a workaround, although weirdly it only works once!

I sign up with a first user, it works. I log out, sign up with a different email and displayName,  and in here: `let user = await admin.auth().getUser(userRecord.uid);` `user.displayName` is undefined, as if the call to get the user returns before the updateProfile function. I think I will just do this manually quitting using firebaseUI.
