### ISSUE TITLE
Cannot deploy functions after updating to v3.15.3

### ISSUE THREAD

**Issue by kyleabens** [firebase/firebase-functions#953]
### [REQUIRED] Version info

**node:**

v14.17.0

**firebase-functions:**
v3.15.3

**firebase-tools:**
v9.16.5

**firebase-admin:**
v9.11.0

### [REQUIRED] Steps to reproduce

1. Update firebase-functions to v3.15.3
2. run firebase deploy --only functions

### [REQUIRED] Expected behavior

The firebase functions should deploy without an issues

### [REQUIRED] Actual behavior

After updating to v3.15.3 I get the following errors:
<img width="634" alt="Screen Shot 2021-08-16 at 9 08 50 AM" src="https://user-images.githubusercontent.com/25699262/129572541-eb17480d-b16d-4601-acc2-e22ba462acf9.png">

**Comment by taeold** [comment]
@kyleabens Hmm the error I'm reading seems to be from typescript compilation. Is there a small reproducible example we can use? Does your code work with previous versions of the SDK (which version is it)?

**Comment by kyleabens** [comment]
@taeold I use typescript v3.7.5 for my firebase functions.  Whenever I updated it to the latest it through even more errors claiming I had 2 different version of node that I was referencing.

**Comment by taeold** [comment]
@kyleabens That node error makes it even more difficult to debug on our side :(.

Can you try pinning firebase-functions to the previous working version and try running `npm run build` to debug your TS compilation? That's where the deploy is going awry.

**Comment by kyleabens** [comment]
@taeold I tried rolling back to v3.14.1 and I still get the same error now.  Could it have something to do with firebase-tools?  I updated that globally as well to 9.16.5.

**Comment by kyleabens** [comment]
@taeold I upgraded typescript to 3.8.3 and that seemed to do the trick.
