### ISSUE TITLE
logger.error doesn't show in the "Health" tab anymore

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-functions#954]
### [REQUIRED] Environment info

Not sure if this is the right place to post this in the myriad of issue trackers. Sorry in advance.

**firebase-tools:**
9.16.3

**Platform:**
Node 14

### [REQUIRED] Test case

Doing a `logger.error('Something')` no longer shows up in the health tab in the firebase console under Functions->Health.

### [REQUIRED] Steps to reproduce
`import { logger } from 'firebase-functions';`
`logger.error('Something')`
Notice that it doesn't show up in the health tab anymore

### [REQUIRED] Expected behavior

That it shows up there - we need to log handled errors to the health tab.

### [REQUIRED] Actual behavior

It never shows up

**Comment by taeold** [comment]
Thanks for reporting the issue @larssn.

I'm not familiar with how error reporting in the health tabs worked before, but you will need to explicitly include an Error object if you want these error logs to show up in the Health tab or in the GCP Error Reporting. e.g.

```
functions.logger.error("this is functions logger error", new Error("From the functions logger"));
```

Since Node.js 10, Google Cloud Functions does not work very well with `console.*` family of functions, and I recommend that you stick with functions logger.

Check out https://cloud.google.com/functions/docs/monitoring/error-reporting on examples of what log statement works/does not work with GCP error reporting tool (just replace `console.` with `functions.logger.`).

Let us know if this helps.

**Comment by larssn** [comment]
As I wrote, it used to log errors in Health tab when you did a `logger.error`. You could log anything.

The health tab now seemingly only reports unhandled errors. It can be problematic that your **handled** errors no longer shows up in the health tab. Imagine having to dig through a huge log file every day to find problems, instead of it being in the health tab.

**Comment by taeold** [comment]
@larssn Any recent changes to your function that you are aware of? Any recent version bump to Firebase Functions SDK or update to the nodejs runtime version?

I can check to see if there were any deliberate changes that were made in the Health tab, but AFAIK, health tab just fetches data from GCP Error Reporting (https://cloud.google.com/error-reporting), which only reports `log.error` that actually includes an error object. I think this behavior might be new in the Nodejs10 runtime.

**Comment by larssn** [comment]
Our NPM versions are updated regularly.

However we did switch to the Node 14 runtime, 3-4 months ago I'd say.

Thanks for the help! 😊

**Comment by taeold** [comment]
Just to get the timeline correct - when you say "it used to log errors in Health tab... You could log anything" - is this 3-4 months ago or like last week?

**Comment by larssn** [comment]
I haven't kept track of when it is used to work like that, but I know it didn't work last week, probably the entire month of August. For all I know it could be the swap to Node 14.

**Comment by taeold** [comment]
@larssn That sounds possible. Given the state of things now, I think we can shape our conversation here as a feature request to automatically wrap strings passed into `functions.logger.error` as an error object. This is arguably backward incompatible change (maybe people don't want errors to show up on Error Reporting? 🤷), so we could sneak it in on the next major release.

**Comment by larssn** [comment]
Sounds good to me 🙂

**Comment by Flucadetena** [comment]
I'm having the same issue, the documentation states using:
```
console.error(new Error('I failed you'));
console.error('I failed you', new Error('I failed you too'));
throw new Error('I failed you'); // Will cause a cold start if not caught
```
But only when I use the last one and "throw" the function it gets reported en "Error Reporting" and it gets logged as an error in the logs in the "cloud functions" section.

If not, it gets reported as a normal log.

**Comment by ishowta** [comment]
It's not complete, but I've tried some way.


```typescript
// Reported correctly with structured data
// https://cloud.google.com/error-reporting/docs/formatting-error-messages
console.error( // `functions.logger` not worked
  JSON.stringify({ // required for reported
    // required for reported
    '@type': 'type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent',
    // log level for reported
    severity: 'ERROR',
    // error title for reported
    message: 'Foo',
    foo: 'bar',
    hey: { yo: 'yeah' },
  })
)

// Reported correctly with simple string
throw new Error("Foo");
functions.logger.error("Foo");
console.error("Foo");

// Reported, but with stringified messages
functions.logger.error("Foo", new Error("Bar"))
functions.logger.error({foo: "hey"}, new Error("Bar"))

// Reported, but stringified and stored in text payload
functions.logger.error(
  new MyError(
    'Foo',
    {bar: "hey"}
  )
)

// Not reported
console.error("Hello world", new Error("Foo"))
throw new functions.https.HttpsError('internal', 'Foo')
```

**Comment by taeold** [comment]
@ishowta Thanks for a thorough experiment. I'll see if I can grab the attention of our tech writer next week to update our content.

In the meantime, I'm curious what version of Nodejs runtime you used to check the output - there seems to be a difference in how error shows up in the Error Dashboard depending on the Nodejs version (12 vs 14 vs 16).

**Comment by Flucadetena** [comment]
@taeold Hi!, I know you tagged @ishowta but im experiencing the same error and I'm using node 14. But I could experience the same error in 12 too. Don't know if it is the case of @ishowta 

Thanks for your time in any case. :)

**Comment by ishowta** [comment]
@taeold I tried it with the Node12 runtime.

**Comment by ishowta** [comment]
@taeold @Flucadetena Sorry, my test code was wrong, so I fixed it and cleaned it up.

Basically, if there is an error instance, it seems to be reported, but only in the form `console.error("something", new Error("error"))` was not reported.

**Comment by SrBrahma** [comment]
@ishowta so how is the best way to log a object with an error stack?

**Comment by Flucadetena** [comment]
> 

Any of the options but, `console.error("something", new Error("error"))` that it is not working at the time.

I use: ```console.error(`your text here ${error}, ${otherData}, ...`)```

And this is working great for me now.

**Comment by taeold** [comment]
Functions Health tab no longer exists :(. Marking the issue as obsolete.
