### ISSUE TITLE
pubsub won't let me subscribe to topics from another project

### ISSUE THREAD

**Issue by thomas-vl** [firebase/firebase-functions#96]
Hi,

Because of the / validation on the function topic I cant subscribe to a topic from another project.

```
export function topic(topic: string): TopicBuilder {
  if (topic.indexOf('/') !== -1) {
    throw new Error('Topic name may not have a /');
  }

  return new TopicBuilder(`projects/${process.env.GCLOUD_PROJECT}/topics/${topic}`);
}
```

Regards,

Thomas

**Comment by justinrosenthal** [comment]
This is working as intended, you may only trigger functions via Pub/Sub topics within your project.

**Comment by RezaRahmati** [comment]
Instead you can create multiple pull subscription on different project and send data to your central http api
