### ISSUE TITLE
Setting RuntimeOptions minInstances not reflected in console.cloud.google.com

### ISSUE THREAD

**Issue by codin-play** [firebase/firebase-functions#968]
### Related issues

(unaware of related issue)

### [REQUIRED] Version info

```
"firebase-admin": "^9.11.1",
"firebase-functions": "^3.15.5",
"firebase-tools": "^9.12.1",
```

**node:**

Firebase Cloud functions 
`Runtime : Node.js 12 `

### [REQUIRED] Test case

When setting a `minInstances` in the `RuntimeOptions` of an `.https.onCall` function the details are not reflected in the functions `detail tab` located on the `console.cloud.google.com` website.

### [REQUIRED] Steps to reproduce

View docs https://firebase.google.com/docs/functions/manage-functions

1.) Create function with code:

```

const notificationRuntimeOpts: functions.RuntimeOptions = {
  minInstances: 3,
  timeoutSeconds: 15,
  memory: '256MB'
};


exports.addMessage = functions.runWith(notificationRuntimeOpts).https.onCall((data, context) => {
  // ...
});

```

2.) Deploy the function

`firebase deploy --only functions`

3.) Navigate to the function detail

`https://console.cloud.google.com/functions/details/us-central1/addMessage?authuser=1&cloudshell=false&project={projectNameHere}&tab=source`

4. Tap `Details` Tab. View the data not being set:

![Screen Shot 2021-09-02 at 4 38 13 PM](https://user-images.githubusercontent.com/83233441/131929219-d32cb367-dddd-4e6c-bf5c-4a6504bd9652.png)

### [REQUIRED] Expected behavior

I expect the `Minimum instances` to be populated with specified Instance data.

### [REQUIRED] Actual behavior

The `Minimum instances` is not populated with specified Instance data. Even after deleting the function entirely and re-deploying the data does not display.

I have no idea if there are actually `minInstances` set and the data field is just missing on the dashboard. Is there a way to tell this? The Metrics Panel also only shows one active instance.

![Screen Shot 2021-09-02 at 4 42 14 PM](https://user-images.githubusercontent.com/83233441/131929508-ef50a4dd-f231-4ef3-add6-0f3649de58be.png)

### Were you able to successfully deploy your functions?

No errors.

**Comment by taeold** [comment]
@codin-play Hmm I'm unable to reproduce on my machine. Can you try:

1) Updating firebase CLI to the latest version?
2) Run deploy with `--debug` flag (`firebase deploy --only functions --debug`) and share what API call is being sent to GCP. You can just paste all of the output and I can help find the relevant snippet.

**Comment by codin-play** [comment]
Oh my gosh - that was it! This was definitely user error.

I was operating with `9.10.0` and updated to `9.17.0` via `npm i -g firebase-tools` and then `curl -sL https://firebase.tools | upgrade=true bash`.

Thank you so much for your assistance @taeold !
