### ISSUE TITLE
No documentation found for cloud functions for firebase v2 on how to transition to using environment variables.

### ISSUE THREAD

**Issue by frikkf** [firebase/firebase-functions#969]
### [REQUIRED] Version info

firebase-functions: 3.15.5

**node:**

v14.6.0

**firebase-functions:**
3.15.5

**firebase-tools:**

9.14.0

**firebase-admin:**

### [REQUIRED] Test case

I am upgrading my firebase-functions version from 3.13 --> 3.15.5 and config() is now not supported.

I digged into the issue and found this code in the config.js file.

```
function config() {
    // K_CONFIGURATION is only set in GCFv2
    if (process.env.K_CONFIGURATION) {
        throw new Error('functions.config() is no longer available in Cloud Functions for ' +
            'Firebase v2. Please see the latest documentation for information ' +
            'on how to transition to using environment variables');
    }
    if (typeof config.singleton === 'undefined') {
        init();
    }
    return config.singleton;
}
```

So it seems there is potential breaking change when bumping a minor version number.

When i try to find the latest documentation, I can't seem to find anything related to a new way of setting environment variables for the firebase functions.

Can someone please direct me to the documentation specifying how to set environment variable for cloud functions for firebase v2?

Or is this a bug?

### [REQUIRED] Steps to reproduce

Deploy a firebase function using functions v3.15.5 and use config()

### [REQUIRED] Expected behavior

Expecting a minor version bump to be a breaking change.
Expected a way to resolve the problem.

### [REQUIRED] Actual behavior
Bumping from firebase-functions 3.13 to 3.15 introduces a breaking change
Cannot seem to find a way to resolve the problem without downgrading firebase-functions

**Comment by mbleigh** [comment]
The `/v2` imports in `firebase-functions` are not ready for public use. If you are requiring `firebase-functions/v2` or any of its sub-imports, the behavior is expected. If you are not requiring any v2 files, please share some of your initialization code so we can see what's happening.
