### ISSUE TITLE
Callable functions - onCall handler uses first argument as context if context is not listed as the second argument (even if it's not used)

### ISSUE THREAD

**Issue by fuzexjj** [firebase/firebase-functions#970]
### [REQUIRED] Version info

**node:** 10

**firebase-functions:** 3.15.3

**firebase-tools:** 9.17.0

**firebase-admin:** 9.11.0

### [REQUIRED] Test case

Client call:

```
functions.httpsCallable('getCustomer')
getCustomer({ customerId: user.customerId })

```
Functions:

```
export const getCustomer = functions.region('europe-west1').https.onCall(async (data) => {
    const customerId = data.customerId // undefined
    // function code...
})
```

### [REQUIRED] Steps to reproduce

**This behaviour appear only in deployed functions, when use it with emulator, everything works fine with one argument**

By removing context from the function args and it will treat data as a context
**I tried to log the data object I was receiving and it had same structure as context object**

```
export const getCustomer = functions.region('europe-west1').https.onCall(async (data, context) => {
    // With context in arguments everything works fine
    const customerId = data.customerId // 'customer_id'
    // function code...
})
```

Deploy a function and call it from any client

### [REQUIRED] Expected behavior

onCall handler uses context as an optional argument

### [REQUIRED] Actual behavior

onCall can't access data if context is not listed as an argument

### Were you able to successfully deploy your functions?

Yes but it breaks the expected behaviour as the doc says:
https://firebase.google.com/docs/functions/callable

"Use functions.https.onCall to create an HTTPS callable function. This method takes two parameters: data, and **optional** context:"

**Comment by joehan** [comment]
Duplicates https://github.com/firebase/firebase-functions/issues/947, which was fixed in v3.15.5 - please update to the latest version and try again!
