### ISSUE TITLE
Unable to import external dependency (Cannot find module)

### ISSUE THREAD

**Issue by falk-stefan** [firebase/firebase-functions#971]
Following the docs ([functions/handle-dependencies](https://firebase.google.com/docs/functions/handle-dependencies)) I am having troubles adding an external dependency to my firebase project. Sorry if this is the wrong channel but this issue is blocking me more or less completely.

I  generated some code which I want to use in my firebase functions.

It's a private package which I am pulling from github, so in my `package.json` I'd have

```json
"dependencies": {
    "@company/package": "1.0.0",
}
```

According to the [docs](https://firebase.google.com/docs/functions/handle-dependencies) this should be fine. I have a `.npmrc` file which defines the repository. `npm i` works fine and I can find the package correctly installed under `node_modules/@company/package`.

However, running the emulators will not work because it cannot find the module:

```
$ firebase emulators:start --inspect-functions
i  emulators: Starting emulators: auth, functions, firestore, database, storage
⚠  functions: You are running the functions emulator in debug mode (port=9229). This means that functions will execute in sequence rather than in parallel.
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: hosting, pubsub
⚠  Your requested "node" version "14" doesn't match your global version "16"
i  firestore: Firestore Emulator logging to firestore-debug.log
i  database: Database Emulator logging to database-debug.log
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/home/sfalk/workspaces/web-mobile/functions" for Cloud Functions...
>  Debugger listening on ws://localhost:9229/e09c9890-f15b-4634-b9bc-b8528f14c03d
>  For help, see: https://nodejs.org/en/docs/inspector
⚠  Error: Cannot find module '@technical-depth/nordigen-client-typescript/api'
Require stack:
- /home/sfalk/workspaces/web-mobile/functions/lib/index.js
- /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/sfalk/workspaces/web-mobile/functions/lib/index.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
⚠  We were unable to load your functions code. (see above)
   - You may be able to run "npm run build" in your functions directory to resolve this.
```

After running `npm run build` I'd get the generated output in `lib/index.js`:

```typescript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.helloWorld = void 0;
const functions = require("firebase-functions");
const api_1 = require("@company/package/api");
// ...
``` 

But the error stays the same.

Just to clarify: my `@company/package` dependency gets installed correctly under `node_modules/@company/package` and it contains an `api.ts` file where the code I require is contained.

How can I successfulle import my library here?

`tsconfig.json`

```json 
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

### See also

- My question on [stackoverflow](https://stackoverflow.com/questions/69062580/getting-error-cannot-find-module-module-when-trying-to-import-custom-packag)

**Comment by falk-stefan** [comment]
@inlined Sorry drag you into this but this issue keeps blocking me. Could you take a look at this issue? I can't see why I am not able to import the module.

**Comment by taeold** [comment]
@falk-stefan I tried reproducing the issue with a test private package without success - my emulator runs successfully.

To make sure this issue is specific to the emulator, have you tried importing your dependency on a node process?

```bash
$ (cd fuctions && node)
> require("@company/package/api");
```

Does this work as expected?

**Comment by falk-stefan** [comment]
@taeold It turns out the problem was indeed with the package itself. I published this using Github Actions but I never called `npm run build` in my workflow. :man_facepalming:. 

Thanks for taking the time!
