### ISSUE TITLE
Getting error exit 16 anonymous

### ISSUE THREAD

**Issue by ziad10a** [firebase/firebase-functions#973]
### [REQUIRED] Version info

**node:**

v14.17.5

**firebase-functions:**

**firebase-tools:**

9.16.5

**firebase-admin:**

### [REQUIRED] Test case

this is the code block that the issue happens inside:
`
exports.matchmaker = functions.database.ref("matchmaking/{playerId}").onCreate((snap, context) => {            

    if(snap.val() !== "searching"){
        console.log("User "+context.params.playerId + " isn't searching, removing it!");
        database.ref("matchmaking/"+context.params.playerId).remove();
        return null;
    }

    // Matchmaking ref
    const matchmakingRef = database.ref("matchmaking");
    

    if(snap.val() !== "searching"){
        console.log("Self status isn't searching, removing it!" + context.params.playerId);
        matchmakingRef.child(context.params.playerId).remove();
        return null;
    }    

    // Generate random game id
    const gameId = database.ref("games").push().key;
    const gameRef = database.ref("games/"+gameId);

    // Read the matchmaking list once
    matchmakingRef.once("value").then((players) => {
        
        let secondPlayer = null;
        // Loop through the players' list and 
        // get an another player that's no us
        players.forEach((player) => {
            if(player.val() === "searching" &&
            player.key !== context.params.playerId) {
                secondPlayer = player;
            }
        });

        // If no other player found just return
        if(secondPlayer == null) {
            console.log("no other player found");
            return players;
        }    

        database.ref("matchmaking").transaction(function (matchmaking) {
            
            //null matchmaking
            if(matchmaking === null){
                console.log("matchmaking is null");
                return matchmaking;
            }
            //Our value has become null
            if(matchmaking[context.params.playerId] === null ){
                console.log("player null = "+context.params.playerId);
                return matchmaking;
            }
            //second player has become null
            if(matchmaking[secondPlayer.key] === null){
                console.log("player null = "+secondPlayer.key);
                return matchmaking;
            }
            //we are not searching
            if(matchmaking[context.params.playerId] !== "searching"){
                console.log("our value is not searching " + context.params.playerId);
                return matchmaking;
            }
            //second player isn't searching
            if(matchmaking[secondPlayer.key] !== "searching"){
                console.log("other player value is not searching " + secondPlayer.key);
                return matchmaking;
            }
            matchmaking[context.params.playerId] = gameId;
            matchmaking[secondPlayer.key] = gameId;

            return matchmaking;

        }).then((result) => {
            
            if (result.snapshot.child(context.params.playerId).val() !== gameId ) {
                if(result.snapshot.child(context.params.playerId).val() === "searching")
                {
                    console.log("##### self game id isn't set, will refresh soon " + result.snapshot.child(context.params.playerId).key);
                    //matchmakingRef.child(context.params.playerId).remove();
                }
                return null
            }

            // Setup the game data
            console.log("set the game data");        
            const gameData = {
                id: gameId,
                playerIds : [context.params.playerId, secondPlayer.key],
                variables : {
                    turn : context.params.playerId
                }
            }
            gameRef.set(gameData).then((result) => {
                console.log("game created");
            });

            return null;
        });

        return null;   
    });

    return null;
});

exports.idleplayer = functions.database.ref("matchmaking/{playerId}").onUpdate((snap, context) => {        

    if(snap.after.val() !== "searching"){        
        setTimeout(function(){
            console.log("delete user "+context.params.playerId);
            database.ref("matchmaking/"+context.params.playerId).remove();
            return null;
        }, 1000);
    }

    return null;
});
`

### [REQUIRED] Steps to reproduce

It might be random but I usually try to match new entries with existing ones then assign to them unique value then remove them from the matchmaking list.

I know saying random wouldn't make any sense cause it's a code at the end but I couldn't figure out where is the exit code that causes this issue

### [REQUIRED] Expected behavior

I can't figure out what's the behaviours cause I'm unaware of the the issue itself

### [REQUIRED] Actual behavior

`
2021-09-13T09:48:09.612Zmatchmaker9kul34o433ae Error: Process exited with code 16 at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:237:22) at process.emit (events.js:375:28) at process.emit (domain.js:470:12) at process.exit (internal/process/per_thread.js:169:15) at Object.sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:38:9) at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:233:22) at process.emit (events.js:375:28) at process.emit (domain.js:470:12) at processPromiseRejections (internal/process/promises.js:245:33) at processTicksAndRejections (internal/process/task_queues.js:96:32)
Error: Process exited with code 16 at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:237:22) at process.emit (events.js:375:28) at process.emit (domain.js:470:12) at process.exit (internal/process/per_thread.js:169:15) at Object.sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:38:9) at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:233:22) at process.emit (events.js:375:28) at process.emit (domain.js:470:12) at processPromiseRejections (internal/process/promises.js:245:33) at processTicksAndRejections (internal/process/task_queues.js:96:32)
`

### Were you able to successfully deploy your functions?

Yes it was successful with no errors

**Comment by taeold** [comment]
As explained in https://stackoverflow.com/a/64970415/7163188, error code 16 usually refers to `uncaughtException` or `unhandledRejection` exceptions that's thrown in your user code.

I notice that in your code includes statement like this:

```js
    database.ref("matchmaking/"+context.params.playerId).remove();
    return null;
```

This is problematic since `database.ref("matchmaking/"+context.params.playerId).remove();` returns a promise, and the code isn't waiting for the promise to be resolved before returning. You should return the promise instead:

```js
    return database.ref("matchmaking/"+context.params.playerId).remove();
```

Better yet, consider handling the error to make debugging easier:

```js
    return database.ref("matchmaking/"+context.params.playerId).remove()
      .then(() => logger.info("Successfully removed node")
      .catch((err) => {
        logger.error(`Failed to remove node: ${err}`);
        throw err
      });
```

Check out https://firebase.google.com/docs/functions/terminate-functions for more info.

This issue doesn't seem to be reporting any bug in the SDK, so I'll close the issue.
