### ISSUE TITLE
Cloud functions work work unless I delete all functions before deploying

### ISSUE THREAD

**Issue by b0ot** [firebase/firebase-functions#975]
### [REQUIRED] Version info

**node:** 12.19.0

**fierbase**: 9.12.1

**firebase-functions:** firebase-functions@3.15.5

**firebase-tools:**

**firebase-admin:** firebase-admin@9.11.1

### [REQUIRED] Test case

**What Should Work**
I test my cloud functions within the Emulator: Everything works
I build my project: quasar build
Deploy it: firebase deploy --except functions
Deploy functions: firebase deploy --only functions
I get message that the functions have deployed successfully

I go to run a callable cloud function:
e.g: exports.addNewOfferToFirebase = functions.https.onCall(async (data, context) => ......
and I get CORS related errors

**Work around:** to get the function to work correctly:
I take the same cloud functions code

1. Comment out all of the functions
2. Deploy the functions
3. Get prompted to delete my functions
4. Enter Y when prompted and delete all of my functions
5. Un-comment my code to re-enable of my functions
6. Deploy the cloud functions

Both of the deployments are successful. 

### [REQUIRED] Steps to reproduce

This has happened multiple times within my project.

### [REQUIRED] Expected behavior

I should be able to deploy and update my cloud functions without first having to delete them

### Were you able to successfully deploy your functions?

No

**Comment by Herobone** [comment]
Apparently this is a issue that is caused not by firebase-functions but rather by firebase-tools. Permissions are not set anymore. This has been an issue before, look at issue #645. There was a fix mentioned [here](https://github.com/firebase/firebase-functions/issues/645#issuecomment-605770593) But doing that on every deploy is not the right solution. This problem also appears in my functions and I needed several hours to find out it was just missing permissions

**Comment by taeold** [comment]
Hi @b0ot. Sorry to hear about your issue.

It's hard to know exactly what's going on in your situation. CORS related error messages are often red-herring; you will see that error message from your client whenever your function isn't accessible for whatever reason. One popular reason is as @Herobone described - by default Firebase Functions (i.e. Google Cloud Functions) aren't publicly accessible, while the firebase tooling tries to make it public, sometimes that could fail.

I don't understand why "delete then re-create functions" trick would work in your case though. Is this a consistently working workaround? Are there any error messages you see in the "successful but ultimately broken" deploys that you can share with us?
