### ISSUE TITLE
Stuck on "functions: cleaning up build files..."

### ISSUE THREAD

**Issue by kyleabens** [firebase/firebase-functions#979]
### Related issues

None

### [REQUIRED] Version info

**node:** 
14.17.0

**firebase-functions:**
3.15.6

**firebase-tools:**
9.18.0

**firebase-admin:**
9.11.1

### [REQUIRED] Test case
Any project that has cloud functions

### [REQUIRED] Steps to reproduce

firebase deploy --only functions

### [REQUIRED] Expected behavior

For the functions to successfully deploy and finish

### [REQUIRED] Actual behavior

Gets hung up at "functions: cleaning up build files..."

It never gets past this step and this just recently started happening and I never upgraded any packages between when it was working and now.

### Were you able to successfully deploy your functions?

No it never successfully deploys

**Comment by taeold** [comment]
We are tracking this issue at https://github.com/firebase/firebase-tools/issues/3694.
