### ISSUE TITLE
Cannot call firebase onCall() function in emulator due to CORS error.

### ISSUE THREAD

**Issue by catsclaw** [firebase/firebase-functions#982]
### Related issues

I didn't see anything that dealt with the emulator/onCall functions which weren't generating errors in the logs.

### [REQUIRED] Version info

**node:**

v14.14.0

**firebase-functions:**

**firebase-tools:**

9.18.0

**firebase-admin:**

### [REQUIRED] Test case

Web: 
```
let firebaseApp = initializeApp({
  apiKey: 'XXX',
  authDomain: 'XXX',
  databaseURL: 'XXX',
  projectId: 'XXX',
  storageBucket: '',
  messagingSenderId: 'XXX',
});

const functions = getFunctions(firebaseApp);
connectFunctionsEmulator(functions, 'local.com', 5001);
export const resyncAllVisaInfo = httpsCallable(functions, 'resyncAllVisaInfo');
resyncAllVisaInfo({});
```

Functions `index.js`:
```
exports.recalcAllVisaInfo = functions.https.onCall(async (data, context) => {
  console.log('RECALC!');
  return {};
});
```
### [REQUIRED] Steps to reproduce

Create a hosted site with functions in the emulator, and try to hit it.

### [REQUIRED] Expected behavior

The function completes, and logs to the log.

### [REQUIRED] Actual behavior

I get ```Access to fetch at 'http://local.com:5001/XXX/us-central1/resyncAllVisaInfo' from origin 'http://local.com:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.``` in my browser.

The logs in the emulator are:

```
16:58:27 I functions Watching "/Users/code/calendar/functions" for Cloud Functions...
16:58:28 I functions http function initialized (http://localhost:5001/XXX/us-central1/parseEmail).
16:58:32 I functions firestore function initialized.
16:58:32 I functions http function initialized (http://localhost:5001/XXX/us-central1/recalcAllVisaInfo).
```

### Were you able to successfully deploy your functions?

I'm running in the emulator. So deployment wasn't needed.

**Comment by taeold** [comment]
@catsclaw

```
connectFunctionsEmulator(functions, 'local.com', 5001);
```

Is `local.com` a typo? This should instead be `localhost` if  you are using the emulator.

**Comment by shauryaaher** [comment]
Yeah, @taeold is right. It's probably http://localhost:5001.

**Comment by catsclaw** [comment]
I added `127.0.0.1    local.com` to my `/etc/hosts` file because Chrome has weird issues around CORS and `localhost` routes. I get the exact same errors using `localhost`.

**Comment by catsclaw** [comment]
`Access to fetch at 'http://localhost:5001/XXX/us-central1/resyncAllVisaInfo' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by taeold** [comment]
@catsclaw One more question - your function name is `recalcAllVisaInfo` but you are calling `resyncAllVisaInfo`. Does the latter function actually exist? If not, that would explain the CORS issue (when you make a POST request to a non-existent function, you get CORS error 🤷 ).

All that being said, I'm not sure how your development environment is set up but if your app is running on localhost and your function is accessible at localhost why is CORS check being done?

**Comment by catsclaw** [comment]
That turns out to be it — function name mismatch. I suppose I can understand that the `httpsCallable(functions, 'recalcAllVisaInfo')` isn't doing any kind of lookup of validation of the route, but for the life of me I can't understand why it doesn't 404 on a non-existent route rather than give a CORS error.

**Comment by taeold** [comment]
I get tripped up by it all the time. To be fair, the behavior is part of the fetch spec:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

Some browsers, like Firefox, returns slightly more helpful message than Chrome (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors).

**Comment by Mauratay** [comment]
Having the exact same issue, calling the same function.
```Access to fetch at 'http://localhost:5001/projectname/us-central1/functioname' from origin 'http://localhost:5051' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```
