### ISSUE TITLE
Cannot deploy Functions to my App.

### ISSUE THREAD

**Issue by lucasdavidferrero** [firebase/firebase-functions#987]
When deploying, It gives errors. Removing `us.artifacts.<appId>.appspot.com` doesn't solve the problem.
### Related issues

https://github.com/firebase/firebase-functions/issues/795

### [REQUIRED] Version info

**node:*14*

**firebase-functions:*^3.15.7*

**firebase-tools:*@9.19.0*

**firebase-admin:*^9.8.0*

### [REQUIRED] Test case
Running the command `firebase deploy --only functions` and successfully update the functions.

### [REQUIRED] Steps to reproduce
I run `firebase deploy --only functions`

### [REQUIRED] Expected behavior
Successfully deploy functions to my project.

### [REQUIRED] Actual behavior
Getting an error that prevent functions to be deployed.

[function-log-lucas.log](https://github.com/firebase/firebase-functions/files/7294812/function-log-lucas.log)

### Were you able to successfully deploy your functions?
Nope

**Comment by taeold** [comment]
@lucasdavidferrero Hey Lucas. I took a quick look at the log and found the following error messages:

> {"code":3,"message":"Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation."}

Can you review your logs from your Firebase Functions and see anything is amiss?

**Comment by lucasdavidferrero** [comment]
Hello Daniel, thanks for the reply. The list of logs in Google Cloud Console looks like this:
![image](https://user-images.githubusercontent.com/15804058/136256374-642e4c8c-dcf4-4867-bcba-c8c113500f5a.png)
If I expand the log of one function I get: 
```
{
  "textPayload": "Function cannot be initialized. Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging\n",
  "insertId": "000000-d51d4868-7cea-4b85-851d-87acc682c8fd",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "eventoRemate-reactivar",
      "region": "southamerica-east1",
      "project_id": "cooperativawebsite"
    }
  },
  "timestamp": "2021-10-06T14:21:37.605654349Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": ""
  },
  "logName": "projects/cooperativawebsite/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "receiveTimestamp": "2021-10-06T14:21:38.197048446Z"
}
```

Watching the logs of a function called `eventoRemate-actualizar`:
```
{
  "textPayload": "    at Module.require (internal/modules/cjs/loader.js:961:19)",
  "insertId": "000019-deb256b9-6497-4247-8430-1c7b71f4d9cf",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "cooperativawebsite",
      "region": "southamerica-east1",
      "function_name": "eventoRemate-actualizar"
    }
  },
  "timestamp": "2021-10-06T14:21:36.553Z",
  "labels": {
    "execution_id": ""
  },
  "logName": "projects/cooperativawebsite/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "receiveTimestamp": "2021-10-06T14:21:37.917356650Z"
}
```
```
{
  "textPayload": "Could not load the function, shutting down.",
  "insertId": "000000-6eb2c6be-78a7-480b-ac76-3e1ef7e25f9e",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "southamerica-east1",
      "function_name": "eventoRemate-actualizar",
      "project_id": "cooperativawebsite"
    }
  },
  "timestamp": "2021-10-06T14:21:36.555Z",
  "labels": {
    "execution_id": ""
  },
  "logName": "projects/cooperativawebsite/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "receiveTimestamp": "2021-10-06T14:21:37.917356650Z"
}
```
To be honest, I don't know why those errors appear. It works properly running in the Emulators, so that means that modules' resolution is fine (I think so).
Another thing to mention here is that I'm using `cheerio` and `gaxios` modules in some of my functions. Finally, the last time I successfully deployed my functions were in the default region (us-central1). I've changed all to 'southamerica-east1'.

**Comment by lucasdavidferrero** [comment]
This problem was solved. Somehow, TSC was compiling a file in the wrong directory.

**Comment by taeold** [comment]
@lucasdavidferrero Thanks for letting us know. Glad to hear that your problem was resolved.

**Comment by pratheek-adi** [comment]
> The error log I'm focusing on:
> 
> ![image](https://user-images.githubusercontent.com/14897098/136293649-f9d04896-c931-45c4-b4ba-202c6c9a676e.png)
> 
> To me this looks like the module you want to import does not exist on the package that's being deployed. You mentioned that the code works locally - is it possible that somehow the package above isn't being included in the deployment?
> 
> I'd take a look at the "Sources" tab to make sure that the referenced file exists at the path specified.

Thank you for this. While the source code wasn't an issue on my end, it was something to do with the build config file about which I was able to think because of your answer!

**Comment by pratheek-adi** [comment]
> The error log I'm focusing on:
> 
> ![image](https://user-images.githubusercontent.com/14897098/136293649-f9d04896-c931-45c4-b4ba-202c6c9a676e.png)
> 
> To me this looks like the module you want to import does not exist on the package that's being deployed. You mentioned that the code works locally - is it possible that somehow the package above isn't being included in the deployment?
> 
> I'd take a look at the "Sources" tab to make sure that the referenced file exists at the path specified.

@taeold Thank you for this. While the source code wasn't an issue on my end, it was something to do with the build config file about which I was able to think because of your answer!
