### ISSUE TITLE
FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail 

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-functions#993]
### Related issues

no

### [REQUIRED] Version info
node 14
"firebase-admin": "^9.12.0",
"firebase-functions": "^3.15.7"

  

### [REQUIRED] Test case

```
const crypto = require("crypto");
const admin = require('firebase-admin');

admin.initializeApp({
    serviceAccountId: 'authenticator@myproject.iam.gserviceaccount.com',
    databaseURL: "https://myproject-541fc-default-rtdb.firebaseio.com/",
    projectId: "myproject-541fc"
});

const functions = require('firebase-functions');
exports.pattaya = functions.https.onCall((data, context) => {
//my stuff
});
```
### [REQUIRED] Steps to reproduce
I've a firebase function that is running for over 2 years without problems....

Recently I decided to test the new https://firebase.google.com/docs/app-check and therefore i needed to update my function from HTTP FUNCTION to HTTP CALLABLE FUNCTION (https://firebase.google.com/docs/functions/callable)

```
BEFORE

const crypto = require("crypto");
const admin = require('firebase-admin');

admin.initializeApp({
});


exports.pattaya = (req, res) => {
//my stuff
};


NOW

const crypto = require("crypto");
const admin = require('firebase-admin');

admin.initializeApp({
    serviceAccountId: 'authenticator@myproject.iam.gserviceaccount.com',
    databaseURL: "https://myproject-541fc-default-rtdb.firebaseio.com/",
    projectId: "myproject-541fc"
});

const functions = require('firebase-functions');
exports.pattaya = functions.https.onCall((data, context) => {
//my stuff
});
```
since them I cant stop getting annoying warnings in the function log

```
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail 
then according to this https://cloud.google.com/functions/docs/configuring/env-var

```
`the GCLOUD_PROJECT variable was set automatically for nodejs 8 only (what is irrational since node 8 was deprecated long ago and firebase even recommend we use node 14)
`
So I went to deploy dashboard, edit function, environment variable, and manually wrote the GCLOUD_PROJECT -> myproject-id

but after that i started getting

Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail
the question is

HOW TO GET RID OF THESE ANNOYING FIREBASE WARNINGS?

will i need to set manually environment variables to all my functions? even they are deployed to GC? does it make sense?
 
### Were you able to successfully deploy your functions?

yes

**Comment by 0x80** [comment]
@inlined  If possible I think this warning should not occur if you pass arguments to initializeApp. I currently work around it by simply setting `FIREBASE_CONFIG=__mute_warning` but that feels like a hack.

I deploy to some platforms outside of firebase-functions which still bundle this code (cloud run, local cli tool), so I'll get the warnings regardless of firebase-tools version. Ideally of course firebase-functions code would only be deployed to firebase functions, but I'd first need to move to a monorepo and spit the different parts to separate packages.

For more info see also [my SO question](https://stackoverflow.com/questions/69871560/why-do-i-keep-seeing-warning-estimating-config-based-on-gcloud-project/69872556#69872556)

**Comment by inlined** [comment]
Though this may change in future versions of the firebase-tools SDK, many event handlers use their own Firebase App that is initialized from this config. If the config is missing things may break. It's much easier to ignore a warning than it is to debug an error that's happening without one.
